### ISSUE TITLE
avatar icon upload failed!!!

### ISSUE THREAD

**Issue by 461316334** [wekan/wekan#1075]
version: wekanteam/wekan:meteor-1.4 in docker 
exception:
```
wekan_1  | SA GridFS - ERROR! { [MongoError: Can't get executor for query { files_id: ObjectId('5948d96fec390a01003706a5'), n: { $gte: 0 } }]
wekan_1  |   name: 'MongoError',
wekan_1  |   ok: 0,
wekan_1  |   errmsg: 'Can\'t get executor for query { files_id: ObjectId(\'5948d96fec390a01003706a5\'), n: { $gte: 0 } }',
wekan_1  |   code: 17241,
wekan_1  |   codeName: 'Location17241' }
wekan_1  | /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:246
wekan_1  |         throw message;
wekan_1  |         ^
wekan_1  |
wekan_1  | Error: Error storing uploaded file to TempStore: Can't get executor for query { files_id: ObjectId('5948d96fec390a01003706a5'), n: { $gte: 0 } }
wekan_1  |     at EventEmitter.<anonymous> (packages/cfs_collection.js:186:28)
wekan_1  |     at emitTwo (events.js:92:20)
wekan_1  |     at EventEmitter.emit (events.js:172:7)
wekan_1  |     at Stream.<anonymous> (packages/cfs_tempstore.js:364:10)
wekan_1  |     at emitOne (events.js:82:20)
wekan_1  |     at Stream.emit (events.js:169:7)
wekan_1  |     at Stream._error (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
wekan_1  |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:128:28
wekan_1  |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:524:58
wekan_1  |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:474:20
wekan_1  |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1194:16
wekan_1  |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1903:9
wekan_1  |     at Server.Base._callHandler (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
wekan_1  |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
wekan_1  |     at [object Object].MongoReply.parseBody (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
wekan_1  |     at [object Object].<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
wekan_wekan_1 exited with code 1
```

**Comment by xet7** [comment]
Known issue with MongoDB 3.4.x.

Use MongoDB 3.2.x
https://github.com/wekan/wekan-mongodb
