### ISSUE TITLE
has no method 'assign'

### ISSUE THREAD

**Issue by CenkSuemen** [wekan/wekan#1130]
Hello Everybody, 
I get this error after the installation of wekan: (Debian 9)

/root/.nvm/v0.10.40/lib/node_modules/npm/lib/config/cmd-list.js:113
module.exports.aliases = Object.assign({}, shorthands, affordances)
                                ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/root/.nvm/v0.10.40/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /root/.nvm/v0.10.40/lib/node_modules/npm/lib/npm.js:37:17
    at Object.<anonymous> (/root/.nvm/v0.10.40/lib/node_modules/npm/lib/npm.js:471:3)
    at Module._compile (module.js:456:26)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v0.10.40` to unset it.
default -> v0.10.40
./autoinstall_wekan.sh: Zeile 45: npm: Kommando nicht gefunden.
./autoinstall_wekan.sh: Zeile 46: npm: Kommando nicht gefunden.

and when I try to start wekan I get this error:
 /etc/init.d/wekan: Zeile 37: /root/.nvm/v0.10.40/bin/forever: Datei oder Verzeichnis nicht gefunden
: Datei oder Verzeichnis nicht gefunden

**Comment by xet7** [comment]
You have old version of Node.js, please see:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-and-build-wekan

And also platforms where Wekan is available:
https://github.com/wekan/wekan/wiki/Platforms
