### ISSUE TITLE
Adding user to board causes node.js to crash

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1131]
I added new user to board, and then node.js crashed with this error. I have Wekan running locally. SMTP settings are most likely not configured properly.

```
/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/mime-node/last-newline.js:28
        this.push(Buffer.from('\r\n'));
                         ^

TypeError: this is not a typed array.
    at Function.from (native)
    at LastNewline._flush (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/mime-node/last-newline.js:28:26)
    at LastNewline.<anonymous> (_stream_transform.js:118:12)
    at LastNewline.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at LastNewline.emit (events.js:166:7)
    at prefinish (_stream_writable.js:458:12)
    at finishMaybe (_stream_writable.js:466:7)
    at endWritable (_stream_writable.js:478:3)
    at LastNewline.Writable.end (_stream_writable.js:443:5)
    at PassThrough.onend (_stream_readable.js:490:10)
    at PassThrough.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at PassThrough.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
```

**Comment by nztqa** [comment]
I can't reproduce it on email 1.2.1 https://atmospherejs.com/meteor/email
See also https://forums.meteor.com/t/sending-emails-via-smtp/36596/6
