### ISSUE TITLE
Set to not use TLS but TLS being used in email anyway

### ISSUE THREAD

**Issue by Clete2** [wekan/wekan#1142]
Hello,
I'm using the latest release and I'm trying to setup e-mail. I've tried to set it up using the admin UI as well as by setting MAIL_URL on the environment variables (and I confirmed it is being picked up). For some reason it is trying to use TLS even though I have set my URL to "smtp://my.server:25" and on the DB I have TLS disabled too.

Why is it trying to use TLS? I've gone through the mail troubleshooting guide to no avail.

```
Exception while invoking method 'ATCreateUserServer' Error: unable to get local issuer certificate
    at Object.Future.wait (/build/programs/server/node_modules/fibers/future.js:449:15)
    at Mail._syncSendMail (packages/meteor.js:213:24)
    at smtpSend (packages/email.js:116:13)
    at Object.Email.send (packages/email.js:174:5)
    at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:849:9)
    at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core.js:1310:16)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    - - - - -
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:623:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:453:38)

```

**Comment by xet7** [comment]
Moved to #1120
