### ISSUE TITLE
Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by msergg** [wekan/wekan#1162]
## Issue
**Impacted version**: 32

**Server Setup Information**:

* Operating System: Red Hat Enterprise Linux Server release 7.2 (Maipo)
* Deployment Method
official binaries in node virtual env + nginx as a frontend
* Node Version:  
node --version
v4.8.4

* MongoDB Version:
db version v3.4.8

Some times I when I use wekan, 
I got my processor load is up to 100% , I got message in the UI :
"Wekan is loading, please wait. Refreshing the page will cause data loss. If Wekan does not load, please check that Wekan server has not stopped."

and in logs there are errors
Exception while invoking method '/checklists/update' TypeError: Cannot read property 'items' of undefined
    at Object.<anonymous> (models/checklists.js:173:26)
    at packages/matb33_collection-hooks.js:486:20
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:485:11
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:484:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
    at [object Object].CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:344:34)
    at [object Object].m.(anonymous function) (packages/allow-deny/allow-deny.js:171:46)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)

Restart is as workaround
Can you investiage what happens?

Thank you

**Comment by xet7** [comment]
It's known issue that Wekan crashes when uploading attachment on MongoDB 3.4.x

Please use MongoDB 3.2.x

For more info about versions please see:
https://github.com/wekan/wekan/blob/devel/Dockerfile

**Comment by msergg** [comment]
Thanks, downgraded - I will test.

**Comment by msergg** [comment]
I think its will be good thing to add recommend versions of dependencies to README file. How do you think?

**Comment by xet7** [comment]
@msergg 

I did add [Requirements page to wiki](https://github.com/wekan/wekan/wiki/Requirements)

**Comment by callahad** [comment]
I'm not sure this is entirely resolved. I'm seeing the same exception ("Exception while invoking method '/checklists/update' TypeError: Cannot read property 'items' of undefined") in the console using Docker with the `mongo:3.2.15` and `wekanteam/wekan:latest` (v32) images.

**Comment by GavinLilly** [comment]
This sounds very much like one of the issues we've been having in #1096

**Comment by callahad** [comment]
I'm not so sure it's necessarily related to that bug -- I'm seeing it on a single-user instance with three boards, about 20 cards, and only one browser tab open. :)

**Comment by xet7** [comment]
Moved to #1198
