### ISSUE TITLE
Add Feature: Copy URL of a card

### ISSUE THREAD

**Issue by AlexanderZobkov** [wekan/wekan#1188]
Sometimes you need to send a card URL to your team mate. For example: to inform him/his about adding the card or asking her/he to adjust the card with certain information or in a certain way.  
Card URL could be retrieved by using the browser itself features. For example, in chrome - Copy link Address. However, the link will not work for others,
It would be nice to this feature on Wekan/card level. For example, a button or link 'Copy card URL' on a card level.

**Comment by xet7** [comment]
This is in progress, see [Roadmap](https://github.com/wekan/wekan/wiki/Roadmap)

**Comment by xet7** [comment]
![copy card link to clipboard](https://user-images.githubusercontent.com/15545/29736793-61e1bad6-8a0d-11e7-94a7-89c72babf0bf.png)

**Comment by AlexanderZobkov** [comment]
Thank you! 
We will be able to try and use that feature when #799 will be completed (particularly #1166 part of it).

**Comment by xet7** [comment]
This work on Standalone Wekan, but not on Sandstorm.

From @AlexanderZobkov at https://github.com/wekan/wekan/issues/799#issuecomment-325558114

> Regarding #1188, probably it make sence to create a new issue (telling that #1188 does not work in Sandstorm) or re-open the old one, for the following reason:
> URLs like https://something.sandcats.io/grain/RANDOMTEXT2/b/sandstorm/libreboard/RANDOMTEXT1 (in my case http://RANDOMTEXT2hostname.domain/b/sandstorm/libreboard/RANDOMTEXT1) that could be taken by using your brower capabilies  does not work for others. they get something like 
```Error: Unauthorized [403]
    at Proxy.makeContext (server/proxy.js:1660:15)
    at server/proxy.js:1899:19
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39```

**Comment by ocdtrekkie** [comment]
I am going to FYI tag @kentonv on this so he can consider it in questions about how apps should reference themselves, which comes up from time to time. Might be a good use for an offer template-like interface where the app code never sees the URL but presents it to the user.

**Comment by kentonv** [comment]
I wonder if you want a /grain/<id>/<path> link, or a /shared/<key>/<path> link? That is, is a user usually intending to send the link to someone who already has access to the board, or are they wanting to implicitly grant access to whomever receives the link?

I tend to think the latter. In that case, the right thing to do might be to use the "share" postMessage() API, which opens the sharing dialog. We could perhaps extend that API with the ability to specify a path, which would then be appended to the generated sharing link.

**Comment by ocdtrekkie** [comment]
I think it's safe to say most people _expect_ a link they send someone will give them access to something, so I'd agree that /shared// is the way to go there.

**Comment by xet7** [comment]
Currently, when pasting links, it opens card, but showing only WeKan part, not Sandstorm at top and lef.
