### ISSUE TITLE
Cannot read property 'items' of undefined while ticking task in checklists

### ISSUE THREAD

**Issue by It4lik** [wekan/wekan#1198]
**Impacted version**: 0.33

**Server Setup Information**:
* Operating System: Ubuntu 16.04.03 LTS (Xenial)
* Deployment Method: manual (manual installation of mongodb & nginx, using distro's package. Wekan installed with wget, tag 0.33)
* Node Version: 4.8.4
* MongoDB Version: 2.6.10
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
I'm discovering Wekan and wanted to say thank you for this nice Trello alternative. 

This "bug" has no impact on the user experience, but still always leverages the same error. 
Whenever a user tick an item in a checklist, this error pops out in the console (I'm still testing the solution and just launch the node server with `node main.js`). 
Here is the error : 
```
Exception while invoking method '/checklists/update' TypeError: Cannot read property 'items' of undefined
    at Object.<anonymous> (models/checklists.js:173:26)
    at packages/matb33_collection-hooks.js:486:20
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:485:11
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:484:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
    at [object Object].CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:344:34)
    at [object Object].m.(anonymous function) (packages/allow-deny/allow-deny.js:171:46)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
```

Again, this seems to have no impact, but I thought it would be nice to inform you anyway. 
Regards, it4

**Comment by nztqa** [comment]
Duplicate #1162 
Cause #1148 
This happens because the activity log is not deleted when checklist items are deleted.

@GhassenRjab Can you look at this?

Fix 1
```
diff --git a/models/activities.js b/models/activities.js
index 208dd62..9136873 100644
--- a/models/activities.js
+++ b/models/activities.js
@@ -39,7 +39,12 @@ Activities.helpers({
     return Checklists.findOne(this.checklistId);
   },
   checklistItem() {
-    return Checklists.findOne(this.checklistId).getItem(this.checklistItemId);
+    const checklist = Checklists.findOne(this.checklistId);
+    if (checklist) {
+      return checklist.getItem(this.checklistItemId);
+    } else {
+      return null;
+    }
   },
 });
```

Fix 2
well...
https://github.com/wekan/wekan/blob/ddc21046b9385ac5ce5bbb9a773484fcd056d10c/models/checklists.js#L98
