### ISSUE TITLE
Error sending Invitation Emails

### ISSUE THREAD

**Issue by janisroze** [wekan/wekan#1209]
The version I m running is

![screenshot from 2017-09-06 09 46 27](https://user-images.githubusercontent.com/2563562/30097893-6892a848-92e8-11e7-8fe3-2355b4321196.png)

I am having problem setting up email and in the log file getting this error. Is the config wrong or am i missing something?

```
Exception in callback of async function: Error: unable to verify the first certificate [email-fail]
    at sendInvitationEmail (models/settings.js:119:13)
    at models/settings.js:136:15
    at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
    at packages/mongo/collection.js:643:5
    at args.(anonymous function) (packages/matb33_collection-hooks.js:391:23)
    at runWithEnvironment (packages/meteor.js:1176:24)
    at packages/meteor.js:1189:14
    at packages/mongo/mongo_driver.js:320:7
    at runWithEnvironment (packages/meteor.js:1176:24)
```

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
