### ISSUE TITLE
Import from Trello fails if the exported board has a checklist

### ISSUE THREAD

**Issue by uusijani** [wekan/wekan#1227]
## Issue
**Impacted version**: 0.38

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method: snap

`snap info wekan` reports snap-id as `jtpboSYvTCEyHoutkkRo1SI9ioSMOUb3` (tracking: stable). I'm not sure how to find out Node and MongoDB versions from the snap, but if the snap ID isn't enough, just show me how to get those version numbers and I'll add them.

* ROOT_URL environment variable (Is there a subfolder?): reproducible both with (https://my-domain.com/kan) and without subdirectory (http://localhost:5000 inside a VM).

**Steps to reproduce**:
1. Create a board in Trello.
2. Create a list in the board.
3. Create a card in the list.
4. Create a checklist in the card.
5. Export the board as JSON.
6. In Wekan, initiate a Trello import.
7. Map the user.

**What I expect to happen**:
For the board to be imported in Wekan.

**What happens**:
The importer reports a '400'. `journalctl -u snap.wekan.wekan.service` reports 

    Exception while invoking method 'importBoard' Error: Sort is required
         at getErrorObject (packages/aldeed_collection2-core.js:480:15)
         at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
         at [object Object].Mongo.Collection.(anonymous function) [as insert] (packag
         at packages/matb33_collection-hooks.js:127:46
         at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
         at Object.directOp (packages/matb33_collection-hooks.js:47:27)
         at Object.self.direct.(anonymous function) [as insert] (packages/matb33_coll
         at models/trelloCreator.js:407:45
         at Array.forEach (native)
         at TrelloCreator.createChecklists (models/trelloCreator.js:400:22)
         at TrelloCreator.create (models/trelloCreator.js:606:10)
         at [object Object].Meteor.methods.importBoard (models/import.js:27:20)
         at packages/check.js:130:16
         at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
         at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:
         at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    Sanitized and reported to the client as: Sort is required [400]

I'm attaching the [failing JSON](https://github.com/wekan/wekan/files/1309169/trello.json.txt) (with email sanitized).

**Comment by ocdtrekkie** [comment]
This should be fixed already when the next release comes out: https://github.com/wekan/wekan/pull/1226

**Comment by uusijani** [comment]
Can confirm: release 0.39 fixes this. Thanks!
