### ISSUE TITLE
Wekan not using email server I set

### ISSUE THREAD

**Issue by ChristopherM87** [wekan/wekan#1236]
I set my SMTP host, port, username, password and TLS in the Admin web interface. But when I try doing a password reset it uses "mailserver.examples.com" not my mail server.

> Exception while invoking method 'forgotPassword' Error: getaddrinfo ENOTFOUND mailserver.examples.com mailserver.examples.com:25
    at Object.Future.wait (/wekan/programs/server/node_modules/fibers/future.js:449:15)
    at Mail._syncSendMail (packages/meteor.js:213:24)
    at smtpSend (packages/email.js:116:13)
    at Object.Email.send (packages/email.js:174:5)
    at AccountsServer.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:614:9)
    at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:546:12)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    - - - - -
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)

I also have set the env variables SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS and SMTP_STARTTLS.

**Comment by killua-eu** [comment]
the `getaddrinfo ENOTFOUND` error means that "mailserver.examples.com" doesn't translate to a valid ip address. To resolve

- check the server name 
- use IP address instead of server name
- make sure your host can lookup domain names correctly

if the above didnt clear it up for you, try google `getaddrinfo ENOTFOUND` ...

**Comment by xet7** [comment]
@ChristopherM87 

Did you add MAIL_URL env variable?

https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

What [platform](https://github.com/wekan/wekan/wiki/Platforms) are you running Wekan on?

For Ubuntu snap, theres issue #1120

**Comment by xet7** [comment]
Please reopen issue, if you still have problems.

**Comment by ChristopherM87** [comment]
I tried tor rebuild the Docker container, now I cannot find the wekan.log file. I have /path/to/wekan/ and under there main.js, programs, README, server, star.json
Nothing in /var/log/
Where would the log file be?
