### ISSUE TITLE
Can't login/create user in docker installation

### ISSUE THREAD

**Issue by erezeshkol** [wekan/wekan#1249]
## Issue
**Impacted version**: latest

I installed and ran the server using the instructions (but without setting up a mail server): https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-for-testing

But I can't login or create a user, so it's completely unusable for me. When I try to create a user, an error is displayed: "From admin is required". Here are the docker-compose logs:
```
wekan_1    | Exception while invoking method 'ATCreateUserServer' Error: From admin is required
wekan_1    |     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
wekan_1    |     at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
wekan_1    |     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
wekan_1    |     at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1328:25)
wekan_1    |     at createUser (packages/accounts-password/password_server.js:1050:25)
wekan_1    |     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1119:10)
wekan_1    |     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core.js:1294:27)
wekan_1    |     at packages/check.js:130:16
wekan_1    |     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
wekan_1    |     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
wekan_1    |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
wekan_1    |     at packages/ddp-server/livedata_server.js:719:19
wekan_1    |     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
wekan_1    |     at packages/ddp-server/livedata_server.js:717:40
wekan_1    |     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
wekan_1    |     at packages/ddp-server/livedata_server.js:715:46
wekan_1    | Sanitized and reported to the client as: From admin is required [400]
wekan_1    |
```

**Comment by temperatio** [comment]
Same here.

**Comment by xet7** [comment]
@erezeshkol @temperatio 

Sorry, I need to revert #1232 that was added in https://github.com/wekan/wekan/pull/1241 , it still needs some work before adding it to Wekan. I will release Wekan v0.41 without it in near future.

**Comment by xet7** [comment]
@erezeshkol @temperatio 

This is already fixed in wekanteam latest tag:
https://hub.docker.com/r/wekanteam/wekan/tags/

The same will be availaibe as tag v0.41 when Docker Hub finishes building it.
