### ISSUE TITLE
Since Update Snap Wekan not Working anymore 0.73

### ISSUE THREAD

**Issue by sirup** [wekan/wekan#1471]
## Issue
**Impacted version**: 0.73

**Server Setup Information**:

* Operating System:
Ubuntu 16.04 with nginx

**Problem description**:
My snap updated from 0.63 to 0.73 today. Since then if I click a card Wekan redirects to 127.0.0.1.
I did not change anything. I tried revert the snap to 0.63, but still the same behaviour?

```
x@y:/etc/nginx/sites-enabled$` sudo systemctl status snap.wekan.wekan
● snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-02-08 15:48:51 CET; 9min ago
 Main PID: 17509 (wekan-control)
    Tasks: 11
   Memory: 273.7M
      CPU: 2min 40.631s
   CGroup: /system.slice/snap.wekan.wekan.service
           ├─17509 /bin/bash /snap/wekan/103/bin/wekan-control
           └─17520 /snap/wekan/103/bin/node main.js

Feb 08 15:50:55 y wekan.wekan[17509]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Feb 08 15:50:55y wekan.wekan[17509]:     at after (packages/matb33_collection-hooks.js:381:9)
Feb 08 15:50:55y wekan.wekan[17509]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
Feb 08 15:50:55 y wekan.wekan[17509]:     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
Feb 08 15:50:55 y wekan.wekan[17509]:     at [object Object].insert (packages/mongo/collection.js:521:37)
Feb 08 15:50:55 y wekan.wekan[17509]:     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
Feb 08 15:50:55y wekan.wekan[17509]:     at cardCreation (models/cards.js:373:14)
Feb 08 15:50:55 y wekan.wekan[17509]:     at Object.<anonymous> (models/cards.js:406:5)
Feb 08 15:50:55 y wekan.wekan[17509]:     at packages/matb33_collection-hooks.js:382:18
Feb 08 15:50:55 y3 wekan.wekan[17509]:     at Array.forEach (native)
```

**Comment by sirup** [comment]
I could solve this issue.
This was my configuration in snap:
```
    root-url:   wekan's root url, eg http://127.0.0.1, https://example.com, https://wekan.example.com, http://example.com/wekan
                No value set, using default value: 'http://127.0.0.1'
```

It worked all the time.
Now I change it to the real url and works again. Don't know why it stopped working however...

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan-snap/issues/29
