### ISSUE TITLE
Wekan is not running up - App crashing - fibers/future.js

### ISSUE THREAD

**Issue by ntaboada** [wekan/wekan#1478]
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System: Mac OSX
* Node Version: v.8.4.0

I am trying to get wekan running up. 
After running $ meteor npm install && meteor, application can't start because it starts crashing.
Seems that is missing some imports. I tried commenting the code, but another file crash too. I don't know if the problem comes from "node-fibers" dependency (i read that in different sources).

Log:

```

W20180210-00:43:15.493(-3)? (STDERR) /Users/owlblackbird/.meteor/packages/meteor-tool/.1.6.1.1dvtqef.9rrr++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180210-00:43:15.493(-3)? (STDERR) 						throw(ex);
W20180210-00:43:15.494(-3)? (STDERR) 						^
W20180210-00:43:15.494(-3)? (STDERR) 
W20180210-00:43:15.494(-3)? (STDERR) TypeError: Meteor.publishRelations is not a function
W20180210-00:43:15.495(-3)? (STDERR)     at boards.js (server/publications/boards.js:61:8)
W20180210-00:43:15.495(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180210-00:43:15.495(-3)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180210-00:43:15.496(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/app/app.js:7878:1
W20180210-00:43:15.496(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:411:36
W20180210-00:43:15.496(-3)? (STDERR)     at Array.forEach (<anonymous>)
W20180210-00:43:15.496(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:220:19
W20180210-00:43:15.496(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:471:5
W20180210-00:43:15.496(-3)? (STDERR)     at Function.run (/Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/profile.js:510:12)
W20180210-00:43:15.496(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:470:11
```

If i comment that file -->

```

W20180210-00:51:26.262(-3)? (STDERR) /Users/owlblackbird/.meteor/packages/meteor-tool/.1.6.1.1dvtqef.9rrr++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180210-00:51:26.263(-3)? (STDERR) 						throw(ex);
W20180210-00:51:26.263(-3)? (STDERR) 						^
W20180210-00:51:26.263(-3)? (STDERR) 
W20180210-00:51:26.263(-3)? (STDERR) ReferenceError: FastRender is not defined
W20180210-00:51:26.263(-3)? (STDERR)     at fast-render.js (server/publications/fast-render.js:1:1)
W20180210-00:51:26.264(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180210-00:51:26.264(-3)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180210-00:51:26.264(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/app/app.js:7861:1
W20180210-00:51:26.264(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:411:36
W20180210-00:51:26.264(-3)? (STDERR)     at Array.forEach (<anonymous>)
W20180210-00:51:26.264(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:220:19
W20180210-00:51:26.264(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:471:5
W20180210-00:51:26.264(-3)? (STDERR)     at Function.run (/Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/profile.js:510:12)
W20180210-00:51:26.265(-3)? (STDERR)     at /Users/owlblackbird/Desktop/Proyectos/package-kanban/.meteor/local/build/programs/server/boot.js:470:11
```

fast-render.js
```

FastRender.onAllRoutes(function() {
  this.subscribe('boards');
});

FastRender.route('/b/:id/:slug', function({ id }) {
  this.subscribe('board', id);
});


```

Can someone help me?

**Comment by xet7** [comment]
@ntaboada 

Install Docker for Mac, and use Docker Compose script, adding root-url etc settings there:
https://github.com/wekan/wekan-mongodb

If you want to build source, clone https://github.com/wekan/wekan repo, copy your docker-compose.yml file there with correct root-url etc settings, and do:

```
docker-compose up -d --build
```
