### ISSUE TITLE
Wekan not working after 1-3 days - Error inside

### ISSUE THREAD

**Issue by sirup** [wekan/wekan#1489]
## Issue
Snap 0.75

**Server Setup Information**:
Ubuntu 16.04

**Problem description**:
After 1-3 days Wekan Stops working (error 504 in web browser).
I have to restart the snap - then it works again.

Here ist the error log:

```
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]: Exception while invoking method '/cards/update' Error: url must be absolute and start with http:// or https://
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Object._call (packages/http/httpcall_server.js:35:11)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Object.call (packages/meteor.js:258:21)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Object.HTTP.post (packages/http/httpcall_common.js:61:20)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Meteor.wrapAsync (server/notifications/outgoing.js:2:8)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at packages/meteor.js:258:21
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at integrations.forEach.integration (server/notifications/outgoing.js:49:24)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Array.forEach (<anonymous>)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at DDPCommon.MethodInvocation.outgoingWebhooks (server/notifications/outgoing.js:48:18)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at packages/check.js:128:16
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at resolve (packages/ddp-server/livedata_server.js:1684:36)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at new Promise (<anonymous>)
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:  => awaited here:
Feb 19 13:07:34 jaf-tux-03 wekan.wekan[14271]:     at Promise.await (/snap/wekan/124/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)

```

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan-snap/issues/29
