### ISSUE TITLE
Wekan snap keeps crashing

### ISSUE THREAD

**Issue by rosmoo** [wekan/wekan#1515]
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System: Ubuntu 16.04.4 LTS
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): snap

Snap installation of Wekan keeps crashing after few hours of use. Restarting snap doesn't help, only restarting machine fixes problem. IIRC, problem started happening when swimlanes appeared. 

`
**systemctl status snap.wekan.wekan**

```
● snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2018-03-01 14:52:49 EET; 18min ago
  Process: 8233 ExecStart=/usr/bin/snap run wekan (code=exited, status=1/FAILURE)
 Main PID: 8233 (code=exited, status=1/FAILURE)

Mar 01 14:52:48 servername systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 14:52:48 servername systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Mar 01 14:52:48 servername systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
Mar 01 14:52:49 servername systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling restart.
Mar 01 14:52:49 servername systemd[1]: Stopped Service for snap application wekan.wekan.
Mar 01 14:52:49 servername systemd[1]: snap.wekan.wekan.service: Start request repeated too quickly.
Mar 01 14:52:49 servername systemd[1]: Failed to start Service for snap application wekan.wekan.
```

**journalctl -u snap.wekan.wekan**

```
Mar 01 14:52:41 servername wekan.wekan[7872]: /snap/wekan/135/programs/server/node_modules/fibers/future.js:313
Mar 01 14:52:41 servername wekan.wekan[7872]:                                                 throw(ex);
Mar 01 14:52:41 servername wekan.wekan[7872]:                                                 ^
Mar 01 14:52:41 servername wekan.wekan[7872]: MongoError: failed to connect to server [/var/snap/wekan/135/share/mongodb-27019.sock:27017] on first connect [MongoError: connect ENOENT /var/snap/wekan/135/share/mongodb-27019.sock]
Mar 01 14:52:41 servername wekan.wekan[7872]:     at Pool.<anonymous> (/snap/wekan/135/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at emitOne (events.js:116:13)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at Pool.emit (events.js:211:7)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at Connection.<anonymous> (/snap/wekan/135/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at Object.onceWrapper (events.js:317:30)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at emitTwo (events.js:126:13)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at Connection.emit (events.js:214:7)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at Socket.<anonymous> (/snap/wekan/135/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at Object.onceWrapper (events.js:315:30)
Mar 01 14:52:41 servername wekan.wekan[7872]:     at emitOne (events.js:116:13)
Mar 01 14:52:41 servername systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 14:52:41 servername systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Mar 01 14:52:41 servername systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
`
```

**Comment by xet7** [comment]
@rosmoo 

Update to latest Wekan snap:
```
sudo snap refresh
```

Do you then have this revision 136 (or newer) of Wekan? Wekan works for me.
```
$ sudo snap list
[sudo] password for user: 
Name   Version           Rev   Developer  Notes
core   16-2.31.1         4110  canonical  core
wekan  0.77-22-gbbca361  136   xet7       -
```

**Comment by xet7** [comment]
@rosmoo 

Do you still have problems with Wekan revision 136 ?

**Comment by rosmoo** [comment]
Apparently I had 0.77-18-gd454fa7  rev 135, when rev 136 was pushed to snap repository? I could almost swear that I refreshed snaps few days ago. Anyways, I'll close this for now and get back, if it keeps crashing :)

**Comment by xet7** [comment]
@rosmoo 

Today has been at least 2 new revisions pushed to snap, fixing bugs etc.
