### ISSUE TITLE
"Is comment only is required" 400 error importing Wekan boards

### ISSUE THREAD

**Issue by ttx** [wekan/wekan#1527]
**Impacted version**: 0.63
**Problem description**:
Exporting a Wekan 0.63 board (sandstorm install) and importing it into another Wekan 0.63 instance (docker install) results in the following error (after matching board users to local users):
```
Exception while invoking method 'importBoard' Error: Is comment only is required
    at getErrorObject (packages/aldeed_collection2-core.js:480:15)
    at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
    at packages/matb33_collection-hooks.js:127:46
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.directOp (packages/matb33_collection-hooks.js:47:27)
    at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
    at WekanCreator.createBoardAndLabels (models/wekanCreator.js:179:35)
    at WekanCreator.create (models/wekanCreator.js:613:26)
    at [object Object].Meteor.methods.importBoard (models/import.js:27:20)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Sanitized and reported to the client as: Is comment only is required [400]
```
**How to reproduce**:
Create a board with more than one member, export it and try to import it on a new instance.

**Workaround**:
Add "isCommentOnly":false to all users in the members array at the top of the exported JSON before importing it in the new instance.

I'm not sure if the issue is in the JSON export (failing to export the members isCommentOnly property) or in the JSON import (failing to default to isCommentOnly=false).

**Comment by xet7** [comment]
I don't know why you use old Docker install. There are import fixes in newer docker quay latest tag, although I have not tested it.

Sandstorm import/export is broken, there is work to update it, but it's not ready yet.

**Comment by ttx** [comment]
This install dates back from early February where 0.63 was recommended (while swimlanes were getting fixed). Feel free to close this if you think it's already fixed in later versions. I thought I should document the workaround somewhere, which is why I created the issue.

**Comment by xet7** [comment]
@ttx 

Please test does import work on newest Standalone Wekan.

If possible, for Standalone Wekan I recommend using Ubuntu Snap version on Debian 9 or Ubuntu 16.04 or later. Snap gets updates automatically. There has been lots of swimlanes fixes, so it's getting quite useable currently.

Sandstorm Wekan also has only couple bugs left, like import/export and creating new board. Other new features like search and swimlanes do work on board upgraded from older version. I recommend waiting for these bugs to be fixed, and not using experimental Sandstorm version yet.

**Comment by ttx** [comment]
Standalone Wekan (latest or 0.63) exports data correctly (including isCommentOnly entries). Importing that data works successfully. The issue was in trying to import JSON data produced by Sandstorm Wekan export. Which sounds like a known issue. Thanks!
