### ISSUE TITLE
What is the exact node version required by wekan

### ISSUE THREAD

**Issue by mouhong** [wekan/wekan#1533]
## Issue
**Impacted version**: 0.77

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): tar
* Node Version: 4.8.6
* MongoDB Version: 3.2

**Problem description**:

I followed the instruction https://github.com/wekan/wekan/wiki/Install-and-Update#install-a-wekan-release to install wekan manually. As stated in the doc, I installed node 4.8.6 via nvm. But when I ran `node main.js`, it said:
```
/var/www/wekan/bundle/programs/server/boot.js:50
    const { pause } = require("./debug.js");
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/wekan/bundle/main.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Looks like the syntax is not recognized by node 4.8.6. 

But if I install node 9.8, and then remove the packages:
```
sudo rm -rf /usr/local/lib/node_modules
sudo rm -rf ~/.npm
rm -rf wekan-VERSION/bundle/programs/server/node_modules
```

and then run `node main.js` again, it said:
```
The module '/var/www/wekan/bundle/programs/server/npm/node_modules/bson-ext/build/Release/bson.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:678:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at bindings (/var/www/wekan/bundle/programs/server/npm/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/var/www/wekan/bundle/programs/server/npm/node_modules/bson-ext/ext/index.js:10:30)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
```

So what is the exact node version is required by wekan? Is there any one can help? Thanks.

**Comment by mouhong** [comment]
It partially works even though I got those errors if I use node 9.8. 
It can show boards, but can't show cards in the boards because nginx returns 502 bad gateway for /sockjs. 

Then I downgraded node to 8.6.4, and the 502 error is gone. However, it keeps signing me out every N seconds (login > go to a board > show cards > all cards disappeared and it shows "you are not authorized to view this page" after a few seconds). I dump data from another wekan installation and restore to the mongo manually.

Really hard to get it to work. :(

**Comment by xet7** [comment]
@mouhong 

Please install snap release from https://github.com/wekan/wekan/releases , it is easiest.

Node versions etc are listed at https://github.com/wekan/wekan/blob/devel/Dockerfile

**Comment by xet7** [comment]
@mouhong 

Newer versions of node don't work yet, see https://github.com/wekan/wekan/issues/1522

**Comment by xet7** [comment]
Recommended way to install Wekan:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
@compumatter 

You can install bundle from:
https://github.com/wekan/wekan/wiki/Platforms

It requires only node/npm/mongodb.

It does not have Snap or Docker.
