### ISSUE TITLE
Error: Removed nonexistent document

### ISSUE THREAD

**Issue by RCohenE5Group** [wekan/wekan#1629]
## Issue

**Server Setup Information**:

* Operating System:Debian
* Deployment Method(snap/sandstorm/mongodb bundle):Snap
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):Nginx
* Node Version:?
* MongoDB Version:?
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): ?

**Problem description**:
Hello
One of our users could not see the content of boards.
The menus works all right, but nothing is shown in the div <div class="board-canvas js-swimlanes js-perfect-scrollbar is-sibling-sidebar-open ui-sortable"></div>

![wekan](https://user-images.githubusercontent.com/17500859/39697640-e38f83f4-51f1-11e8-80f2-58246c271c85.jpg)

On the /var/sys/log I can see : 
```
May  7 12:18:15 wekan wekan.wekan[23269]: Exception in removed observe/observeChanges callback: Error: Removed nonexistent document 8GoEvLevyjxFyrnDo
May  7 12:18:15 wekan wekan.wekan[23269]:     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
May  7 12:18:15 wekan wekan.wekan[23269]:     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
May  7 12:18:15 wekan wekan.wekan[23269]:     at Subscription.removed (packages/ddp-server/livedata_server.js:1292:19)
May  7 12:18:15 wekan wekan.wekan[23269]:     at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
May  7 12:18:15 wekan wekan.wekan[23269]:     at runWithEnvironment (packages/meteor.js:1240:24)
May  7 12:18:15 wekan wekan.wekan[23269]:     at packages/meteor.js:1253:14
May  7 12:18:15 wekan wekan.wekan[23269]:     at packages/mongo/observe_multiplex.js:182:30
May  7 12:18:15 wekan wekan.wekan[23269]:     at Array.forEach (<anonymous>)
May  7 12:18:15 wekan wekan.wekan[23269]:     at Function._.each._.forEach (packages/underscore.js:139:11)
May  7 12:18:15 wekan wekan.wekan[23269]:     at Object.task (packages/mongo/observe_multiplex.js:176:9)
May  7 12:18:15 wekan wekan.wekan[23269]:     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)
May  7 12:18:15 wekan wekan.wekan[23269]:     at packages/meteor.js:846:12
```

As I don't understand how to solve this, I tried to create a new user with the same email. As there is no "delete user" function, I changed the email of the previous one, and invited the user with the same email. But I had the error : 

```
May  7 12:01:33 wekan wekan.wekan[23269]: Exception in callback of async function: Error: Email must be unique [invitation-generated-fail]
May  7 12:01:33 wekan wekan.wekan[23269]:     at models/settings.js:138:21
May  7 12:01:33 wekan wekan.wekan[23269]:     at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
May  7 12:01:33 wekan wekan.wekan[23269]:     at packages/mongo/collection.js:618:5
May  7 12:01:33 wekan wekan.wekan[23269]:     at args.(anonymous function) (packages/matb33_collection-hooks.js:391:23)
May  7 12:01:33 wekan wekan.wekan[23269]:     at runWithEnvironment (packages/meteor.js:1240:24)
May  7 12:01:33 wekan wekan.wekan[23269]:     at packages/meteor.js:1253:14
May  7 12:01:33 wekan wekan.wekan[23269]:     at packages/mongo/mongo_driver.js:319:7
May  7 12:01:33 wekan wekan.wekan[23269]:     at runWithEnvironment (packages/meteor.js:1240:24)
```

It seems that somewhere the old email is kept I don't know where.
I'm completely blocked and the user cannot see boards. Please tell me where I can unlock this.
Thanks a lot.

**Comment by xet7** [comment]
Export boards, and import them to new install of Wekan Snap.
