### ISSUE TITLE
Attachments.forEach is not a function (1.08 release)

### ISSUE THREAD

**Issue by gramakri** [wekan/wekan#1734]
## Issue

**Server Setup Information**:
Wekan on Cloudron

* Did you test in newest Wekan?:
Yes

* Wekan version:
1.08

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Cloudron
* Node Version:
8.9.4

**Problem description**:

I am updating the Wekan package on Cloudron. The 1.08 release seems to crash at startup when running the migrations. This is a fresh wekan installation.

```
10:25:47 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] + exec /usr/local/bin/gosu cloudron:cloudron node /app/code/.build/bundle/main.js
10:25:48 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] Presence started serverId=85eqnoTdeJaLM5RvQ
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] > Starting change-attachments-type-for-non-images migration.
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] /app/code/.build/bundle/programs/server/node_modules/fibers/future.js:280
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] 						throw(ex);
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] 						^
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] 
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f] TypeError: Attachments.forEach is not a function
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f]     at Object.Migrations.add [as migrationCallback] (server/migrations.js:58:15)
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f]     at packages/idmontie_migrations.js:238:17
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f]     at Function.time (/app/code/.build/bundle/programs/server/profile.js:309:28)
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f]     at /app/code/.build/bundle/programs/server/boot.js:423:13
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f]     at /app/code/.build/bundle/programs/server/boot.js:464:5
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f]     at Function.run (/app/code/.build/bundle/programs/server/profile.js:510:12)
10:25:49 [eb40e154-5ab0-4227-baa0-5e81dd9bea7f]     at /app/code/.build/bundle/programs/server/boot.js:462:11
```

**Comment by xet7** [comment]
@gramakri 

Thanks ! I will make release v1.09 to fix this soon.

**Comment by gramakri** [comment]
Thanks @xet7 !
