### ISSUE TITLE
Checklists.forEach is not a function; data migration

### ISSUE THREAD

**Issue by centigrade-kdk** [wekan/wekan#1753]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: YES
* Wekan version: v1.13
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker

**Problem description**:

Currently we stuck in Version v0.60 because of all the migration Problems.
First we were effected by: https://github.com/wekan/wekan/issues/1576 and now are we see following error during startup of v1.13 with the date from v0.60:

```
TypeError: Checklists.forEach is not a function
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:183:14)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/build/programs/server/profile.js:309:28)
    at /build/programs/server/boot.js:423:13
    at /build/programs/server/boot.js:464:5
    at Function.run (/build/programs/server/profile.js:510:12)
    at /build/programs/server/boot.js:462:11
```

**Comment by centigrade-kdk** [comment]
@xet7 After your changes I get now following error:

```
Error: Title is required
    at getErrorObject (packages/aldeed_collection2-core.js:480:15)
    at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
    at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
    at packages/matb33_collection-hooks.js:127:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object.directOp (packages/matb33_collection-hooks.js:47:27)
    at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
    at _.sortBy.forEach (server/migrations.js:186:29)
    at Array.forEach (<anonymous>)
    at Checklists.find.forEach.checklist (server/migrations.js:185:39)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:183:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/build/programs/server/profile.js:309:28)
    at /build/programs/server/boot.js:423:13
```

**Comment by centigrade-kdk** [comment]
@xet7 Is it really necessary that checklists have a title?
If yes than the migration process should give them a title if they didn't have a title before

See: https://github.com/wekan/wekan/blob/4b65c5cc3359eb090e87498b3501629cb54081e2/server/migrations.js#L187

**Comment by xet7** [comment]
@centigrade-kdk 

Do you still have errors in upgrade to Wekan v1.14 ?

**Comment by xet7** [comment]
@centigrade-kdk

Please add full error messages you get.

**Comment by xet7** [comment]
@centigrade-kdk 

Sorry, now I noticed you already added error messages. I'll look at it.

**Comment by centigrade-kdk** [comment]
In parallel I try out following bugfix `title: (item.title ? item.title : 'Automatically chosen name during migration'),` for line https://github.com/wekan/wekan/blob/4b65c5cc3359eb090e87498b3501629cb54081e2/server/migrations.js#L187

**Comment by xet7** [comment]
I try making title optional.

**Comment by xet7** [comment]
I made this change:
```
wekan$ git diff
diff --git a/models/checklists.js b/models/checklists.js
index c58453e..2277736 100644
--- a/models/checklists.js
+++ b/models/checklists.js
@@ -7,6 +7,7 @@ Checklists.attachSchema(new SimpleSchema({
   title: {
     type: String,
     defaultValue: 'Checklist',
+    optional: true,
   },
   finishedAt: {
     type: Date,
```
I will add it to new release.

**Comment by centigrade-kdk** [comment]
The fix I tried worked, so making it optional should do the job as well

**Comment by xet7** [comment]
Actually, I think it's better that I set default value in migration, using your example. Thanks!

**Comment by centigrade-kdk** [comment]
@xet7 It looks like that the optional property does not have any effect.
I still get the exact same error as before.
Overall I would argue, that it is good that we enforce a title for checklists. Maybe it has also other negative effects if we allow undefined title properties.

Using a english default title is a bad UX for users who selected an other language, but I don't think this will happen often. All migrations after this bugfix won't encounter this problem.

**Comment by xet7** [comment]
@centigrade-kdk 

Thanks! I will fix it in next release.
