### ISSUE TITLE
[Issue] Exception while invoking method 'importBoard' Error: Checklist id is required

### ISSUE THREAD

**Issue by d3dbit** [wekan/wekan#1761]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: v1.18
* Operating System: Ubuntu 18.04 LTS (Google Computer Engine)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker v18.03.1-ce
* Node Version: v8.11.3
* MongoDB Version: v3.2.20 

**Problem description**:
- After trying to restore a Board from a JSON Backup I have received the next exception:
```
Exception while invoking method 'importBoard' Error: Checklist id is required
    at getErrorObject (packages/aldeed_collection2-core.js:480:15)
    at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
    at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
    at packages/matb33_collection-hooks.js:127:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object.directOp (packages/matb33_collection-hooks.js:47:27)
    at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
    at wekanChecklistItems.forEach (models/wekanCreator.js:471:53)
    at Array.forEach (<anonymous>)
    at WekanCreator.createChecklistItems (models/wekanCreator.js:462:25)
    at WekanCreator.create (models/wekanCreator.js:674:10)
    at DDPCommon.MethodInvocation.importBoard (models/import.js:27:20)
    at packages/check.js:128:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
Sanitized and reported to the client as: Checklist id is required [400]
```

**Comment by xet7** [comment]
@d3dbit 

From what Wekan version JSON backup file is?

**Comment by d3dbit** [comment]
JSON backup from: v1.11
I have tried to restore it to: v1.18

**Comment by hever** [comment]
Maybe same problem - my import of backup does not working well, some checklist items not imported. Trying to find where's problem and found something.

Create checklist -> Create item -> Delete checklist

Then when you try export board, import will fail. This is because there is something like this:

`... checklists":[],"checklistItems":[{"_id":"5obmCiwjxew6saRjb","title":"item","checklistId":"w8w947vMNgH3QiD25","cardId":"ZJx9zBRaGKxsLjEZg","sort":0,"isFinished":false,"userId":"GPgtvBwTB6kzdYruj"}], ...`

No checklists, but checklistItems. Maybe there is problem in moment of deleting checklist, that items of deleted checklist still exists. Or if this is some feature, import may ignore this item and go to the next items. Now, it will stop importing items of checklists and at the end of import, there's message "400".

**Comment by xet7** [comment]
@d3dbit @hever 

Please test with newest Wekan v1.34. Thanks!

**Comment by xet7** [comment]
@d3dbit @hever 

Does this still happen on newest Wekan?
