### ISSUE TITLE
Error 400 v1.43 Each time we want to import a board

### ISSUE THREAD

**Issue by fulollo** [wekan/wekan#1880]
Hi, someone have an idea to solve it?
Thank you

**Comment by xet7** [comment]
@fulollo 

Are you sure you are running v1.43 ? Because I fixed import bug already in it.
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v143-2018-09-06-wekan-release

What Wekan snap version you have?
```
sudo snap list
```
Does updating help?
```
sudo snap refresh
```
What do logs say?
```
sudo snap logs wekan.wekan
```
Or if you are running on Docker, what do Docker logs say?
```
sudo docker logs wekan-app
```

**Comment by fulollo** [comment]
@xet7 
the updating don't help.

order results for snap list :
Name   Version  Rev   Tracking  Publisher   Notes
core   16-2.35  5328  stable    canonicalâ  core
wekan  1.43     259   stable    xet7        -

order results for snap logs wekan.wekan :
administrateur@SRV-PROJECT:~$ sudo snap logs wekan.wekan
2018-09-07T09:49:01Z wekan.wekan[9228]:     at WekanCreator.createBoardAndLabels                                                                                                                                                      (models/wekanCreator.js:196:35)
2018-09-07T09:49:01Z wekan.wekan[9228]:     at WekanCreator.create (models/wekan                                                                                                                                                     Creator.js:670:26)
2018-09-07T09:49:01Z wekan.wekan[9228]:     at DDPCommon.MethodInvocation.import                                                                                                                                                     Board (models/import.js:27:20)
2018-09-07T09:49:01Z wekan.wekan[9228]:     at packages/check.js:128:16
2018-09-07T09:49:01Z wekan.wekan[9228]:     at Meteor.EnvironmentVariable.EVp.wi                                                                                                                                                     thValue (packages/meteor.js:1186:15)
2018-09-07T09:49:01Z wekan.wekan[9228]:     at Object._failIfArgumentsAreNotAllC                                                                                                                                                     hecked (packages/check.js:127:41)
2018-09-07T09:49:01Z wekan.wekan[9228]:     at maybeAuditArgumentChecks (package                                                                                                                                                     s/ddp-server/livedata_server.js:1765:18)
2018-09-07T09:49:01Z wekan.wekan[9228]:     at DDP._CurrentMethodInvocation.with                                                                                                                                                     Value (packages/ddp-server/livedata_server.js:719:19)
2018-09-07T09:49:01Z wekan.wekan[9228]:     at Meteor.EnvironmentVariable.EVp.wi                                                                                                                                                     thValue (packages/meteor.js:1186:15)
2018-09-07T09:49:01Z wekan.wekan[9228]: Sanitized and reported to the client as:                                                                                                                                                      Is no comments is required [400]

**Comment by xet7** [comment]
@fulollo 

When importing, did you map all trello users to same already previously created existing wekan users?

**Comment by xet7** [comment]
@fulollo 

Username in wekan can be different than username in trello. But for each imported user on board there should be existing user in wekan.

**Comment by xet7** [comment]
@fulollo 

Here is how to add users:
https://github.com/wekan/wekan/wiki/Adding-users

**Comment by xet7** [comment]
Hmm, actually it's also enough if one user is mapped. I'll try to find a way to duplicate this bug.

**Comment by xet7** [comment]
@fulollo 

Is the problem same if you try to import some other Trello board?

**Comment by fulollo** [comment]
@xet7  
I tried to import a board, exported from the same server

**Comment by xet7** [comment]
@fulollo 

Ok, it seems that import of Wekan board does not work correctly. Thanks for reporting! I'll look how to fix this.

I did not get error 400, but it still did not import all.

**Comment by xet7** [comment]
Moved to #1903
