### ISSUE TITLE
Admin panel: delete users

### ISSUE THREAD

**Issue by HLFH** [wekan/wekan#1889]
Hi,

## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.45.0
* Operating System: Ubuntu 18.04.1
* Deployment Method: source
* Http frontend if any: Nginx
* Node Version: 8.12.0
* ROOT_URL environment variable: https://wekan.example.com

**Problem description**:
> meteor npm install --save source-map-support

is fixing the following issue:

>  % node main.js
/srv/http/wekan/programs/server/boot.js:151
sourcemap_support.install({
                  ^

TypeError: sourcemap_support.install is not a function
    at Object.<anonymous> (/srv/http/wekan/programs/server/boot.js:151:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/http/wekan/main.js:4:1)
    at Module._compile (module.js:653:30)

On Wekan 1.45.0.
Also, instead of making some users only inactive, I would love to delete them on the https://wekan.example.com/people page.

**Comment by xet7** [comment]
Admin Panel issue moved to #802
