### ISSUE TITLE
The new Avatar feature seems to be broken

### ISSUE THREAD

**Issue by nata-goddanti** [wekan/wekan#190]
I tried to upload a image, but the image does not seem to be showing up. Also the initials does not seem to be appearing on the avatar when the image is not shown. 

![image](https://cloud.githubusercontent.com/assets/203255/8133582/19bec992-10de-11e5-9eda-1e353256525f.png)

![image](https://cloud.githubusercontent.com/assets/203255/8133606/3cef6bba-10de-11e5-9bf3-003abae412ff.png)

**Comment by ePirat** [comment]
Which browser are you using?

**Comment by nata-goddanti** [comment]
I am using Google Chrome.

**Comment by ePirat** [comment]
Are you sure you are running the latest version in production mode? Can't reproduce the problem here.

**Comment by nata-goddanti** [comment]
That is weird. I am using the latest instance at newui.libreboard.com. My Chrome version is Version 43.0.2357.124 (64-bit). The avatar image I was trying to load is a 84kb Jpeg image. When I checked the console I am getting this error:


4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:3 Exception in template helper: TypeError: Cannot read property '0' of undefined
    at t.Users.helpers.getInitials (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:380:896)
    at Object.Template.userAvatarInitials.helpers.initials (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:358:540)
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4038
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:63:16446
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4286
    at Function.e._withTemplateInstanceFunc (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:64:3107)
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4193
    at f.call (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1842)
    at f.mustacheImpl (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1097)
    at Object.f.mustache (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1156)
2015-06-16 10:45:09.766 4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:3 Exception in template helper: TypeError: Cannot read property '0' of undefined
    at t.Users.helpers.getInitials (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:380:896)
    at Object.Template.userAvatarInitials.helpers.viewPortWidth (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:358:629)
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4038
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:63:16446
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4286
    at Function.e._withTemplateInstanceFunc (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:64:3107)
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4193
    at f.call (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1842)
    at f.mustacheImpl (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1097)
    at Object.f.mustache (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1156)
2015-06-16 10:45:09.766 4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:63 Error: Invalid value for <svg> attribute viewBox="0 0  15"p.update @ 4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:63
2015-06-16 10:45:09.767 4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:3 Exception in template helper: TypeError: Cannot read property '0' of undefined
    at t.Users.helpers.getInitials (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:380:896)
    at Object.Template.userAvatarInitials.helpers.initials (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:358:540)
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4038
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:63:16446
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4286
    at Function.e._withTemplateInstanceFunc (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:64:3107)
    at http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:202:4193
    at f.call (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1842)
    at f.mustacheImpl (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1097)
    at Object.f.mustache (http://newui.libreboard.com/4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:152:1156)
2015-06-16 10:45:23.748 4ca0a43a23e4bc25748de1d84c79b427ad567c97.js:128 Uncaught Error: FS.Collection insert: file does not pass collection filters

**Comment by mquandalle** [comment]
I understand the error, will fix it.

**Comment by ePirat** [comment]
I don't think that this is really the latest development version there, not sure.

**Comment by nata-goddanti** [comment]
@mquandalle  I still could not able to upload the avatar, which is a 84kb jpeg image, although I am seeing the initials. Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/203255/8194633/a4be98c8-1431-11e5-9794-473e18fb3576.png)

when I was looking in to the console, I am getting this error. 


d9cbcd2da4ba004d1ace25ea7f2a8ea70d480d77.js:128 Uncaught Error: FS.Collection insert: file does not pass collection filters

**Comment by nata-goddanti** [comment]
I was testing on firefox and it does give the same error as well.

![image](https://cloud.githubusercontent.com/assets/203255/8194774/b156e918-1432-11e5-9c6b-a44edd2558c9.png)

**Comment by mquandalle** [comment]
That's because there is a (somehow arbitrary) 32Kio limit on avatar size (see https://github.com/libreboard/libreboard/blob/80a4bdd417f6d11b828ca9a2f09c0d87ae7efe48/collections/avatars.js#L6).

This limitation is here because we don't have any server-side image compression infrastructure for now (and it is not easy to set up, as we need to handle any supported platforms), so avatars are sent to there full size to the clients. Should I set a higher limit?

And yes we need better error reporting, but that whole avatar thing is pretty boring to implement. I hope will be able to extract this feature in a community maintained package reasonably soon.

**Comment by ePirat** [comment]
I think using some tool like imagemagick (optionally) like a lot of other web apps and software (i.e. Mediawiki) does, should be a reasonable way to handle this, although not that easy to implement.

**Comment by mquandalle** [comment]
Yes this would be reasonable, but the problem is that I want LibreBoard to be easily self-hostable, which mean that I have to make sure the imagemagick binary is installed in every supported targets (ie, docker images, sandstorm package, heroku image, and manual installation). This is too much work for me to be implemented for the next release.

**Comment by ePirat** [comment]
Yeah sure, that's why I suggested to make it optional, no matter when the feature will be added. So if there is for some reason no imagemagick it should just use the avatar without conversion if it is reasonable small.

**Comment by nata-goddanti** [comment]
Then, how about increasing the size to say 60 or 70 (or may be 100 as upper limit),  as most avatars fit in to that limit, till there is a reasonable solution in the community maintained package.

**Comment by PrestonL** [comment]
It might even help if it at the very least, the interface said: "Upload Avatar (70Kb Limit)".  Setting the limit to even 128KB would help.

**Comment by 1kidvidiot** [comment]
This error is still here, and is doing exactly the same as described above.

**Comment by MarinaBoboshko** [comment]
Still reproduce. Also not upload jpeg of any size
