### ISSUE TITLE
Cannot setup mail server via snap variables

### ISSUE THREAD

**Issue by suprovsky** [wekan/wekan#1906]
## Issue
I am unable to set up a mail server name via snap variable mail-from. When I perform the same action the same server credentials from Admin Panel, everything work smoothly.
Because full user name is incorrect, my mailer-daemon from my mailbox server send me notifications sent by an email set in variable. When I enter my notifier email credentials in Admin Panel with the same mail-from data, I got the email from a right sender.
**Server Setup Information**:

* Did you test in newest Wekan?: Of course!
* Wekan version: 1.49
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: v8.12.0
* MongoDB Version: completely no idea how could I check it in snap :(
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://subdomain.example.com

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
It is not needed to add it, I gave verbose info below.
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
Not a problem inside a browser.
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
```
my-hostname ~ # snap logs wekan.wekan
2018-09-20T15:20:57Z wekan.wekan[1463]: OAUTH2_USERINFO_ENDPOINT= (default value)
2018-09-20T15:20:57Z wekan.wekan[1463]: OAUTH2_TOKEN_ENDPOINT= (default value)
2018-09-20T15:20:57Z wekan.wekan[1463]: MONGO_URL=mongodb:///var/snap/wekan/274/share/mongodb-27019.sock/wekan
2018-09-20T15:21:05Z wekan.wekan[1463]: Presence started serverId=nevermind
2018-09-20T15:21:05Z wekan.wekan[1463]: Note: you are using a pure-JavaScript implementation of bcrypt.
2018-09-20T15:21:05Z wekan.wekan[1463]: While this implementation will work correctly, it is known to be
2018-09-20T15:21:05Z wekan.wekan[1463]: approximately three times slower than the native implementation.
2018-09-20T15:21:05Z wekan.wekan[1463]: In order to use the native implementation instead, run
2018-09-20T15:21:05Z wekan.wekan[1463]:   meteor npm install --save bcrypt
2018-09-20T15:21:05Z wekan.wekan[1463]: in the root directory of your application.
```
- *If logs are very long, attach them in .zip file*
They are not, just posted below. Let me know if it is not enough.

```
my-hostname ~ # snap get wekan
Key        Value
mail-from  Wekan Notifications <wekan@mydomain.com>
mail-url   smtps://mylogin@mailserver.net:mysupersecretpassword@mailserver.net:465/
port       3000
root-url   https://mydomain.com
```

```
my-hostname ~ # ufw status
Status: inactive
```

```
my-hostname ~ # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain f2b-sshd (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

```
my-hostname ~ # snap run wekan 'mongodb --version'
MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/274/share (default value)
MONGODB_BIND_IP= (default value)
MONGODB_PORT=27019 (default value)
MAIL_URL=smtps://mylogin@mailserver.net:mysupersecretpassword@mailserver.net:465/
MAIL_FROM=Wekan Notifications <wekan@mydomain.com>
/snap/wekan/274/bin/wekan-read-settings: line 18: export: `<mylogin@mailserver.net>': not a valid identifier
ROOT_URL=https://mydomain.com
PORT=3000
DISABLE_MONGODB=false (default value)
CADDY_ENABLED=false (default value)
CADDY_BIND_PORT=3001 (default value)
WITH_API=true (default value)
MATOMO_ADDRESS= (default value)
MATOMO_SITE_ID= (default value)
MATOMO_DO_NOT_TRACK=true (default value)
MATOMO_WITH_USERNAME=false (default value)
BROWSER_POLICY_ENABLED=true (default value)
TRUSTED_URL= (default value)
WEBHOOKS_ATTRIBUTES= (default value)
OAUTH2_CLIENT_ID= (default value)
OAUTH2_SECRET= (default value)
OAUTH2_SERVER_URL= (default value)
OAUTH2_AUTH_ENDPOINT= (default value)
OAUTH2_USERINFO_ENDPOINT= (default value)
OAUTH2_TOKEN_ENDPOINT= (default value)
MONGO_URL=mongodb:///var/snap/wekan/274/share/mongodb-27019.sock/wekan
Presence started serverId=nevermind
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
supra-ovh ~ # snap run wekan /bin/bash
MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/274/share (default value)
MONGODB_BIND_IP= (default value)
MONGODB_PORT=27019 (default value)
MAIL_URL=smtps://mylogin@mailserver.net:mysupersecretpassword@mailserver.net:465/
MAIL_FROM=Wekan Notifications <mylogin@mailserver.net>
/snap/wekan/274/bin/wekan-read-settings: line 18: export: `<mylogin@mailserver.net>': not a valid identifier
ROOT_URL=https://mydomain.com
PORT=3000
DISABLE_MONGODB=false (default value)
CADDY_ENABLED=false (default value)
CADDY_BIND_PORT=3001 (default value)
WITH_API=true (default value)
MATOMO_ADDRESS= (default value)
MATOMO_SITE_ID= (default value)
MATOMO_DO_NOT_TRACK=true (default value)
MATOMO_WITH_USERNAME=false (default value)
BROWSER_POLICY_ENABLED=true (default value)
TRUSTED_URL= (default value)
WEBHOOKS_ATTRIBUTES= (default value)
OAUTH2_CLIENT_ID= (default value)
OAUTH2_SECRET= (default value)
OAUTH2_SERVER_URL= (default value)
OAUTH2_AUTH_ENDPOINT= (default value)
OAUTH2_USERINFO_ENDPOINT= (default value)
OAUTH2_TOKEN_ENDPOINT= (default value)
MONGO_URL=mongodb:///var/snap/wekan/274/share/mongodb-27019.sock/wekan
Presence started serverId=q3ieRFeSkCeMo2KtS
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

```

**Comment by xet7** [comment]
Do you have both Rocket.Chat and Wekan installed on same server? Because it seems node does not start, there is EADDRINUSE error of something already running at same port

Usually Rocket.Chat is at port 3000 and Wekan at port 3001, like this:
https://github.com/wekan/wekan/wiki/OAuth2#2-install-wekan

**Comment by suprovsky** [comment]
> Do you have both Rocket.Chat and Wekan installed on same server? Because it seems node does not start, there is EADDRINUSE error of something already running at same port
> 
> Usually Rocket.Chat is at port 3000 and Wekan at port 3001, like this:
> https://github.com/wekan/wekan/wiki/OAuth2#2-install-wekan

The only thing which can use this port is another Wekan instance, I think that generated this error.
I think a root of the problem are these lines:
```
MAIL_FROM=Wekan Notifications <mylogin@mailserver.net>
/snap/wekan/274/bin/wekan-read-settings: line 18: export: `<mylogin@mailserver.net>': not a valid identifier
```
This error happens when the variable is exported by ``export`` command with wrong syntax and I have completely no idea which I have done wrong, because I used the same mail-from template from [Email Troubleshooting](https://github.com/wekan/wekan/wiki/Troubleshooting-Mail) section.

I have not configured any OAuth yet and I think I will do it after we resolve this problem.
