### ISSUE TITLE
Access denied [403] on download attachment

### ISSUE THREAD

**Issue by mabushey** [wekan/wekan#1958]
## Issue

**Server Setup Information**:
Using docker-compose, with jwilder proxy & lets encrypt companion for SSL.

* Did you test in newest Wekan?:
Using image `quay.io/wekan/wekan`

* Wekan version:
No idea how to find this, not in admin panel

* Operating System:
Docker on Ubuntu 18.04

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
docker-compose

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
jwilder nginx proxy

* Node Version:
```
wekan@80a6aca92829:/$ node -v
v8.12.0
```
* MongoDB Version:
`image: mongo:3.2.21`
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):
https://todo.[redacted].com

**Problem description**:
- *Explain steps how to reproduce*
Upload pdf. Click download link under attachment

- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
`docker logs -f wekan-app` does not log anything for this error. I do have this in the log:
```
Exception in removed observe/observeChanges callback: Error: Removed nonexistent document jHXp7shgKGD22Pcfv
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:394:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1292:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1240:24)
    at packages/meteor.js:1253:14
    at packages/mongo/observe_multiplex.js:182:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:176:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)
    at packages/meteor.js:846:12
```

**Comment by zypA13510** [comment]
> Wekan version:
> No idea how to find this, not in admin panel

You can find it from admin panel -> Version (top navigation, along with _People_ and _Settings_)

**Comment by xet7** [comment]
Try newest Wekan.
