### ISSUE TITLE
Windows installation from source problems

### ISSUE THREAD

**Issue by arradoq** [wekan/wekan#1984]
I'm new on wekan, or even meteor. Currently starting to interested on wekan and there occur some problem during running git bash >meteor

Here is the log for the error
`Errors prevented startup:

   While selecting package versions:
   error: unknown package in top-level dependencies: wekan:wekan-ldap
   unknown package in top-level dependencies: wekan:accounts-cas
`
If anyone has some solution, I would try it right now

**Comment by tugal** [comment]
Hey

mkdir -p ~/repos/wekan/packages
cd ~/repos/wekan/packages
git clone https://github.com/wekan/wekan-ldap.git wekan-ldap
git clone https://github.com/wekan/accounts-cas.git accounts-cas

**Comment by xet7** [comment]
I added some beginning of build scripts here, but did run out of time, please try to add more to them as PRs. They are not finished yet.

https://github.com/wekan/wekan/blob/edge/rebuild-wekan.bat

https://github.com/wekan/wekan/blob/edge/start-wekan.bat

**Comment by KrunalDholakiya** [comment]
After running rebuild-wekan.bat, I'm facing below issues:

PS C:\repos\wekan> meteor update --all-packages
kadira:flow-router: updating npm dependencies -- page, qs...
C:\Users\krunal_dholakiya\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\krunal_dholakiya\AppData\Local\.meteor\packages\lucasantoniassi_accounts-lockout\1.0.0\os\accounts-lockout.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.wrapper [as open] (C:\tools\fs\files.js:1609:35)
    at Object.files.readBufferWithLengthAndOffset (C:\tools\fs\files.js:1860:20)
    at C:\tools\isobuild\unibuild.js:122:26
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\krunal_dholakiya\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Function.fromJSON (C:\tools\isobuild\unibuild.js:119:7)
    at C:\tools\isobuild\isopack.js:921:33
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\krunal_dholakiya\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:908:7)
    at Isopack.initFromPath (C:\tools\isobuild\isopack.js:828:17)
    at C:\tools\isobuild\isopack-cache.js:280:23
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at Profile.time (C:\tools\isobuild\isopack-cache.js:266:24)
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:256:15)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\krunal_dholakiya\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74:24)
    at C:\tools\project-context.js:869:25
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:868:18)
    at C:\tools\project-context.js:300:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
    at Profile.run (C:\tools\project-context.js:282:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
    at C:\tools\cli\commands-packages.js:1610:20
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.main.captureAndExit (C:\tools\cli\main.js:275:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1609:8)
    at Command.func (C:\tools\cli\commands-packages.js:1683:29)
    at C:\tools\cli\main.js:1531:15

**Comment by xet7** [comment]
@KrunalDholakiya

rebuild-wekan.bat does not work yet.

This wiki page lists what ways work currently:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

There is making new Wekan website in progress that would make finding these easier.

**Comment by KrunalDholakiya** [comment]
@xet7 Ok got it. Basically my purpose is I want to have my custom Wekan app where i want to do few modification as per my requirement. Can you guide me to do it? Using meteor command I'm able to run the app but whenever I make changes in code its not reflecting in browser. Or should I use wekan-dev?

**Comment by xet7** [comment]
@KrunalDholakiya 

Please add new GitHub issue with topic and description of feature you want to add to Wekan. I will guide you how to get it added to official Wekan, so you don't need to keep modifying source all the time.

**Comment by xet7** [comment]
@KrunalDholakiya 

Add issue to here https://github.com/wekan/wekan/issues

**Comment by KrunalDholakiya** [comment]
@xet7 issue added. Below is the link.
https://github.com/wekan/wekan/issues/2276#issue-423592602
