### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by Broxxx3** [wekan/wekan#2004]
Cannot login to snap version 1.71.0
No POST or GET, no console messages, no websock activity, no reaction at all.
A revert to v1.70.0 helps, in 1.70.0 everything is fine.

Linux Ubuntu 4.4.0-139-generic

**Comment by xet7** [comment]
Strange, login works for me on snap 1.71.0

Do you still have root-url etc set correctly? If not, set them again.
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys
```
sudo snap get wekan
```
Are your your snap services running enabled and active?
```
$ sudo snap services
Service                              Startup  Current
wekan.caddy                          enabled  active
wekan.mongodb                        enabled  active
wekan.wekan                          enabled  active
```
Is your login method correct, password or LDAP ?
```
mongo --port 27019

use wekan

db.users.find();
```
Does your wekan webpage load at all?

**Comment by xet7** [comment]
Here is script for mongo shell:
https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
@Akuket 

Do you have any ideas how to debug this? Does password and LDAP login work for you?

**Comment by xet7** [comment]
@Akuket 

When I build wekan from source and start with command meteor, I get this error when logging in or registering. After some tries, registering and logging in works.
```
$ cd wekan
$ meteor --port 4000
=> App running at: http://localhost:4000/
I20181117-16:05:33.271(2)? Exception from sub user-authenticationMethod id D74tDK98ppsytEEkq Error: Match error: Expected string, got null
I20181117-16:05:33.272(2)?     at exports.check (packages/check.js:55:15)
I20181117-16:05:33.272(2)?     at Subscription.<anonymous> (server/publications/users.js:22:3)
I20181117-16:05:33.272(2)?     at packages/matb33_collection-hooks.js:307:21
I20181117-16:05:33.272(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20181117-16:05:33.273(2)?     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
I20181117-16:05:33.273(2)?     at packages/check.js:128:16
I20181117-16:05:33.273(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20181117-16:05:33.273(2)?     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
I20181117-16:05:33.274(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
I20181117-16:05:33.274(2)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
I20181117-16:05:33.274(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20181117-16:05:33.282(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20181117-16:05:33.282(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20181117-16:05:33.282(2)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20181117-16:05:33.282(2)?     at packages/ddp-server/livedata_server.js:559:43
I20181117-16:05:33.283(2)? Sanitized and reported to the client as: Match failed [400]
```

**Comment by Akuket** [comment]
Hello,

@Broxxx3 Did you try to use the LDAP authentication? If it was for registering one user and the environment variable DEFAULT_AUTHENTICATION_METHOD wasn't defined, it's normal. But if it was for logging in with an existing account, I don't know why because it works fine for me.

For the standard registering process, i have

**Comment by xet7** [comment]
Login failure is already fixed.
