### ISSUE TITLE
Got error when sign up: Exception from sub user-authenticationMethod id 8hdGCWWoW89yCJLML Error: Match error: Expected string, got null

### ISSUE THREAD

**Issue by kyleduo** [wekan/wekan#2071]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: YES
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? YES
* Wekan version: quay.io/wekan/wekan:latest (2018-12-23)
* If this is about old version of Wekan, what upgrade problem you have?: NO
* Operating System: CentOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker-mongo
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):Nginx
* Node Version:-
* MongoDB Version:-
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):-

**Problem description**:
1. visite signup page.
2. enter username, email, password. Got error log in wekan-app's log.
3. record of user has been inserted to mongo, and email has not verified.
4. user can login using username and password.

**Comment by kyleduo** [comment]
It’s quite weird that wekan works fine on my mac using docker, but got error on remote CentOS server with the same configuration.

**Comment by kyleduo** [comment]
@xet7 Thanks for your answer.
The smtp settings is correct and i've received emails when on my Mac with the same setting.
I've tried delete containers and remove db and reinstall but nothing change. I'll try clean and installing again.

**Comment by kyleduo** [comment]
@xet7 I tried to clean up and re-install. And I met up the same error. When I log in to mongo I found the database has 0 data and I can not log in using even username and password. The full error log is following.

```
Exception from sub user-authenticationMethod id iPG3HbL5nsnxFqX2i Error: Match error: Expected string, got null
    at exports.check (packages/check.js:55:15)
    at Subscription.<anonymous> (server/publications/users.js:22:3)
    at packages/matb33_collection-hooks.js:307:21
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
    at packages/check.js:128:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
    at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]
```

**Comment by xet7** [comment]
I made some fixes.

1) Cleanup
```
git clone https://github.com/wekan/docker-cleanup-volumes
cd docker-cleanup-volumes
./start.sh
```
2) Get newest docker-compose.yml
```
wget https://raw.githubusercontent.com/wekan/wekan/devel/docker-compose.yml
```
Edit for ROOT-URL etc if required and then:
```
docker-compose up -d
```
And then restore backup if needed:
https://github.com/wekan/wekan/wiki/Backup
