### ISSUE TITLE
remove login dropdown don´t work

### ISSUE THREAD

**Issue by GAm7** [wekan/wekan#2089]
**Server Setup Information**:
* Wekan version: 1.98.0
* Operating System: Debian 9.6
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 8.15.0
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://wekan.domainname.de

After i read the changelog that since v1.95 it is now possible to remove login dropdown for Password or ldap Log-in I have set the setting as indicated in the changelog: 

> snap set wekan default-authentication-method='ldap'

after this i checked the setting

> snap get wekan
> Key                            Value
> default-authentication-method  ldap

but Wekan is still showing the login dropdown for Password or ldap, even after a restart.

**Comment by xet7** [comment]
Yes, because that was removed in [Wekan v1.96](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v196-2018-12-24-wekan-release) because login did not work at all #2072:
- Revert "Improve authentication" and "Default Authentication Method" to make login work again.

But now that I noticed updated comment from #2072 , so maybe if email login could be fixed, it could be included again:

**Update:** actually can sign in using *username/password* method, but *e-mail/password* method is affected

`snap logs wekan.wekan` shows:

```
2018-12-24T12:31:29Z wekan.wekan[5665]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
2018-12-24T12:31:29Z wekan.wekan[5665]:     at packages/ddp-server/livedata_server.js:559:43
2018-12-24T12:31:29Z wekan.wekan[5665]: Sanitized and reported to the client as: Match failed [400]
```

**Comment by xet7** [comment]
Dropdown can be hidden at Admin Panel / Layout.
