### ISSUE TITLE
Docker container crash (process out of memory)

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2150]
Setup Information
Wekan Version: 2.02
Deployment Method: Docker (4 containers)
Docker Image: quay.io/wekan/wekan:v2.02
Front-End: Nginx:Alpine (latest)
MongoDB Version: 3.2.21
Node Version: 8.15
Root URL: https://example.com

Host System:
OS: CentOS 7
CPU: 8 CPU
RAM: 16 GB

Problem description:
Wekan containers crash.

Sample Docker Logs:
```
<--- Last few GCs --->
ac[1:0x23ed6f0]  6698416 ms: Mark-sweep 546.1 (673.4) -> 539.8 (674.9) MB, 296.9 / 0.8 ms  (+ 1015.7 ms in 1084 steps since start of marking, biggest step 107.4 ms, walltime since start of marking 1406 ms) finalize incremental marking via task GC in old spa[1:0x23ed6f0]  6699953 ms: Mark-sweep 548.4 (674.9) -> 541.0 (675.9) MB, 301.2 / 0.9 ms  (+ 997.0 ms in 1090 steps since start of marking, biggest step 104.9 ms, walltime since start of marking 1391 ms) finalize incremental marking via task GC in old spac

<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: node::Abort() [node]
 2: 0x8ccf9c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: 0xa6552b [node]
 6: v8::internal::MarkCompactCollector::Evacuate() [node]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [node]
 8: v8::internal::Heap::MarkCompact() [node]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
10: 0xe0ce78 [node]
11: v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [node]
12: v8::internal::IncrementalMarkingJob::Task::RunInternal() [node]
13: v8::internal::CancelableTask::Run() [node]
14: node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
15: 0x9b7c4b [node]
16: 0x9c8970 [node]
17: uv_run [node]
18: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [node]
19: node::Start(int, char**) [node]
20: __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
21: 0x89f101 [node]

```
and another
```
packages/meteor.js:847
    }).run();
       ^

RangeError: Out of memory
    at Immediate._onImmediate (packages/meteor.js:847:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Presence started serverId=pQNwyeiARX5soZqBn
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Got exception while reading last entry: MongoError: no connection available
packages/meteor.js:847
    }).run();
       ^

RangeError: Out of memory
    at Immediate._onImmediate (packages/meteor.js:847:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Presence started serverId=6y8fMuL6CbvDsHEfC
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
*** Repeated a few hundred+ times ***
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by xet7** [comment]
Did you limit amount of RAM available in Docker container? If Wekan or MongoDB does not get enough RAM, Yes it will crash.

**Comment by rjevnikar** [comment]
I didn't limit the amount of RAM - should I be?

**Comment by xet7** [comment]
@rjevnikar 

No, there does not need to be any limits.

Did you use docker-compose.yml from wekan/wekan repo? Or how did you start Wekan ?

**Comment by xet7** [comment]
Have you installed all updates to CentOS 7, Docker and docker-compose?
What versions of Docker and docker-compose are you using?

**Comment by rjevnikar** [comment]
I was waiting until the scroll bar issue was resolved before updating.
Yes, I used the compose file.

**Comment by xet7** [comment]
Please test does newest Wekan crash too.

**Comment by xet7** [comment]
Newest Docker is 18.09.1, please upgrade:
https://docs.docker.com/engine/release-notes/

**Comment by rjevnikar** [comment]
[logs.zip](https://github.com/wekan/wekan/files/2822140/logs.zip)
@xet7 the containers crashed again.
I've attached the logs.
Wekan v 2.12
Docker version 18.09.1, build 4c52b90
docker-compose version 1.22.0, build f46880fe

**Comment by xet7** [comment]
There are some errors about Subtasks not defined. This could be because of current Subtasks bugs, that you can find from Wekan GitHub open issues. For example, if some card is moved away from Subtasks, it could cause Wekan board not loading. Fixing Subtasks bugs would make Wekan work again.

Another, but worse option is to delete Subtasks from database.

Stop wekan-app container:
```
docker stop wekan-app
```
Then connect to MongoDB container
```
docker start wekan-db
docker exec -it wekan-db bash
mongo
use wekan
show collections
```
Etc.

**Comment by xet7** [comment]
There are also error messages about hugepages, but I don't know does it help at all to disable or enable them:
https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/
https://superuser.com/questions/1309438/how-to-enable-huge-page-support-in-a-dockerfile

**Comment by rjevnikar** [comment]
I'm still having containers crash - using v2.17
HTP have been disabled.
When containers crash, changes and updates are not being written in the database., and therefore disappear when the user next goes to the board.

docker log for a crashed container
```
Got exception while reading last entry: MongoError: no connection available
packages/meteor.js:847
    }).run();
       ^

RangeError: Out of memory
    at Immediate._onImmediate (packages/meteor.js:847:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Presence started serverId=ppbbiLAGSJGCnJ6zF
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
Got exception while reading last entry: MongoError: no connection available
packages/meteor.js:847
    }).run();
       ^

RangeError: Out of memory
    at Immediate._onImmediate (packages/meteor.js:847:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

```

**Comment by rjevnikar** [comment]
after the performance improvements made in v2.32 this particular type of crash hasn't occured.
I'll close this issue, if the problem reoccurs, I'll open another one.
