### ISSUE TITLE
Exception while invoking method 'importBoard' Error: Did not check() all arguments during call to 'importBoard'

### ISSUE THREAD

**Issue by rblomme** [wekan/wekan#2199]
**Server Setup Information**:

* Wekan version: 2.23 Rev 432
* Operating System: Ubuntu 18.04.2 LTS
* Deployment Method:
snapd: 2.37.1.1
* Http frontend if any:
nginx: 1.14.0
* Node Version: v8.15.0
* MongoDB Version: v3.2.22

**Problem description**:
when I import a board "from previous export", the GUI throws an error 500,
and the syslog file shows

```
Exception while invoking method 'importBoard' Error: Did not check() all arguments during call to 'importBoard'
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check.js:483:13)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:131:16)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at Promise (packages/ddp-server/livedata_server.js:715:46)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at new Promise (<anonymous>)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at packages/mdg_meteor-apm-agent.js:2617:38
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)
Feb 21 13:45:26 tw06v056 wekan.wekan[24225]:     at packages/ddp-server/livedata_server.js:559:43

```

- *steps how to reproduce*:
create a new board "test", create a list "test", create a new card "test"
export board
move board to archive
go to "boards in archive" and delete the board "test"
Add board - import board - From previous export
paste the json content of the exported "test" board - click "import"
Map members - click "Done"
=> 500

click "All boards" => the test board is available

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows 
no errors on console
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
```
2019-02-21T13:08:46Z wekan.wekan[24225]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at Promise (packages/ddp-server/livedata_server.js:715:46)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at new Promise (<anonymous>)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at packages/mdg_meteor-apm-agent.js:2617:38
2019-02-21T13:08:46Z wekan.wekan[24225]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)
2019-02-21T13:08:46Z wekan.wekan[24225]:     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by xet7** [comment]
Try newest Wekan.
