### ISSUE TITLE
Errors observed when deleting archived cards

### ISSUE THREAD

**Issue by darren-teo** [wekan/wekan#2230]
## Errors observed when deleting archived cards

**Server Setup Information**:
* Wekan version: v2.23.
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* MongoDB Version: 3.2.21

**Problem description**:
*Steps to reproduce:*
- *Move card to Archive*
- *Select Archive from Board menu*
- *Delete archived card*

*Errors observed from docker logs:*
```
Exception in removed observe/observeChanges callback: Error: Removed nonexistent document b4ExeRJNBoJaKbPG8
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:394:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1292:19)
    at Subscription.subscriptionProto.(anonymous function) [as removed] (packages/mdg_meteor-apm-agent.js:2857:30)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1240:24)
    at packages/meteor.js:1253:14
    at packages/mongo/observe_multiplex.js:182:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:176:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)
    at packages/meteor.js:846:12
Exception in removed observe/observeChanges callback: Error: Removed nonexistent document b4ExeRJNBoJaKbPG8
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:394:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1292:19)
    at Subscription.subscriptionProto.(anonymous function) [as removed] (packages/mdg_meteor-apm-agent.js:2857:30)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1240:24)
    at packages/meteor.js:1253:14
    at packages/mongo/observe_multiplex.js:182:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:176:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)
    at packages/meteor.js:846:12
Exception while invoking method '/cards/remove' ReferenceError: Subtasks is not defined
    at cardRemover (models/cards.js:1365:3)
    at Object.Cards.after.remove (models/cards.js:1418:5)
    at packages/matb33_collection-hooks.js:574:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:573:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:572:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:588:5)
    at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)
    at ns.Collection.CollectionPrototype._validatedRemove (packages/allow-deny/allow-deny.js:406:34)
    at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
    at packages/check.js:128:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
```
Is there anything wrong with this? Sometimes when this happened, i noticed the UI for Archive goes out of whack.
![image](https://user-images.githubusercontent.com/32067070/53786356-7853b580-3f56-11e9-9f59-3d81df811dac.png)

**Comment by rjevnikar** [comment]
`Exception while invoking method '/cards/remove' ReferenceError: Subtasks is not defined` - appears to be the same problem as #2115.

I've seen the `Exception in removed observe/observeChanges callback: Error: Removed nonexistent document...` error in my logs, but haven't been able to determine what causes it. I may be completely off the mark, but @darren-teo, are you using oplog tailing (using MONGO_OPLOG environment variable)?

**Comment by darren-teo** [comment]
> `Exception while invoking method '/cards/remove' ReferenceError: Subtasks is not defined` - appears to be the same problem as #2115.
> 
> I've seen the `Exception in removed observe/observeChanges callback: Error: Removed nonexistent document...` error in my logs, but haven't been able to determine what causes it. I may be completely off the mark, but @darren-teo, are you using oplog tailing (using MONGO_OPLOG environment variable)?

Just closing the loop. No, I'm not using oplog tailing.
