### ISSUE TITLE
[Bug] Export and Reimport an board with exists since v2.18

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2237]
## Issue
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 2.42
* Operating System: Ubuntu with snap

**Problem description**:
- Export an Board with 8 Lines, some card with exists since v2.18 (for one month)
- Import the json file (i try it some days ago and it works at this time)

`2019-03-07T07:01:36Z wekan.wekan[7937]: Exception while invoking method 'importBoard' { stack: 'Error: Swimlane id is required
\n    at getErrorObject (packages/aldeed_collection2-core.js:480:15)
\n    at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
\n    at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
\n    at packages/matb33_collection-hooks.js:127:46
\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
\n    at Object.directOp (packages/matb33_collection-hooks.js:47:27)
\n    at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
\n    at wekanCards.forEach.card (models/wekanCreator.js:302:35)
\n    at Array.forEach (<anonymous>)
\n    at WekanCreator.createCards (models/wekanCreator.js:257:16)
\n    at WekanCreator.create (models/wekanCreator.js:787:10)
\n    at DDPCommon.MethodInvocation.importBoard (models/import.js:27:20)
\n    at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)
\n    at packages/check.js:128:16
\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
\n    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)',
2019-03-07T07:01:36Z wekan.wekan[7937]:   source: 'method' }
2019-03-07T07:01:36Z wekan.wekan[7937]: Sanitized and reported to the client as: Swimlane id is required [400]`

edit:
The export an reimport was with the current version

**Comment by sfahrenholz** [comment]
Since V2.45

2019-03-13T07:48:10Z wekan.wekan[657]: Exception while invoking method 'importBoard' { stack: 'Error: Swimlane id is required
at getErrorObject (packages/aldeed_collection2-core.js:480:15)
at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
at packages/matb33_collection-hooks.js:127:46
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
at Object.directOp (packages/matb33_collection-hooks.js:47:27)
at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
at wekanCards.forEach.card (models/wekanCreator.js:306:35)
at Array.forEach (<anonymous>)
at WekanCreator.createCards (models/wekanCreator.js:257:16)
at WekanCreator.create (models/wekanCreator.js:795:10)
at DDPCommon.MethodInvocation.importBoard (models/import.js:27:20)
at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)
at packages/check.js:128:16
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)',
2019-03-13T07:48:10Z wekan.wekan[657]:   source: 'method' }
