### ISSUE TITLE
Error when removing checklist item

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2240]
**Environment Setup Information**:
Wekan version: 2.42
Node version: 8.15.1
MongoDB version: 3.2.21
Docker install - 4 containers, each on a 2cpu-8GB VM running RHEL 7.2
HTTPS frontend - Nginx, root URL configured correctly

**Problem description**:
In the logs, I noticed the following error:
`2019-03-08T15:13:49.329216303Z Exception while invoking method '/checklistItems/                                      remove' TypeError: Cannot read property 'title' of undefined
2019-03-08T15:13:49.329265571Z     at Object.Activities.after.insert (models/act                                      ivities.js:171:44)
2019-03-08T15:13:49.329270526Z     at packages/matb33_collection-hooks.js:382:18
2019-03-08T15:13:49.329273958Z     at Array.forEach (<anonymous>)
2019-03-08T15:13:49.329278018Z     at Function._.each._.forEach (packages/unders                                      core.js:139:11)
2019-03-08T15:13:49.329281267Z     at after (packages/matb33_collection-hooks.js                                      :381:9)
2019-03-08T15:13:49.329284412Z     at Object.<anonymous> (packages/matb33_collec                                      tion-hooks.js:396:12)
2019-03-08T15:13:49.329287747Z     at Object.collection.(anonymous function) [as                                       insert] (packages/matb33_collection-hooks.js:146:21)
2019-03-08T15:13:49.329291478Z     at ns.Collection.insert (packages/mongo/colle                                      ction.js:491:37)
2019-03-08T15:13:49.329294407Z     at ns.Collection.Mongo.Collection.(anonymous                                       function) [as insert] (packages/aldeed_collection2-core.js:232:19)
2019-03-08T15:13:49.329297478Z     at itemRemover (models/checklistItems.js:104:                                      14)
2019-03-08T15:13:49.329300686Z     at Object.ChecklistItems.after.remove (models                                      /checklistItems.js:210:5)
2019-03-08T15:13:49.329303671Z     at packages/matb33_collection-hooks.js:574:20
2019-03-08T15:13:49.329306638Z     at Array.forEach (<anonymous>)
2019-03-08T15:13:49.329309626Z     at Function._.each._.forEach (packages/unders                                      core.js:139:11)
2019-03-08T15:13:49.329312609Z     at packages/matb33_collection-hooks.js:573:11
2019-03-08T15:13:49.329315540Z     at Array.forEach (<anonymous>)
`

**Comment by andresmanelli** [comment]
@rjevnikar could you tell me if this is fixed with https://github.com/wekan/wekan/commit/2ec1664408d9515b5ca77fbb46ef99208eb8cff0?

**Comment by xet7** [comment]
I'm currently building new Wekan v2.44 release that includes this fix. Please add comment to this issue if there still is problem after upgrading to Wekan v2.44.

**Comment by xet7** [comment]
Needs to be tested before closing this.

**Comment by rjevnikar** [comment]
I haven't been able to repeat the error with 2.44, so unless someone else sees it, I think this s resolved.
