### ISSUE TITLE
[Bug] The Mongo server and the Meteor query disagree on how many documents match your query

### ISSUE THREAD

**Issue by justinr1234** [wekan/wekan#2271]
```
aw7xs
2019-03-18 16:07:35-05:00Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"_id":{"$in":["66J8FYGicYaTMaRmC","zRrNXMX8eKTMEukBj","Hp5GEnyiXAZzXKZFy","5ABYxw5QCXNcLpF2p","en5s5BSPi9aQkPoyk","fL728XLE3ghHbFb76","KjMLSQsFWNGGNRtu9","TggjQ2CpcbCwZRrhd","rcJcHkwt9hYbfEg6g","nhbPtpy6LkGsfFQzR","aqvgSurq7ckiQoWa8"]}}
aw7xs
2019-03-18 16:07:35-05:00 at packages/mongo/oplog_observe_driver.js:881:15
aw7xs
2019-03-18 16:07:35-05:00 at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
aw7xs
2019-03-18 16:07:35-05:00 at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
aw7xs
2019-03-18 16:07:35-05:00 at OplogObserveDriver.proto._publishNewResults (packages/mdg_meteor-apm-agent.js:2902:38)
aw7xs
2019-03-18 16:07:35-05:00 at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
aw7xs
2019-03-18 16:07:35-05:00 at packages/mongo/oplog_observe_driver.js:699:14
aw7xs
2019-03-18 16:07:35-05:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
aw7xs
2019-03-18 16:07:35-05:00 at packages/meteor.js:502:25
aw7xs
2019-03-18 16:07:35-05:00 at runWithEnvironment (packages/meteor.js:1240:24)
```

**Comment by justinr1234** [comment]
https://github.com/meteor/meteor/issues/9619#issuecomment-464655546

**Comment by xet7** [comment]
@justinr1234 

Is there some code that could fix this? Can you make a PR ?

**Comment by justinr1234** [comment]
@xet7 I'm not sure what the fix is, just trying to leave some breadcrumbs

**Comment by rjevnikar** [comment]
Using docker, version 2.48,  I'm seeing a similar error in my logs:
```
Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"cardId":{"$in":[bunch of card ids..."]}}
    at packages/mongo/oplog_observe_driver.js:881:15
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
    at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
    at OplogObserveDriver.proto._publishNewResults (packages/mdg_meteor-apm-agent.js:2902:38)
    at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
    at packages/mongo/oplog_observe_driver.js:699:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1240:24)
Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"cardId":{"$in":[bunch of card ids....]}}
    at packages/mongo/oplog_observe_driver.js:881:15
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
    at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
    at OplogObserveDriver.proto._publishNewResults (packages/mdg_meteor-apm-agent.js:2902:38)
    at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
    at packages/mongo/oplog_observe_driver.js:699:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1240:24)
Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"cardId":{"$in":[bunch of card ids]}}
    at packages/mongo/oplog_observe_driver.js:881:15
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
    at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
    at OplogObserveDriver.proto._publishNewResults (packages/mdg_meteor-apm-agent.js:2902:38)
    at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
    at packages/mongo/oplog_observe_driver.js:699:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1240:24)
Exception in setInterval callback: Error: read ECONNRESET
    at TCP.onread (net.js:622:25)

```

**Comment by xet7** [comment]
Today 2019-07-08 I also got this same error on https://github.com/wekan/wekan master branch that has Meteor 1.8.1:
```
8-10:06:38.573(-4)? Meteor APM: completed instrumenting the app
=> Meteor server restarted
I20190708-10:08:05.229(-4)? Presence started serverId=fDYRrfyCfw8ns8CnJ
I20190708-10:08:06.164(-4)? Meteor APM: completed instrumenting the app
=> Meteor server restarted
=> Client modified -- refreshing (x7)
W20190708-12:03:43.172(-4)? (STDERR) The Mongo server and the Meteor query disagree on how many documents match your query. Cursor description:  CursorDescription {
W20190708-12:03:43.173(-4)? (STDERR)   collectionName: 'boards',
W20190708-12:03:43.173(-4)? (STDERR)   selector: 
W20190708-12:03:43.173(-4)? (STDERR)    { _id: 'BwD8uETn6akvJN2wK',
W20190708-12:03:43.174(-4)? (STDERR)      archived: false,
W20190708-12:03:43.174(-4)? (STDERR)      '$or': [ [Object], [Object] ] },
W20190708-12:03:43.174(-4)? (STDERR)   options: { transform: [Function], limit: 1, sort: { _id: 1 } } }
I20190708-12:03:43.174(-4)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"_id":"BwD8uETn6akvJN2wK","archived":false,"$or":[{"permission":"public"},{"members":{"$elemMatch":{"isActive":true}}}]}
I20190708-12:03:43.174(-4)?     at packages/mongo/oplog_observe_driver.js:884:15
I20190708-12:03:43.175(-4)?     at Object.Meteor._noYieldsAllowed (packages/meteor.js:778:12)
I20190708-12:03:43.175(-4)?     at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
I20190708-12:03:43.175(-4)?     at OplogObserveDriver.proto._publishNewResults (packages/mdg:meteor-apm-agent/lib/hijack/wrap_observers.js:23:38)
I20190708-12:03:43.175(-4)?     at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
I20190708-12:03:43.175(-4)?     at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
I20190708-12:03:43.175(-4)?     at packages/mongo/oplog_observe_driver.js:191:10
I20190708-12:03:43.175(-4)?     at packages/mongo/oplog_observe_driver.js:15:9
I20190708-12:03:43.175(-4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190708-12:03:43.176(-4)?     at packages/meteor.js:550:25
I20190708-12:03:43.176(-4)?     at runWithEnvironment (packages/meteor.js:1286:24)
```

**Comment by justinr1234** [comment]
I believe there was a mongo DB upgrade between meteor 1.7 and meteor 1.8. Perhaps there is an out dated mongo DB being used between Meteor server and mongo server.

**Comment by xet7** [comment]
I did update mongo package version, I don't know yet does it help.
https://github.com/wekan/wekan/commit/96065d11a543852c1069cbab528bd08508b4a27c

**Comment by justinr1234** [comment]
No the package version, the actual mongodb. Are you seeing this on local or when deployed to a live production server?

**Comment by justinr1234** [comment]
https://blog.meteor.com/meteor-1-8-erases-the-debts-of-1-7-77af4c931fe3

They upgraded from mongo 3 to mongo 4. This could cause issues if you're running an old mongo 3 instance somewhere but upgrade to meteor 1.8 running mongo 4 libraries.

**Comment by xet7** [comment]
I am seeing this issue on master branch with command `meteor --port 4000`, using Meteor's built-in mongodb. I was modifying some .styl files and got this error.

**Comment by justinr1234** [comment]
Is this with a fresh mongodb or are you using an "old" mongo that you previous ran? Try with a fresh wekan and fresh mongodb.

**Comment by justinr1234** [comment]
```
p70rx
2019-07-16 07:45:36-05:00The Mongo server and the Meteor query disagree on how many documents match your query. Cursor description: CursorDescription {
p70rx
2019-07-16 07:45:36-05:00 collectionName: 'boards',
p70rx
2019-07-16 07:45:36-05:00 selector:
p70rx
2019-07-16 07:45:36-05:00 { _id: 'N9tEoe3fWX8NGTbSL',
p70rx
2019-07-16 07:45:36-05:00 archived: false,
p70rx
2019-07-16 07:45:36-05:00 '$or': [ [Object], [Object] ] },
p70rx
2019-07-16 07:45:36-05:00 options: { transform: [Function], limit: 1, sort: { _id: 1 } } }
p70rx
2019-07-16 07:45:36-05:00Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"_id":"N9tEoe3fWX8NGTbSL","archived":false,"$or":[{"permission":"public"},{"members":{"$elemMatch":{"isActive":true}}}]}
p70rx
2019-07-16 07:45:36-05:00 at packages/mongo/oplog_observe_driver.js:884:15
p70rx
2019-07-16 07:45:36-05:00 at Object.Meteor._noYieldsAllowed (packages/meteor.js:778:12)
p70rx
2019-07-16 07:45:36-05:00 at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
p70rx
2019-07-16 07:45:36-05:00 at OplogObserveDriver.proto._publishNewResults (packages/mdg:meteor-apm-agent/lib/hijack/wrap_observers.js:23:38)
p70rx
2019-07-16 07:45:36-05:00 at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
p70rx
2019-07-16 07:45:36-05:00 at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
p70rx
2019-07-16 07:45:36-05:00 at packages/mongo/oplog_observe_driver.js:191:10
p70rx
2019-07-16 07:45:36-05:00 at packages/mongo/oplog_observe_driver.js:15:9
p70rx
2019-07-16 07:45:36-05:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
p70rx
2019-07-16 07:45:36-05:00 at packages/meteor.js:550:25
p70rx
2019-07-16 07:45:36-05:00 at runWithEnvironment (packages/meteor.js:1286:24)
```
