### ISSUE TITLE
Bug: File not uploaded properly, clicking on download does not do anything

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2281]
From @justinr1234

Hey, seeing issues with file record being created in the DB but the file itself not stored in DB. Shows up on a card but clicking download doesn’t do anything.

**Comment by justinr1234** [comment]
Looks like it eventually results in a server crash:

```
w6dwb
2019-03-22 16:44:02-05:00MongoError: no chunks found for file, possibly corrupt
w6dwb
2019-03-22 16:44:02-05:00 at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
w6dwb
2019-03-22 16:44:02-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:825:29
w6dwb
2019-03-22 16:44:02-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:1201:5
w6dwb
2019-03-22 16:44:02-05:00 at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
w6dwb
2019-03-22 16:44:02-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
w6dwb
2019-03-22 16:44:02-05:00 at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
w6dwb
2019-03-22 16:44:02-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
w6dwb
2019-03-22 16:44:02-05:00 at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
w6dwb
2019-03-22 16:44:02-05:00 at setCursorNotified (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
w6dwb
2019-03-22 16:44:02-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
w6dwb
2019-03-22 16:44:02-05:00 at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
w6dwb
2019-03-22 16:44:02-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
w6dwb
2019-03-22 16:44:02-05:00 at _combinedTickCallback (internal/process/next_tick.js:131:7)
w6dwb
2019-03-22 16:44:02-05:00 at process._tickDomainCallback (internal/process/next_tick.js:218:9)
w6dwb
2019-03-22 16:44:02-05:00Application exited with code: 7
```

**Comment by justinr1234** [comment]
Looks like it had trouble writing the file to begin with:

```
mmhqm
2019-03-22 15:31:48-05:00MongoError: file with id 5c95463320089f0007b1b9bd not opened for writing
mmhqm
2019-03-22 15:31:48-05:00 at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
mmhqm
2019-03-22 15:31:48-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
mmhqm
2019-03-22 15:31:48-05:00 at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
mmhqm
2019-03-22 15:31:48-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
mmhqm
2019-03-22 15:31:48-05:00 at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
mmhqm
2019-03-22 15:31:48-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
mmhqm
2019-03-22 15:31:48-05:00 at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
mmhqm
2019-03-22 15:31:48-05:00 at setCursorNotified (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
mmhqm
2019-03-22 15:31:48-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
mmhqm
2019-03-22 15:31:48-05:00 at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
mmhqm
2019-03-22 15:31:48-05:00 at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
mmhqm
2019-03-22 15:31:48-05:00 at _combinedTickCallback (internal/process/next_tick.js:131:7)
mmhqm
2019-03-22 15:31:48-05:00 at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
