### ISSUE TITLE
Import LDAP Users

### ISSUE THREAD

**Issue by B2RN** [wekan/wekan#2354]
This doesn't seem to be the same issue as #14, but correct me if I'm wrong.

We've got Wekan set up and working with LDAP auth, but importing all of the users in the user base DN doesn't seem to work:

```
ldap-background-sync                              true
ldap-background-sync-import-new-users             true
ldap-background-sync-interval                     100
ldap-background-sync-keep-existant-users-updated  true
```

Is there a way to force the sync? Logs aren't showing any attempts at syncing, although any login related log messages are there and show no errors.

We're running this on CentOS 7.5 via snapd.

**Comment by pshunter** [comment]
Hi, i'm a total newbie in meteor on js development, just an admin who needs to get user sync to work. I had a look at this and as bcoppens says, the problem seems to come from here : 
```
Meteor.startup(() => {
  Meteor.defer(() => {
    LDAP.settings_get('LDAP_BACKGROUND_SYNC', addCronJob);
    LDAP.settings_get('LDAP_BACKGROUND_SYNC_INTERVAL', addCronJob);
  });
});
```

the "settings.get" function effectively accepts the second parameter (addCronJob) but actually does nothing with it. I would replace these two lines with : `if(LDAP.settings_get('LDAP_BACKGROUND_SYNC')){addCronJob;}`

Moreover, with addCron job not being called, it seems that the synced-cron package does never get pulled in the final bundle.

**Comment by pshunter** [comment]
well, I made some progress in implementing a fix : i added the percolate:synced-cron package and imported it in sync.js : `import {SyncedCron} from 'meteor/percolate:synced-cron';`
However, while it seems to go further, the package does not seem to import correctly :
```
Presence started serverId=7zzssND2Z7S4sBfZY
Kadira: completed instrumenting the app
[INFO] Enabling LDAP Background Sync 
Exception in callback of async function: TypeError: Cannot read property 'add' of undefined
    at addCronJobDebounced (packages/wekan-ldap/server/sync.js:432:16)
    at runWithEnvironment (packages/meteor.js:1240:24)
```
where undefined refers to `SyncedCron.add` at L432 in sync.js. Now I'm somewhat lost. Meteor/Node/js experts ?

**Comment by pshunter** [comment]
Hi,
I found out that I had to add the percolate:synced-cron package in packages/wekan-ldap/package.js so it gets really imported. Nothing complains that something is missing until you try to use the package and then it's just undefined. Go figure...
Next I had to fiddle with the fact that SyncedCron actually imports as SyncedCron.SyncedCron, but it's there. Now I have the following messages in the log : 
`[INFO] Enabling LDAP Background Sync `
`{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"LDAP_Sync\" next run @0","time":{"$date":1563455180310},"level":"info"}
`
So it seems to be willing to do something but somehow doesn't schedule the sync job.
If anyone is listening, stay tuned...

**Comment by benh57** [comment]
@pshunter great work, i was going down the same path as you 3 days ago. Keep us posted.

**Comment by xet7** [comment]
@pshunter 

Great work, keep going !!!

**Comment by pshunter** [comment]
There it is, cleaned up to be merged against master. As I explained, this fix could use additional polish since I'm not Meteor-fluent :)

**Comment by benh57** [comment]
Tried this out (latest master) and got this crash, any ideas?

Jul 26 04:11:44 wekan Wekan: [INFO] Enabling LDAP Background Sync
Jul 26 04:11:44 wekan Wekan: Exception in callback of async function: TypeError: str.toLowerCase is not a function
Jul 26 04:11:44 wekan Wekan: at Object.later.parse.text (/usr/local/wekan/build-0/programs/server/npm/node_modules/meteor/percolate_synced-cron/node_modules/later/later.js:1506:34)
Jul 26 04:11:44 wekan Wekan: at Object.schedule (packages/wekan-ldap/server/sync.js:436:22)
Jul 26 04:11:44 wekan Wekan: at scheduleEntry (packages/percolate_synced-cron.js:126:24)
Jul 26 04:11:44 wekan Wekan: at packages/percolate_synced-cron.js:163:7
Jul 26 04:11:44 wekan Wekan: at Function._.each._.forEach (packages/underscore.js:147:22)
Jul 26 04:11:44 wekan Wekan: at packages/percolate_synced-cron.js:162:7
Jul 26 04:11:44 wekan Wekan: at Object.startup (packages/meteor.js:992:5)
Jul 26 04:11:44 wekan Wekan: at Object.SyncedCron.start (packages/percolate_synced-cron.js:160:10)
Jul 26 04:11:44 wekan Wekan: at addCronJobDebounced (packages/wekan-ldap/server/sync.js:445:6)
Jul 26 04:11:44 wekan Wekan: at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by benh57** [comment]
Aha - no crash if i remove the LDAP_BACKGROUND_SYNC_INTERVAL setting (so it just uses the default)

Jul 26 04:36:06 wekan Wekan: [WARN] Lookup for unset variable: LDAP_BACKGROUND_SYNC_INTERVAL
Jul 26 04:36:06 wekan Wekan: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"LDAP_Sync\" next run @Thu Jul 25 2019 22:00:00 GMT-0700 (Pacific Daylight Time)","time":{"$date":1564115766890},"level":"info"}


With the env var LDAP_BACKGROUND_SYNC_INTERVAL=10000, it crashed with the above stack

**Comment by xet7** [comment]
@benh57 

Thanks for testing, I will change default. Does sync work?

**Comment by benh57** [comment]
The sync worked, but it only synced 26 people rather than everyone. I'll investigate why.

**Comment by benh57** [comment]
Interesting, the log says:
 26 17:00:01 wekan Wekan: [INFO] Import running. Users imported until now: 300

But, the GUI shows 'The number of people is: 26'

**Comment by xet7** [comment]
@benh57 

It could be that Wekan Admin Panel shows users from wrong part of Users table. You could look where it did import those 300 users, using for example nosqlbooster.

**Comment by benh57** [comment]
Will check that.

I put in a new issue to track the crash with the INTERVAL set https://github.com/wekan/wekan/issues/2570

**Comment by pshunter** [comment]
Hi, I also saw the admin "people" panel choking on users imported from LDAP. While the import is running, refreshing it would show 26, then higher numbers, but it always failed to list all users.
However, users can be looked up and added on a board even if not found on the admin panel. Also, checking the database shows that many users have been imported (about 1500 for me).

**Comment by xet7** [comment]
@pshunter 

I'll check is infinite scroll added to people panel. Maybe it's not yet there, and it tries to load too much.
