### ISSUE TITLE
Access denied [403] when upload avatar

### ISSUE THREAD

**Issue by HonorLee-cn** [wekan/wekan#238]
Access denied [403]

[Error] Error: "Queue" failed [503] Error in method "/cfs/files/:value/:value/", Error: MongoError: Invalid modifier specified $setOnInsert     at Object.Future.wait (/home/wwwroot/bug_server/.bui... [undefined], r@http://bug.chh.la/e5a981121ede6b91485e57eca35bda25a642e12e.js:3:3354
http://bug.chh.la/e5a981121ede6b91485e57eca35bda25a642e12e.js:227:3620
http://bug.chh.la/e5a981121ede6b91485e57eca35bda25a642e12e.js:227:964
http://bug.chh.la/e5a981121ede6b91485e57eca35bda25a642e12e.js:1:8451
onreadystatechange@http://bug.chh.la/e5a981121ede6b91485e57eca35bda25a642e12e.js:227:2260

**Comment by HonorLee-cn** [comment]
After upgrade MongoDB,avatar upload success,but it cause another error on server

root@LocalHost:/home/wwwroot/bug_server/.build/bundle# node /home/wwwroot/bug_server/.build/bundle/main.js
Meteor._wrapAsync has been renamed to Meteor.wrapAsync
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at ServerResponse.res.write (/home/wwwroot/bug_server/.build/bundle/programs/server/npm/webapp/node_modules/connect/lib/middleware/compress.js:110:17)
    at ServerResponse.res.end (/home/wwwroot/bug_server/.build/bundle/programs/server/npm/webapp/node_modules/connect/lib/middleware/compress.js:116:14)
    at sendResponseIfDone (packages/cfs:http-methods/http.methods.server.api.js:542:1)
    at IncomingMessage.<anonymous> (packages/cfs:http-methods/http.methods.server.api.js:567:1)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by HonorLee-cn** [comment]
"Edit Attachments" will also cause "Error:write after end" error when uploading image files

**Comment by mquandalle** [comment]
You need to use node v0.10.40

**Comment by mquandalle** [comment]
Does that help?
