### ISSUE TITLE
Sanitized and reported to the client as: Text is required [400]

### ISSUE THREAD

**Issue by jordi1972** [wekan/wekan#2391]
Trying to import a Trello JSON, it gives me this error:
Sanitized and reported to the client as: Text is required [400].

This is the journal:

may 03 12:16:46 wekan.sia.local wekan.wekan[5157]: Exception while invoking method 'importBoard' { stack: 'Error: Text is required\n    at getErrorObject (packages/
may 03 12:16:46 wekan.sia.local wekan.wekan[5157]: source: 'method' }
may 03 12:16:46 wekan.sia.local wekan.wekan[5157]: Sanitized and reported to the client as: Text is required [400]

And the log:

2019-05-03T10:16:46Z wekan.wekan[5157]: Exception while invoking method 'importBoard' { stack: 'Error: Text is required\n    at getErrorObject (packages/aldeed_collection2-core.js:480:15)\n    at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)\n    at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)\n    at packages/matb33_collection-hooks.js:127:46\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)\n    at Object.directOp (packages/matb33_collection-hooks.js:47:27)\n    at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)\n    at comments.forEach.comment (models/trelloCreator.js:303:49)\n    at Array.forEach (<anonymous>)\n    at trelloCards.forEach.card (models/trelloCreator.js:292:18)\n    at Array.forEach (<anonymous>)\n    at TrelloCreator.createCards (models/trelloCreator.js:228:17)\n    at TrelloCreator.create (models/trelloCreator.js:637:10)\n    at DDPCommon.MethodInvocation.importBoard (models/import.js:29:20)\n    at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n    at packages/check.js:128:16',
2019-05-03T10:16:46Z wekan.wekan[5157]: source: 'method' }
2019-05-03T10:16:46Z wekan.wekan[5157]: Sanitized and reported to the client as: Text is required [400]

Any idea?

Thanks

**Comment by necarnot** [comment]
Hello,

I'd rather not look as a troll, and I'm willing to help according to my means, but my skills are limited, and though I'm facing the same issue, and needing this issue to be resolved, may I ask what I could do to help you help us?

The version implied are below, and the context is the same (import json from Trello).

Best regards.

Nico

Wekan Version | 3.80.0
-- | --
1.9.2
12.16.1
3.2.22
wiredTiger
 
Linux
linux
x64
4.15.0-88-generic

**Comment by xet7** [comment]
@necarnot 

Can you save that Trello JSON to textfile, compress it to .zip file and upload it to here?
https://www.dropbox.com/request/KQqepyd0Jr62GHfWETfF

I would look how to fix that error.

**Comment by necarnot** [comment]
Thank you Lauri for your help.
I posted the file in your dropbox.

Thank you.

**Comment by necarnot** [comment]
Hello Lauri,

Did you receive the log files I sent you?

Nico

**Comment by xet7** [comment]
@necarnot 

Thanks for reminding! I looked at my Dropbox, it seems that I have received that file. I will look at those.
