### ISSUE TITLE
Github Oauth integration fails with "Error in OAuth Server: Cannot use 'in' operator to search for '[]'"

### ISSUE THREAD

**Issue by hpvb** [wekan/wekan#2438]
I've tested the docker images: 
* quay.io/wekan/wekan:meteor-1.8
* quay.io/wekan/wekan:master
* quay.io/wekan/wekan:edge
* quay.io/wekan/wekan:v2.75
* quay.io/wekan/wekan:devel

With the following environment file:
```
MONGO_URL=mongodb://localhost:27017/wekan
ROOT_URL=https://wekan.godotengine.org
WITH_API=true
BROWSER_POLICY_ENABLED=true
OAUTH2_ENABLED=true
OAUTH2_LOGIN_STYLE=redirect
OAUTH2_CLIENT_ID=***
OAUTH2_SECRET=***
OAUTH2_SERVER_URL=https://github.com
OAUTH2_AUTH_ENDPOINT=/login/oauth/authorize
OAUTH2_USERINFO_ENDPOINT=https://api.github.com/user
OAUTH2_TOKEN_ENDPOINT=/login/oauth/access_token
OAUTH2_ID_MAP=login
OAUTH2_USERNAME_MAP=login
OAUTH2_FULLNAME_MAP=name
OAUTH2_EMAIL_MAP=email
DEBUG=true
```

After completing the login flow I get the following error in the Wekan log:

```
XXX: getToken response:  { access_token: 'XXX',
  token_type: 'bearer',
  scope: '' }
XXX: register token: { access_token: 'XXX',
  token_type: 'bearer',
  scope: '' }
XXX: getUserInfo response:  { login: 'hpvb',
  id: 2591099,
  node_id: 'MDQ6VXNlcjI1OTEwOTk=',
  avatar_url: 'https://avatars2.githubusercontent.com/u/2591099?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/hpvb',
  html_url: 'https://github.com/hpvb',
  followers_url: 'https://api.github.com/users/hpvb/followers',
  following_url: 'https://api.github.com/users/hpvb/following{/other_user}',
  gists_url: 'https://api.github.com/users/hpvb/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/hpvb/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/hpvb/subscriptions',
  organizations_url: 'https://api.github.com/users/hpvb/orgs',
  repos_url: 'https://api.github.com/users/hpvb/repos',
  events_url: 'https://api.github.com/users/hpvb/events{/privacy}',
  received_events_url: 'https://api.github.com/users/hpvb/received_events',
  type: 'User',
  site_admin: false,
  name: 'Hein-Pieter van Braam',
  company: 'Prehensile Tales B.V',
  blog: 'prehensile-tales.com',
  location: 'Uitgeest',
  email: 'hp@tmm.cx',
  hireable: null,
  bio: null,
  public_repos: 24,
  public_gists: 8,
  followers: 35,
  following: 0,
  created_at: '2012-10-18T17:02:47Z',
  updated_at: '2019-05-30T02:23:57Z' }
XXX: userinfo: { login: 'hpvb',
  id: 2591099,
  node_id: 'MDQ6VXNlcjI1OTEwOTk=',
  avatar_url: 'https://avatars2.githubusercontent.com/u/2591099?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/hpvb',
  html_url: 'https://github.com/hpvb',
  followers_url: 'https://api.github.com/users/hpvb/followers',
  following_url: 'https://api.github.com/users/hpvb/following{/other_user}',
  gists_url: 'https://api.github.com/users/hpvb/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/hpvb/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/hpvb/subscriptions',
  organizations_url: 'https://api.github.com/users/hpvb/orgs',
  repos_url: 'https://api.github.com/users/hpvb/repos',
  events_url: 'https://api.github.com/users/hpvb/events{/privacy}',
  received_events_url: 'https://api.github.com/users/hpvb/received_events',
  type: 'User',
  site_admin: false,
  name: 'Hein-Pieter van Braam',
  company: 'Prehensile Tales B.V',
  blog: 'prehensile-tales.com',
  location: 'Uitgeest',
  email: 'hp@tmm.cx',
  hireable: null,
  bio: null,
  public_repos: 24,
  public_gists: 8,
  followers: 35,
  following: 0,
  created_at: '2012-10-18T17:02:47Z',
  updated_at: '2019-05-30T02:23:57Z' }
{"line":"431","file":"oauth.js","message":"Error in OAuth Server: Cannot use 'in' operator to search for '[]' in null","time":{"$date":1559185527368},"level":"warn"}
Exception while invoking method 'login' { stack: 'TypeError: Cannot use \'in\' operator to search for \'[]\' in null\n    at packages/underscore.js:894:15\n    at Array.forEach (<anonymous>)\n    at _.each._.forEach (packages/underscore.js:139:11)\n    at Function._.pick (packages/underscore.js:893:5)\n    at Object.handleOauthRequest (packages/wekan-oidc.js:48:20)\n    at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)\n    at middleware (packages/oauth.js:203:5)\n    at packages/oauth.js:176:5',
  source: 'method' }
```

**Comment by road42** [comment]
This seems to be the same as issue #2206. Maybe you have a look at it.

**Comment by xet7** [comment]
Moved to #2206
