### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by mauzao9** [wekan/wekan#249]
Hello, i am facing one error when trying to run the server at the last step, can share some light on what did gone wrong?

```
bacon@ubuntu:~/wekan/.build/bundle$ node main.js
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
/home/bacon/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/bacon/wekan/.build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/bacon/wekan/.build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/home/bacon/wekan/.build/bundle/programs/server/boot.js:162:18)
    at packages/npm-bcrypt/packages/npm-bcrypt.js:9:1
    at packages/npm-bcrypt/packages/npm-bcrypt.js:13:1
bacon@ubuntu:~/wekan/.build/bundle$ sudo node main.js
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
/home/bacon/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/idmontie_migrations/packages/idmontie_migrations.js:32:1
    at packages/idmontie_migrations/packages/idmontie_migrations.js:148:1
    at /home/bacon/wekan/.build/bundle/programs/server/packages/idmontie_migrations.js:165:4
    at /home/bacon/wekan/.build/bundle/programs/server/packages/idmontie_migrations.js:172:3
    at /home/bacon/wekan/.build/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/bacon/wekan/.build/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
```

**Comment by flippingtables** [comment]
I had the same issue, try running node.js version 0.10.40.

**Comment by mauzao9** [comment]
Works with that version indeed, much thanks!
So there is no admin far i see yet?

**Comment by ePirat** [comment]
No, there are no admin settings or an admin account implemented yet, as far as I know. (btw if your issue is resolved, please close this bug and if you another issue not related to this, open a new one)

**Comment by kramer65** [comment]
You can solve at least one of the errors (`Error: MONGO_URL must be set in environment`) by following the tip in the error. You can set the MONGO_URL as follows:

    export MONGO_URL=mongodb://localhost:27017/wekan

About the other error (`Error: Module did not self-register`), I have no idea. I'm actually facing that myself as well.

**Comment by AlexanderS** [comment]
The `Error: Module did not self-register` is related to the meteor framework. What node version are you using? Did you run `npm install` in the bundle directory? Please also check the other pointers given in: https://github.com/meteor/meteor/issues/7512. 

Note: You should *not* use `sudo` to run node.

**Comment by Vladimir37** [comment]
Node v4.6.0
`Error: Module did not self-register`

**Comment by xet7** [comment]
Please use Docker version or precompiled tar.gz version.

Closing issue.
