### ISSUE TITLE
Importing board with multiple check list fails

### ISSUE THREAD

**Issue by pcurie** [wekan/wekan#2548]
Hello Team,

Running Wekan 2.97 I face this issue, I can export the board without problems and the data is present in the json, but when I import it, I get an error 400 on the web ui.

In the logs I have this :

```
Exception while invoking method 'importBoard' { stack: 'Error: Checklist id is required\n    at getErrorObject (packages/aldeed_collection2-core.js:480:15)\n    at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)\n    at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)\n    at packages/matb33_collection-hooks.js:127:46\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)\n    at Object.directOp (packages/matb33_collection-hooks.js:47:27)\n    at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)\n    at wekanChecklistItems.forEach (models/wekanCreator.js:598:53)\n    at Array.forEach (<anonymous>)\n    at WekanCreator.createChecklistItems (models/wekanCreator.js:589:25)\n    at WekanCreator.create (models/wekanCreator.js:822:10)\n    at DDPCommon.MethodInvocation.importBoard (models/import.js:29:20)\n    at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n    at packages/check.js:128:16\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)\n    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)',
  source: 'method' }
Sanitized and reported to the client as: Checklist id is required [400]
```

The import still finish but most of the check lists are gone from the cards.

I run export from 2.97 and also import on 2.97, two different instances.

Any help solving this would be appreciated.

Thank you

**Comment by xet7** [comment]
@pcurie 

It looks like a bug, so someone could look how to fix it. Code is at this GitHub repos at directory `wekan/models/`

**Comment by xet7** [comment]
Try newest Wekan.
