### ISSUE TITLE
Doesnt work on my traefik setup probably because of the MONGO_URL.

### ISSUE THREAD

**Issue by thepenguinthatwants** [wekan/wekan#2556]
## Issue

**Server Setup Information**:

OS debian 9
Using Traefik.

```
wekan-db   | 2019-07-19T09:39:41.177+0000 I CONTROL  [initandlisten] build environment:
wekan-db   | 2019-07-19T09:39:41.177+0000 I CONTROL  [initandlisten]     distmod: debian81
wekan-db   | 2019-07-19T09:39:41.177+0000 I CONTROL  [initandlisten]     distarch: x86_64
wekan-db   | 2019-07-19T09:39:41.177+0000 I CONTROL  [initandlisten]     target_arch: x86_64
wekan-db   | 2019-07-19T09:39:41.177+0000 I CONTROL  [initandlisten] options: { replication: { oplogSizeMB: 128 }, storage: { mmapv1: { smallFiles: true } } }
wekan-db   | 2019-07-19T09:39:41.198+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1G,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
wekan-db   | 2019-07-19T09:39:41.372+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
wekan-db   | 2019-07-19T09:39:41.389+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
wekan-db   | 2019-07-19T09:39:41.389+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
wekan-db   | 2019-07-19T09:39:41.389+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
wekan-app  |
wekan-app  | /build/programs/server/node_modules/fibers/future.js:313
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^
wekan-app  | MongoError: failed to connect to server [172.168.1.200:27017] on fi                                                                                                                                                             rst connect [MongoError: connection 0 to 172.168.1.200:27017 timed out]
wekan-app  |     at Pool.<anonymous> (/build/programs/server/npm/node_modules/me                                                                                                                                                             teor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
wekan-app  |     at emitOne (events.js:116:13)
wekan-app  |     at Pool.emit (events.js:211:7)
wekan-app  |     at Connection.<anonymous> (/build/programs/server/npm/node_modu                                                                                                                                                             les/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
wekan-app  |     at Object.onceWrapper (events.js:317:30)
wekan-app  |     at emitTwo (events.js:126:13)
wekan-app  |     at Connection.emit (events.js:214:7)
wekan-app  |     at Socket.<anonymous> (/build/programs/server/npm/node_modules/                                                                                                                                                             meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:197:10)
wekan-app  |     at Object.onceWrapper (events.js:313:30)
wekan-app  |     at emitNone (events.js:106:13)
wekan-app  |
wekan-app  | /build/programs/server/node_modules/fibers/future.js:313
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^
wekan-app  | MongoError: failed to connect to server [172.168.1.200:27017] on first connect [MongoError: connection 0 to 172.168.1.200:27017 timed out]
wekan-app  |     at Pool.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
wekan-app  |     at emitOne (events.js:116:13)
wekan-app  |     at Pool.emit (events.js:211:7)
wekan-app  |     at Connection.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
wekan-app  |     at Object.onceWrapper (events.js:317:30)
wekan-app  |     at emitTwo (events.js:126:13)
wekan-app  |     at Connection.emit (events.js:214:7)
wekan-app  |     at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:197:10)
wekan-app  |     at Object.onceWrapper (events.js:313:30)
wekan-app  |     at emitNone (events.js:106:13)
wekan-app exited with code 1

```

**Problem description**:

I already have a working traefik setup but I tried to get wekan work by the docker-compose example that I found in.

https://github.com/wekan/wekan/wiki/Traefik-and-self-signed-SSL-certs

I don't have any clue what might be mongodb URL. So I set it to
      - MONGO_URL=mongodb://172.168.1.200:27017/wekan

Other informations are probably all right such as ROOT_URL etc. There was no mention about what to put into the MONG_URL or how to check what is the right value.

**Comment by thepenguinthatwants** [comment]
- MONGO_URL=mongodb://wekandb:27017/wekan

seems to work now.
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml checked from here.
