### ISSUE TITLE
Feedback: Error when Install Wekan 3.03

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2585]
I deleted all containers in Docker on Win10 and install the wekan V3.03 with the officia docker-compose.yml.
the wekan-app and wekan-db are always restarting...
when I use docker logs wekan-app
Error info:
MongoNetworkError: failed to connect to server [wekandb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND wekandb wekandb:27017]
    at Pool.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
when I use docker logs wekan-db:
Error info is :

2019-08-06T13:41:08.293+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=a3ba018f146f
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] db version v4.0.11
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] git version: 417d1a712e9f040d54beca8e4943edce218e9a8c
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] modules: none
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] build environment:
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-08-06T13:41:08.296+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { oplogSizeMB: 128 }, storage: { mmapv1: { smallFiles: true } } }
2019-08-06T13:41:08.296+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-08-06T13:41:08.296+0000 I STORAGE  [initandlisten]
2019-08-06T13:41:08.296+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2019-08-06T13:41:08.296+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2019-08-06T13:41:08.296+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=478M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2019-08-06T13:41:09.190+0000 I STORAGE  [initandlisten] WiredTiger message [1565098869:190867][1:0x7fefe0f5aa80], txn-recover: Main recovery loop: starting at 34/768 to 35/256
2019-08-06T13:41:09.278+0000 I STORAGE  [initandlisten] WiredTiger message [1565098869:278255][1:0x7fefe0f5aa80], txn-recover: Recovering log 34 through 35
2019-08-06T13:41:09.395+0000 I STORAGE  [initandlisten] WiredTiger message [1565098869:395891][1:0x7fefe0f5aa80], txn-recover: Recovering log 35 through 35
2019-08-06T13:41:09.472+0000 I STORAGE  [initandlisten] WiredTiger message [1565098869:472922][1:0x7fefe0f5aa80], txn-recover: Set global recovery timestamp: 0
2019-08-06T13:41:10.006+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2019-08-06T13:41:10.162+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
2019-08-06T13:41:10.162+0000 I CONTROL  [initandlisten]
2019-08-06T13:41:10.162+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-08-06T13:41:10.162+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-08-06T13:41:10.162+0000 I CONTROL  [initandlisten]
2019-08-06T13:41:10.262+0000 F CONTROL  [initandlisten] ** IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.6 before attempting an upgrade to 4.0; see http://dochub.mongodb.org/core/4.0-upgrade-fcv for more details.
2019-08-06T13:41:10.262+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2019-08-06T13:41:10.262+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
2019-08-06T13:41:10.262+0000 I STORAGE  [initandlisten] WiredTigerKVEngine shutting down
2019-08-06T13:41:10.281+0000 I STORAGE  [initandlisten] Shutting down session sweeper thread
2019-08-06T13:41:10.281+0000 I STORAGE  [initandlisten] Finished shutting down session sweeper thread
2019-08-06T13:41:10.515+0000 I STORAGE  [initandlisten] Downgrading WiredTiger datafiles.
2019-08-06T13:41:11.047+0000 I STORAGE  [initandlisten] WiredTiger message [1565098871:47471][1:0x7fefe0f5aa80], txn-recover: Main recovery loop: starting at 35/3456 to 36/256
2019-08-06T13:41:11.136+0000 I STORAGE  [initandlisten] WiredTiger message [1565098871:136691][1:0x7fefe0f5aa80], txn-recover: Recovering log 35 through 36
2019-08-06T13:41:11.267+0000 I STORAGE  [initandlisten] WiredTiger message [1565098871:267322][1:0x7fefe0f5aa80], txn-recover: Recovering log 36 through 36
2019-08-06T13:41:11.339+0000 I STORAGE  [initandlisten] WiredTiger message [1565098871:339198][1:0x7fefe0f5aa80], txn-recover: Set global recovery timestamp: 0
2019-08-06T13:41:12.751+0000 I STORAGE  [initandlisten] shutdown: removing fs lock...
2019-08-06T13:41:12.751+0000 I CONTROL  [initandlisten] now exiting
2019-08-06T13:41:12.751+0000 I CONTROL  [initandlisten] shutting down with code:62

**Comment by xet7** [comment]
You have old Wekan database data still:
> Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.

If you have not taken backup, you can change MongoDB back to version 3.2.22 by using old docker-compose.yml at https://github.com/wekan/wekan devel branch, and then making backup like this:
```
docker exec -it wekan-db bash
cd /data
mongodump
exit
docker cp wekan-db:/data/dump .
```
For cleanup, on Linux I use this kind of start.sh script:
https://github.com/wekan/docker-cleanup-volumes

But I don't know where Wekan Docker volumes are stored at Windows. Wekan MongoDB data is stored outside of Docker containers in volume, as described at docker-compose.yml, so those volumes need to be deleted.

After that, with new docker-compose.yml, if you use only at localhost then you don't need to modify ROOT_URL. Otherwise, more info at https://github.com/wekan/wekan/wiki/Settings

Then start Wekan, and restore data:
```
docker-compose up -d
docker cp dump wekan-db:/data/
docker stop wekan-app
docker exec -it wekan-db bash
cd /data
mongorestore --drop --noIndexRestore
rm -rf dump
exit
docker start wekan-app
```
After that, Wekan is at http://localhost . Windows firewall will ask to allow port 80.

**Comment by javen9881** [comment]
Oh, Yes, I make it. thanks
