### ISSUE TITLE
ReferenceError: cardAssignees is not defined

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2612]
After updating I can't edit cards. Adding or changing dates doesn't work either. But mails are send with the changes in it, which are not saved. 

![Untitled](https://user-images.githubusercontent.com/1153741/62918100-eec6d000-bd9e-11e9-9b6d-5952b68a335c.gif)

```
Exception while invoking method '/cards/update' ReferenceError: cardAssignees is not defined
    at Object.Cards.before.update (models/cards.js:1788:5)
    at packages/matb33_collection-hooks.js:467:28
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:466:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:465:9)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
    at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
    at MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
    at currentArgumentChecker.withValue (packages/check/match.js:118:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:52:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Session.sessionProto.protocol_handlers.method (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:51:44)
    at packages/ddp-server/livedata_server.js:559:43

```

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 3.16.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: debian 10
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 8.16.0
* MongoDB Version: 4.0.11, wiredtiger
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):https://redaktion.bonn.digital

**Comment by saschafoerster** [comment]
@xet7 Thanks! :)
