### ISSUE TITLE
Do not send email notify when mentioning user in comment

### ISSUE THREAD

**Issue by zztalker** [wekan/wekan#2735]
## Issue

When try to mention user by @username in comment got traceback in log, and no emails sent.

```
Exception while invoking method '/card_comments/insert' TypeError: Cannot read property 'emails' of undefined
    at Object.Activities.after.insert (models/activities.js:197:38)
    at packages/matb33_collection-hooks.js:382:18
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:381:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
    at ns.Collection.insert (packages/mongo/collection.js:520:39)
    at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
    at commentCreation (models/cardComments.js:101:14)
    at Object.CardComments.after.insert (models/cardComments.js:121:5)
    at packages/matb33_collection-hooks.js:382:18
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:381:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
    at ns.Collection.CollectionPrototype._validatedInsert (packages/allow-deny/allow-deny.js:256:27)
    at MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
    at currentArgumentChecker.withValue (packages/check/match.js:118:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
```

**Server Setup Information**:

Docker image: quay.io/wekan/wekan

```
Wekan Version | 3.42.0
Node version | 8.16.1
```

If I press test [Send test email to yourself] button it works fine.

**Comment by zztalker** [comment]
I've updated the image to version 3.44.0 and problem was gone.
