### ISSUE TITLE
Wekan (bundle version) 3.45 is broken

### ISSUE THREAD

**Issue by fpaillot** [wekan/wekan#2742]
## Issue

When we try to install wekan 3.45 (bundle version), we get this : 

`> bcrypt@3.0.6 install /opt/wekan/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

module.js:550
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/wekan/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

Node version is "8.16.1" and npm version is "6.4.1" on Ubuntu 16.04.

We tried a lot of things based on what we found on google for this kind of error (running as root, trying to change package release, ..)

Thanks !

**Comment by xet7** [comment]
I tried bundle on Ubuntu 16.04, it did work fine. [Bundle install info here](https://github.com/wekan/wekan/wiki/Platforms#not-exposed-to-internet-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures-no-automatic-updates-no-sandboxing).
