### ISSUE TITLE
Bug: can't delete user from a board

### ISSUE THREAD

**Issue by suprovsky** [wekan/wekan#2764]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yeah
* Did you test in newest Wekan?: yeah
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yeah no problems with it
* Wekan version: 3.49
* Operating System: Ubuntu 19.10 but the same thing happened on Ubuntu 19.04 before the upgrade
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 8.16.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*

I can't record an animated gif, because I want to keep users anonymized.
To delete user I clicked on the user avatar in the Members section of the board, clicked Delete from board and Delete member. He got deleted, but after that he got added again.

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
`Exception from Tracker recompute function: undefined
fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:1 Error: cannot call methods on draggable prior to initialization; attempted to call method 'option'
    at Function.error (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:19:2107)
    at HTMLAnchorElement.<anonymous> (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:221:5706)
    at Function.each (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:19:3172)
    at p.fn.init.each (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:19:1139)
    at p.fn.init.t.fn.<computed> [as draggable] (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:221:5450)
    at f.View.<anonymous> (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:339:431412)
    at https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63:18999
    at Function.e._withTemplateInstanceFunc (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63:37826)
    at https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63:18951
    at Object.f._withCurrentView (https://<anonymized domain>/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63:23077) undefined`
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
`2019-10-26T07:36:26Z wekan.wekan[1225]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at ns.Collection.update (packages/mongo/collection.js:585:31)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at ns.Collection.Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core.js:232:19)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at memberId (models/boards.js:1067:15)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at Object.keys.forEach.set (models/boards.js:1053:9)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at Array.forEach (<anonymous>)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at foreachRemovedMember (models/boards.js:1042:27)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at Object.Boards.before.update (models/boards.js:1066:7)
2019-10-26T07:36:26Z wekan.wekan[1225]:     at packages/matb33_collection-hooks.js:467:28
2019-10-26T07:36:26Z wekan.wekan[1225]:     at Array.forEach (<anonymous>)
`

**Comment by xet7** [comment]
Please try with newest Wekan.
