### ISSUE TITLE
Board export times out

### ISSUE THREAD

**Issue by cimm** [wekan/wekan#2776]
I am using the snap version of Wekan 3.49.0 on an Ubuntu 18.04 64-bit box and can no longer export a board. The snap config looks like:

```
Key                         Value
port                        3001
richer-card-comment-editor  false
root-url                    https://[REDACTED]
with-api                    true
```

Clicking the export button makes browser spin for few minutes (as in "hold on, loading this for you") after which it spews a  `File not found` error. The log doesn't show anything special. The board is not extremely large (maybe a few 100 cards) and I tried removing a lot of cards already.

Some cards can't be removed, not sure if this is a separate issue or if it's linked. An impossible to delete card does show in the logs:

```
2019-10-31T15:17:18Z wekan.wekan[9210]: Exception while invoking method '/cards/remove' TypeError: Cannot read property 'title' of undefined
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.Activities.after.insert (models/activities.js:222:36)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at packages/matb33_collection-hooks.js:382:18
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Array.forEach (<anonymous>)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at after (packages/matb33_collection-hooks.js:381:9)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at ns.Collection.insert (packages/mongo/collection.js:520:39)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.ChecklistItems.before.remove (models/checklistItems.js:238:16)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at packages/matb33_collection-hooks.js:558:28
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Array.forEach (<anonymous>)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at packages/matb33_collection-hooks.js:557:11
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Array.forEach (<anonymous>)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at ns.Collection.remove (packages/mongo/collection.js:620:31)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at cardRemover (models/cards.js:1541:18)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.Cards.before.remove (models/cards.js:1718:5)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at packages/matb33_collection-hooks.js:558:28
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Array.forEach (<anonymous>)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at packages/matb33_collection-hooks.js:557:11
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Array.forEach (<anonymous>)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-10-31T15:17:18Z wekan.wekan[9210]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)
```

I tried narrowing down this issue but it happens with cards with or without lists, with or without tags, with or without people or attachments.

I don't care about the deleting cards too much, just mentioning it since it might be related to the board exporting. The export is annoying since some of our salaries are calculated on the data in that export and... well... we can't calculate the salaries if we can't see the data.

My guess is that the server simply times out after a few minutes. Any hints how I can start debugging this?

Thank you!

**Comment by xet7** [comment]
This is because some of your checklists do not have checklist titles (checklist names). You can add checklist titles and try again.

I will try to fix this sometime.

**Comment by xet7** [comment]
Like your error shows, it stops to this line where it checks for 'checklist.title' that does not exist:
https://github.com/wekan/wekan/blob/master/models/activities.js#L222

**Comment by cimm** [comment]
Thank you!

I tried and indeed, I can reproduce the error. Create a card and add a checklist _with a title_ (since you can't add a checklist without). Now... _delete the checklist_... and... you have an unremovable card.

The deletion of the checklist seems to be the issue. The checklist is removed so has more title... hence the error when you try to delete the card.

Problem is I currently don't have a workaround, I can add a title (the checklist has been removed remember) and adding _new_ checklist with a title doesn't seem to tick it into believing it has one.

Not a MongoDB expert but it looks like deleting the checklist doesn't really remove it from the database.

**Comment by xet7** [comment]
With [nosqlbooster](https://nosqlbooster.com/downloads) GUI you can connect through ssh to server localhost port 27019 and there from wekan database look at those boards and delete remaining checklist.

**Comment by cimm** [comment]
Thank you.

I managed to delete the cards via the mongo shell. If anyone else would have the same issue:

``js
$ mongo --port 27019
> use wekan
> db.cards.deleteMany({ archived: true })
```

:warning: This will *delete all* archived cards in all boards. Change the filter to your preference.

@xet7 I had an undeletable board. Removing the undeletable cards on this board fixed that issue, I can now delete the board, cool. The main issue isn't resolved sadly enough, I still can't export the board. The board has 188 cards so I don't think it's a performance issue.

**Comment by xet7** [comment]
@cimm 

When you try to export board, what errors you get at browser inspect console?

At All Boards page, can you duplicate board and then export it ?

**Comment by cimm** [comment]
The only output in the logs are the always recurring

```
2019-11-02T20:44:55Z mongod.27019[10620]: [conn4] received client metadata from 127.0.0.1:58630 conn4: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.0.0-1021-gcp" }, platform: "Node.js v8.16.1, LE, mongodb-core: 2.0.11" }
```

lines but I think these are heartbeats or something, aren't they? Don't think they have anything to do with the export process.

Clicking the `Export board` option shows the Firefox "loading page" animation in the title bar and after +/- 3 minutes it shows the standard "File not found" error (status code `200` though).

![Screenshot from 2019-11-02 21-50-28](https://user-images.githubusercontent.com/68112/68076867-d624ef80-fdba-11e9-8c6e-dfdd2ae338f4.png)

Nothing in the Firefox console.

I copied the URL and tried with `wget`, same issue, loads for a few minutes... error:

```
HTTP request sent, awaiting response... 502 Proxy Error
2019-11-02 21:51:49 ERROR 502: Proxy Error.
```

Duplicating the board from the "All Boards" doesn't work. Nothing in the logs but the Firefox console gives:

```
Exception while simulating the effect of invoking 'cloneBoard' ReferenceError: "Buffer is not defined"
    s https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:339
    wrapAsync https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:1
    attachments https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:339
    build https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:339
    cloneBoard https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:339
    p https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:83
    withValue https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:1
    apply https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:83
    call https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:83
    click .js-clone-board https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:339
    s/t[n]/</< https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:233
    _withCurrentView https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63
    s/t[n]/< https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:233
    _withTemplateInstanceFunc https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63
    n https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:233
    i https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63
    _withCurrentView https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63
    i https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63
    delegatedHandler https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:63
    dispatch https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:19
    handle https://REDACTED/fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js?meteor_js_resource=true:19
fe8fd6cb3d67139c3453a8275948aad1fabfb8f8.js:1:6755
```

Does this help in any way?

**Comment by xet7** [comment]
Well, you could try Wekan edge version. It has some fixes, but could change order of lists, although it has some list ordering features too.

```
sudo snap refresh wekan --edge --amend
```
Then try export again. In edge version, you can move cards and lists when you click at right top corner your username / Change Settings / Show desktop drag handles. Then from those cross looking handles you can move cards and lists.

If you like to go back to stable version, you can do it with:
```
sudo snap refresh wekan --stable --amend
```
