### ISSUE TITLE
Fix some webhooks about board delete etc, and some webhook messages missing

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2950]
Just a note to myself.

I was fixing webhooks from wekan v3.79 to v3.83:

Before:
https://github.com/wekan/wekan/blob/v3.80/models/activities.js#L124-L130

After:
https://github.com/wekan/wekan/blob/master/models/activities.js#L124-L133

Problem is, there is no webhook message about board delete, for example when getting message with Global Webhooks at Admin Panel to Rocket.Chat.

There is some error that board title is undefined:
```
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: Exception while invoking method '/boards/remove' TypeError: Cannot read property 'title' of undefined
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Object.<anonymous> (models/activities.js:126:28)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at packages/matb33collection-hooks.js:422:18
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Array.forEach (<anonymous>)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Function..each..forEach (packages/underscore.js:139:11)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at after (packages/matb33_collection-hooks.js:421:9)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Object.<anonymous> (packages/matb33_collection-hooks.js:436:12)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Object.collection.<computed> [as insert] (packages/matb33_collection-hooks.js:150:21)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at ns.Collection.insert (packages/mongo/collection.js:520:39)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Object.<anonymous> (models/lists.js:382:16)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at packages/matb33_collection-hooks.js:598:28
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Array.forEach (<anonymous>)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Function..each..forEach (packages/underscore.js:139:11)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at packages/matb33_collection-hooks.js:597:11
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Array.forEach (<anonymous>)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Function..each..forEach (packages/underscore.js:139:11)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Object.<anonymous> (packages/matb33_collection-hooks.js:596:9)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Object.collection.<computed> [as remove] (packages/matb33_collection-hooks.js:150:21)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at ns.Collection.remove (packages/mongo/collection.js:620:31)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at models/boards.js:1190:15
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Array.forEach (<anonymous>)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at boardRemover (models/boards.js:1188:62)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Object.<anonymous> (models/boards.js:1394:5)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at packages/matb33_collection-hooks.js:598:28
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Array.forEach (<anonymous>)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Function..each._.forEach (packages/underscore.js:139:11)
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at packages/matb33_collection-hooks.js:597:11
Mar 1 17:06:42 ip-172-31-35-186 wekan.wekan[30813]: at Array.forEach (<anonymous>)
``` 
But, I got this log from someone else's script, it's not my script.

With web UI, when deleting boards, it should send webhook message about deletion.

There is community discussion about this here:
https://community.vanila.io/?t=a7f0bc8e-72d1-4e6f-88cf-8f084c5adccc

Also, some webhook messages do not have translations, so I should add them sometime.

And also check that all possible board actions have webhook message.

**Comment by xet7** [comment]
Also, I could check are webhook messages translated, or does it need some change to Wekan code so that webhook messages would be translated.

**Comment by bandresen** [comment]
To give my 2 cents regarding webhooks. I think it's more important that all the information is contained in the payload, than to have a translation of the string that is compiled.

For example the move card webhook contains quite a bit of information in the compiled string, but not as an item in the payload. (Example: what swimline, what list, and username)

Do you consider these individual bugs that should be reported per webhook?

**Comment by xet7** [comment]
@bandresen 

This issue already contains these:
- translating webhooks
- adding more info to webhooks
- fixing webhooks

I will later combine more of other webhook issues to this webhook.

Translations are very important to everyone that can not speak/write/read English.

**Comment by xet7** [comment]
@jtbairdsr

Do you have time to add activities and webhooks for these, if they don't yet exist?

- Archive board
- Create board
- Delete board
- Rename Board
- Rename Swimlane
- Rename Card

**Comment by xet7** [comment]
@jtbairdsr 

This is not in any way critical or urgent, so I can also look at this sometime.

For you, this #3007 is more important.

**Comment by xet7** [comment]
Largely resolved in the current code (upcoming WeKan release). Board, list and swimlane deletion already create removeBoard/removeList/removeSwimlane activities, so their outgoing webhooks already fire. The one remaining gap — no webhook on CARD deletion — was fixed in commit 7bb7540ba ( https://github.com/wekan/wekan/commit/7bb7540ba ) (see #1587), and the act-deleteCard/act-removeBoard/act-removeList/act-removeSwimlane i18n strings were added so these activities render. Please reopen with specifics if a particular webhook message is still missing.
