### ISSUE TITLE
Build from Source BCrupt@3.0.7 Error

### ISSUE THREAD

**Issue by Keelan** [wekan/wekan#2979]
## Issue

    bcrypt@3.0.7 install /home/wekan/bundle/programs/server/npm/node_modules/bcrypt
    node-pre-gyp install --fallback-to-build
    
    internal/modules/cjs/loader.js:979
      throw err;
      ^
    
    Error: Cannot find module '../'
    Require stack:
    - /home/wekan/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
        at Function.Module._load (internal/modules/cjs/loader.js:859:27)
        at Module.require (internal/modules/cjs/loader.js:1036:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/home/wekan/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp:15:20)
        at Module._compile (internal/modules/cjs/loader.js:1147:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
        at Module.load (internal/modules/cjs/loader.js:996:32)
        at Function.Module._load (internal/modules/cjs/loader.js:896:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/wekan/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp'
      ]
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! bcrypt@3.0.7 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the bcrypt@3.0.7 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/wekan/.npm/_logs/2020-03-31T18_21_51_535Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the meteor-dev-bundle@ install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/wekan/.npm/_logs/2020-03-31T18_21_51_597Z-debug.log
    wekan@SECOND:~/bundle/programs/server$

    bcrypt@3.0.7 install /home/wekan/bundle/programs/server/npm/node_modules/bcrypt
    node-pre-gyp install --fallback-to-build

    internal/modules/cjs/loader.js:979
      throw err;
      ^

    Error: Cannot find module '../'
    Require stack:
    - /home/wekan/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
        at Function.Module._load (internal/modules/cjs/loader.js:859:27)
        at Module.require (internal/modules/cjs/loader.js:1036:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/home/wekan/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp:15:20)
        at Module._compile (internal/modules/cjs/loader.js:1147:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
        at Module.load (internal/modules/cjs/loader.js:996:32)
        at Function.Module._load (internal/modules/cjs/loader.js:896:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/wekan/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp'
      ]
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! bcrypt@3.0.7 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the bcrypt@3.0.7 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output         above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/wekan/.npm/_logs/2020-03-31T18_21_51_535Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the meteor-dev-bundle@ install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/wekan/.npm/_logs/2020-03-31T18_21_51_597Z-debug.log
    wekan@SECOND:~/bundle/programs/server$

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: **Yes**
* Did you test in newest Wekan?: **Trying to install  3.86**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings? **Not got that far**
* Wekan version: **3.86**
* If this is about old version of Wekan, what upgrade problem you have?: **No fresh install**
* Operating System: **Ubuntu 16.04**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **Source, im on OVH so need to build form source**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **None**
* Node Version:  **13.12.0** (i tried 8.16.2 as the guide says, same error)
* MongoDB Version: **4.2.5**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?: **Chrome**

**Problem description**:
- Download latest release from https://releases.wekan.team/ (3.86)
- Unpack zip file
- cd to bundle/programs/server
- npm install
- Will fail with bcrypt install error

**Comment by xet7** [comment]
There is no need to build from source or to run `npm install`, because there is prebuild bundle/.zip file wekan-VERSION.zip at https://releases.wekan.team , see https://github.com/wekan/wekan/wiki/Raspberry-Pi for install info. Node version required is currently 12.16.1, and MongoDB 3.2.x - 4.x (any of those, newest prefererred). You can use start-wekan.sh or SystemD service to run it.

**Comment by Keelan** [comment]
Using start-wekan.sh

https://i.imgur.com/Ux7fIdv.png

**Comment by Keelan** [comment]
`wekan@SECOND:~$ ./start-wekan.sh`

> /home/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoNetworkError: failed to connect to server [127.0.0.1:27018] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27018
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/home/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:311:20)
    at /home/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /home/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /home/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/home/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/home/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:418:26)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
wekan@SECOND:~$


**MongoDB is running**

`wekan@SECOND:~$ systemctl status  mongod`

> mongod.service - MongoDB Database Server
   Loaded: loaded (/lib/systemd/system/mongod.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-03-31 17:01:52 EDT; 6min ago
     Docs: https://docs.mongodb.org/manual
 Main PID: 23859
   CGroup: /system.slice/mongod.service
           └─23859 n/a
wekan@SECOND:~$

**Comment by xet7** [comment]
In your `start-wekan.sh` you probably have this:
```
export MONGO_URL='mongodb://127.0.0.1:27018/wekan'
```
Usually MongoDB is installed to port 27017, so please change this to:
```
export MONGO_URL='mongodb://127.0.0.1:27017/wekan'
```
Sorry about confusion, I will make this change to Wekan source code.

**Comment by Keelan** [comment]
`wekan@SECOND:~$ ./start-wekan.sh`

> /home/wekan/.build/bundle/programs/server/node_modules/@babel/parser/lib/index.js:12
  constructor(label, conf = {}) {
                          ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/home/wekan/.build/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/wekan/.build/bundle/programs/server/node_modules/reify/lib/parsers/babel.js:3:21)
    at Module._compile (module.js:409:26)
wekan@SECOND:~$
