### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3007]
@jtbairdsr

I got this error about notifications. Do you have time to look at it?
```
I20200411-00:00:00.017(3) (percolate_synced-cron.js:87) SyncedCron: Starting "notification_cleanup".
I20200411-00:00:00.023(3) (percolate_synced-cron.js:87) SyncedCron: Exception "notification_cleanup" TypeError: user.profile.notifications is not iterable
    at Object.job (models/users.js:955:51)
    at packages/percolate_synced-cron.js:242:26
    at scheduleTimeout (packages/percolate_synced-cron.js:290:7)
    at packages/percolate_synced-cron.js:338:42
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)
```

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3010
