### ISSUE TITLE
Move selection doesn't work

### ISSUE THREAD

**Issue by rptl** [wekan/wekan#3119]
Server Setup Information
Did you test in newest Wekan?: yes
Wekan version: 4.04.0
Operating System:Debian 9.9
Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
Node Version: 12.16.3
What webbrowser version are you using? Android Chrome

Steps to reproduce:
1 -Click "Multi-Selection"
2- Select cards
3- Click "Move selection" and pick a list. Nothing happens.

Stack trace:
```
Exception while invoking method '/customFields/update' TypeError: Cannot read property 'title' of undefined
    at Object.<anonymous> (models/activities.js:125:17)
    at packages/matb33_collection-hooks.js:422:18
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:421:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:436:12)
    at Object.collection.<computed> [as insert] (packages/matb33_collection-hooks.js:150:21)
    at ns.Collection.insert (packages/mongo/collection.js:523:39)
    at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
    at Object.<anonymous> (models/customFields.js:209:18)
    at packages/matb33_collection-hooks.js:506:28
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:505:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:504:9)
    at Object.collection.<computed> [as update] (packages/matb33_collection-hooks.js:150:21)
    at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
    at MethodInvocation.m.<computed> (packages/allow-deny/allow-deny.js:173:46)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
```

Tested on Firefox and Chrome

**Comment by marc1006** [comment]
@rptl Do you know since which version it's broken?

**Comment by rptl** [comment]
To be honest I have never seen it working. Started with Wekan at least 2
months ago on 3.x , so I believe before that.
