### ISSUE TITLE
Abnormal CPU usage - wekan not responding

### ISSUE THREAD

**Issue by kilbane45** [wekan/wekan#3203]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: We use wekan as daily since almost a year and this issue still on
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 4.17
* Operating System: CentOS Linux release 7.7.1908 (virtualized)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx SSL
* Node Version: 12.18.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox and Chrome

**Problem description**:

Our wekan is used by about 20-30 users simultaneously, running on a 8 x 2.3Ghz, 16Go ram virtual machine. It often goes "mad" by taking massive amount of cpu on node main.js process (sometimes 350% uc use in htop). Wekan become unresponsive, users loose cards and modifications and we need to stop/start the snap to get it work "normal". It's hard to say if it's a particular action that trigger thoses lags because i've not all users near me. When we do "PI plannings", same board can have more than 30 users looking at it and more than one user making modification on it.

![wekan_cpu](https://user-images.githubusercontent.com/67906727/86593706-fe8e6a80-bf95-11ea-95e7-755e3295f5f0.PNG)
![wekan_cpu_treeview](https://user-images.githubusercontent.com/67906727/86593774-254ca100-bf96-11ea-93ac-67ce3f6be377.PNG)

Here is last snap log but for example i got issue today at ~11:30 AM, don't think this error is related to cpu use.

2020-07-06T09:57:59Z wekan.wekan[85688]: Exception in removedobserveChanges callback: Error: Removed nonexistent document 22HehP4ow3XHHrZ8E
2020-07-06T09:57:59Z wekan.wekan[85688]: at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Session.removed (packages/ddp-server/livedata_server.js:394:10)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Subscription.subscriptionProto.<computed> [as removed] (packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:89:30)
2020-07-06T09:57:59Z wekan.wekan[85688]: at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
2020-07-06T09:57:59Z wekan.wekan[85688]: at runWithEnvironment (packages/meteor.js:1286:24)
2020-07-06T09:57:59Z wekan.wekan[85688]: at packages/meteor.js:1299:14
2020-07-06T09:57:59Z wekan.wekan[85688]: at packages/mongo/observe_multiplex.js:178:30
2020-07-06T09:57:59Z wekan.wekan[85688]: at Array.forEach (<anonymous>)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Function._.each._.forEach (packages/underscore.js:139:11)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Object.task (packages/mongo/observe_multiplex.js:172:9)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
2020-07-06T09:57:59Z wekan.wekan[85688]: at packages/meteor.js:894:12

**Comment by kilbane45** [comment]
More log if i extend the log command to 1000 lines

2020-07-06T09:10:44Z wekan.wekan[90485]: Exception in removedobserveChanges callback: Error: Removed nonexistent document HCG5X8q4953CyoW88
2020-07-06T09:10:44Z wekan.wekan[90485]: at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
2020-07-06T09:10:44Z wekan.wekan[90485]: at Session.removed (packages/ddp-server/livedata_server.js:394:10)
2020-07-06T09:10:44Z wekan.wekan[90485]: at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
2020-07-06T09:10:44Z wekan.wekan[90485]: at Subscription.subscriptionProto.<computed> [as removed] (packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:89:30)
2020-07-06T09:10:44Z wekan.wekan[90485]: at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
2020-07-06T09:10:44Z wekan.wekan[90485]: at runWithEnvironment (packages/meteor.js:1286:24)
2020-07-06T09:10:44Z wekan.wekan[90485]: at packages/meteor.js:1299:14
2020-07-06T09:10:44Z wekan.wekan[90485]: at packages/mongo/observe_multiplex.js:178:30
2020-07-06T09:10:44Z wekan.wekan[90485]: at Array.forEach (<anonymous>)
2020-07-06T09:10:44Z wekan.wekan[90485]: at Function._.each._.forEach (packages/underscore.js:139:11)
2020-07-06T09:10:44Z wekan.wekan[90485]: at Object.task (packages/mongo/observe_multiplex.js:172:9)
2020-07-06T09:10:44Z wekan.wekan[90485]: at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
2020-07-06T09:10:44Z wekan.wekan[90485]: at packages/meteor.js:894:12
2020-07-06T09:24:33Z wekan.wekan[90485]: (node:92642) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received undefined
2020-07-06T09:24:33Z wekan.wekan[90485]: at write_ (_http_outgoing.js:653:11)
2020-07-06T09:24:33Z wekan.wekan[90485]: at ServerResponse.write (_http_outgoing.js:621:15)
2020-07-06T09:24:33Z wekan.wekan[90485]: at models/export.js:93:11
2020-07-06T09:24:33Z wekan.wekan[90485]: at doCall (packages/meteorhacks_picker.js:128:14)
2020-07-06T09:24:33Z wekan.wekan[90485]: at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
2020-07-06T09:24:33Z wekan.wekan[90485]: at processNextRoute (packages/meteorhacks_picker.js:90:14)
2020-07-06T09:24:33Z wekan.wekan[90485]: at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
2020-07-06T09:24:33Z wekan.wekan[90485]: at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
2020-07-06T09:24:33Z wekan.wekan[90485]: at packages/meteorhacks_picker.js:162:10
2020-07-06T09:24:33Z wekan.wekan[90485]: at /snap/wekan/913/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2020-07-06T09:24:33Z wekan.wekan[90485]: (node:92642) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 65)
2020-07-06T09:24:33Z wekan.wekan[90485]: (node:92642) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-07-06T09:24:41Z wekan.wekan[90485]: (node:92642) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received undefined
2020-07-06T09:24:41Z wekan.wekan[90485]: at write_ (_http_outgoing.js:653:11)
2020-07-06T09:24:41Z wekan.wekan[90485]: at ServerResponse.write (_http_outgoing.js:621:15)
2020-07-06T09:24:41Z wekan.wekan[90485]: at models/export.js:93:11
2020-07-06T09:24:41Z wekan.wekan[90485]: at doCall (packages/meteorhacks_picker.js:128:14)
2020-07-06T09:24:41Z wekan.wekan[90485]: at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
2020-07-06T09:24:41Z wekan.wekan[90485]: at processNextRoute (packages/meteorhacks_picker.js:90:14)
2020-07-06T09:24:41Z wekan.wekan[90485]: at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
2020-07-06T09:24:41Z wekan.wekan[90485]: at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
2020-07-06T09:24:41Z wekan.wekan[90485]: at packages/meteorhacks_picker.js:162:10
2020-07-06T09:24:41Z wekan.wekan[90485]: at /snap/wekan/913/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

2020-07-06T09:57:59Z wekan.wekan[85688]: Exception in removedobserveChanges callback: Error: Removed nonexistent document 22HehP4ow3XHHrZ8E
2020-07-06T09:57:59Z wekan.wekan[85688]: at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Session.removed (packages/ddp-server/livedata_server.js:394:10)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Subscription.subscriptionProto.<computed> [as removed] (packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:89:30)
2020-07-06T09:57:59Z wekan.wekan[85688]: at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
2020-07-06T09:57:59Z wekan.wekan[85688]: at runWithEnvironment (packages/meteor.js:1286:24)
2020-07-06T09:57:59Z wekan.wekan[85688]: at packages/meteor.js:1299:14
2020-07-06T09:57:59Z wekan.wekan[85688]: at packages/mongo/observe_multiplex.js:178:30
2020-07-06T09:57:59Z wekan.wekan[85688]: at Array.forEach (<anonymous>)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Function._.each._.forEach (packages/underscore.js:139:11)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Object.task (packages/mongo/observe_multiplex.js:172:9)
2020-07-06T09:57:59Z wekan.wekan[85688]: at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
2020-07-06T09:57:59Z wekan.wekan[85688]: at packages/meteor.js:894:12

**Comment by Keelan** [comment]
https://github.com/wekan/wekan/issues/3202 same issue
I've narrowed it down to checklists on my end. Do you have big checklists?

**Comment by kilbane45** [comment]
I've seen your issue about checklist, i don't know if they make use of checklist, i don't think so but i'll check tomorrow on the biggest board. I've those CPU issues for a long time.

**Comment by kilbane45** [comment]
Hi ! After reviewing boards, no big checlist (maybe <10 checks max), no copy/paste used for them. The board which is most used has many cards (maybe 50+) but the "load on scroll" do his job well for high card number after initial board load.

When load is high i can't even fully load the user list in admin (currently ~150 in base)...

**Comment by xet7** [comment]
Users losing data is basically UI/UX issue.

Most users are familiar with normal HTML/PHP pages, where they see updates on webpage when they reload page.

But Meteor web framework has [Optimistic UI](https://blog.meteor.com/optimistic-ui-with-meteor-67b5a78c3fcf) that does show change on webbrowser immediately, but it takes time for backend to save all data.

## Wekan would work fine this way
1. User logins to Wekan, and never uses `reload webpage` white using Wekan. User only click visible on-page navigation.
2. Big amount of Wekan code and data is loaded to browserside. This takes some time.
3. After that, Wekan works fast, shows UI changes immediately, and after some time data is saved to serverside.
4. If there is some check at serverside that prevents saving to serverside, clientside is reverted to original status. This is [Optimistic UI](https://blog.meteor.com/optimistic-ui-with-meteor-67b5a78c3fcf).

## What actually happens
1. Because users see Wekan UI responding immediately, users mistakenly expect saving to server and reload of Wekan webpage happen immediately.
2. Users keep reloading Wekan webpage, so Wekan loses all clientside cached code and data that Wekan did not have any time to save to serverside.
3. When Wekan page is reloaded, it loads all that code and data again from serverside to clientside. Many users loading Wekan webpage at the same time causes more server load.

## How this kind of UI/UX issue is usually fixed
1. When something big is loading, there is spinner visible, like when loading Wekan first time.
2. When something is saving, there is some blinking dot or some other visible spinner until data is saved to serverside. This is currently missing.
3. When user tries to navigate away from page, or tries to reload webpage, there is some popup notifying that there is still unsaved data and user should wait until saving is finished. This is currently missing.
4. When network connection is lost, and data is not yet saved to serverside, if user waits for network connection to come back then data is saved to serverside. There is already info when network connection is lost or it has come back, but there is not yet info has all data been saved to serverside. It would probably be possible to improve this so Wekan would work well offline and sync to server when online.

**Comment by xet7** [comment]
I have used one app that had spinners when something was happening, but it did not have Optimistic UI.

## How non-Optimistic UI works
1. Click some button.
2. Spinner comes up. I'm waiting until that process has really finished, so spinner ends.
3. I click some other button.
4. Spinner comes up. I'm waiting until that process has really finished, so spinner ends.

So this causes me to feel that app is slow. In practice, large amount of operations does take time.

## What users actually expect
1. Click something.
2. Change happens immediately at webbrowser.
3. Process keeps running at serverside at background until it is finished.

Currently some Wekan actions run at browserside, some at serverside, and some at both.

## Why changes are not immediate
1. Big boards and big checklists can a lot of data. It takes a lot of time to duplicate all that.

## What if there were [deduplication](https://en.wikipedia.org/wiki/Data_deduplication) to save disk space?
1. When some board were copied, that copy of board would have new id of new board added to board table, no actual data were copied. It would happen instantly.
2. If something were changed on board, that change would be compared to other existing data with a hash, so each data were saved only once. But for big files, generating hash would take more CPU time.
3. ChangeLog of all board changes could make possible unlimited undo/redo of some or all changes.
4. From ChangeLog would be possible to generate some stats about progress, etc.
5. But saving all changes that happens at Wekan would use more disk space. Currently database only has latest changes, with no undo/redo. Some limited amount of history is saved, but not all possible changes.
6. Deduplication would maybe increase database structure complexity, and increate CPU time required to hash all data.

**Comment by nata-g** [comment]
Can the reactivity be controlled by Redis oplog package?
 https://github.com/cult-of-coders/redis-oplog. It looks like some of the reactivity can be controlled and is much more easier way for scaling users

**Comment by xet7** [comment]
@nata-g 

Redis oplog is one of the many ways to scale Wekan, but I have not tested it yet.

Other ways are:

1. [Setup MongoDB oplog](https://github.com/wekan/wekan/issues/2711#issuecomment-601163047), if you are not using Redis oplog. Currently Wekan Snap does not have oplog set.
2. Running [MongoDB on bare metal NVME drive improves performance a lot](https://github.com/wekan/wekan/wiki/Scaling)
3. Read though [Meteor scaling docs](https://galaxy-guide.meteor.com/scaling.html) and use them to improve performance. Also [Meteor docs](https://docs.meteor.com) has info about Meteor features.
4. Fix Linked cards make load all cards of database #2688 . There should not be too much sending data browserside, because browser can not handle that, browser will slow down or crash.
5. [Debug](https://github.com/wekan/wekan/wiki/Debugging) where Wekan is spending most time, for example with MongoDB logging etc. That Debug page does mention Apollo and GraphQL but there is currently no plans to add that big amount of code and additional complexity. Current REST API is much easier to code and manage than GraphQL that could easily expose too much data and make possible too large queries to fetch all Wekan database data so everything slows down.
6. Optimize database queries, so that only visible data is loaded to webbrowser.
7. When reading and writing a lot of data, do it with streaming of small amount of data at a time, so server or browser RAM is not the limit. For example, I will fix this on [CSV/TSV export](https://github.com/wekan/wekan/issues/3173) where it's currently possible to export small board but not a big board.
8. Check where code really needs to run, browser or serverside, and how often. Wekan has some cron package included already for removing old notifications and syncing ldap users.
9. Adding some MongoDB indexes, depeding are some missing. Some time ago Wekan got speedup when some missing indexes were added.

So it depends where is the bug or bottleneck.

Both Wekan and RocketChat use Meteor full stack web framework. Currently RocketChat is more optimized and handles much larger amount of users, with low CPU usage.

It's not like limit would be Node.js or MongoDB or Meteor (or any other programming language/database/web framework), those are very fast. Usually scalability is about some bug or bottleneck, loading too much data at once to browser or RAM.

Although I'm in progress of fixing some of those mentioned, it would be nice speedup if also others at Wekan Community could help and submit pull requests for fixes.

**Comment by kilbane45** [comment]
Hi Xet7 !

Thanks a lot for this extended answer ! I really appreciate :)

I've already said to my users to not refresh but i expect a lot of them still do it... Especially when they said that they loose data. I've understood that client view is not always what server has on db. You nailed it when you say that it lacks so UI feedback telling that there is a delta between local and server data. Like the one saying that we loose server connection.

i've seen that csv/tsv export failed, but json works after some time waiting (and not UI feedback telling that export is running).

On same server i use rocketchat and i have absolutely no issue with him, But we expected different feedback of ui from a chat than wekan imho and i have less users on it (less than 20).

btw i don't know where i can myself do improvements, like externalise mongodb ? edit meteor configuration ? i'm not very familiar with this but i can search if it can help with global wekan performance. Also are those edit lost when snap is will update ?

**Comment by xet7** [comment]
@kilbane45 

Snap is for production use with automatic updates, changes are overwritten.

[Here is development info](https://github.com/wekan/wekan/issues/3071#issuecomment-622300835)

Wekan Snap releases happens like this:
1. I check new pull requests, and merge them to Wekan, fix them if needed, commit to https://github.com/wekan/wekan that has all Wekan platforms in same master branch. I do not maintain any other fork of Wekan, because that would take huge amount of time with all the merging back and forth. I have also written [blogpost about benefits of contributing to upstream Wekan](https://blog.wekan.team/2018/02/benefits-of-contributing-your-features-to-upstream-wekan/).
2. At Canonical's Snap website I click `Build`, so Canonical's build servers download Wekan code from https://github.com/wekan/wekan
3. Build server checks `snapcraft.yaml`, `snap-src/*` and `snap/*` for build instructions how to build snap.
4. Build server does many checks to files, including security checks, and notifies me by email if there are outdated vulnerable dependencies.
5. If all checks are OK, build server uploads .snap package to Snap Store at https://snapcraft.io
6. Most of about 8k servers worldwide where Wekan Snap is installed download and run Wekan Snap package and run the latest version of Wekan. This is great way to keep up-to-date when there has been important security fix to Node.js or some other Wekan dependency or Wekan code. Currently all known security issues have been already fixed.
7. At those servers where Wekan Snap is installed, Wekan is at secure Snap sandbox where code is read only at `/snap/wekan` and all changeable files are at `/var/snap/wekan/common/` like MongoDB database raw data and Caddyfile https://caddyserver.com web server config. Wekan code can not read or write outside of `/var/snap/wekan/common/` so that's why if Caddy hosts also other websites, website files need to be below `/var/snap/wekan/common/` directory. For example, I do host Wekan releases at `/var/snap/wekan/common/releases.wekan.team` that is visible at https://releases.wekan.team using [CloudFlare SSL Caddy config](https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config) and [bare metal servers donated to Wekan by CNCF that is big part of Linux Foundation](https://blog.wekan.team/2019/06/wekan-on-raspi3-and-arm64-server-now-works-and-whats-next-with-cncf/).

**Comment by xet7** [comment]
@kilbane45

Wekan Snap includes:
- wekan.caddy: Caddy server
- wekan.wekan: Node.js and Javascript code
- wekan.mongodb: MongoDB database at localhost:27019

When developing Wekan using `meteor` command it uses MongoDB that is included in Meteor. By default it starts and port 2000, and there is command line option to run it at some other port. Development mode detects Wekan code changes and rebuilds combined code to `wekan/.build/bundle`.

When running for production with only bash script, bundle, Node.js and MongoDB, then MongoDB URL is here at https://github.com/wekan/wekan/blob/master/start-wekan.sh#L10
```
export MONGO_URL='mongodb://127.0.0.1:27017/wekan'
```
This does mean that:
- MongoDB is running at localhost port 27017, it is not exposed outside of server
- Name of servers database here is `wekan`. If you change that name for example to `wekantest`, then when Wekan starts, it will automatically create that new databas `wekantest` to same server, similar like same MySQL server can have many databases created with commands `CREATE DATABASE wekan; CREATE DATABASE wekantest;`

Snap MongoDB does run by default on port 27019, it started at [`wekan/snap-src/bin/mongodb-control`](https://github.com/wekan/wekan/blob/master/snap-src/bin/mongodb-control).

Snap has many settings, that can be seen at server bash shell with:
```
wekan.help | less
```
Source of those settings is at these files:
- https://github.com/wekan/wekan/blob/master/snap-src/bin/wekan-help
- https://github.com/wekan/wekan/blob/master/snap-src/bin/config

For Docker, they are at:
- https://github.com/wekan/wekan/blob/master/Dockerfile (included inside Docker container)
- https://github.com/wekan/wekan/blob/master/docker-compose.yml (user modifiable, starts containers with those settings)

https://github.com/wekan/wekan/blob/master/snap-src/bin/mongodb-control

**Comment by xet7** [comment]
When not using `meteor` command in development, that MongoDB can be installed on same server or some remote server, specifying where it is in MongoDB URL. MongoDB URL can also include authentication username and password. Currently MongoDB at Snap at localhost does not have any authentication username or password, those that have ssh access to server can [Backup](https://github.com/wekan/wekan) database with mongodump (similar to mysqldump) and also optionally [export all MongoDB data to JSON files where files are base64 encoded](https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file).

With nosqlbooster that is MongoDB editing GUI it's possible to tunnel though SSH to Wekan Snap server localhost port 27019 to visually view and edit text data and download all attachments as files.

**Comment by Keelan** [comment]
To prevent refresh, maybe throw an alert warning of data loss? `onbeforeunload`

**Comment by TheMasterFX** [comment]
Same here. Our server has about 180 users (6 Core, 16 GB RAM). Works fine most times, but after 1-2 Weeks node.js has > 100% load and wekan is not usable anymore. After restarting wekan everthing is fine for 1-2 weeks.
For me it would be sufficient as workaround a monitoring skript which restarts wekan when node.js has a high CPU load for, lets say, 5 minutes or so. Any ideas how to implement this?

**Comment by xet7** [comment]
@TheMasterFX 

You could have nightly cron script as root that does `snap stop wekan && snap start wekan`

**Comment by TheMasterFX** [comment]
> @TheMasterFX
> 
> You could have nightly cron script as root that does `snap stop wekan && snap start wekan`
Yes thats possible. But the problem is unpredicable. I seems like it only happens when it is used over the day

**Comment by xet7** [comment]
If you at daytime automatically detect high CPU load, like when Wekan is duplicating big board, then doing a restart in middle of that operation sure causes lost data.

**Comment by xet7** [comment]
Anyway, I'm currently figuring out how to fix this.

**Comment by TheMasterFX** [comment]
Do Wekan boards create a high traffic/connections when they are opended continuously?
I ask some users of our wekan board, and there are a couple (maybe dozens) of boards which are opened in the browser all the time (they are basically used on a wall mounted display to track the project progress for bigger scrum teams).
If so, how prevent?

**Comment by xet7** [comment]
@TheMasterFX 

Wekan has realtime web interface. When something happens on some board, other users do get same change visible immediately. That does take some CPU time. Both server and client PCs should have enough RAM, and fast SSD or NVME disk.

There is no settings for Wekan users to "prevent" this. Improving performance requires many changes to code.

It is possible for anyone to participate to fund work of improving performance, at https://wekan.team/commercial-support/

**Comment by xet7** [comment]
If someone likes to speed up their Wekan, they can save attachments from database with nosqlbooster GUI (connect via SSH to server localhost port 27019) , copy files to some other Intranet server, and use them in input fields markdown like this:

```
<img src="http://192.168.0.200/cat.jpg" width="100"> 

[important.pdf](http://192.168.0.200/important.pdf)
```
Then at Wekan board click right hamburger menu / cog in right side of menu, Board Settings / Card Settings / Hide Attachments.

**Comment by xet7** [comment]
Related to speed, I noticed at https://github.com/wekan/wekan-snap/issues/139#issuecomment-741488565 that feature `Admin Panel / Global Webhooks` makes creating new board very slow. That Global Webhooks feature sends all boards actions to some URL. I will think would it be possible to make that feature faster. When Global Webhook is removed, creating new board works fast.

**Comment by TheMasterFX** [comment]
So I'm getting to that point that wekan is basically unusable 2-5 times a day (nodejs > 100% sometimes over 200% cpu load). We have about 200 Users (maybe 20-50 online at the same time). 4 Core, 16 GB RAM (5 GB free).
I just updated to version v4.87 (from 4.5x or so). Nothin really changed.
I put a global announcement not to click the reload button of the browser and let the pages load. Nothing really changed. What can I do? How to help?
Using Wekan via Snap.

**Comment by xet7** [comment]
@TheMasterFX 

Wekan is a lot faster if:
- There is no Global Webhooks and Webhooks
- There is no IFTTT Rules
- Wekan is running on NVME disk
- Wekan is using server that has faster CPU core

Other than that, for adding scalability, I'm thinking is it more important to be:
a) more scalable on single server self-hosted
b) more scalable on global scale

Because there are ways for sometime in future to have a) or b) but they are completely different tech, I'm looking what tech would enable both.

**Comment by TheMasterFX** [comment]
Hi xet,
it not that it is just slow. It is unreachable (timeout) 2-5 times a day. I have to restart wekan.service all the time.
There are not webhooks and ifft rules used in this installation.

**Comment by xet7** [comment]
@TheMasterFX 

Please upgrade to newest Wekan is v4.91 . Older versions have bugs.

Do you have any possibility to change to server that has more powerful CPU ?

**Comment by Brulf** [comment]
hi @xet7 you mention to upgrade to v4.91 as older versions have bugs, does this resolve any issues related to #3252 as this seems to be directly related to abnormal CPU usage we have experienced and possibly what @TheMasterFX is experiencing, once that exception has been thrown performance degrades considerably until the service is restarted.

**Comment by TheMasterFX** [comment]
> Do you have any possibility to change to server that has more powerful CPU ?
Before I used a 4 Core/16 GB in our vmware infrastructure, I used an 6C/12Thread Xeon with 32 GB RAM. But it was almost the same behavior.
One thing which just came in my mind is (since now we have 2-5 times a day a > 200% load on nodejs), we have now more people doing homeoffce and using Wekan over a VPN Tunnel. So the latency is much higher than being directly connected to our company network. Maybe this fact favors this behavior that Wekan (or nodejs) crashes so often?!

**Comment by xet7** [comment]
@TheMasterFX 

I don't know does latency matter. It could also be some bug. I'll think.

**Comment by TheMasterFX** [comment]
Then it is a bug which is present since 4.1x or so.

**Comment by xet7** [comment]
@TheMasterFX 

Is it possible for you to try in what version there is no bug, and next version does have bug? Then I could look at code changes, what is the difference. It would help a lot to know specific version numbers.

**Comment by TheMasterFX** [comment]
@xet7
> Is it possible for you to try in what version there is no bug, and next version does have bug?
For me there was no version yet without that nodejs > 100% CPU load problem (starting from 3.9 to now).

**Comment by xet7** [comment]
Moved to #3345
