### ISSUE TITLE
Login with CAS required custom changes, integrate directly to Wekan?

### ISSUE THREAD

**Issue by faelys** [wekan/wekan#3204]
Hello,

I'm trying to setup Wekan by adapting the `docker-compose.yml` to work with CAS authentication, and when authenticating with a user not yet seen by Wekan, the CAS validation fails with the following error and beginning of stack trace:

```
wekan-app  | Exception while invoking method 'login' TypeError: Cannot read property 'oidc' of undefined
wekan-app  |     at AccountsServer._onCreateUserHook (models/users.js:916:23)
wekan-app  |     at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1079:23)
wekan-app  |     at MethodInvocation.<anonymous> (packages/wekan-accounts-cas.js:261:29)
wekan-app  |     at packages/accounts-base/accounts_server.js:462:31
wekan-app  |     at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)
```

From the analysis below, I assume further levels are unnecessary, but I can provide them if needed.

I'm not sue this is the relevant version identification, but I have the docker image id `808c60d0a7a3` for `wekanteam/wekan`.

My `docker-compose.yml` is mostly vanilla:

```
--- upstream-docker-compose.yml Mon Jul  6 18:47:10 2020
+++ my-docker-compose.yml       Mon Jul  6 18:47:53 2020
@@ -146,7 +146,7 @@
       # For example, if you want to have wekan on port 3001,
       # use 3001:8080 . Do not add any extra address etc here, that way it does not work.
       # remove port mapping if you use nginx reverse proxy, port 8080 is already exposed to wekan-tier network
-      - 80:8080
+      - 127.0.0.1:8081:8080
     environment:
       - MONGO_URL=mongodb://wekandb:27017/wekan
       #---------------------------------------------------------------
@@ -161,7 +161,7 @@
       #  - http://example.com
       #  - http://boards.example.com
       #  - http://192.168.1.100    <=== using at local LAN
-      - ROOT_URL=http://localhost  #   <=== using only at same laptop/desktop where Wekan is installed
+      - ROOT_URL=http://wekan.my-corp.tld
       #---------------------------------------------------------------
       # ==== EMAIL SETTINGS ====
       # Email settings are required in both MAIL_URL and Admin Panel,
@@ -170,8 +170,8 @@
       # NOTE: Special characters need to be url-encoded in MAIL_URL.
       #       You can encode those characters for example at: https://www.urlencoder.org
       #- MAIL_URL=smtp://user:pass@mailserver.example.com:25/
-      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
-      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
+      - MAIL_URL=smtp://smtp.my-corp.tld:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
+      - MAIL_FROM=Wekan Notifications <noreply.wekan@my-corp.tld>
+      # ==== CAS AUTHENTICATION FOR MY-CORP ====
+      - CAS_ENABLED=true
+      - METEOR_SETTINGS={"cas":{"validateUrl":"https://cas.my-corp.tld/cas/default/user/cas/p3/serviceValidate","attributes":{"firstname":"cas:first_name","lastname":"cas:last_name","mail":"cas:email","debug":true}},"public":{"cas":{"loginUrl":"https://cas.my-corp.tld/cas/default/user/cas/login"}}}
+      # TODO: add My-corp internal CA to the trusted database
+      - NODE_TLS_REJECT_UNAUTHORIZED=0
+      #---------------------------------------------------------------
       #---------------------------------------------------------------
       # ==== OPTIONAL: MONGO OPLOG SETTINGS =====
       # https://github.com/wekan/wekan-mongodb/issues/2#issuecomment-378343587
```

When trying to authenticate using CAS, everything works fine until the response to `serviceValidate` is processed. In [cas_server.js#L237](https://github.com/wekan/wekan/blob/39be9aa58da1ddda16b41e92b12f118169049fed/packages/wekan-accounts-cas/cas_server.js#L237), but when the user is unknown to Wekan (e.g. because it is their first login), the user is created by calling `Accounts.insertUserDoc({}, options)` which can be seen in the above stack trace, with `options` being filled from the CAS response.

From there, things go outside of Wekan to `accounts-base` package, where basically `options` is mapped to `user` parameter name and `{}` to `options` parameter name (a bit tricky), and `user.services` is not assumed to exist at this point, since its existence is tested before iterating on it.

From there, `accounts-base` calls the createUserHook, which can be found in [users.js#L916](https://github.com/wekan/wekan/blob/master/models/users.js#L916) which starts with `if (user.services.oidc) {`, which fails because `user.services` is undefined.

Tracing the issue back to `cas_server.js`, the variable `options` there is created from a hardcoded schema, without any `services`.

So as it stands, unless I'm missing something, there is no way from `Accounts.insertUserDoc` in `cas_server.js` to a successful user insertion.

Am I doing something wrong? Should I configure something differently upstream to avoid this codepath?

**Comment by faelys** [comment]
Note that we successfully worked around this issue by overriding `cas_server.js` to include an empty `services` inside the variable `options` mentioned above.

I don't know whether this fix is correct or even makes sense though.

**Comment by Meeques** [comment]
@xet7 

Can you tell me how much funding would be needed for the CAS authentication to work with ubuntu snap?

**Comment by xet7** [comment]
@Meeques 

1000 euro.

**Comment by jgribonvald** [comment]
@xet7 @Meeques if we are several to fund this feature, is it possible ?

**Comment by xet7** [comment]
@Meeques 

I received funding. Thanks! Please email support@wekan.team , so we can discuss this at support chat. Or alternatively, if you are already at support chat, write there to me about this.

@jgribonvald 

CAS server access would help. Please email support@wekan.team , so we can discuss this at support chat. Also link to CAS docker would help.

Additional funding is also welcome, if possible.

Moved to here from https://github.com/wekan/wekan/issues/4515#issuecomment-1129922555

Some related links:

- [Building WeKan from source and submitting PR](https://github.com/wekan/wekan/wiki/Emoji)
- https://github.com/wekan/wekan/tree/master/packages/wekan-accounts-cas
- https://github.com/wekan/wekan/wiki/CAS
- [CAS related added PRs](https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+CAS)
- RocketChat repo may have some newer CAS code https://github.com/RocketChat/Rocket.Chat

**Comment by xet7** [comment]
Hmm. When looking at this, here is some try to use CAS https://github.com/wekan/wekan/issues/4515#issue-1239717302

WeKan CAS was added at:
- https://github.com/wekan/wekan/pull/1742
- https://github.com/wekan/wekan/issues/4515

RocketChat CAS seems to be Typescript code:
- https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/cas-validate

According to https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/cas-validate/package.json CAS code is originally forked from https://github.com/kcbanner/node-cas

Does somebody use CAS with RocketChat or some other Open Source app?

**Comment by jgribonvald** [comment]
> Does somebody use CAS with RocketChat or some other Open Source app?
Yes and with RocketChat

**Comment by jgribonvald** [comment]
If it can help, I've found this repository: https://plmlab.math.cnrs.fr/plmshift/plmkan/-/tree/642a7a87ed3330feac87b3a28ce8b8b014dc7303/packages/wekan-accounts-cas

**Comment by xet7** [comment]
@jgribonvald

> Also @xet7 if you want we can provide you a CAS server access, else you can found a CAS docker.

Where is CAS server docker?

**Comment by jgribonvald** [comment]
> @jgribonvald
> 
> > Also @xet7 if you want we can provide you a CAS server access, else you can found a CAS docker.
> 
> Where is CAS server docker?

You can follow this doc https://apereo.github.io/cas/6.5.x/installation/Docker-Installation.html

**Comment by jgribonvald** [comment]
@xet7 do you have a timeline, or a date of availability of this development ?
Thanks a lot

**Comment by xet7** [comment]
@jgribonvald 

For this feature, I guess Q1 2023.

For some other features, I did say I try to get them ready this year, it's quite tight schedule. Ready or not, next year will come soon.

**Comment by Meeques** [comment]
Hi Lauri, are there any updates regarding this issue? Kind regards!

**Comment by xet7** [comment]
@Meeques

I try to add this soon, at early Q3 2023.

**Comment by Meeques** [comment]
Hi @xet7 is there an update on this?

**Comment by xet7** [comment]
@Meeques 

WeKan development is in full speed, I'm adding all paid features ASAP. There are new releases very often. But there is no exact estimate are some of these features ready this year or at beginning of next year.

**Comment by jgribonvald** [comment]
Hi @xet7 is there some progress here ?
it's the last time i guess we can't wait more, we will go on an other product... :cry:

**Comment by xet7** [comment]
And, for any paid feature, please contact Commercial Support, and help with testing feature:
https://wekan.team/commercial-support/

**Comment by jgribonvald** [comment]
@xet7 
I'm really sorry if you misunderstood my words, this wasn't my willing.

After if you watch the timeline of this issue this request was funded in october 2022, so why this isn't available after one and a half year ?  I purposed some help here like at support@wekan.team but nobody never responded to me, if you need help in testing / installing CAS respond to e-mail or tag me here.

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan/discussions/5387

From @nedelcu8

"line":"406","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC https://mydomain.com/cas/oidc/accessToken: failed [400] {\"error\":\"invalid_grant\"}","time":{"$date":1714046138161},"level":"warn"}

**Comment by xet7** [comment]
Related:

Does OAuth support multiple CAS providers?

https://github.com/wekan/wekan/discussions/5383

(Short answer: Not yet, but maybe in future, if we figure it out)

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan/discussions/5387#discussioncomment-9418312

From @nedelcu8

Hello , regarding this issue , i was not referring to CAS directly , I am trying to use oauth to implement a CAS login and we got that error.
Does that mean the feature is not implemented ?

From @xet7 

OAuth2 is not CAS.

For Docker, CAS settings are here https://github.com/wekan/wekan/blob/main/docker-compose.yml#L695-L698

For Snap, they are like this:
```
sudo snap set wekan cas-enabled='true'
sudo snap set wekan cas-base-url='https://cas.example.com/cas'
sudo snap set wekan cas-login-url='https://cas.example.com/login'
sudo snap set wekan cas-validate-url='https://cas.example.com/cas/p3/serviceValidate'
```

CAS code is here:

https://github.com/wekan/wekan/tree/main/packages/wekan-accounts-cas

**Comment by nedelcu8** [comment]
Yes Oauth is not CAS  but it can be implemented in such a way to get CAS login 
https://apereo.github.io/2019/02/19/cas61-as-oauth-authz-server/
and when I tried to do so I got the error : from https://github.com/wekan/wekan/discussions/5387
