### ISSUE TITLE
Unauthorized OAuth2.0 external authentication server

### ISSUE THREAD

**Issue by dieguincf** [wekan/wekan#3224]
Hello, I am trying to configure authentication through OAuth2.0 with an external server and when trying to authenticate it gives me the following error:

2020-07-27T14:43:49Z wekan.wekan[12979]: {"line":"403","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC https://www.-----.--/---/api/oauth/token: failed [401] {\"timestamp\":\"2020-07-27T14:43:48.113+0000\",\"status\":401,\"error\":\"Unauthorized\",\"message\":\"Unauthorized\",\"path\":\"/---/api/oauth/token\"}","time":{"$date":1595861028211},"level":"warn"}
2020-07-27T14:43:49Z wekan.wekan[12979]: Exception while invoking method 'login' Error: Failed to get token from OIDC https://www.-----.--/---/api/oauth/token: failed [401] {"timestamp":"2020-07-27T14:43:48.113+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/---/api/oauth/token"}
2020-07-27T14:43:49Z wekan.wekan[12979]:     at getToken (packages/wekan-oidc.js:104:20)
2020-07-27T14:43:49Z wekan.wekan[12979]:     at Object.handleOauthRequest (packages/wekan-oidc.js:29:15)
2020-07-27T14:43:49Z wekan.wekan[12979]:     at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)
2020-07-27T14:43:49Z wekan.wekan[12979]:     at middleware (packages/oauth/oauth_server.js:170:5)
2020-07-27T14:43:49Z wekan.wekan[12979]:     at /snap/wekan/944/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

Is it a wekan or server error?

What I can do?

**Comment by xet7** [comment]
Examples:
- https://github.com/wekan/wekan/wiki/Azure
- https://github.com/wekan/wekan/wiki/OAuth2

**Comment by dieguincf** [comment]
> Examples:
> 
> * https://github.com/wekan/wekan/wiki/Azure
> * https://github.com/wekan/wekan/wiki/OAuth2

Hi, thanks for the answer but it doesn't answer my question.

I have followed the configuration steps detailed in the links you have shared and I have been able to configure it with Rocket.chat and Auth0. The problem is when I try to configure with another external server. I don't know if that is because of something I have not configured correctly or because the external server does not authorize me and does not send me the token.

There it says "Unauthorized", why?

**Comment by xet7** [comment]
@dieguincf 

If you like to configure Auth0 directly with Wekan, info is here:
https://github.com/wekan/wekan/wiki/OAuth2#auth0

But if you configure Auth0 with RocketChat:
https://github.com/wekan/wekan/wiki/OAuth2#3-add-rocketchat-settings
and then RocketChat to Wekan:
https://github.com/wekan/wekan/wiki/OAuth2#4-add-wekan-settings
then you need to first login to RocketChat, to be able to login to Wekan.
