### ISSUE TITLE
Docker fail

### ISSUE THREAD

**Issue by schurb** [wekan/wekan#329]
Trying to use Wekan with Kitematic on a Mac and get this error: 

```
Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at Package (packages/idmontie_migrations/packages/idmontie_migrations.js:32:1)
    at Package (packages/idmontie_migrations/packages/idmontie_migrations.js:148:1)
    at /built_app/programs/server/packages/idmontie_migrations.js:165:4
    at /built_app/programs/server/packages/idmontie_migrations.js:172:3
    at /built_app/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/built_app/programs/server/node_modules/underscore/underscore.js:79:11)
```

**Comment by mquandalle** [comment]
The docker container only contains the Wekan application but not its associated Mongo database. You need to provide a URL to a Mongo database using the `MONGO_URL` environment variable, as the error tells you. As you already use docker, one easy way to run this database is to use the official mongodb docker image:

```
docker run -d --name wekan-db mongo
docker run -d --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e ROOT_URL=http://example.com" -p 8080:80 mquandalle/wekan
```

You can also use `docker-compose` to run these two containers at once.

**Comment by schurb** [comment]
I will try to figure it out tomorrow. I have no clue what I am doing ;) but thanks for the hint.
