### ISSUE TITLE
Can't delete board - Exception while invoking method '/boards/remove' TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#3290]
I can't delete a board, that is archived. When I try to delete the board, then it reappears after reloading.

Secondary problem: All the users from the archived and then deleted boards are notified via email about single cards being deleted. 

Reproduce: 
- Click on "All boards" and delete one of the boards. Error message appears in logs after certain time. Reloading makes the deleted board re-appear. Former members of board get's a lot of messages about single cards being deleted. 

```
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]: Exception while invoking method '/boards/remove' TypeError: Cannot read property 'title' of undefined
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.<anonymous> (models/activities.js:225:36)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at packages/matb33_collection-hooks.js:422:18
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Array.forEach (<anonymous>)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at after (packages/matb33_collection-hooks.js:421:9)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:436:12)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.collection.<computed> [as insert] (packages/matb33_collection-hooks.js:150:21)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at ns.Collection.insert (packages/mongo/collection.js:523:39)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.<anonymous> (models/checklistItems.js:238:16)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at packages/matb33_collection-hooks.js:598:28
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Array.forEach (<anonymous>)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at packages/matb33_collection-hooks.js:597:11
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Array.forEach (<anonymous>)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:596:9)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.collection.<computed> [as remove] (packages/matb33_collection-hooks.js:150:21)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at ns.Collection.remove (packages/mongo/collection.js:623:31)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at cardRemover (models/cards.js:1957:18)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.<anonymous> (models/cards.js:2160:5)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at packages/matb33_collection-hooks.js:598:28
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Array.forEach (<anonymous>)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at packages/matb33_collection-hooks.js:597:11
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Array.forEach (<anonymous>)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:596:9)

```

**Server Setup Information**:
Wekan Version 4.40.0
Meteor: 1.11.1
Node: 12.18.4
MongoDB: 3.2.22, wiredTiger
Debian 10, Installation with Snap

**Comment by saschafoerster** [comment]
It is really weird, this error happens with a lot of other deletes: a single card, a list or even the whole board. 
I am really wondering what is wrong: when I export all my boards as JSON, then I get about 500MB of JSON-files. But the MongoDB is about 4GB and doesn't change a bit, if I delete a lot of cards. In some boards, they come back like little zombies (after deleting, reloading, they reappear).

**Comment by xet7** [comment]
@saschafoerster 

I would think MongoDB reserves that 4 GB of space, and if something is deleted, same space is reused for new data.

For having less space used, I think you mean something like `COMPACT` or `VACUUM` in other databases.

About that error, I think at 2nd line this says where that error happens at code:
```
Sep 30 17:22:41 vm2bonndigital wekan.wekan[28289]:     at Object.<anonymous> (models/activities.js:225:36)
```

**Comment by BOKE2014** [comment]
I did have the same issue, and I found that I couldn't get it back after I deleted  a list of a board.
