### ISSUE TITLE
Disappearing comments (and other cards subelements)

### ISSUE THREAD

**Issue by jakub2503** [wekan/wekan#3349]
**Server Setup Information**:

* Wekan version: Latest - 4.52
* Operating System: Ubuntu 18.04
* Deployment Method: snap
* Http frontend: Nginx
* Node Version: 12.19.1
* MongoDB Version: 3.2.22
* What webbrowser version are you using? Chrome / Firefox

**Problem description**:
- Comments, checklists, subtasks previously added to the cards are not visible, when opening specific card (which contains already added elements). Newly added elements are visible.
- I am using wekan since yesterday. I have created one board. Yesterday I have added two comments in one of cards. These comments are not visible anymore. I can see the comments count in the card lookup, next to the comments icon. Same happens to other listed elements.
- No errors or warnings in console (Chrome)

Snap log (this error is listed multiple times):
`2020-11-13T10:53:05Z wekan.wekan[2189]: Exception in removedobserveChanges callback: Error: Removed nonexistent document pfa5Rd99nLqhTYGfb
2020-11-13T10:53:05Z wekan.wekan[2189]:     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at runWithEnvironment (packages/meteor.js:1286:24)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at packages/meteor.js:1299:14
2020-11-13T10:53:05Z wekan.wekan[2189]:     at packages/mongo/observe_multiplex.js:178:30
2020-11-13T10:53:05Z wekan.wekan[2189]:     at Array.forEach (<anonymous>)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at Object.task (packages/mongo/observe_multiplex.js:172:9)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
2020-11-13T10:53:05Z wekan.wekan[2189]:     at packages/meteor.js:894:12
`
Best regards,
Jakub M

**Comment by xet7** [comment]
> Wekan version: Latest - 4.52
Operating System: Ubuntu 18.04
Deployment Method: snap
Http frontend: Nginx
Node Version: 14.14.0
MongoDB Version: 4.4.1

I don't understand those versions? Snap should have Node.js 12.19.0 and MongoDB 3.2.x.

Wekan does not yet work with Node.js 14.14.0

Currently Wekan is used with Node.js 12.19.0

I don't know is this in any way related to #2934

**Comment by jakub2503** [comment]
Pardon me, Node version is 12.19.1 and MongoDB 3.2.22. The problem still persists, and I don't see any corelation between [#2934 ](https://github.com/wekan/wekan/issues/2934) as there are less than 3 comments.
