### ISSUE TITLE
SyncedCron duplicate key error

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3378]
Hi,
I noticed that today when running Wekan in Meteor development mode `meteor --port 4000`, there is this error from SyncedCron.

TODO later: try to find out why this happens. 

```
I20201130-22:23:24.254(2) (percolate_synced-cron.js:87) SyncedCron: Scheduled "notification_cleanup" next run @Mon Nov 30 2020 22:23:23 GMT+0200 (Eastern European Standard Time)
W20201130-22:27:18.904(2)? (STDERR) (node:20986) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
I20201201-00:00:00.020(2) (percolate_synced-cron.js:87) SyncedCron: Starting "notification_cleanup".
I20201201-00:00:00.030(2) (percolate_synced-cron.js:87) SyncedCron: Finished "notification_cleanup".
I20201201-23:59:59.002(2) (percolate_synced-cron.js:87) SyncedCron: Starting "notification_cleanup".
I20201201-23:59:59.017(2) (percolate_synced-cron.js:87) SyncedCron: Finished "notification_cleanup".
I20201202-00:00:00.039(2)? Exception in setTimeout callback: BulkWriteError: E11000 duplicate key error collection: meteor.cronHistory index: intendedAt_1_name_1 dup key: { intendedAt: new Date(1606860000000), name: "notification_cleanup" }
I20201202-00:00:00.040(2)?     at OrderedBulkOperation.handleWriteError (/home/user/.meteor/packages/npm-mongo/.3.8.1.16mfer0.acwz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:1257:9)
I20201202-00:00:00.041(2)?     at resultHandler (/home/user/.meteor/packages/npm-mongo/.3.8.1.16mfer0.acwz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:521:23)
I20201202-00:00:00.041(2)?     at /home/user/.meteor/packages/npm-mongo/.3.8.1.16mfer0.acwz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/pool.js:405:18
I20201202-00:00:00.042(2)?     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
I20201202-00:00:00.042(2)?   driver: true,
I20201202-00:00:00.043(2)?   code: 11000,
I20201202-00:00:00.043(2)?   writeErrors: [ WriteError { err: [Object] } ],
I20201202-00:00:00.044(2)?   result: BulkWriteResult {
I20201202-00:00:00.044(2)?     result: {
I20201202-00:00:00.044(2)?       ok: 1,
I20201202-00:00:00.045(2)?       writeErrors: [Array],
I20201202-00:00:00.045(2)?       writeConcernErrors: [],
I20201202-00:00:00.046(2)?       insertedIds: [Array],
I20201202-00:00:00.047(2)?       nInserted: 0,
I20201202-00:00:00.047(2)?       nUpserted: 0,
I20201202-00:00:00.048(2)?       nMatched: 0,
I20201202-00:00:00.048(2)?       nModified: 0,
I20201202-00:00:00.049(2)?       nRemoved: 0,
I20201202-00:00:00.050(2)?       upserted: [],
I20201202-00:00:00.050(2)?       lastOp: [Object]
I20201202-00:00:00.050(2)?     }
I20201202-00:00:00.051(2)?   }
I20201202-00:00:00.051(2)? }
```

**Comment by argargarg** [comment]
Hi Lauri, I have Wekan installed via snap on Ubuntu Server 18.04.5 LTS.
The problem I am investigating is that since yesterday LDAP auth against my FreeIPA server has stopped working.

I can see in the `snap.wekan.wekan` journalctl output that the LDAP connection from Wekan is timing out after 10000 (default value). Other software (GitLab, Nextcloud etc.) are still using LDAP auth fine. I am able to query the LDAP directory fine using `ldapsearch` with Wekan's bind user creds from the Wekan server.

I also see the below in the `journalctl` output:
```
Jan 27 13:51:00 wekan.wekan[1281]: Exception in setTimeout callback: BulkWriteError: E11000 duplicate key error collection: wekan.cronHistory index: intendedAt_1_name_1 dup key: { : new Date
Jan 27 13:51:00 wekan.wekan[1281]:     at OrderedBulkOperation.handleWriteError (/snap/wekan/1296/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:12
Jan 27 13:51:00 wekan.wekan[1281]:     at resultHandler (/snap/wekan/1296/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:521:23)
Jan 27 13:51:00 wekan.wekan[1281]:     at /snap/wekan/1296/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:405:18
Jan 27 13:51:00 wekan.wekan[1281]:     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
Jan 27 13:51:00 wekan.wekan[1281]:   driver: true,
Jan 27 13:51:00 wekan.wekan[1281]:   code: 11000,
Jan 27 13:51:00 wekan.wekan[1281]:   writeErrors: [ WriteError { err: [Object] } ],
Jan 27 13:51:00 wekan.wekan[1281]:   result: BulkWriteResult {
Jan 27 13:51:00 wekan.wekan[1281]:     result: {
Jan 27 13:51:00 wekan.wekan[1281]:       ok: 1,
Jan 27 13:51:00 wekan.wekan[1281]:       writeErrors: [Array],
Jan 27 13:51:00 wekan.wekan[1281]:       writeConcernErrors: [],
Jan 27 13:51:00 wekan.wekan[1281]:       insertedIds: [Array],
Jan 27 13:51:00 wekan.wekan[1281]:       nInserted: 0,
Jan 27 13:51:00 wekan.wekan[1281]:       nUpserted: 0,
Jan 27 13:51:00 wekan.wekan[1281]:       nMatched: 0,
Jan 27 13:51:00 wekan.wekan[1281]:       nModified: 0,
Jan 27 13:51:00 wekan.wekan[1281]:       nRemoved: 0,
Jan 27 13:51:00 wekan.wekan[1281]:       upserted: []
Jan 27 13:51:00 wekan.wekan[1281]:     }
Jan 27 13:51:00 wekan.wekan[1281]:   }
Jan 27 13:51:00 wekan.wekan[1281]: }
```

My Wekan server is running the latest snap release. Released yesterday.

**Comment by argargarg** [comment]
Further to my last - I have:
* Reverted the snap using `sudo snap revert wekan`
* Rebooted the server

Result:
* LDAP is working again
* I no longer see the `Exception in setTimeout callback: BulkWriteError: E11000.....` error in the logs.

**Comment by xet7** [comment]
@argargarg 

You can check [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md) for recent LDAP changes by other Wekan LDAP contributors, and tag those users at GitHub with `@username` in comment of this issue to ask anything.

I do not have any LDAP server where I could test anything LDAP related.

**Comment by argargarg** [comment]
Thank you for the ChangeLog link.

I think the latest release may have changed my explicitly set (but also the previous default) `LDAP_REJECT_UNAUTHORIZED=false` setting to `true` - but I haven't checked yet to be sure. If so the correct way to fix my LDAP issue will be install my CA's cert at the correct location on my Wekan server (as opposed to change the setting back to `false`).

I will upgrade snap to latest release again and post the results later. Will also check to see whether I am seeing the **SyncedCron duplicate key error** in the latest snap release (the actual reason for this issue existing). Thanks.
