### ISSUE TITLE
Can no longer upload attachments

### ISSUE THREAD

**Issue by RaZ0r1994** [wekan/wekan#3443]
## Issue
Wekan completely crashes when uploading an attachment to a card.

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues
- LDAP: https://github.com/wekan/wekan-ldap/issues
- UCS: https://github.com/wekan/univention/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 4.81
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Windows server 2019
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Using the windows bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): 
* Node Version: running "node" in cmd shows version v15.6.0
* MongoDB Version: MongoDB 4.2.6
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome  87.0.4280.141

**Problem description**:

The issue started when upgrading from wekan 4.75 to wekan 4.79. Now updated to wekan 4.81 and the issue is still there.

When i try to upload an attachment to a card wekan completely crashes witht he following error message:

Error log:

`SA GridFS - ERROR! undefined
packages\cfs_collection.js:186
        self.emit('error', new Error('Error storing uploaded file to TempStore: ' + error.message), fileObj);          // 153
                                                                                          ^

TypeError: Cannot read property 'message' of undefined
    at EventEmitter.<anonymous> (packages\cfs_collection.js:186:91)
    at EventEmitter.emit (node:events:391:22)
    at EventEmitter.emit (node:domain:470:12)
    at GridWriteStream.<anonymous> (packages/cfs:tempstore/tempStore.js:348:10)
    at GridWriteStream.emit (node:events:391:22)
    at GridWriteStream.EventEmitter.emit (node:domain:470:12)
    at GridWriteStream.FlushWritable.emit (C:\Users\Administrator\Desktop\wekan-4.81\bundle\programs\server\npm\node_modules\meteor\cfs_gridfs\node_modules\gridfs-stream\node_modules\flushwritable\lib\FlushWritable.js:37:31)
    at GridWriteStream._error (C:\Users\Administrator\Desktop\wekan-4.81\bundle\programs\server\npm\node_modules\meteor\cfs_gridfs\node_modules\gridfs-stream\lib\writestream.js:246:7)
    at C:\Users\Administrator\Desktop\wekan-4.81\bundle\programs\server\npm\node_modules\meteor\cfs_gridfs\node_modules\gridfs-stream\lib\writestream.js:265:8
    at processTicksAndRejections (node:internal/process/task_queues:76:11)`

**Comment by xet7** [comment]
Yes, because you are using Node 15.x. You should use Node 12.x, that is currently 12.20.1. Node version is listed at Dockerfile of https://github.com/wekan/wekan
