### ISSUE TITLE
Problem with upgrade.

### ISSUE THREAD

**Issue by User19022** [wekan/wekan#3511]
Hello, 
I'm trying to update to the latest version. 
Before, I used version 3.9.x 

I downloaded: https://releases.wekan.team/wekan-4.91.zip
I am using nvm to select nodejs v12.20.1

Can I have a hint? 

OS: Ubuntu 20.04.2 
mongodb:  v3.2.22
nodejs: v12.20.1
npm: 6.14.11

LOG:

```
42 timing stage:executeActions Completed in 34ms
43 timing stage:rollbackFailedOptional Completed in 0ms
44 silly install runPostinstallTopLevelLifecycles
45 silly build meteor-dev-bundle@
46 info linkStuff meteor-dev-bundle@
47 silly linkStuff meteor-dev-bundle@ has /home/wekan/wekan30012021/bundle/programs as its parent node_modules
48 silly install meteor-dev-bundle@
49 info lifecycle meteor-dev-bundle@~install: meteor-dev-bundle@
50 verbose lifecycle meteor-dev-bundle@~install: unsafe-perm in lifecycle true
51 verbose lifecycle meteor-dev-bundle@~install: PATH: /home/wekan/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/wekan/wekan30012021/bundle/programs/server/node_modules/.bin:/home/wekan/.nvm/versions/node/v12.20.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
52 verbose lifecycle meteor-dev-bundle@~install: CWD: /home/wekan/wekan30012021/bundle/programs/server
53 silly lifecycle meteor-dev-bundle@~install: Args: [ '-c', 'node npm-rebuild.js' ]
54 timing audit submit Completed in 896ms
55 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 896ms
56 timing audit body Completed in 1ms
57 silly lifecycle meteor-dev-bundle@~install: Returned: code: 1  signal: null
58 info lifecycle meteor-dev-bundle@~install: Failed to exec install script
59 verbose stack Error: meteor-dev-bundle@ install: `node npm-rebuild.js`
59 verbose stack Exit status 1
59 verbose stack     at EventEmitter.<anonymous> (/home/wekan/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
59 verbose stack     at EventEmitter.emit (events.js:314:20)
59 verbose stack     at ChildProcess.<anonymous> (/home/wekan/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
59 verbose stack     at ChildProcess.emit (events.js:314:20)
59 verbose stack     at maybeClose (internal/child_process.js:1022:16)
59 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
60 verbose pkgid meteor-dev-bundle@
61 verbose cwd /home/wekan/wekan30012021/bundle/programs/server
62 verbose Linux 5.4.0-65-generic
63 verbose argv "/home/wekan/.nvm/versions/node/v12.20.1/bin/node" "/home/wekan/.nvm/versions/node/v12.20.1/bin/npm" "install"
64 verbose node v12.20.1
65 verbose npm  v6.14.10
66 error code ELIFECYCLE
67 error errno 1
68 error meteor-dev-bundle@ install: `node npm-rebuild.js`
68 error Exit status 1
69 error Failed at the meteor-dev-bundle@ install script.
69 error This is probably not a problem with npm. There is likely additional logging output above.
70 verbose exit [ 1, true ]
```

**Comment by xet7** [comment]
@User19022 

I recommend installing Snap version instead.

- https://github.com/wekan/wekan/wiki/Backup
- https://github.com/wekan/wekan-snap/wiki/Install

**Comment by HLFH** [comment]
I had the same issue on Arch Linux. The upgrade was not working. I installed the bloated snap version, and I disabled snap.mongodb, so I can use my own mongodb instance, and it worked...

**Comment by xet7** [comment]
@User19022 

Did you use `start-wekan.sh` to start Wekan? Or how did you start Wekan?

For me using bundle does work.

I have not used nvm. I use n.
