### ISSUE TITLE
Can't invite or manually add users. “Exception while invoking method 'setCreateUser' Error: Match error: Expected Array”

### ISSUE THREAD

**Issue by djxcee** [wekan/wekan#3539]
## Issue
**Server Setup Information**:
* Did you test in newest Wekan?: **I believe I am currently on the latest.**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings? **Yes**
* Wekan version: **4.93.0**
* Operating System: **Unraid 6.9.0 rc3**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **Wekan & MongoDB Dockers**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Nginx Proxy Manager**
* Node Version: **12.20.1**
* MongoDB Version: **4.4.3**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Chrome & Firefox**

**Problem description**:
- *Explain steps how to reproduce* I **can’t have users added.  Email invites & manual add will result in “Exception while invoking method 'setCreateUser' Error: Match error: Expected Array”  I am the only person & admin on this instance.**

Presence started serverId=*****************
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Sun Feb 07 2021 22:56:45 GMT-0800 (Pacific Standard Time)","time":{"$date":1612767405518},"level":"info"}
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Exception while invoking method 'setCreateUser' Error: Match error: Expected Array
    at check (packages/check/match.js:36:17)
    at MethodInvocation.setCreateUser (models/users.js:816:9)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:655:17)
    at check (packages/check/match.js:36:17)
    at MethodInvocation.setCreateUser (models/users.js:816:9)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Match failed',
  details: undefined,
  errorType: 'Meteor.Error'
}

Exception while invoking method 'setCreateUser' Error: Match error: Expected Array
    at check (packages/check/match.js:36:17)
    at MethodInvocation.setCreateUser (models/users.js:816:9)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:655:17)
    at check (packages/check/match.js:36:17)
    at MethodInvocation.setCreateUser (models/users.js:816:9)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Match failed',
  details: undefined,
  errorType: 'Meteor.Error'
}

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3544
