### ISSUE TITLE
Environment specific: OpenID Connect with Keycloak Incorrect redirect_uri

### ISSUE THREAD

**Issue by hamsterbacke** [wekan/wekan#3542]
## Issue
**Server Setup Information**:
docker using wekanteam/wekan:v4.93
wekan behind a nginx proxy.
reachable as https://wekan.domain.tl/wekan
ldap configured => works
normal user => works
oauth2 configured => does not work

configured keycloak as described in https://github.com/wekan/wekan/wiki/Keycloak

* Did you test in newest Wekan?:
yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
yes
* Wekan version:
4.93
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
nginx
* MongoDB Version:
mongo:4.4.3-bionic
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
Chrome

**Problem description**:
The docker container says when I click on "anmelden mit oidc":
```
{"line":"405","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC https://sso-portal.domain.tld/auth/realms/test/protocol/openid-connect/token: failed [400] {\"error\":\"invalid_grant\",\"error_description\":\"Incorrect redirect_uri\"}","time":{"$date":1612795136883},"level":"warn"}
Exception while invoking method 'login' Error: Failed to get token from OIDC https://sso-portal.domain.tld/auth/realms/test/protocol/openid-connect/token: failed [400] {"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
    at getToken (packages/wekan-oidc.js:144:22)
    at Object.handleOauthRequest (packages/wekan-oidc.js:42:15)
    at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth/oauth_server.js:170:5)
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```
I am logged in in keycloak because I can see a session in keycloak for this specific client.
I also tried setting OAUTH2_LOGIN_STYLE=redirect but this seems to be totally ignored and there is always the popup.
The variables are:
```
             - DEBUG=true
            - OAUTH2_ENABLED=true
            - OAUTH2_LOGIN_STYLE=redirect
            - OAUTH2_CLIENT_ID=wekan_client
            - OAUTH2_SECRET=secret
            - OAUTH2_SERVER_URL=https://sso-portal.domain.tld/auth
            - OAUTH2_AUTH_ENDPOINT=/realms/test/protocol/openid-connect/auth
            - OAUTH2_USERINFO_ENDPOINT=/realms/test/protocol/openid-connect/userinfo
            - OAUTH2_TOKEN_ENDPOINT=/realms/test/protocol/openid-connect/token
            - OAUTH2_FULLNAME_MAP=given_name
            - OAUTH2_REQUEST_PERMISSIONS=openid profile email
            - OAUTH2_USERNAME_MAP=username
            - OAUTH2_ID_MAP=username
            - OAUTH2_EMAIL_MAP=email

```

**Comment by nimasamii** [comment]
That is a Keycloak setting in the "wekan_client" in your "test" Realm.
Make sure you have "https://wekan.domain.tl/*" in your valid redirect URLs, then trace what actual redirect URL is used and allow only that.

**Comment by hamsterbacke** [comment]
That is the problem. I have the right redirect URL specified. If i put something wrong in it wekan says:
![error_wekan_invalid_redirect_uri](https://user-images.githubusercontent.com/3926904/107274410-a13d2900-6a50-11eb-922b-aa5ac119aa57.png)
Keycloak says:
`keycloak_1  | 20:00:53,495 WARN  [org.keycloak.events] (default task-87) type=LOGIN_ERROR, realmId=test, clientId=wekan_client, userId=null, ipAddress=10.2.3.129, error=invalid_redirect_uri, redirect_uri=https://wekan.domain.tld/wekan/_oauth/oidc`

If I put the redirect uri https://wekan.domain.tld/wekan/_oauth/oidc or https://wekan.domain.tld/wekan/* in valid redirect uri, keycloak says:
`keycloak_1  | 20:03:41,253 WARN  [org.keycloak.events] (default task-90) type=CODE_TO_TOKEN_ERROR, realmId=test, clientId=wekan_client, userId=6117eb6b-e7f5-4663-839a-e0019628682c, ipAddress=10.1.1.30, error=invalid_code, grant_type=authorization_code, code_id=3f697f62-4295-45c7-a274-baad4bbd4729, client_auth_method=client-secret`

wekan says:
```
{"line":"405","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC https://sso-portal.domain.tld/auth/realms/test/protocol/openid-connect/token: failed [400] {\"error\":\"invalid_grant\",\"error_description\":\"Incorrect redirect_uri\"}","time":{"$date":1612815251072},"level":"warn"}
Exception while invoking method 'login' Error: Failed to get token from OIDC https://sso-portal.domain.tld/auth/realms/test/protocol/openid-connect/token: failed [400] {"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
    at getToken (packages/wekan-oidc.js:144:22)
    at Object.handleOauthRequest (packages/wekan-oidc.js:42:15)
    at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth/oauth_server.js:170:5)
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by rasos** [comment]
Wekan seems to ignore the Base URL set in keycloak. We always got the login popup window as localhost.  We had to set in `docker-compose.yml`

        ROOT_URL=https://wekan.domain.tld

and we had to add the mapping

```
- OAUTH2_ID_MAP=preferred_username
- OAUTH2_USERNAME_MAP=preferred_username
- OAUTH2_FULLNAME_MAP=given_name
- OAUTH2_EMAIL_MAP=email
```

**Comment by xet7** [comment]
@rasos 

Yes, setting ROOT_URL is required always for Wekan to work correctly

Yes, only login popup works. Redirect does not work yet #3845

**Comment by mqu** [comment]
facing same issue with wekan + openid on keycloak.

keycloak log:
```
WARN  [org.keycloak.events] (executor-thread-4290) type=LOGIN_ERROR, realmId=ASAP, clientId=wekan-kalif, userId=null, ipAddress=82.X.X.X.X, error=invalid_redirect_uri, redirect_uri=https://keycloak.company.net/_oauth/oidc
```
I can't understand why redirect_url is on my SSO server and not back to my wekan application URL. Here is decoded URL
```
https://keycloak.company.net/auth/realms/ASAP/protocol/openid-connect/auth?
loginStyle=popup
&client_id=wekan-kalif
&response_type=code
&redirect_uri=https://keycloak.company.net/_oauth/oidc
&state=eyJsb2dpblN0eWxlIj...mYWxzZX0=
&scope=openid profile email
```
- scope seem to be wrong : contains 3 values separated with one space.

here is my setting in docker-compose.yml
```
- DEBUG=true
- OAUTH2_ENABLED=true
- OAUTH2_LOGIN_STYLE=redirect
- OAUTH2_CLIENT_ID=wekan-kalif
- OAUTH2_SERVER_URL=https://sso.company.net/auth
- ROOT_URL=https://sso.company.net/
- OAUTH2_AUTH_ENDPOINT=/realms/ASAP/protocol/openid-connect/auth
- OAUTH2_USERINFO_ENDPOINT=/realms/ASAP/protocol/openid-connect/userinfo
- OAUTH2_TOKEN_ENDPOINT=/realms/ASAP/protocol/openid-connect/token
- OAUTH2_SECRET=valy...obeal
- OAUTH2_ID_MAP=preferred_username
- OAUTH2_USERNAME_MAP=preferred_username
- OAUTH2_FULLNAME_MAP=given_name
- OAUTH2_EMAIL_MAP=email
```

Keycloak settings:
```
client protocol: openid-connect
Access type: confidential

Root URL: https://wekan.kalif.company.net
Valid redirect URL: https://wekan.kalif.company.net/_oauth/oidc
base URL: https://wekan.kalif.company.net
admin URL: https://wekan.kalif.company.net
Web Origin: https://wekan.kalif.company.net/* ; *
```

**Comment by CaffeineSheep** [comment]
@mqu Did you end up getting things working? I'm struggling to get KeyCloak working with Wekan, myself.

**Comment by mqu** [comment]
@CaffeineSheep : nope. Sorry.
