### ISSUE TITLE
Error on editing custom fields after the last update from 25.02.2021 (very important for us)

### ISSUE THREAD

**Issue by bbyszio** [wekan/wekan#3612]
## Issue

Add these issues to elsewhere:
- SECURITY ISSUES: https://github.com/wekan/wekan/blob/master/SECURITY.md
- UCS: https://github.com/wekan/univention/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: **Yes**
* Wekan version: **5.00**
* Operating System: **Ubuntu 18.0.**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **snap**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **apache**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Chrome latest version**

**Problem description**:
After the last Update from 25.02.2021 i'm not able to fill or edit custom fields.  The entered value appaer for a second and disappaer then.

snap logs wekan says:
```
2021-02-26T10:05:44Z wekan.wekan[1193]: Exception while invoking method '/cards/update' ReferenceError: actitivy is not defined
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Object.<anonymous> (models/activities.js:253:9)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at packages/matb33_collection-hooks.js:422:18
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Array.forEach (<anonymous>)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at after (packages/matb33_collection-hooks.js:421:9)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:436:12)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Object.collection.<computed> [as insert] (packages/matb33_collection-hooks.js:150:21)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at ns.Collection.insert (packages/mongo/collection.js:523:39)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at models/cards.js:2118:22
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Function._.each._.forEach (packages/underscore.js:147:22)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at cardCustomFields (models/cards.js:2101:7)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Object.<anonymous> (models/cards.js:2310:5)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at packages/matb33_collection-hooks.js:506:28
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Array.forEach (<anonymous>)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at packages/matb33_collection-hooks.js:505:11
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Array.forEach (<anonymous>)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:504:9)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Object.collection.<computed> [as update] (packages/matb33_collection-hooks.js:150:21)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at MethodInvocation.m.<computed> (packages/allow-deny/allow-deny.js:173:46)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at packages/check/match.js:118:15
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at packages/ddp-server/livedata_server.js:719:19
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at packages/ddp-server/livedata_server.js:717:46
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at packages/ddp-server/livedata_server.js:715:46
2021-02-26T10:05:44Z wekan.wekan[1193]:     at new Promise (<anonymous>)
2021-02-26T10:05:44Z wekan.wekan[1193]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
```

**Comment by BaronvSchroeder** [comment]
> After the last Update from 25.02.2021 i'm not able to fill or edit custom fields. The entered value appaer for a second and disappaer then.

i can confirm this, since yesterday it is not possible to fill or edit custom fields.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3610 . Will be in next Wekan release v5.01.
