### ISSUE TITLE
LDAP logins lead to "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by robert-scheck** [wekan/wekan#3614]
Using `quay.io/wekan/wekan:latest` (image ID 1bc809402294) the installation here ends up with this when trying to log in using an LDAP user:

```
Exception while invoking method 'login' RangeError: Maximum call stack size exceeded
    at Object.EJSON.clone (packages/ejson/ejson.js:551:15)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
```

Oh, I would like to note that LDAP itself was completely working during initial setup and it stopped working at some unknown point in time, discovered after a restart of the Wekan container followed by an explicit logout. Existing sessions (from LDAP users) are still working, just new logins from LDAP users end like above (in the frontend, there is no error, it just shows the login page again after trying to login). The issue persisted when updating from v4.81 to latest, thus it feels like a bug.

**Comment by bewoodall** [comment]
Ran into this problem myself today. Looking at the code ([/packages/wekan-ldap/server/sync.js](https://github.com/wekan/wekan/blob/df54863e7243b0b067ec2d30d8352ff1838931c4/packages/wekan-ldap/server/sync.js#L250)) it appeared this was happening while trying to get the user's email from LDAP. My setting for LDAP_EMAIL_FIELD was invalid. Setting it blank cleared up the issue.

So in a way it is user error, however, it would be nice if that code had some exception handling with more useful log messages including things such as any relevant environment variables.
