### ISSUE TITLE
Environment specific: LDAP - Not able to create user account when LDAP entity has more than one "mail" field

### ISSUE THREAD

**Issue by mlang38** [wekan/wekan#3630]
## Issue

**Server Setup Information**:
* Did you test in newest Wekan?: **yes**
* Wekan version: **Snap  5.03-2-g44cf82c  1394  latest/stable  xet7**
* Operating System: **Ubuntu 20.04.2 LTS LXC container**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **Snap**

**Problem description**:
I'm using OpenLDAP directory.
I have to set `ldap-sync-user-data='true'` and `ldap-sync-user-data-fieldmap='{"cn":"name,"mail":"email"}'` to have email fields because the email address cannot be inferred from `ldap-user-search-field='uid'` and a `ldap-default-domain`.

Background sync works well for the majority of my LDAP users, but for those having **more than one `mail` entity field**, for email aliases, I've got this error :

```
[DEBUG] Identifying user with: uid
[DEBUG] Mapping field cn -> name
[DEBUG] user.name changed to: <the_user_fullname>
[DEBUG] Mapping field mail -> email
[DEBUG] Identifying user with: uid
[DEBUG] New user data {
  "username": "<user_uid>",
  "email": {
    "type": "Buffer",
    "data": [
      112,
      105,
      <... more numbers>
      102,
      114
    ]
  }
}
[ERROR] Error creating user {
  "message": "Match error: Expected string, got object in field email",
  "path": "email",
  "sanitizedError": {
    "isClientSafe": true,
    "error": 400,
    "reason": "Match failed",
    "message": "Match failed [400]",
    "errorType": "Meteor.Error"
  },
  "errorType": "Match.Error"
}
```

By browsing quickly the Wekan repo I guess the problem is coming from somewhere like [here](https://github.com/wekan/wekan/blob/44cf82caab8d11773a4607e0c2f9db5c38d72b4d/packages/wekan-ldap/server/sync.js#L150), but it's perhaps a bad clue.

**Comment by xet7** [comment]
@mlang38 

That could be correct place.

From database schema it looks like there could be more that one email address:
https://github.com/wekan/wekan/blob/master/models/users.js#L42

You could try adding some `console.log(...);` lines to see what values those fields are.

Also [check in database](https://github.com/wekan/wekan/wiki/Backup) is at Wekan database users collection/table all those email addresses.

You can build Wekan code like this https://github.com/wekan/wekan/wiki/Emoji

If it looks like it does not yet work with many email addresses, it should be fixed so it works.

Thanks!

**Comment by mlang38** [comment]
I've tried to build Wekan as in your Emoji wiki page, in a Ubuntu 20.10 Vagrant box. It breaks at the `meteor build .build --directory` stage.

```
wekan-accounts-cas: updating npm dependencies -- xml2js, cas...                          
/home/vagrant/.meteor/packages/meteor-tool/.2.1.0.yuair9.drob++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise
/promise_server.js:218                                                                     
      throw error;                                                                         
      ^                                      
                                                                                                                                                                                       
Error: ENOENT: no such file or directory, lstat '/vagrant/packages/wekan-accounts-cas/.npm/package-new-1fjqfzk.p8bk/node_modules/lodash/fp'                                            
    at Object.lstatSync (fs.js:1007:3)                                                     
    at /home/vagrant/.meteor/packages/meteor-tool/.2.1.0.yuair9.drob++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1642:23
...
```

By the way, the `rebuild-wekan.sh` script is quite dangerous. It doesn't check if the build has succeeded. Then `cd ../../../..`, therefore it can go to `/` root folder, then does some `find . ... | xargs rm -f`on the whole system. Always start such scripts with `set -euo pipefail`, really.

**Comment by xet7** [comment]
@mlang38 

Please send pull request with that pipefail added.
