### ISSUE TITLE
ERR_INVALID_CHAR

### ISSUE THREAD

**Issue by devilmengcry** [wekan/wekan#3644]
## Issue

https://boards.wekan.team/cfs/files/attachments/eFNQpSvRuZDxsTSR9/%E4%B8%AD%E6%96%87%20abc%20123.jpg?token=eyJhdXRoVG9rZW4iOiIzNDB0alRkdXFSb1NFRTFjNm0xVGlZay1oV2pObnZ2UjFidWxpXzB1S2V4In0%3D&download=true

**Problem description**:
```
wekan-app  | (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
wekan-app  | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekan-app  |       throw error;
wekan-app  |       ^
wekan-app  |
wekan-app  | TypeError [ERR_INVALID_CHAR] [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
wekan-app  |     at ServerResponse.setHeader (_http_outgoing.js:533:3)
wekan-app  |     at ServerResponse.res.setHeader (/build/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/lib/patch.js:134:22)
wekan-app  |     at packages/cfs_http-methods.js:622:17
wekan-app  |     at Function._.each._.forEach (packages/underscore.js:147:22)
wekan-app  |     at packages/cfs_http-methods.js:618:11 {
wekan-app  |   code: 'ERR_INVALID_CHAR'
wekan-app  | }
```

**Comment by xet7** [comment]
Moved to #2759
