### ISSUE TITLE
Error handling in rebuild-wekan.sh

### ISSUE THREAD

**Issue by tod31** [wekan/wekan#3704]
## Issue

I just tried setting up a wekan development environment with WSL2. While executing rebuild-wekan.sh with option 2 (build wekan) there was an error in https://github.com/wekan/wekan/blob/769bb7a55dcf59417781b16ea70e04773950ab9d/rebuild-wekan.sh#L84

```
/home/wsl/.meteor/packages/meteor-tool/.2.1.0.1dx09im.4iypf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.readMetadataFromDirectory (/tools/isobuild/isopack.js:205:28)
    at exports.Tropohouse._alreadyDownloaded (/tools/packaging/tropohouse.js:320:19)
    at exports.Tropohouse._makeDownloader (/tools/packaging/tropohouse.js:391:33)
    at /tools/packaging/tropohouse.js:568:29
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:565:20
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/wsl/.meteor/packages/meteor-tool/.2.1.0.1dx09im.4iypf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at exports.PackageMap.eachPackage (/tools/packaging/package-map.js:49:7)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:561:16)
    at /tools/project-context.js:857:25
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:856:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:855:13)
    at /tools/project-context.js:300:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:290:18)
    at /tools/project-context.js:282:12
    at Function.run (/home/wsl/.meteor/packages/meteor-tool/.2.1.0.1dx09im.4iypf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:281:13)
    at /tools/cli/commands.js:1007:20
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:275:29)
    at buildCommand (/tools/cli/commands.js:1004:8)
    at /tools/cli/commands.js:945:25
    at Function.run (/home/wsl/.meteor/packages/meteor-tool/.2.1.0.1dx09im.4iypf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at /tools/cli/commands.js:943:18
    at /home/wsl/.meteor/packages/meteor-tool/.2.1.0.1dx09im.4iypf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/wsl/.meteor/packages/meteor-tool/.2.1.0.1dx09im.4iypf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1529:7
```

Subsequently the following cd ...
https://github.com/wekan/wekan/blob/769bb7a55dcf59417781b16ea70e04773950ab9d/rebuild-wekan.sh#L86
... failed as the directory was not found, leading to ...
https://github.com/wekan/wekan/blob/769bb7a55dcf59417781b16ea70e04773950ab9d/rebuild-wekan.sh#L90
... cd-ing from `/mnt/d/wekan` into `/`. The following cleanup ...
https://github.com/wekan/wekan/blob/769bb7a55dcf59417781b16ea70e04773950ab9d/rebuild-wekan.sh#L93-L96
... thus was performed on the complete WSL, which mounts the local drives of Windows under /mnt/c, /mnt/d, ...

I noticed the error, as I got permission errors from the find command on several directories and stopped the script. I hope I stopped the script soon enough, as in my case the deletions of \*phantom\* or \*.swp would have definitely affected important data. I am currently investigating a backup, whether there were directories or files which got potentially deleted.

**Comment by tod31** [comment]
Maybe use pushd and popd instead of cd?

**Comment by tod31** [comment]
I dont know why, but although I installed the dependencies first (option 1), I had to manually install npm...

**Comment by a1198457636** [comment]
@xet7 

Hello, I installed wekan source code as the above person reported the same error  

Install Wekan dependencies and Build Wekan have finished

the third step error Run Meteor for dev on http://CUSTOM-IP-ADDRESS:PORT  

![1647569519(1)](https://user-images.githubusercontent.com/19585529/158925312-08f64095-a503-414c-9905-b0dd76c8ede5.jpg)


Please take care of that. Thank you

CentOS7
![微信截图_20220318101546](https://user-images.githubusercontent.com/19585529/158925363-666adef9-c3a4-4813-bf1d-91503f61304c.png)

**Comment by xet7** [comment]
Build script is only for Ubuntu and Debian based systems. Not for WSL or CentOS.

For running WeKan without container at Windows, see used Node.js etc versions from https://wekan.github.io Download section , and Offline Windows link.
