### ISSUE TITLE
Updating from 5.17 to 5.19: ERR fibers.node is missing

### ISSUE THREAD

**Issue by mpc3k** [wekan/wekan#3714]
## Issue

**Server Setup Information**: Uberspace 7 (see https://lab.uberspace.de/guide_wekan.html)

* Did you test in newest Wekan?: 
I am about to. This issue is about updating …
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
Did that, was working before.
* Wekan version: Currently 5.17
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: 
Linux Architecture 3.10.0-1160.6.1.el7.x86_64
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Uberspace 7, see https://lab.uberspace.de/guide_wekan.html
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
Nginx
* Node Version:
v14.15.4
* MongoDB Version:
MongoDB shell version v4.4.4

**Problem description**:
I've previously installed Wekan 5.07 on my Uberspace 7, employing above said install procedure. After an initial update to 5.17 made my Installation inaccessible, I tried to work out a solution with the nice folk of Uberspace support. They got it working, and looking for future proofness, created an update script (which will be published here too, once I can report it to be repeatedly successful) to ease updates in the future, and encourage others to do so too.

The issue here is the same as before using the script though, and it's the dreaded
"fibers.node is missing"
thing again, which prevents wekan from being started by supervisord successfully. Wekan remains stuck in an endless restart loop and FATAL state.

Here's an excerpt of supervisord.log:
2021-04-13 22:32:46,226 DEBG fd 18 closed, stopped monitoring <POutputDispatcher at 139952679880680 for <Subprocess at 139952679975176 with name wekan in state STARTING> (stdout)>
2021-04-13 22:32:46,227 DEBG fd 20 closed, stopped monitoring <POutputDispatcher at 139952679881688 for <Subprocess at 139952679975176 with name wekan in state STARTING> (stderr)>
2021-04-13 22:32:46,227 INFO exited: wekan (exit status 1; not expected)
2021-04-13 22:32:46,227 DEBG received SIGCLD indicating a child quit
2021-04-13 22:32:48,234 INFO spawned: 'wekan' with pid 3706
2021-04-13 22:32:48,490 DEBG 'wekan' stderr output:
## There is an issue with `node-fibers` ##
`/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node` is missing.

Try running this to fix the issue: /opt/nodejs12/bin/node /home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/build

2021-04-13 22:32:48,491 DEBG 'wekan' stderr output:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Module.Mp.load (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module.Mp._compile (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

2021-04-13 22:32:48,493 DEBG 'wekan' stderr output:
/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module.Mp._compile (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Module.Mp.load (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ion/wekan/wekan-5.17/bundle/programs/server/boot.js:2:15)

2021-04-13 22:32:48,498 DEBG fd 17 closed, stopped monitoring <POutputDispatcher at 139952679881688 for <Subprocess at 139952679975176 with name wekan in state STARTING> (stdout)>
2021-04-13 22:32:48,498 DEBG fd 19 closed, stopped monitoring <POutputDispatcher at 139952679879600 for <Subprocess at 139952679975176 with name wekan in state STARTING> (stderr)>
2021-04-13 22:32:48,498 INFO exited: wekan (exit status 1; not expected)
2021-04-13 22:32:48,499 DEBG received SIGCLD indicating a child quit
2021-04-13 22:32:51,503 INFO spawned: 'wekan' with pid 3730
2021-04-13 22:32:51,744 DEBG 'wekan' stderr output:
## There is an issue with `node-fibers` ##
`/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node` is missing.

Try running this to fix the issue: /opt/nodejs12/bin/node /home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/build

2021-04-13 22:32:51,745 DEBG 'wekan' stderr output:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Module.Mp.load (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module.Mp._compile (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

2021-04-13 22:32:51,748 DEBG 'wekan' stderr output:
/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module.Mp._compile (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Module.Mp.load (/home/ion/wekan/wekan-5.17/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ion/wekan/wekan-5.17/bundle/programs/server/boot.js:2:15)

2021-04-13 22:32:51,754 DEBG fd 17 closed, stopped monitoring <POutputDispatcher at 139952679880536 for <Subprocess at 139952679975176 with name wekan in state STARTING> (stdout)>
2021-04-13 22:32:51,754 DEBG fd 19 closed, stopped monitoring <POutputDispatcher at 139952679879600 for <Subprocess at 139952679975176 with name wekan in state STARTING> (stderr)>
2021-04-13 22:32:51,754 INFO exited: wekan (exit status 1; not expected)
2021-04-13 22:32:51,754 DEBG received SIGCLD indicating a child quit
2021-04-13 22:32:52,755 INFO gave up: wekan entered FATAL state, too many start retries too quickly

Okay, so let's try rebuilding as recommended by "/opt/nodejs12/bin/node /home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/build":
$ /opt/nodejs12/bin/node /home/ion/wekan/wekan-5.17/bundle/programs/server/node_modules/fibers/build
`linux-x64-72-glibc` exists; testing
Problem with the binary; manual build incoming
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@14.15.4 | linux | x64
gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/ion/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ion/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ion/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ion/.cache/node-gyp/14.15.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ion/.cache/node-gyp/14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/ion/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ion/.cache/node-gyp/14.15.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ion',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /home/ion) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/ion/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-1160.6.1.el7.x86_64
gyp ERR! command "/opt/nodejs14/bin/node" "/home/ion/bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /home/ion
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v8.0.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`

Please be aware that I am not proficient with node and system architectures, and would need more explicit instructions. I know how to navigate in Shells and use several packet managers on OS X to do stuff, tho I'm not a coder. Thank you for helping!

**Comment by xet7** [comment]
Wekan only works with Node.js 12.x, currently 12.22.1
- https://github.com/wekan/wekan/blob/master/Dockerfile#L15
- https://nodejs.org/dist/
- https://nodejs.org/dist/v12.22.1/

Wekan does not work with Node.js 14.x
