### ISSUE TITLE
v5.20/5.22 - Orphaned file report in admin section is running infinite and does not end ...

### ISSUE THREAD

**Issue by urmel1960** [wekan/wekan#3716]
## Issue

The new orphaned file report in admin section is running infinite and does not end and has no results . 
According to release notes there should be 2 reports - I do have 4 (the one with the issue mentiones above and a rule report where I do not see what the value will be ..?)

Wekan Version  5.20.0
snap 
ubuntu 20.04

**Comment by urmel1960** [comment]
still same problem with 5.22

**Comment by jrsupplee** [comment]
@urmel1960 

> ## Issue
> 
> The new orphaned file report in admin section is running infinite and does not end and has no results .
> According to release notes there should be 2 reports - I do have 4 (the one with the issue mentiones above and a rule report where I do not see what the value will be ..?)

What do you mean by running infinite?  Is there no visual response or is it locking up your browser?

**Comment by jrsupplee** [comment]
@urmel1960 

If you have shell access to the server could you run the following command and share the output:

```
sudo snap logs -n 40 wekan.wekan
```

**Comment by urmel1960** [comment]
@jrsupplee 
The report is running - the indicator on the right side of the left column is running - but the report never ends and gives no result.

![grafik](https://user-images.githubusercontent.com/144102/115112343-6a6e1c80-9f85-11eb-827f-18bc4aeda390.png)


The log says 

`2021-04-17T06:37:59Z wekan.wekan[123402]: Exception from sub orphanedAttachments id tQqLLRkyKZqsHKJD7 TypeError: Cannot read property 'attachments' of undefined
2021-04-17T06:37:59Z wekan.wekan[123402]:     at server/publications/attachments.js:38:39
2021-04-17T06:37:59Z wekan.wekan[123402]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Subscription.<anonymous> (server/publications/attachments.js:37:51)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at packages/matb33_collection-hooks.js:347:24
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Subscription._handler (packages/matb33_collection-hooks.js:346:28)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at packages/check/match.js:118:15
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at packages/ddp-server/livedata_server.js:1046:15
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Subscription.MeteorX.Subscription._runHandler (packages/lamhieu_unblock.js:68:22)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Session.MeteorX.Session._startSubscription (packages/lamhieu_unblock.js:56:7)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at Session.MeteorX.Session.protocol_handlers.sub (packages/lamhieu_unblock.js:27:15)
2021-04-17T06:37:59Z wekan.wekan[123402]:     at packages/ddp-server/livedata_server.js:559:43
2021-04-17T06:38:30Z wekan.wekan[123402]: Exception from sub orphanedAttachments id tvG7hWEzWQLyECjeD TypeError: Cannot read property 'attachments' of undefined
2021-04-17T06:38:30Z wekan.wekan[123402]:     at server/publications/attachments.js:38:39
2021-04-17T06:38:30Z wekan.wekan[123402]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Subscription.<anonymous> (server/publications/attachments.js:37:51)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at packages/matb33_collection-hooks.js:347:24
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Subscription._handler (packages/matb33_collection-hooks.js:346:28)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at packages/check/match.js:118:15
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at packages/ddp-server/livedata_server.js:1046:15
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Subscription.MeteorX.Subscription._runHandler (packages/lamhieu_unblock.js:68:22)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Session.MeteorX.Session._startSubscription (packages/lamhieu_unblock.js:56:7)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at Session.MeteorX.Session.protocol_handlers.sub (packages/lamhieu_unblock.js:27:15)
2021-04-17T06:38:30Z wekan.wekan[123402]:     at packages/ddp-server/livedata_server.js:559:43
`

**Comment by jrsupplee** [comment]
@xet7 

```
  Attachments.find({}, { fields: { copies: 1 } }).forEach(att => {
    keys.push(new ObjectID(att.copies.attachments.key));
  });
```

This code for the orphaned files report is failing because the `copies` field does not have an `attachments` attribute.

Is this just bad data?  Or is `copies` nulled in certain circumstances?
