### ISSUE TITLE
Importing json exports fails.

### ISSUE THREAD

**Issue by KeptnArgo** [wekan/wekan#3742]
## Issue

Importing json export fails.

when creating board from "From previous export" i get 
```

2021-04-21T14:17:22Z wekan.wekan[114651]: Exception while invoking method 'importBoard' Error: Sort is required
2021-04-21T14:17:22Z wekan.wekan[114651]:     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:214:25)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/matb33_collection-hooks.js:131:46
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Object.self.direct.<computed> [as insert] (packages/matb33_collection-hooks.js:130:30)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at models/wekanCreator.js:395:35
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Array.forEach (<anonymous>)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at WekanCreator.createCards (models/wekanCreator.js:316:16)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at WekanCreator.create (models/wekanCreator.js:959:10)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at MethodInvocation.importBoard (models/import.js:35:20)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/check/match.js:118:15
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:719:19
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:717:46
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:715:46
2021-04-21T14:17:22Z wekan.wekan[114651]:     at new Promise (<anonymous>)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:559:43
2021-04-21T14:17:22Z wekan.wekan[114651]: Sanitized and reported to the client as: errorClass [Error]: Sort is required [400]
2021-04-21T14:17:22Z wekan.wekan[114651]:     at getErrorObject (packages/aldeed_collection2-core.js:486:28)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:214:25)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/matb33_collection-hooks.js:131:46
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Object.self.direct.<computed> [as insert] (packages/matb33_collection-hooks.js:130:30)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at models/wekanCreator.js:395:35
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Array.forEach (<anonymous>)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at WekanCreator.createCards (models/wekanCreator.js:316:16)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at WekanCreator.create (models/wekanCreator.js:959:10)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at MethodInvocation.importBoard (models/import.js:35:20)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/check/match.js:118:15
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:719:19
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:717:46
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:715:46
2021-04-21T14:17:22Z wekan.wekan[114651]:     at new Promise (<anonymous>)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2021-04-21T14:17:22Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:559:43 {
2021-04-21T14:17:22Z wekan.wekan[114651]:   isClientSafe: true,
2021-04-21T14:17:22Z wekan.wekan[114651]:   error: 400,
2021-04-21T14:17:22Z wekan.wekan[114651]:   reason: 'Sort is required',
2021-04-21T14:17:22Z wekan.wekan[114651]:   details: '[{"name":"sort","type":"required","value":null}]',
2021-04-21T14:17:22Z wekan.wekan[114651]:   errorType: 'Meteor.Error'
2021-04-21T14:17:22Z wekan.wekan[114651]: }
```

when choosing "From Trello":

```
2021-04-21T14:17:49Z wekan.wekan[114651]: Exception while invoking method 'importBoard' TypeError: Cannot read property 'background' of undefined
2021-04-21T14:17:49Z wekan.wekan[114651]:     at TrelloCreator.createBoardAndLabels (models/trelloCreator.js:162:46)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at TrelloCreator.create (models/trelloCreator.js:760:26)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at MethodInvocation.importBoard (models/import.js:35:20)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at packages/check/match.js:118:15
2021-04-21T14:17:49Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:719:19
2021-04-21T14:17:49Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:717:46
2021-04-21T14:17:49Z wekan.wekan[114651]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:715:46
2021-04-21T14:17:49Z wekan.wekan[114651]:     at new Promise (<anonymous>)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2021-04-21T14:17:49Z wekan.wekan[114651]:     at packages/ddp-server/livedata_server.js:559:43
```

Wekan Version 	5.22.0
Meteor version 	2.2
Node version 	12.22.1
MongoDB version 	3.2.22
MongoDB storage engine 	wiredTiger
MongoDB Oplog enabled 	
OS Type 	Linux
OS Platform 	linux
OS Arch 	x64

**Comment by tod31** [comment]
Got another one:

```
Exception while invoking method 'importBoard' Error: Start at is not a valid date
    at getErrorObject (packages\aldeed_collection2-core.js:480:15)
    at ns.Collection.doValidate (packages\aldeed_collection2-core.js:462:13)
    at ns.Collection.Mongo.Collection.<computed> [as insert] (packages\aldeed_collection2-core.js:214:25)
    at packages\matb33_collection-hooks.js:131:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at Object.directOp (packages\matb33_collection-hooks.js:47:27)
    at Object.self.direct.<computed> [as insert] (packages\matb33_collection-hooks.js:130:30)
    at CsvCreator.createCards (models/csvCreator.js:373:22)
    at CsvCreator.create (models/csvCreator.js:392:10)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)

    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: errorClass [Error]: Start at is not a valid date [400]
    at getErrorObject (packages\aldeed_collection2-core.js:486:28)
    at ns.Collection.doValidate (packages\aldeed_collection2-core.js:462:13)
    at ns.Collection.Mongo.Collection.<computed> [as insert] (packages\aldeed_collection2-core.js:214:25)
    at packages\matb33_collection-hooks.js:131:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at Object.directOp (packages\matb33_collection-hooks.js:47:27)
    at Object.self.direct.<computed> [as insert] (packages\matb33_collection-hooks.js:130:30)
    at CsvCreator.createCards (models/csvCreator.js:373:22)
    at CsvCreator.create (models/csvCreator.js:392:10)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)

    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Start at is not a valid date',
  details: '[{"name":"startAt","type":"badDate","value":{"$date":null}},{"name":"dueAt","type":"badDate","value":{"$date":null}},{"name":"endAt","type":"badDate","value":{"$date":null}}]',
  errorType: 'Meteor.Error'
}
```
