### ISSUE TITLE
Problems with wekan-ical-server script since 5.23.0

### ISSUE THREAD

**Issue by mks-85** [wekan/wekan#3806]
Hi there,

OS: ubuntu 20.04
Wekan 5.28.0 installed by snap

I'm using 
https://github.com/LukasGasior1/wekan-ical-server/tree/python3
which is an python3 script and brings an ical-server.

Worked fine until wekan version 5.22.0

Now I get the following exception.

In Line 40 of script it checks for card_info['dueAt'] if there is NULL, but it gets not NULL back from the api, it get's a spaces.

Any changes on wekan so the script must be modified or a bug on wekan which will be fixed?

Exception happened during processing of request from ('192.168.XX.XX', 65344)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/ahsorg-sys/wekan_ical_server_pierre1.py", line 40, in do_GET
    if "dueAt" in info: create_ical_event(cal, board, list, card, info)
  File "/home/ahsorg-sys/wekan_ical_server_pierre1.py", line 18, in create_ical_event
    event.add('dtstart').value = dateutil.parser.parse(card_info['dueAt'])
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 75, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
----------------------------------------
^CTraceback (most recent call last):
  File "/home/ahsorg-sys/wekan_ical_server_pierre1.py", line 51, in <module>
    httpd.serve_forever()
  File "/usr/lib/python3.8/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)

**Comment by mks-85** [comment]
@xet7 Hi Lauri, could you please help to identify if this is a wekan issue or a issue by the ical-server-script?

Thx a lot!
