### ISSUE TITLE
BUG: Database error attempting to change a account 

### ISSUE THREAD

**Issue by bbyszio** [wekan/wekan#3855]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: yes
* Wekan version: 5.33.0
* Operating System: linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node Version: 12.22.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome

**Problem description**:
When i try to change a user account the is the following database error. It dosn't matter which field i want to change. There is allways the same error. After that error the user is not longer be able to login over LDAP. But he can log in with passwort method. When i look on the user in the admin area there is written as login method "undefined". I can change it to LDAP, but if i save the changes, the error comes again. Anyways, after these step the user is be able to log in over LDAP again.

Here is the error: ( from: snap logs -f wekan)

`2021-06-11T09:25:41Z wekan.wekan[29702]: Exception while invoking method 'setEmailVerified' Error: Did not check() all arguments during call to 'setEmailVerified'
2021-06-11T09:25:41Z wekan.wekan[29702]:     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:515:13)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:122:16)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:719:19
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:717:46
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:715:46
2021-06-11T09:25:41Z wekan.wekan[29702]:     at new Promise (<anonymous>)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:559:43
2021-06-11T09:25:41Z wekan.wekan[29702]: Exception while invoking method 'setInitials' Error: Did not check() all arguments during call to 'setInitials'
2021-06-11T09:25:41Z wekan.wekan[29702]:     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:515:13)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:122:16)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:719:19
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:717:46
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:715:46
2021-06-11T09:25:41Z wekan.wekan[29702]:     at new Promise (<anonymous>)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2021-06-11T09:25:41Z wekan.wekan[29702]:     at packages/ddp-server/livedata_server.js:559:43
`

**Comment by xet7** [comment]
@bbyszio 

Is the problem that save button does not save?

When you look at database users table [with MongoDB GUI](https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui), does save button change value?

Or, if you change it to ldap directly at database, does it work then?

**Comment by bbyszio** [comment]
@xet7 
Unfortunately, the behavior has remained the same. But now without an error message in the log files.

I have not tested it yet to make the changes directly via MongoDB GUI. I won't get to that until tomorrow.

**Comment by bbyszio** [comment]
@xet7 
I have now looked at my data set directly in the database. There is "authenticationMethod: ldap". 
"Authentication method: undefined" is in the admin area in the front end. 
When I edit the account it says "Authentication type: Password" 
So I have 3 different displays for the authentication method at the same time. The LDAP method works.

**Comment by xet7** [comment]
Moved to #4560
