### ISSUE TITLE
JSon import fails

### ISSUE THREAD

**Issue by BartoszBroda** [wekan/wekan#3918]
## Issue

Cannot import previously exported board.

**Server Setup Information**:
Docker images:
Export from: v5.36
Import to: v5.36 and tested with v5.40

**Problem description**:
1. Exported board to json
2. Tried importing board, got errors:

`Exception while invoking method 'importBoard' TypeError: Cannot read property 'forEach' of undefined
    at WekanCreator.createBoardAndLabels (models/wekanCreator.js:274:26)
    at WekanCreator.create (models/wekanCreator.js:955:26)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43`

I think the exported board had no and it looks like the importer tries to iterate over them.

**Comment by BartoszBroda** [comment]
I manage to fix it, temporary workaround was to:
1. enter the docker
2. modify ./build/programs/server/app/app.js (adding if(boardToImport.labels)  before boardToImport.labels.forEach )
3. restart docker

I think if you add that check to models/wekanCreator.js:274 it will be fixed for all.

(note, I'm not js dev so this might be a way off)
