### ISSUE TITLE
Massive amount of lag during regular use of wekan

### ISSUE THREAD

**Issue by tromlet** [wekan/wekan#3938]
## Issue

Our version of wekan (it's the snap package) gets extraordinarily laggy extraordinarily often. When I go into the box, I see CPU spiking for the node process. It's never crazy, but I *constantly* get the "This page is slowing down Firefox. To speed up your browser, stop this page" warning banner up at the top, and it's a good 10-15 seconds before I can really get in and *USE* Wekan. It didn't used to do this, and I don't understand what would be causing it.

I feel like this started after a major update, but I'm not totally sure which one - and the box itself (a VM) has a dual-core processor with 4 GB of RAM. We aren't a huge workgroup, we have a decent number of boards (probably 20-30? I can't see all of them), but generally probably only about two to three active users at a time, with a total of 18 users.

**Server Setup Information**:

1. **OS:** CentOS 8.3.2011
2. **CPU:** VMware dual-core (Opteron 8384)
3. **RAM:** 4 GB
4. **Disk:** 30 GB VHD

| Query | Value |
|---|---|
| **Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:** | Yes |
| **Did you test in newest Wekan?:** | Yes |
| **For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings?:** | Yes |
| **Wekan version:** | `5.44` |
| **If this is about old version of Wekan, what upgrade problem you have?:** | n/a |
| **Operating System:** | CentOS 8.3.2011 |
| **Deployment Method(snap/docker/sandstorm/mongodb bundle/source):** | snap |
| **Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):** | Caddy 2 |
| **Node Version:** | Whichever comes with the snap? |
| **MongoDB Version:** | Whichever comes with the snap? |
| **Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?:** | Firefox 89.0.2 |

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
```log

Aug 04 15:50:36 wekan.example.com systemd[1]: Stopping Service for snap application wekan.wekan...
-- Subject: Unit snap.wekan.wekan.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit snap.wekan.wekan.service has begun shutting down.
Aug 04 15:50:36 wekan.example.com systemd[1]: snap.wekan.wekan.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit snap.wekan.wekan.service has successfully entered the 'dead' state.
Aug 04 15:50:36 wekan.example.com systemd[1]: Stopped Service for snap application wekan.wekan.
-- Subject: Unit snap.wekan.wekan.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit snap.wekan.wekan.service has finished shutting down.
Aug 04 15:50:36 wekan.example.com systemd[1]: Started Service for snap application wekan.wekan.
-- Subject: Unit snap.wekan.wekan.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit snap.wekan.wekan.service has finished starting up.
-- 
-- The start-up result is done.
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: DEBUG=true
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MONGO_LOG_DESTINATION=devnull (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MONGO_URL= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MONGODB_BIND_UNIX_SOCKET= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MONGO_URL= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MONGODB_BIND_IP=127.0.0.1 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MONGODB_PORT=27019 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MAIL_URL=smtp://mail.example.com:993
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MAIL_FROM=Wekan <wekan@example.com>
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: ROOT_URL=https://wekan.example.com
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: PORT=3001
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: DISABLE_MONGODB=false (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: CADDY_ENABLED=true
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: CADDY_BIND_PORT=3001 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: WITH_API=true (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: RICHER_CARD_COMMENT_EDITOR=false
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: CARD_OPENED_WEBHOOK_ENABLED=false (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: ACCOUNTS_LOCKOUT_KNOWN_USERS_FAILURES_BEFORE=3 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: ACCOUNTS_LOCKOUT_KNOWN_USERS_PERIOD=60 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: ACCOUNTS_LOCKOUT_KNOWN_USERS_FAILURE_WINDOW=15 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: ACCOUNTS_LOCKOUT_UNKNOWN_USERS_FAILURES_BERORE=3 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: ACCOUNTS_LOCKOUT_UNKNOWN_USERS_LOCKOUT_PERIOD=60 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: ACCOUNTS_LOCKOUT_UNKNOWN_USERS_FAILURE_WINDOW=15 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MAX_IMAGE_PIXEL= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: IMAGE_COMPRESS_RATIO= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: BIGEVENTS_PATTERN=NONE (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: NOTIFICATION_TRAY_AFTER_READ_DAYS_BEFORE_REMOVE= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: NOTIFY_DUE_DAYS_BEFORE_AND_AFTER= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: NOTIFY_DUE_AT_HOUR_OF_DAY= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: EMAIL_NOTIFICATION_TIMEOUT=30000 (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: CORS= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: CORS_ALLOW_HEADERS= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: CORS_EXPOSE_HEADERS= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MATOMO_ADDRESS= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MATOMO_SITE_ID= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MATOMO_DO_NOT_TRACK=true (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: MATOMO_WITH_USERNAME=false (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: BROWSER_POLICY_ENABLED=true (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: TRUSTED_URL= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: WEBHOOKS_ATTRIBUTES= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_ENABLED=false (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_CA_CERT= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_LOGIN_STYLE=redirect (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_CLIENT_ID= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_SECRET= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_SERVER_URL= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_AUTH_ENDPOINT= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_USERINFO_ENDPOINT= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_TOKEN_ENDPOINT= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_ID_MAP= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_USERNAME_MAP= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_FULLNAME_MAP= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_ID_TOKEN_WHITELIST_FIELDS= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_EMAIL_MAP= (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_REQUEST_PERMISSIONS='openid profile email' (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: OAUTH2_ADFS_ENABLED=false (default value)
Aug 04 15:50:37 wekan.example.com wekan.wekan[27454]: LDAP_ENABLE=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_PORT=389
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_HOST=ldap.example.com
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_AD_SIMPLE_AUTH= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_BASEDN=dc=example,dc=com
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_LOGIN_FALLBACK=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_RECONNECT=true (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_TIMEOUT=10000
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_IDLE_TIMEOUT=10000
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_CONNECT_TIMEOUT=10000
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_AUTHENTIFICATION=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_AUTHENTIFICATION_USERDN=uid=wekan,cn=users,dc=example,dc=com
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_AUTHENTIFICATION_PASSWORD=wekanpassword
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_LOG_ENABLED=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_BACKGROUND_SYNC=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_BACKGROUND_SYNC_INTERVAL=300
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_ENCRYPTION=tls
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_CA_CERT=-----BEGIN CERTIFICATE-----asfdsafsafsafsafsafsafsafsafsafsafsadfsafsafsadfdsa-----END CERTIFICATE-----
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_REJECT_UNAUTHORIZED=false
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_USER_AUTHENTICATION=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_USER_AUTHENTICATION_FIELD=uid (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_USER_SEARCH_FILTER=(&(objectclass=person))
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_USER_SEARCH_SCOPE=sub
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_USER_SEARCH_FIELD=uid
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_SEARCH_PAGE_SIZE=0 (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_SEARCH_SIZE_LIMIT=0 (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_GROUP_FILTER_ENABLE=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_GROUP_FILTER_OBJECTCLASS= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_GROUP_FILTER_GROUP_ID_ATTRIBUTE= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_GROUP_FILTER_GROUP_MEMBER_ATTRIBUTE= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_GROUP_FILTER_GROUP_MEMBER_FORMAT= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_GROUP_FILTER_GROUP_NAME= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_UNIQUE_IDENTIFIER_FIELD= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_UTF8_NAMES_SLUGIFY=true (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_USERNAME_FIELD=uid
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_FULLNAME_FIELD=displayName
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_MERGE_EXISTING_USERS=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_SYNC_USER_DATA=true
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_SYNC_USER_DATA_FIELDMAP={
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]:         "displayName": "name",
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]:         "initials": "initials",
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]:         "mail": "email"
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: }
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_SYNC_GROUP_ROLES= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_DEFAULT_DOMAIN= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_EMAIL_MATCH_ENABLE=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_EMAIL_MATCH_REQUIRE=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_EMAIL_MATCH_VERIFIED=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_EMAIL_FIELD=mail
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_SYNC_ADMIN_STATUS= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LDAP_SYNC_ADMIN_GROUPS= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: HEADER_LOGIN_ID= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: HEADER_LOGIN_FIRSTNAME=Header login firstname. Example for siteminder: HEADERFIRSTNAME (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: HEADER_LOGIN_LASTNAME=Header login firstname. Example for siteminder: HEADERLASTNAME (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LOGOUT_WITH_TIMER=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LOGOUT_IN= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LOGOUT_ON_HOURS= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: LOGOUT_ON_MINUTES= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: DEFAULT_AUTHENTICATION_METHOD=ldap
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: ATTACHMENTS_STORE_PATH= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: PASSWORD_LOGIN_ENABLED=true (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: CAS_ENABLED=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: CAS_BASE_URL= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: CAS_LOGIN_URL= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: CAS_VALIDATE_URL= (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: SAML_ENABLED=false (default value)
Aug 04 15:50:38 wekan.example.com wekan.wekan[27454]: SAML_PROVIDER= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_ENTRYPOINT= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_ISSUER= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_CERT= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_IDPSLO_REDIRECTURL= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_PRIVATE_KEYFILE= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_PUBLIC_CERTFILE= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_IDENTIFIER_FORMAT= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_LOCAL_PROFILE_MATCH_ATTRIBUTE= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: SAML_ATTRIBUTES= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: ORACLE_OIM_ENABLED=false (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: RESULTS_PER_PAGE= (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: WAIT_SPINNER=Bounce (default value)
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: caddy is enabled, adjusting ports
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: CADDY_PORT=3001
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: PORT=3001
Aug 04 15:50:39 wekan.example.com wekan.wekan[27454]: MONGO_URL=mongodb://127.0.0.1:27019/wekan
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: Note: you are using a pure-JavaScript implementation of bcrypt.
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: While this implementation will work correctly, it is known to be
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: approximately three times slower than the native implementation.
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: In order to use the native implementation instead, run
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]:   meteor npm install --save bcrypt
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: in the root directory of your application. You may also need to
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: install build tools to compile bcrypt. For more information see:
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: https://github.com/nodejs/node-gyp#installation
Aug 04 15:50:45 wekan.example.com wekan.wekan[27454]: Presence started serverId=asdfasdfasdfadsfa
Aug 04 15:50:48 wekan.example.com wekan.wekan[27454]: > Starting add-card-number-allowed migration.
Aug 04 15:50:48 wekan.example.com wekan.wekan[27454]: > Finishing add-card-number-allowed migration.
Aug 04 15:50:48 wekan.example.com wekan.wekan[27454]: > Starting assign-boardwise-card-numbers migration.
Aug 04 15:50:52 wekan.example.com wekan.wekan[27454]: > Finishing assign-boardwise-card-numbers migration.
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]: [INFO] Enabling LDAP Background Sync
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]: Exception in callback of async function: TypeError: str.toLowerCase is not a function
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.later.parse.text (/snap/wekan/1624/programs/server/npm/node_modules/meteor/percolate_synced-cron/node_modules/later/later.js:1506:34)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.schedule (packages/wekan-ldap/server/sync.js:452:22)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at scheduleEntry (packages/percolate_synced-cron.js:126:24)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at packages/percolate_synced-cron.js:163:7
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Function._.each._.forEach (packages/underscore.js:147:22)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at packages/percolate_synced-cron.js:162:7
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.startup (packages/meteor.js:992:5)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.SyncedCron.start (packages/percolate_synced-cron.js:160:10)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at addCronJobDebounced (packages/wekan-ldap/server/sync.js:461:6)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at runWithEnvironment (packages/meteor.js:1286:24)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]: Exception in callback of async function: TypeError: str.toLowerCase is not a function
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.later.parse.text (/snap/wekan/1624/programs/server/npm/node_modules/meteor/percolate_synced-cron/node_modules/later/later.js:1506:34)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.schedule (packages/wekan-ldap/server/sync.js:452:22)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at scheduleEntry (packages/percolate_synced-cron.js:126:24)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at packages/percolate_synced-cron.js:163:7
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Function._.each._.forEach (packages/underscore.js:147:22)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at packages/percolate_synced-cron.js:162:7
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.startup (packages/meteor.js:992:5)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at Object.SyncedCron.start (packages/percolate_synced-cron.js:160:10)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at notificationCleanupDebounced (models/users.js:1399:16)
Aug 04 15:50:53 wekan.example.com wekan.wekan[27454]:     at runWithEnvironment (packages/meteor.js:1286:24)
Aug 04 15:51:05 wekan.example.com wekan.wekan[27454]: (node:29088) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

**Comment by xet7** [comment]
Does your server have SSD or NVME disk? Normal HDD is very slow, when compared to SSD.

Chromium based browsers are much faster executing Javascript than Firefox.

**Comment by tromlet** [comment]
It does not. We're using 7,200 RPM HDDs in a RAID array across a fiber channel SAN to store our VMs at the moment. Boss is reticent to spend money on... modern hardware. I may be able to give our system higher-speed I/O on the 10,000 RPM array sometime soon, but I doubt we'll be getting any serious SSD arrays anytime soon. :(

**Comment by xet7** [comment]
Yes, there are major differences between Wekan versions. In recent versions, these have sometimes happened:

Slowdowns:
- major new features
- a lot of Javascript added to browserside, that could make Wekan slower

Speedups:
- add new index to MongoDB database
- move a lot of Javascript to serverside
- remove a lot of Javascript etc

Anyway, I recommend newest Wekan, that has newest security fixes of Node.js etc.

**Comment by xet7** [comment]
Wekan bundle of Javascript etc files is about 46 000 files. It kind of needs Linux filesystem and SSD.

**Comment by xet7** [comment]
Well, I have been planning to do optimized version of Wekan, if I have enough time for that. Athough, user experience with it could be very different than with current drag-drop full-featured Wekan.

**Comment by tromlet** [comment]
I did actually update to the latest version of Wekan before I posted this. I will try to see if we can't get some more rapid storage underneath, but that's good to know.

**Comment by xet7** [comment]
There is still a lot of root to optimize current Wekan:
- [Moving code serverside like was done with exceljs](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v536-2021-06-29-wekan-release)
- [Removing extra dependencies like was done with accounts-lockout, about 100 MB less code](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v535-2021-06-14-wekan-release).

Anyone is welcome to send similar pull requests to optimize Wekan.

**Comment by xet7** [comment]
Maybe https://github.com/wekan/wekan/wiki/Allow-private-boards-only
