### ISSUE TITLE
Exception in global search

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3947]
With Wekan v5.50, I observe the following exception:

    Exception from sub globalSearch id 2XXAdcbsD5he7dpqf TypeError: CardCommentReactions.find is not a function
        at findCards (server/publications/cards.js:721:28)
        at Subscription.<anonymous> (server/publications/cards.js:105:10)
        at packages/matb33_collection-hooks.js:347:24
        at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
        at Subscription._handler (packages/matb33_collection-hooks.js:346:28)
        at packages/check/match.js:118:15
        at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
        at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
        at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
        at packages/ddp-server/livedata_server.js:1046:15
        at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
        at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
        at Subscription.MeteorX.Subscription._runHandler (packages/lamhieu_unblock.js:68:22)
        at Session.MeteorX.Session._startSubscription (packages/lamhieu_unblock.js:56:7)
        at Session.sub (packages/ddp-server/livedata_server.js:625:12)
        at Session.MeteorX.Session.protocol_handlers.sub (packages/lamhieu_unblock.js:27:15)
        at packages/ddp-server/livedata_server.js:559:43

It happens when I visit the global search and enter something in the search field.

I cannot tell when the problem was introduced because I see it also for v5.48 and v5.49. I don’t want to go back further to avoid any damage to the DB.

**Comment by G41n4x** [comment]
Same here

**Comment by syndimann** [comment]
Was definitely introduced by https://github.com/wekan/wekan/pull/3945  will have a look at it and provide PR asap

**Comment by xet7** [comment]
FIxed at https://github.com/wekan/wekan/pull/3949
