### ISSUE TITLE
Add Feature: Import/Export CSV/Excel/PDF

### ISSUE THREAD

**Issue by jadeqwang** [wekan/wekan#395]
It would be awesome to be able to import CSV's into a Wekan board, as many other apps have the option of exporting task data into a spreadsheet format (including forms and Gmail-plugin-CRMs). (I'm trying to migrate off of Streak (which is buggy and hard to use) to tracking my tasks on Wekan.

I'm going to suggest a format that's optimized for a CRM-type task, but am open to other suggestions (esp. if this sounds crazy) for Mapping CSV to Kanban board. 

MVP:
- Every row becomes one card (except the header row). 
- The first column is the name of the card. 
- The 2nd column has the "list" that the card should be in (e.g., the "stage" of the customer). 
- The titles of the lists are populated from the limited set of options in the 2nd column.
- Data from all other columns are put into the Description of the card, separated by new lines.

Super fancy:
- Show the user a list of header rows and let the user choose which column is the name of the card, which column is the list, and which columns to ignore completely

**Comment by floatinghotpot** [comment]
@jadeqwang I guess you will be interested in my PR. https://github.com/wekan/wekan/pull/397

**Comment by floatinghotpot** [comment]
This feature has been implemented in PR #413

**Comment by xet7** [comment]
Moved to here from #2926 

From @steep-nb

Exporting Lists, Swimlanes, Boards or Cards to a pdf or Excel sheet would be perfect!
We need a whole List in a sheet which we can show someone, who doesn't use wekan.

From @xet7 

Related code is here:
1. Old export to CSV PR https://github.com/wekan/wekan/pull/413
2. Forked Wekan repo that seem to have Export to Excel, but it has some Chinese characters in code https://github.com/gameendman/wekan and https://snapcraft.io/wekan-ag . Could @gameendman contribute those changes to official Wekan, with Chinese converted to English? I have not checked what all that Excel related code does.
3. From trapa, attached PHP code that converts Wekan Export JSON to CSV summary reports.

[WekanExportJSONtoCSVwithPHP.zip](https://github.com/wekan/wekan/files/4276711/WekanExportJSONtoCSVwithPHP.zip)

It would be nice if some Wekan contributor would spend time to clean up and combine code from these and send pull request to integrate these directly to Wekan.

**Comment by brymut** [comment]
More than happy to have a go at this over the next week and submit a PR

**Comment by xet7** [comment]
@brymut 

Yes you are welcome to do so. I will first wait for you to try add PR.

This issue currently has [$300 bounty](https://www.bountysource.com/issues/28141826-add-feature-import-export-csv-excel-pdf). So after completing this, it's possible for you to get it. Another alternative is to give that bounty to me to support my maintaining of Wekan. Both choises are OK. [More info about bounties](https://wekan.team/bounties/).

**Comment by signalcodec** [comment]
Thank-you for working on this...

I love this thing, excel export is the only thing stopping me convincing other folk to fully jump on-board with it. Means a lot to me.

**Comment by xet7** [comment]
Anyone can test current version of this on Docker quay latest, with default unmodified docker-compose.yml at https://github.com/wekan/wekan

**Comment by gerroon** [comment]
Is it possible to add importing the .json file from a file browser instead of pasting it to this feature? Thew reason is that big imports are very painful.

**Comment by signalcodec** [comment]
The closed solution ignores custom fields.

**Comment by xet7** [comment]
@brymut 

Can you add export/import of custom fields?

**Comment by brymut** [comment]
No prob, I'll have a look at it this week and set up a PR. Sorry for overlooking it, just hadn't noticed it from the other import methods. 

Initial thoughts on this, I'm thinking that custom fields could be represented as extra columns at the right of the rest of the import/export csv columns. With headers like maybe `CustomField-{name of field}-{type}-{showOnCard}-{automaticallyOnCard }-{showLabelOnMiniCard}-{createdAt}-{modifiedAt}`. What do you think @signalcodec @xet7 ?

**Comment by signalcodec** [comment]
Sounds great

**Comment by xet7** [comment]
@brymut 

I don't know, try something that seems to export that data custom fields have.

**Comment by brymut** [comment]
@xet7 yeah, I just realised when I opened up my text editor that I was describing the fields and not the data in the fields. Thinking of something else

**Comment by brymut** [comment]
Set up a PR for the custom fields. Each custom field will have its own column in the CSV/TSV, with the header describing the custom field and the data in the corresponding card row if the card has any data on the custom field.

**Comment by xet7** [comment]
@brymut 

I did add your PR for custom fields, but now export csv/tsv does not work at Source and Snap.

For Snap, you can try it at experimental:
```
sudo snap refresh wekan --edge --amend
```
You can change back to stable this way:
```
sudo snap refresh wekan --stable --amend
```
I did not check Sandstorm yet.

It could be related to #3110

**Comment by brymut** [comment]
ok, I'll have a look

**Comment by xet7** [comment]
Custom fields import/export CSV/TSV was broken because of ostrio-files changes, I did revert those so it did seem like it does work at Snap at least, on new Wekan v4.05 I'm currently in progress of releasing.

**Comment by xet7** [comment]
On Snap I'm currently getting this error. It seems that adding this check did not help https://github.com/wekan/wekan/commit/8eafa1ac66fdcf5fb5f0a95aa6cfee454ddad67f .

@brymut 

Can you try to fix it?
```
May 25 23:56:23 localhost wekan.wekan[10935]: (node:12299) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'question' of undefined
May 25 23:56:23 localhost wekan.wekan[10935]:     at models/exporter.js:325:21
May 25 23:56:23 localhost wekan.wekan[10935]:     at Array.forEach (<anonymous>)
May 25 23:56:23 localhost wekan.wekan[10935]:     at Exporter.buildCsv (models/exporter.js:282:18)
May 25 23:56:23 localhost wekan.wekan[10935]:     at models/export.js:86:20
May 25 23:56:23 localhost wekan.wekan[10935]:     at doCall (packages/meteorhacks_picker.js:128:14)
May 25 23:56:23 localhost wekan.wekan[10935]:     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
May 25 23:56:23 localhost wekan.wekan[10935]:     at processNextRoute (packages/meteorhacks_picker.js:90:14)
May 25 23:56:23 localhost wekan.wekan[10935]:     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
May 25 23:56:23 localhost wekan.wekan[10935]:     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
May 25 23:56:23 localhost wekan.wekan[10935]:     at packages/meteorhacks_picker.js:162:10
May 25 23:56:23 localhost wekan.wekan[10935]:     at /snap/wekan/865/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
May 25 23:56:23 localhost wekan.wekan[10935]: (node:12299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by brymut** [comment]
I'll have a look

**Comment by signalcodec** [comment]
On some boards, this feature is throwing a very generic error of 'Can't Download - Server Error'

If you give me a location to look for logs I can provide more info.

**Comment by Shahin-rmz** [comment]
Hi, 
As I can see `import csv` function works, but only as importing a board. is it possible to import `csv ` as cards to a list of a board?
Thanks

**Comment by xet7** [comment]
@Shahin-rmz 

Use api.py from https://github.com/wekan/wekan to add card. Also see https://wekan.github.io/api/

For example, in bash loop read one line of text from CSV at a time, split by comma, call API. Using API may require having 7 second pause between API calls, to not overload WeKan.

Alternatively, export WeKan board JSON at right sidebar => Board Settings => Export => JSON), make script that converts CSV to JSON, and All Boards => Add Board => From previous export of JSON

**Comment by Gzime** [comment]
Hi

When I export the Board to Excel, the Description column is exported with HTML tags and the checklist is not exported at all! How can I export all the data from the Board?!

**Comment by xet7** [comment]
@Gzime 

> Description column is exported with HTML tags

I think currently HTML is not rendered to plain text when exporting, to keep HTML formatting. 

Examples of rendering is at https://github.com/wekan/wekan/blob/main/packages/markdown/src/template-integration.js

> the checklist is not exported at all!

Maybe there is something missing from this code?

https://github.com/wekan/wekan/blob/main/models/server/ExporterExcel.js

**Comment by xet7** [comment]
@Gzime 

With Excel export, are you looking for:

a) Printable nice looking Excel page, losing some HTML code not important ?

b) Have all formatting exported also ?

**Comment by xet7** [comment]
@Gzime 

If you have some solutions, can you send them as pull requests?

**Comment by xet7** [comment]
Fixed in the upcoming WeKan release. See CHANGELOG.md Upcoming section.
