### ISSUE TITLE
Problems with smtp mail configuration in docker .

### ISSUE THREAD

**Issue by cristomoya-dev** [wekan/wekan#4019]
**when I send an email I get the following**

```
Note: you are using a pure-JavaScript implementation of bcrypt.,
While this implementation will work correctly, it is known to be,
approximately three times slower than the native implementation.,
In order to use the native implementation instead, run,
,
  meteor npm install --save bcrypt,
,
in the root directory of your application. You may also need to,
install build tools to compile bcrypt. For more information see:,
https://github.com/nodejs/node-gyp#installation,
Presence started serverId=hyvJbozcNNEo8FCeq,
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Fri Sep 24 2021 06:34:55 GMT+0000 (Coordinated Universal Time)","time":{"$date":1632465295665},"level":"info"},
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.,
(node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:587,
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16),
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
```
**My configuration is Docker, image 5.60**

```
- MAIL_URL=smtps://wekan@dominio.es:pass@smtp.dominio.com:465?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false
 - MAIL_FROM=Notificación <wekan@dominio.es>
 

```
![imagen](https://user-images.githubusercontent.com/53434479/134631550-1b75bb59-9302-4eaa-b522-dc118f2b388c.png)

**Comment by FuXXz** [comment]
Unfortunately, I can no longer send emails either

2021-09-25T11:48:54.147080699Z (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:587,
2021-09-25T11:48:54.147103533Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16),
2021-09-25T11:48:54.147107561Z (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
2021-09-25T11:48:54.147112159Z (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xet7** [comment]
Moved to #4001
