### ISSUE TITLE
Wekan v5.78: Mermaid Diagram error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4251]
Hi,
it seems I'm getting this error about https://github.com/wekan/wekan/wiki/Mermaid-Diagram, it could be related to  Mermaid issue https://github.com/mermaid-js/mermaid/issues/421 
```
Uncaught RangeError: Maximum call stack size exceeded.
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2)
    at HTMLBodyElement.wrapper (dombackend.js:47)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2)
    at HTMLBodyElement.wrapper (dombackend.js:47)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2)
    at HTMLBodyElement.wrapper (dombackend.js:47)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2)
```

This could be related to:
- #4220
- #4061
- #3614  
- #3099
- #1096

Does someone use Mermaid diagram? I presume that it could be possible. I'll think can this be fixed. PRs welcome.

**Comment by xet7** [comment]
Maybe I'll check what version of Mermaid WeKan has, and check is there newer version of Mermaid?

**Comment by xet7** [comment]
I added Mermaid diagram back, after figuring out correct dependencies.

**Comment by aboire** [comment]
I still get the error when I update to 6.05
`Uncaught RangeError: Maximum call stack size exceeded.
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1100602)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2:1100602)
    at HTMLBodyElement.wrapper (dombackend.js:47:28)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1100602)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2:1100602)
    at HTMLBodyElement.wrapper (dombackend.js:47:28)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1100602)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2:1100602)
    at HTMLBodyElement.wrapper (dombackend.js:47:28)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1100602)`

**Comment by xet7** [comment]
@aboire

**Comment by xet7** [comment]
@aboire 

What platform? Source/Snap/UCS/Docker/Sandstorm?

**Comment by aboire** [comment]
it's source

**Comment by CardYZ** [comment]
I still get the error when I update to 6.18 
docker pull wekanteam/wekan:v6.18
622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122 
        
       Uncaught RangeError: Maximum call stack size exceeded.
    at Function.it [as find] (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122:2707)
    at d.fn.init.find (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122:19702)
    at HTMLBodyElement.s (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:221:1481)
    at Function.it [as find] (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122:2931)
    at d.fn.init.find (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122:19702)
    at HTMLBodyElement.s (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:221:1481)
    at Function.it [as find] (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122:2707)
    at d.fn.init.find (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122:19702)
    at HTMLBodyElement.s (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:221:1481)
    at Function.it [as find] (622536a0b3f5738f4b31ca76994e94ecb89fc7a6.js?meteor_js_resource=true:122:2931)

**Comment by CardYZ** [comment]
On the login page

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/commit/072778b9aaefd7fcaa7519b1ce1cafc1704d646d

Related #4512

**Comment by xet7** [comment]
- Try to fix again Mermaid Diagram error: Maximum call stack size exceeded.
- Added bigger text size for Diagram.
- https://github.com/wekan/wekan/issues/4251
- https://stackoverflow.com/questions/66825888/maximum-text-size-in-diagram-exceeded-mermaid-js
- https://github.com/mermaid-js/mermaid/blob/74b1219d62dd76d98d60abeeb36d4520f64faceb/src/defaultConfig.js#L39
- https://github.com/wekan/cli-table3
- https://www.npmjs.com/package/@wekanteam/markdown-it-mermaid
- https://github.com/wekan/markdown-it-mermaid
- https://github.com/wekan/wekan/blob/master/packages/markdown/src/template-integration.js
```
Markdown.use(markdownItMermaid,{
  maxTextSize: 50000,
});
```
