### ISSUE TITLE
Exception in callback of async function: errorClass [Error]: Connection timeout [email-fail]

### ISSUE THREAD

**Issue by tnannen** [wekan/wekan#4360]
## Issue Server Installation - Test

We can get our own idea whats gonig wrong.
We cannot configure the email "service" for notifcation, Invitation, 

### Error Message
Exception in callback of async function: errorClass [Error]: Connection timeout [email-fail]

Maybe one of you has any idea what we are doing wrong.

Thank you very much in advance

Thorsten

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by jixian79** [comment]
i have same problem,  Dcoker compose
MAIL_URL=smtps://contact%40example.com:xxxxxxx@smpt.exmail.qq.com:465

@xet7   

```
xception in callback of async function: errorClass [Error]: Connection timeout [email-fail]
    at sendInvitationEmail (models/settings.js:297:13)
    at models/settings.js:379:19
    at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
    at packages/mongo/collection.js:935:9
    at wrappedCallback (packages/matb33:collection-hooks/insert.js:59:23)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/mongo_driver.js:316:7
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/mongo_driver.js:364:7
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  isClientSafe: true,
  error: 'email-fail',
  reason: 'Connection timeout',
  details: undefined,
  errorType: 'Meteor.Error'
}

```
