### ISSUE TITLE
WeKan v6.12 errors

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4407]
Snap error, when trying to upgrade https://boards.wekan.team

```
error: error running snapctl: get which option?
NODE_OPTIONS=--max_old_space_size=4096 (default value)
```

Currently that WeKan v6.12 is at edge channel. Please make backup before trying it. I have not pushed it to docker etc yet.
```
sudo snap refresh wekan --edge --amend
```
And back to stable:
```
sudo snap refresh wekan --stable --amend
```
I'll also test Sandstorm version, I don't know are all images visible there.

**Comment by gramakri** [comment]
Trying to update the Cloudron package. Fresh install fails with the below:

```
17:38:26 - > Starting migrate-attachment-drop-index-cardId migration.
17:38:26 - /app/code/build/bundle/programs/server/node_modules/fibers/future.js:313
17:38:26 - throw(ex);
17:38:26 - ^
17:38:26 - 
17:38:26 - MongoError: ns not found 884a9f34d151b107.attachments
17:38:26 - at MessageStream.messageHandler (/app/code/build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:268:20)
17:38:26 -     at MessageStream.emit (events.js:400:28)
17:38:26 -     at MessageStream.emit (domain.js:475:12)
17:38:26 - at processIncomingData (/app/code/build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
17:38:26 - at MessageStream._write (/app/code/build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
17:38:26 -     at writeOrBuffer (internal/streams/writable.js:358:12)
17:38:26 -     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
17:38:26 -     at Socket.ondata (internal/streams/readable.js:731:22)
17:38:26 -     at Socket.emit (events.js:400:28)
17:38:26 -     at Socket.emit (domain.js:475:12)
17:38:26 -     at addChunk (internal/streams/readable.js:293:12)
17:38:26 -     at readableAddChunk (internal/streams/readable.js:267:9)
17:38:26 -     at Socket.Readable.push (internal/streams/readable.js:206:10)
17:38:26 -     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
17:38:26 - operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1647049103 },
17:38:26 - ok: 0,
17:38:26 - code: 26,
17:38:26 - codeName: 'NamespaceNotFound',
17:38:26 - '$clusterTime': {
17:38:26 - clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1647049103 },
17:38:26 - signature: {
17:38:26 - hash: Binary {
17:38:26 - _bsontype: 'Binary',
17:38:26 - sub_type: 0,
17:38:26 - position: 20,
17:38:26 - buffer: Buffer(20) [Uint8Array] [
17:38:26 - 145,  37, 129, 17, 239, 226,
17:38:26 - 56, 193, 184, 88, 157, 208,
17:38:26 - 162,   6,  92, 64, 104,  37,
17:38:26 - 167,  67
17:38:26 - ]
17:38:26 - },
17:38:26 - keyId: Long { _bsontype: 'Long', low_: 5, high_: 1646787151 }
17:38:26 - }
17:38:26 - }
17:38:26 - }
```

Maybe related to https://github.com/wekan/wekan/commit/6d5651e53f269f248129039389b9171b0dc7133d (@mfilser)

**Comment by mfilser** [comment]
@gramakri
I tested the "drop index" code without the index exist, no errors.
I read in the error message something about Namespace, i don't see anything about Namespace in the related code, maybe a special Cloudron situation...

**Comment by mfilser** [comment]
@xet7
Just for your Info, my PR would not fix the snap error. I had only a look qt the comment of @gramakri

**Comment by xet7** [comment]
@mfilser 

Ok thanks!

**Comment by nebulade** [comment]
Thanks for the patch, I just ran our app e2e tests with it and it has fixed the issue for the Cloudron package!
