### ISSUE TITLE
UserId will not be set in Checklists by import from Trello

### ISSUE THREAD

**Issue by buttermilchmensch** [wekan/wekan#4417]
### Server Setup Information

* Did you test in newest Wekan?: 6.09.0
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Debian GNU/Linux 10 (buster)
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 12.22.10
* MongoDB Version: 4.4.6
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox, Safari, Chrome

### Problem description
By importing a board with a JSON file from Trello to our Wekan we get the message to map the members. If we do this, the next message is to map the members but without the members. (See the screenshots.)

If we click on "Erledigt" (= Done) at the last screenshot the board will be imported again. (I think this is a bug.)

<img width="595" alt="InkedWekanMitgliederZuordnen01_LI" src="https://user-images.githubusercontent.com/25295482/158473340-9dc4756d-72e5-49a1-8303-96bb5068c5a0.jpg">
<img width="595" alt="InkedWekanMitgliederZuordnen02_LI" src="https://user-images.githubusercontent.com/25295482/158473354-05b48a31-b467-4289-9d53-078e3c9b22b4.jpg">
<img width="595" alt="WekanMitgliederZuordnen03" src="https://user-images.githubusercontent.com/25295482/158473364-abe378d1-6718-4e9a-9a81-39e8c2e5cacc.png">

Further we are using the [Wekan-Cleanup Skript](https://github.com/wekan/wekan-cleanup). If this is running it's deleting the orphan checklists with no userId. And so I saw that the imported checklists have no userId and will be deleted if we run the script and this is a bug too I think.

I hope you can help us to find the failure and maybe make a better wekan. :)

#### Logs
```
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at Request.<anonymous> (/snap/wekan/1998/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at Request.emit (events.js:314:20)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at Request.EventEmitter.emit (domain.js:483:12)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at IncomingMessage.<anonymous> (/snap/wekan/1998/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at Object.onceWrapper (events.js:420:28)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at IncomingMessage.emit (events.js:326:22)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at endReadableNT (_stream_readable.js:1241:12)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-03-15T22:30:00+01:00 wekan.wekan[31318]: (node:32242) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 135)
```

**Comment by buttermilchmensch** [comment]
My workaround is:
1. run the cleanup.py script befor the import.
2. import the JSON file
3. update the Wekan MongoDB to set a existing userId with following command
`db.checklists.update({userId: null},{$set:{userId: "TGKzSC6HSQbAg44TJ"}},{multi:true})`

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
