### ISSUE TITLE
Failed to import JSON from Trello

### ISSUE THREAD

**Issue by akhudushin** [wekan/wekan#4418]
Receiving error when attempting to import JSON from Trello:

```
Exception while invoking method 'importBoard' ReferenceError: Attachment is not defined
    at models/trelloCreator.js:449:13
    at Array.forEach (<anonymous>)
    at models/trelloCreator.js:426:21
    at Array.forEach (<anonymous>)
    at TrelloCreator.createCards (models/trelloCreator.js:288:17)
    at TrelloCreator.create (models/trelloCreator.js:758:10)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

Possible typo at 449 and 451 lines. Should be "Attachments".

https://github.com/wekan/wekan/blob/90be8ff936bd7edb1c67c6c296640509f8bfdc66/models/trelloCreator.js#L449

**Comment by hatl** [comment]
I can confirm that issue.
Tried importing several boards - alway resluting in the mentioned error message.

**Comment by 2447254731** [comment]
Well, I'm occuring the same problem while deploying an [offline Windows version](https://github.com/wekan/wekan/wiki/Offline) with the latest version 6.15.
I've tried correct that as well as other 3 lines(16986, 16988, 20818, 20820) with "Attachments" in `\programs\server\app\app.js`
And it didn't work, though few attachments were attached now.
Now I got these error information in Powershell:
```
Exception while invoking method 'importBoard' ReferenceError: links is not defined
    at models/trelloCreator.js:455:9
    at Array.forEach (<anonymous>)
    at TrelloCreator.createCards (models/trelloCreator.js:288:17)
    at TrelloCreator.create (models/trelloCreator.js:758:10)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```
Seems there wasn't just one small problem needing corrections?

**Comment by xet7** [comment]
@2447254731 

Thanks for info ! We are currently developing attachments related fixes.

**Comment by xet7** [comment]
Not all fixed yet.

**Comment by xet7** [comment]
Moved to #4877

**Comment by oninoni** [comment]
```
Exception while invoking method 'importBoard' ReferenceError: Attachment is not defined
    at models/trelloCreator.js:453:13
    at Array.forEach (<anonymous>)
    at models/trelloCreator.js:430:21
    at Array.forEach (<anonymous>)
    at TrelloCreator.createCards (models/trelloCreator.js:292:17)
    at TrelloCreator.create (models/trelloCreator.js:764:10)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at packages/ddp-server/livedata_server.js:827:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:775:23)
    at packages/ddp-server/livedata_server.js:639:43
 ```
 
 Seems to be happening again?
