### ISSUE TITLE
At Sandstorm, newest experimental WeKan error when starting

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4438]
```
> Finishing migrate-avatars-collectionFS-to-ostrioFiles migration.
> Starting migrate-attachment-drop-index-cardId migration.
/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoError: ns not found
    at MessageStream.messageHandler (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:470:12)
    at processIncomingData (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:726:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0
}
```

**Comment by ocdtrekkie** [comment]
I have not yet tried upgrading an existing grain, so I am not sure if this is maybe a bug in that particular migration or not?

**Comment by xet7** [comment]
@ocdtrekkie 

I'm currently building Sandstorm WeKan v6.13, you can try does it work, when it's pushed to experimental soon.

**Comment by xet7** [comment]
It seems v6.13 works for me. It there is any problems, please add new issue.
