### ISSUE TITLE
LDAP authentication doesn't support mutliple emails in LDAP accounts

### ISSUE THREAD

**Issue by buzztiaan** [wekan/wekan#4452]
Latest wekan on a LXC , LDAP authentication fully works, but -doesnt- work for LDAP users with more than a single email address configured.

Relevant log from the login attempt: 

```
Apr 04 20:28:17 wekan node[30297]: Exception while invoking method 'login' RangeError: Maximum call stack size exceeded
Apr 04 20:28:17 wekan node[30297]:     at EJSON.clone (packages/ejson/ejson.js:551:15)
Apr 04 20:28:17 wekan node[30297]:     at Array.map (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:580:14)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
Apr 04 20:28:17 wekan node[30297]:     at Array.forEach (<anonymous>)
Apr 04 20:28:17 wekan node[30297]:     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
Apr 04 20:28:17 wekan node[30297]:     at packages/ejson/ejson.js:600:22
```

**Comment by buzztiaan** [comment]
This user in LDAP has 4 email addresses, yet that ejson breaks 12 times, seems like its tripping over itself 3 times?

**Comment by xet7** [comment]
@buzztiaan 

You could look at LDAP code:
https://github.com/wekan/wekan/tree/master/packages

Some have sent other changes related to other login methods, groups, etc: https://github.com/wekan/wekan/pull/4450

It's possible to test and send PR this way:
https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

I don't have any LDAP server running. LDAP has been added mostly by other contributors.

**Comment by xet7** [comment]
Some more auth code is also here:
- https://github.com/wekan/wekan/blob/master/server/authentication.js
- https://github.com/wekan/wekan/blob/master/client/components/main/layouts.js#L320

**Comment by xet7** [comment]
Some Users/Orgs code here:
- https://github.com/wekan/wekan/tree/master/models

**Comment by xet7** [comment]
And Admin Panel Org/People code here:
- https://github.com/wekan/wekan/tree/master/client/components/settings

**Comment by buzztiaan** [comment]
The code was indeed assuming no user could ever have multiple addresses.

This fixed it ;

```
+++ programs/server/packages/wekan-ldap.js
@@ -1158,7 +1158,14 @@
     });
   }
 
-  return ldapUser.getLDAPValue(emailField);
+  const ldapMail = ldapUser.getLDAPValue(emailField);
+  if (typeof ldapMail === 'string') {
+    return ldapMail;
+  } else {
+    return ldapMail[0].toString();
+  }
 }
 
 function getLdapFullname(ldapUser) {
```
