### ISSUE TITLE
Bug: WeKan v6.15 duplicate board has some errors

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4459]
When clicking Duplicate board, there is some errors at browser console, and duplicated board is only visible after reloading webpage. It does copy board and attachments, but there's this bug.

# Firefox

![duplicate-firefox](https://user-images.githubusercontent.com/15545/161976452-9745db29-741a-44f4-9f57-07c3ebe82ff5.png)

# Chrome

![duplicate-chrome](https://user-images.githubusercontent.com/15545/161976490-1c1eb71c-9c45-40aa-b6d3-2e1a444fb002.png)

**Comment by xet7** [comment]
At terminal logs, it seems to be that same `Attachments.insert is not a function` error, my previous try to fix did not work:

```
I20220406-15:36:19.379(3)? Exception while invoking method 'copyBoard' TypeError: Attachments.insert is not a function
I20220406-15:36:19.382(3)?     at models/cards.js:588:19
I20220406-15:36:19.382(3)?     at Array.forEach (<anonymous>)
I20220406-15:36:19.383(3)?     at Document.copy (models/cards.js:586:27)
I20220406-15:36:19.383(3)?     at models/lists.js:201:12
I20220406-15:36:19.383(3)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
I20220406-15:36:19.384(3)?     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
I20220406-15:36:19.384(3)?     at Document.copy (models/lists.js:200:8)
I20220406-15:36:19.384(3)?     at models/swimlanes.js:146:12
I20220406-15:36:19.384(3)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
I20220406-15:36:19.385(3)?     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
I20220406-15:36:19.385(3)?     at Document.copy (models/swimlanes.js:142:23)
I20220406-15:36:19.385(3)?     at models/boards.js:598:16
I20220406-15:36:19.386(3)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
I20220406-15:36:19.386(3)?     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
I20220406-15:36:19.386(3)?     at Document.copy (models/boards.js:596:8)
I20220406-15:36:19.386(3)?     at MethodInvocation.copyBoard (server/publications/boards.js:332:20)
I20220406-15:36:19.387(3)?     at packages/check/match.js:118:15
I20220406-15:36:19.387(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20220406-15:36:19.387(3)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
I20220406-15:36:19.388(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
I20220406-15:36:19.388(3)?     at packages/ddp-server/livedata_server.js:719:19
I20220406-15:36:19.388(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20220406-15:36:19.388(3)?     at packages/ddp-server/livedata_server.js:717:46
I20220406-15:36:19.389(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20220406-15:36:19.389(3)?     at packages/ddp-server/livedata_server.js:715:46
I20220406-15:36:19.389(3)?     at new Promise (<anonymous>)
I20220406-15:36:19.390(3)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20220406-15:36:19.390(3)?     at packages/ddp-server/livedata_server.js:559:43
```
