### ISSUE TITLE
Server crash after update wekan from version 5 to 6

### ISSUE THREAD

**Issue by devagleo** [wekan/wekan#4504]
### Server Setup Information
Wekan version: Tested on 6.20
Operating System: Windows Server 2019
Deployment Method: Windows LAN Offline
Http frontend: Wekan Only
Node Version: 12.22.3
MongoDB Version: 4.2.14
Test Google Chrom 97.0.4692.71, Edge.

### Problem description
For a long time we worked on version 5.88, today we decided to upgrade to the current version 6.20
Version 6.20 starts, but after someone tries to open a web page, the server crashes.
Rollback to version 5.88 allows it to work and there is no error. Maybe some new variable is missing in .bat?

#### Reproduction Steps
Rollback to version 5.88 - work.
Upgrade to version 6.20 - server crash.

#### Logs 5.88
```
C:\Program Files\nodejs>node --unhandled-rejections=none C:\install\wekan-5.88\bundle\main.js
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application. You may also need to
install build tools to compile bcrypt. For more information see:
https://github.com/nodejs/node-gyp#installation
Presence started serverId=aCXeNsGWmbAZRTc4k
```

#### Logs 6.20
```
C:\Program Files\nodejs>node --unhandled-rejections=none C:\install\wekan-6.20\bundle\main.js
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application. You may also need to
install build tools to compile bcrypt. For more information see:
https://github.com/nodejs/node-gyp#installation
Presence started serverId=JGLojevvsBswSEz7w
C:\install\wekan-6.20\bundle\programs\server\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:375:7)
    at module (models/attachments.js:13:22)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at Module.moduleLink [as link] (C:\install\wekan-6.20\bundle\programs\server\npm\node_modules\meteor\modules\node_modules\reify\lib\runtime\index.js:52:22)
    at module (server/publications/attachments.js:1:24)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at require (packages\modules-runtime.js:258:21)
    at C:\install\wekan-6.20\bundle\programs\server\app\app.js:32035:1
    at C:\install\wekan-6.20\bundle\programs\server\boot.js:401:38
    at Array.forEach (<anonymous>)
    at C:\install\wekan-6.20\bundle\programs\server\boot.js:226:21
    at C:\install\wekan-6.20\bundle\programs\server\boot.js:464:7
    at Function.run (C:\install\wekan-6.20\bundle\programs\server\profile.js:280:14)
    at C:\install\wekan-6.20\bundle\programs\server\boot.js:463:13 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

[start-wekan-Impersonal.bat.txt](https://github.com/wekan/wekan/files/8638211/start-wekan-Impersonal.bat.txt)

**Comment by xet7** [comment]
Yes, this https://github.com/wekan/wekan/blob/master/start-wekan.bat#L16

Also please use Node.js version mentioned at https://wekan.github.io Download section.
