### ISSUE TITLE
WeKan Snap builds fail, and about multi-CPU-platform Snap

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4505]
Hi,
WeKan Snap builds fail. I'm posting here, because this is too long text for Snapcraft forum, I got error when posting.

Snapcraft forum post is here:
https://forum.snapcraft.io/t/wekan-snap-does-not-build-and-about-multi-cpu-platform-snaps/29898/2

WeKan Snap failing build:

[wekan-snap-build-log.txt](https://github.com/wekan/wekan/files/8649091/wekan-snap-build-log.txt)

Currently using this snapcraft.yaml:
https://github.com/wekan/wekan/blob/master/snapcraft.yaml

Here I have tried to create newer multi-CPU platform Snap, but it does not work properly yet, something is missing. It is trying to use prebuilt bundles, because currently using snapcraft to build bundle does not work:
https://github.com/wekan/wekan/blob/master/.future-snap/snapcraft.yaml

Here is how long time ago that kind of prebuilt bundle build used to work:
https://github.com/wekan/wekan-snap/blob/master/snapcraft.yaml

amd64 bundle is built with this script:
https://github.com/wekan/wekan/blob/master/rebuild-wekan.sh#L79

arm64 bundle is built with this script, it's from amd64 bundle and some additional changes:
https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-a.sh

s390x bundle is built with this script, it's from amd64 bundle and some additional changes:
https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-s.sh

ppc64el bundle is built with this script, it's from amd64 bundle and some additional changes:
https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-o.sh

If some of those MongoDB versions are not available, maybe I'll try to build them, if possible.

That amd64 bundle uses old caddy v1, but for that and others I plan to add caddy v2 from https://caddyserver.com

Any help?

**Comment by xet7** [comment]
Now after some changes to snapcraft.yaml at https://github.com/wekan/wekan , I get this error, when building with command `snapcraft`:

```
+ rm install_meteor.sh
+ rm -rf .build
+ chmod u+w app.json package-lock.json package.json scalingo.json settings.json
+ npm install
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/npm/lib/utils/unsupported.js
- /usr/share/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/npm/lib/utils/unsupported.js',
    '/usr/share/npm/bin/npm-cli.js'
  ]
}
```

**Comment by xet7** [comment]
Related #4524 and https://github.com/wekan/wekan/issues/4423#issuecomment-1112181784

**Comment by xet7** [comment]
When building at snapcraft.io , at bottom of build is there messages:
```
[23/May/2022:20:07:41 +0000] "CONNECT registry.npmjs.org:443 HTTP/1.1" 200 19404 "-" "-"
[23/May/2022:20:07:41 +0000] "CONNECT registry.npmjs.org:443 HTTP/1.1" 200 57735 "-" "-"
[23/May/2022:20:07:41 +0000] "CONNECT registry.npmjs.org:443 HTTP/1.1" 200 8240 "-" "-"
[23/May/2022:20:07:41 +0000] "CONNECT registry.npmjs.org:443 HTTP/1.1" 200 39251 "-" "-"

> fibers@5.0.1 install /build/wekan/parts/wekan/build/.build/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/build/wekan/parts/wekan/build/.build/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function ‘void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&))’:
../src/fibers.cc:355:87: warning: cast between incompatible function types from ‘uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’} to ‘v8::AccessorNameGetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’} [-Wcast-function-type]
  355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                                                       ^~~~~~
../src/fibers.cc:355:123: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} to ‘v8::AccessorNameSetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} [-Wcast-function-type]
  355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                                                                                           ^~~~~~
In file included from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
../src/fibers.cc: At global scope:
/usr/include/nodejs/src/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  573 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/usr/include/nodejs/src/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
  607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/fibers.cc:930:1: note: in expansion of macro ‘NODE_MODULE’
  930 | NODE_MODULE(fibers, init)
      | ^~~~~~~~~~~
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/build/wekan/parts/wekan/build/.build/bundle/programs/server/node_modules/fibers/build'
Installed in `/build/wekan/parts/wekan/build/.build/bundle/programs/server/node_modules/fibers/bin/linux-x64-64-glibc/fibers.node`
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/build/wekan/parts/wekan/build/.build/bundle/programs/server)
added 157 packages from 85 contributors and audited 157 packages in 7.216s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm ERR! Callback called more than once.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-23T20_07_41_415Z-debug.log
Failed to run 'override-build': Exit code was 1.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 196, in run
    self.build()
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 182, in build
    self.run_build_command(
  File "/usr/lib/python3/dist-packages/lpbuildd/target/operation.py", line 46, in run_build_command
    return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/lxd.py", line 533, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lxc', 'exec', 'lp-focal-amd64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/lpbuildd-git-proxy', '--env', 'SNAPPY_STORE_NO_CDN=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build-request-id": "lp-71510165", "build-request-timestamp": "2022-05-23T19:58:51Z", "build_url": "https://launchpad.net/~build.snapcraft.io/+snap/100453500e32d01a904a5c483a898df3/+build/1771602"}', '--env', 'SNAPCRAFT_BUILD_ENVIRONMENT=host', '--', '/bin/sh', '-c', 'cd /build/wekan && linux64 snapcraft']' returned non-zero exit status 2.
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=focal --arch=amd64 SNAPBUILD-1771602
Scanning for processes to kill in build SNAPBUILD-1771602
```

**Comment by xet7** [comment]
Hmm, probably npm install needs `--unsafe-perm` https://github.com/meteor/meteor/issues/9696#issuecomment-368834249 , I'll try

**Comment by xet7** [comment]
That `npm ERR! Callback called more than once` looks line network issues like at https://issues.apache.org/jira/browse/CB-11102

**Comment by xet7** [comment]
Hmm, I found Snap package that seems to have MongoDB 5, maybe trying to use that would work. I'll try.

https://github.com/juju/juju-db-snap/tree/5.3

https://snapcraft.io/juju-db

**Comment by xet7** [comment]
Maybe some Snap upgrades related info:

https://forum.snapcraft.io/t/call-for-testing-snapcraft-7/30201/15

https://forum.snapcraft.io/t/micro-howto-migrate-from-core20-to-core22/30188

**Comment by xet7** [comment]
Newest failed build log, from 20h ago.

[wekan-build-fail-2022-06-01.txt](https://github.com/wekan/wekan/files/8809705/wekan-build-fail-2022-06-01.txt)

**Comment by bbyszio** [comment]
Are there any news or ideas when we can have updates in snap again?

**Comment by xet7** [comment]
@bbyszio 

Current status is that Snap builds stop to [this error](https://forum.snapcraft.io/t/wekan-snap-does-not-build-and-about-multi-cpu-platform-snaps/29898/3):

> Your error is coming from dependencies specified in meteor. They are trying to install source-map-support but failing due to a hash checksum mismatch. I don’t know why the hashes are not matching, but the error is below:
>
> npm ERR! code EINTEGRITY
> npm ERR! sha512-2A3Rox3Zq2hUrDE/Vi3LEa/zLCOMj8F1HlMttze0jZmmQLzJjosp1mVtUCMbOTKIurqVm5xOatncI+6KJrngCg== integrity checksum failed when using sha512: wanted sha512-2A3Rox3Zq2hUrDE/Vi3LEa/zLCOMj8F1HlMttze0jZmmQLzJjosp1mVtUCMbOTKIurqVm5xOatncI+6KJrngCg== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
>
> The expected hash checksum is defined in .build/bundle/programs/server/npm-shrinkwrap.json after running the meteor build .build --directory --allow-superuser command, and it is the subsequent npm install --unsafe-perm that is failing.
>
> I don’t have a fix, but hopefully this will help you to get further…

I'll try without package-lock.json, or re-creating it. Also I'll try some way to upgrade database version.

**Comment by xet7** [comment]
@bbyszio 

I did get Snap builds working, but there is not yet migration from MongoDB 3.2.2 to MongoDB 5.x.

If you would like to try newest WeKan Snap, it's possible this way:

```
ssh yourserver@example.com

sudo su

cd /root

mkdir backup

cd backup

snap stop wekan.wekan

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/wekan/current/lib/x86_64-linux-gnu

export PATH="$PATH:/snap/wekan/current/bin"

snap get wekan > snap-settings.sh

mongodump --port 27019

snap stop wekan.mongodb

cp -pR /var/snap/wekan/common common

rm /var/snap/wekan/common/*.wt

rm /var/snap/wekan/common/WiredTige*

rm /var/snap/wekan/common/*.bson

rm /var/snap/wekan/common/*.lock

rm -rf /var/snap/wekan/common/journal

rm -rf /var/snap/wekan/common/diagnostic.data

snap refresh wekan --channel=latest/candidate --amend

snap start wekan

snap stop wekan.wekan

mongorestore --drop --port 27019

snap start wekan.wekan
```

**Comment by saschafoerster** [comment]
I had to manually install the mongodb-tools, so that this doesn't get an error: 

```
root@vm:~/backup# mongorestore --drop --port 27019
-bash: mongorestore: command not found
```
I installed mongo manually (Debian 11 Bullseye): 
```
wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -
 echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | tee /etc/apt/sources.list.d/mongodb-org.list
apt-get install mongodb-org-tools 
```
After that it worked out. I am not on Wekan 6.28 with Snap. 
Is there anything else to to, if "regular" snap updates are working again? Change from this maybe? 
`snap refresh wekan --channel=latest/candidate --amend`

**Comment by xet7** [comment]
@saschafoerster 

I can not release to stable before I have somehow figured out automatic migrations from MongoDB 3.x to 5.x. That's why using candidate reguires mongodump and mongorestore.

That candidate does have newest WeKan.

These lines above add paths to mongodump and mongorestore in current installed snap:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/wekan/current/lib/x86_64-linux-gnu

export PATH="$PATH:/snap/wekan/current/bin"
```

**Comment by saschafoerster** [comment]
After migration I tried to click on the button "attachment-move" in the admin backend. Result was that the CPU and file-system started heavy working till the VM was almost not reachable anymore. I stopped Wekan after some time being irresponsive and restarted. Upgrade was visible, but I had lost all attachments (they where not visible anymore). So I am trying to revert everything back to version 4.09 as I had before.

**Comment by xet7** [comment]
@saschafoerster 

If you did like instructions above, you have a copy of `cp -pR /var/snap/wekan/common` at your directory `/root/common`. Or alternatively, dump directory made with mongodump.

1. Stop WeKan:
```
sudo snap stop wekan
```
2. Delete everything from common
```
rm -rf /var/snap/wekan/common/*
```
3. Change to stable snap and stop wekan, and delete temporary files:
```
sudo snap refresh wekan --stable --amend
sudo snap stop wekan
rm -rf /var/snap/wekan/common/*
```
4. Copy all data back
```
rm -rf /var/snap/wekan
cp -pR /root/common/* /var/snap/wekan/common/
```
5. Start wekan
```
sudo snap start wekan
```

**Comment by saschafoerster** [comment]
I used this 
> 4. Copy all data back
> cp -pR /root/backup/common/* /var/snap/wekan/common/

Thanks for your help, as always, @xet7. At least now I know, that the direct upgrade from 6.09 to 6.28 has it's own problems, even if the snap-upgrade and the mongo-upgrade would work. :) I turned off auto-updating for now and call it a night.

**Comment by saschafoerster** [comment]
Oh, and my emails (and our clients emails) are filled with this kind of messages: 

`"undefined deleted attachment Image123.jpeg at card "Cardname" at list "Produktion" at swimlane Default at board "Boardname" https://wekan.url/b/link`

**Comment by xet7** [comment]
@saschafoerster 

Yes, I presume I need to move all migrations related code from WeKan to separate migration tool.

You pressed the magic button at Admin Panel, that moves all attachments from MongoDB database to filesystem. That's kind of CPU intensive.

Also there were migrations related code running, that moves attachments from MongoDB to filesystem and back. Changing from CollectionFS to Meteor-Files code.

**Comment by xet7** [comment]
And, I also presume I need to make changes to WeKan code so that it would work with any previous and current database structure.

That separate migration app could try to verify each migration step, that it's done slowly enough, without impacting running WeKan speed.

**Comment by xet7** [comment]
@saschafoerster 

Thanks for being so brave and testing this!

**Comment by xet7** [comment]
This is old issue. Sometime will happen more CPU/OS etc support, when it becomes possible.

**Comment by sh2515** [comment]
I get the following error after completing the process above and adding mongo-tools.
`2024-05-22T16:03:50.181+0000    error connecting to host: failed to connect to mongodb://localhost:27019/: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: localhost:27019, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp 127.0.0.1:27019: connect: connection refused }, ] }`
I have started the dB and wekan separately but this still fails with same error. This is using snap from the above process to upgrade from 6.09

**Comment by xet7** [comment]
@sh2515 

What process? Upgrading 6.09 does not work yet. I hope you did take backups before trying to upgrade.

Usually Snap is started with:
```
sudo snap start wekan
```
Or alternatively, starting parts of wekan:
```
sudo snap start wekan.mongodb

sudo snap start wekan.wekan
``

**Comment by sh2515** [comment]
The process I used was June 17 2022. 

I understand that there is no migration yet due to mongodb 3 and mongodb 5 which is why it has stayed at 6.09.

However I have tried to manually do the update as described above but found that error.

I have since changed the mogodb to port 27019 and this now brings up the following error
`2024-05-22T16:20:08.150+0000    Failed: error connecting to db server: no reachable servers`

I tried both of the above ways to bring wekan back up but has failed.

I understand that the issue is with migration from mogodb 3 to 5. However for those that are new to the wekan can they just install the latest version? If so is it a stable version?

**Comment by xet7** [comment]
@sh2515 

For new users, info is here for newest version:

https://github.com/wekan/wekan/discussions/5385

I added it to also top of these wiki pages:

https://github.com/wekan/wekan-snap/wiki

https://github.com/wekan/wekan-snap/wiki/Install

Yes, I do know, people are impatient, and are waiting for automatic upgrade.

**Comment by sh2515** [comment]
Just gone through the eprocess 27th of June 22 to restore, but has failed.

The
`cp -pR /root/common/* /var/snap/wekan/common/`
Is wrong and you need to recreate the `wekan` and `common` folder otherwise it will error out
`mkdir /var/snap/wekan/ && mkdir /var/snap/common/ `
However I still get 503 server is temporarily unavailable.

**Comment by xet7** [comment]
@sh2515 

What version of wekan Snap ?

```
sudo snap list
``

**Comment by xet7** [comment]
From Snap Stable 6.09 Snap, MongoDB raw database files are only compatible with MongoDB 3.2.22 version of 6.09 Snap. They are not compatible with WeKan v7.x Snap Candidate.

**Comment by sh2515** [comment]
> @sh2515
> 
> What version of wekan Snap ?
> 
> ```
> sudo snap list
> ```

Wekan 6.09 is listed

I went from stable to the latest unstable snap. Thenm when that didn't work I have tried to revert back to 6.09 stable, which failed.
