### ISSUE TITLE
Upgrade Wekan (docker) to 6.29 : I can't add attachment

### ISSUE THREAD

**Issue by xavier-GitHub76** [wekan/wekan#4586]
Hello,

I upgrade Wekan (docker) to  : 6.29
I can't add attachment.
My database is mongo 4.4.4

Logs (application) : 
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Mon Jul 11 2022 08:13:03 GMT+0000 (Coordinated Universal Time)","time":{"$date":1657527183622},"level":"info"}
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Exception while invoking method '_FilesCollectionStart_attachments' TypeError: Cannot read property 'replace' of undefined
    at FilesCollection.namingFunction (models/attachments.js:26:48)
    at FilesCollection._prepareUpload (packages/ostrio:files/server.js:990:26)
    at MethodInvocation.FilesCollection._methods.<computed> (packages/ostrio:files/server.js:849:33)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1882:18)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43

Thanks for your help.
Regards

**Comment by xavier-GitHub76** [comment]
The bug is not present with application downgrade to 6.28 (database unchanged).

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/4585#issuecomment-1180385281
