### ISSUE TITLE
Wekan 6.30 Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by joyinfo** [wekan/wekan#4591]
The error occurs in login page.

mermaid.esm.min.mjs:2 Uncaught RangeError: Maximum call stack size exceeded.
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1079114)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2:1079114)
    at HTMLBodyElement.wrapper (dombackend.js:47:28)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1079114)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2:1079114)
    at HTMLBodyElement.wrapper (dombackend.js:47:28)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1079114)
    at jQuery.fn.init.find (mermaid.esm.min.mjs:2:1079114)
    at HTMLBodyElement.wrapper (dombackend.js:47:28)
    at Function.Sizzle [as find] (mermaid.esm.min.mjs:2:1079114)

<img width="1358" alt="Screen Shot 2022-07-14 at 14 56 11" src="https://user-images.githubusercontent.com/20535391/178920558-d955980f-2307-46d6-8124-ff6a65da8e9d.png">

**Comment by joyinfo** [comment]
@xet7 if I did as commits below:
  [Part 1](https://github.com/wekan/wekan/commit/23a403644c7db44392d4b0498ee0fc85c504d974),
  [Part 2](https://github.com/wekan/wekan/commit/998d2f5b445b6bf2bc6cd16beac7231a0cf94fc3),
  [Part 3](https://github.com/wekan/wekan/commit/443b40cff3cf507887c20639224ac1447acfaf88).

The error will become in modules.js:
<img width="1365" alt="Screen Shot 2022-07-14 at 15 00 19" src="https://user-images.githubusercontent.com/20535391/178921317-cdd4a7ba-0444-4200-93c6-708b6dfdd731.png">

**Comment by xet7** [comment]
Try newest WeKan.

**Comment by aboire** [comment]
I have the same error with version 6.54, trying the workaround or without, increasing maxTextSize does not change anything for me
