### ISSUE TITLE
Validate attachment error at PR Meteor files 2.2.1 fixes + attachment view

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4640]
@mfilser 

After adding PR [Meteor files 2.2.1 fixes + attachment view](https://github.com/wekan/wekan/pull/4638)

When adding attachment image, I get this error:
```
I20220816-21:53:51.728(3)? Exception in defer callback: ReferenceError: validateAttachment is not defined
I20220816-21:53:51.730(3)?     at MethodInvocation.validateAttachmentAndMoveToStorage (models/attachments.js:195:7)
I20220816-21:53:51.731(3)?     at packages/check/match.js:118:15
I20220816-21:53:51.731(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220816-21:53:51.732(3)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
I20220816-21:53:51.732(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1882:18)
I20220816-21:53:51.733(3)?     at packages/ddp-server/livedata_server.js:1803:15
I20220816-21:53:51.733(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220816-21:53:51.734(3)?     at packages/ddp-server/livedata_server.js:1801:36
I20220816-21:53:51.734(3)?     at new Promise (<anonymous>)
I20220816-21:53:51.735(3)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1800:12)
I20220816-21:53:51.735(3)?     at Server.apply (packages/ddp-server/livedata_server.js:1739:26)
I20220816-21:53:51.736(3)?     at Server.call (packages/ddp-server/livedata_server.js:1721:17)
I20220816-21:53:51.736(3)?     at models/attachments.js:91:31
I20220816-21:53:51.737(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220816-21:53:51.737(3)?     at packages/meteor.js:555:25
I20220816-21:53:51.738(3)?     at runWithEnvironment (packages/meteor.js:1320:24)
I20220816-21:53:51.738(3)?  => awaited here:
I20220816-21:53:51.738(3)?     at Promise.await (/home/wekan/.meteor/packages/promise/.0.12.0.1em0tku.tme++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20220816-21:53:51.739(3)?     at Server.apply (packages/ddp-server/livedata_server.js:1752:22)
I20220816-21:53:51.739(3)?     at Server.call (packages/ddp-server/livedata_server.js:1721:17)
I20220816-21:53:51.739(3)?     at models/attachments.js:91:31
I20220816-21:53:51.739(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220816-21:53:51.740(3)?     at packages/meteor.js:555:25
I20220816-21:53:51.740(3)?     at runWithEnvironment (packages/meteor.js:1320:24)
```

**Comment by mfilser** [comment]
@xet7 
Oh, sorry, i only checked uploading the file and didn't look at the console. Thanks for your quick fix.
