### ISSUE TITLE
cronHistory notification cleanup duplicate key

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4642]
It seems somehow I just got duplicate key:
```
Exception in setTimeout callback: MongoServerError: E11000 duplicate key error collection: wekan.cronHistory index: intendedAt_1_name_1 dup key: { intendedAt: new Date(1660683600000), name: "notification_cleanup" }
    at /home/wekan/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/insert.js:51:33
    at /home/wekan/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection_pool.js:273:25
    at handleOperationResult (/home/wekan/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/server.js:363:9)
    at MessageStream.messageHandler (/home/wekan/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:474:9)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/home/wekan/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
    at MessageStream._write (/home/wekan/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
```

**Comment by xet7** [comment]
This duplicate-key error came from the old SyncedCron-based `notification_cleanup` job writing to the `wekan.cronHistory` collection (unique index `intendedAt_1_name_1`). That code path no longer exists: notification cleanup was rewritten as a plain `Meteor.setInterval` job (server/models/users.js, `runNotificationCleanup`/`startNotificationCleanup` around lines 1149-1192) with no SyncedCron history collection, and the project migrated off percolate:synced-cron entirely. The `cronHistory` collection and its `intendedAt_1_name_1` index are gone from the codebase, so this E11000 error can no longer occur. Closing as fixed; please reopen if you see it again on the latest release.
