### ISSUE TITLE
Attachments not visible

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4644]
Attachment is at MongoDB database on newest WeKan Snap Candidate, newest Meteor, Node.js 14.x, MongoDB 5.x.

Link to attachment at minicard:

```
<div class="minicard-cover" style="background-image: url('/cdn/storage/attachments/mH2oPrY3Sx2oFNuDA/original/mH2oPrY3Sx2oFNuDA.png?dummyReloadAfterSessionEstablished=abcd1234');"></div>
```
Attachment details at database. File is at database, not at filesystem.
```
{
  "_id": "mH2oPrY3Sx2oFNuDA",
  "name": "UCS-nested-icons.png",
  "extension": "png",
  "ext": "png",
  "extensionWithDot": ".png",
  "path": "/var/snap/wekan-gantt-gpl/common/files/mH2oPrY3Sx2oFNuDA-UCS-nested-icons.png",
  "meta": {
    "boardId": "cxw7o5A4iemFQiwhP",
    "cardId": "CrHbsSdzqGfFGzsH8",
    "listId": "PDkxvnukZfb2RdTcG",
    "swimlaneId": "fP8wfXkjBzqs22gYE",
    "source": "import"
  },
  "type": "image/png",
  "mime": "image/png",
  "mime-type": "image/png",
  "size": 52022,
  "userId": "jmBkZ4KqncQuKWM9r",
  "versions": {
    "original": {
      "path": "/data/attachments/mH2oPrY3Sx2oFNuDA-original-UCS-nested-icons.png",
      "size": 52022,
      "type": "image/png",
      "extension": "png",
      "meta": {},
      "storage": "fs"
    }
  },
  "_downloadRoute": "/cdn/storage",
  "_collectionName": "attachments",
  "isVideo": false,
  "isAudio": false,
  "isImage": true,
  "isText": false,
  "isJSON": false,
  "isPDF": false,
  "_storagePath": "/var/snap/wekan-gantt-gpl/common/files/mH2oPrY3Sx2oFNuDA-UCS-nested-icons.png"
}
```
Avatar icon is also broken:
```
https://example.com/cdn/storage/avatars/fQALJcbzTgvMssHtL/original/fQALJcbzTgvMssHtL.jpg?auth=false&brokenIsFine=true
```
This is example of cfs.avatars.filerecord:
```
db.getCollection("cfs.avatars.filerecord").update({ _id: "abcd1234" }, {
    $set: {
        "original": {
            "name": "aaaaabbbbb.jpg",
            "updatedAt": ISODate("2019-07-02T16:52:43.572+03:00"),
            "size": 5200,
            "type": "image/jpeg"
        },
        "userId": "aaaabbbbb",
        "uploadedAt": ISODate("2020-07-02T15:54:42.106+03:00"),
        "copies": {
            "avatars": {
                "name": "aaaaabbbbb.jpg",
                "type": "image/jpeg",
                "size": 5200,
                "key": "aaaabbbbb",
                "updatedAt": ISODate("2020-07-02T16:54:42.113+03:00"),
                "createdAt": ISODate("2020-07-02T16:54:42.113+03:00")
            }
        }
    }
})
```
This is example of cfs.attachments.filerecord:
```
db.getCollection("cfs.attachments.filerecord").update({ _id: "zyMDW3ECnxvG57u9w" }, {
    $set: {
        "original": {
            "type": "image/png",
            "size": 585972,
            "updatedAt": ISODate("2018-10-31T10:43:36.000+02:00"),
            "name": "Screenshot_201.png"
        },
        "boardId": "wn6jSd",
        "cardId": "AxiDN33",
        "userId": "9ztgWFy",
        "uploadedAt": ISODate("2020-06-12T01:49:03.886+03:00"),
        "copies": {
            "attachments": {
                "name": "Screenshot_201.png",
                "type": "image/png",
                "size": 585972,
                "key": "5ee2",
                "updatedAt": ISODate("2020-06-12T01:49:04.638+03:00"),
                "createdAt": ISODate("2020-06-12T01:49:04.638+03:00")
            }
        }
    }
})
```
According to nosqlbooster, attachment files are at:
- attachments.files (355)
- avatars.files (12)
- cfs_gridfs.attachments.files (4.4K)
- cfs_gridfs.avatars.files (260)

Example of attachments.files:
```
{
  "_id": "abcde",
  "length": 415386,
  "chunkSize": 261120,
  "uploadDate": "2020-05-15T09:21:34.633Z",
  "filename": "example.xlsx",
  "contentType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "metadata": {
    "boardId": "abcde1234",
    "swimlaneId": "abcde1234",
    "listId": "abcde1234",
    "cardId": "abcde1234",
    "versionName": "original",
    "fileId": "abcde1234"
  }
}
``` 
Example of avatars.files:
```
{
  "_id": "abcd1234",
  "length": 27094,
  "chunkSize": 261120,
  "uploadDate": "2022-02-03T12:19:51.396Z",
  "filename": "image.jpg",
  "md5": "abcd1234",
  "contentType": "image/jpeg",
  "metadata": {
    "versionName": "original",
    "fileId": "abcd1234"
  }
}
```
To be continued...

**Comment by xet7** [comment]
Filenames have:
- Spaces
- Russian/Scandinavian/Chinese etc characters
- URLencoding on some filenames
- etc

**Comment by mfilser** [comment]
I read above something about `cfs`. This war the "old" file storage implementation, or?

Also at the first JSON you mentioned the attachment is stored at database, but:
- storage = "fs"
- gridFsFileId is missing

Maybe it not stored in database, but at filesystem?
If all JSON above is from the same Wekan instance i think the migration from CFS to Meteor-Files didn't finish...

**Comment by xet7** [comment]
Example is WeKan roadmap board, there images and avatars are not visible, and I don't know what URL has correct images:

https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license

**Comment by mfilser** [comment]
Avatars are only stored at database

**Comment by xet7** [comment]
I removed 2 ostrio finished migration records from database, stopped and started wekan, and attachments are not yet visible

**Comment by mfilser** [comment]
Do you still have the migration log from the server console ?

**Comment by xet7** [comment]
@mfilser 

At /var/log/syslog are many errors like this:


```
Aug 17 00:45:30 web wekan_wekanteam.wekan[73599]: error: error running snapctl: get which option?
Aug 17 00:45:30 web wekan_wekanteam.wekan[71411]: NODE_OPTIONS=--max_old_space_size=4096 (default value)
Aug 17 00:45:30 web wekan_wekanteam.wekan[71411]: MONGO_URL=mongodb://127.0.0.1:27025/wekan
Aug 17 00:45:35 web wekan_wekanteam.wekan[73604]: > Starting migrate-attachments-collectionFS-to-ostrioFiles migration.
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]: > Finishing migrate-attachments-collectionFS-to-ostrioFiles migration.
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]: > Starting migrate-avatars-collectionFS-to-ostrioFiles migration.
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]: > Finishing migrate-avatars-collectionFS-to-ostrioFiles migration.
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]: Error:  /var/snap/wekan/common/files/avatars/tNp9iikDJPFPjTStG-Happyface.PNG Error [MongoError]: file with id 62fc1002ae38e81f85e008dd not opened for writing
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at Function.MongoError.create (/snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at handleCallback (/snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at handleCallback (/snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at handleCallback (/snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at setCursorNotified (/snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at queryCallback (/snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]:   driver: true
Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]: }

Aug 17 00:45:38 web wekan_wekanteam.wekan[73604]: Error:  /var/snap/wekan/common/files/avatars/tNp9iikDJPFPjTStG-Happyface.PNG Error [MongoError]: file with id 62fc1002ae38e81f85e008dd not opened for writing

Aug 17 00:45:39 web wekan_wekanteam.wekan[73604]: Error:  /var/snap/wekan/common/files/attachments/wjwC3WTpv2sRKQBPQ-Доступ в HPSM для сотрудников АНО ЦАРСС.msg Error [MongoError]: file with id 62fc1000ae38e81f85e00892 not opened for writing
```

And many Duplicate keys:
```
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]: MongoServerError: E11000 duplicate key error collection: wekan.attachments index: _id_ dup key: { _id: "czLvofmc2kAZ88yNf" }
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/insert.js:51:33
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection_pool.js:273:25
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at handleOperationResult (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/server.js:363:9)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at MessageStream.messageHandler (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:474:9)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at MessageStream.emit (events.js:400:28)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at MessageStream.emit (domain.js:475:12)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at processIncomingData (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at MessageStream._write (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at writeOrBuffer (internal/streams/writable.js:358:12)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at Socket.ondata (internal/streams/readable.js:731:22)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at Socket.emit (events.js:400:28)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at Socket.emit (domain.js:475:12)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at addChunk (internal/streams/readable.js:293:12)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at readableAddChunk (internal/streams/readable.js:267:9)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:   index: 0,
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:   code: 11000,
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:   keyPattern: { _id: 1 },
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]:   keyValue: { _id: 'czLvofmc2kAZ88yNf' }
Aug 17 00:46:17 web wekan_wekanteam.wekan[73604]: }

Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]: MongoServerError: E11000 duplicate key error collection: wekan.avatars index: _id_ dup key: { _id: "vRHD53To2xDNDRpFc" }
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/insert.js:51:33
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at /snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection_pool.js:273:25
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at handleOperationResult (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/server.js:363:9)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at MessageStream.messageHandler (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:474:9)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at MessageStream.emit (events.js:400:28)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at MessageStream.emit (domain.js:475:12)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at processIncomingData (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at MessageStream._write (/snap/wekan/2167/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at writeOrBuffer (internal/streams/writable.js:358:12)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at Socket.ondata (internal/streams/readable.js:731:22)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at Socket.emit (events.js:400:28)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at Socket.emit (domain.js:475:12)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at addChunk (internal/streams/readable.js:293:12)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at readableAddChunk (internal/streams/readable.js:267:9)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:   index: 0,
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:   code: 11000,
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:   keyPattern: { _id: 1 },
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]:   keyValue: { _id: 'vRHD53To2xDNDRpFc' }
Aug 17 00:45:40 web wekan_wekanteam.wekan[73604]: }
```

**Comment by mfilser** [comment]
@xet7 
Strange, i don't have any idea why there are "duplicate key" error's. Do you know which code generates the id's ?

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan/pull/4638#issuecomment-1227643306

Not seeing attachments is #4644 , it's because some attachment migrations from CollectionFS to Meteor-Files are incomplete, attachments have wrong URLs, so they are not visible. Attachments are still at MongoDB database, and can be viewed with [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup#using-nosqlbooster-closed-source-mongodb-gui-with-wekan-snap-to-edit-mongodb-database).
