### ISSUE TITLE
wekan mongo error

### ISSUE THREAD

**Issue by g-giordano** [wekan/wekan#4664]
I have run 
git clone https://github.com/wekan/wekan.git
edit ROOT_URL on docker-compose.yml with your ip
cd wekan
docker-compose up -d
but I have this error

 MongoServerSelectionError: getaddrinfo EAI_AGAIN wekandb
    at Timeout._onTimeout (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'wekandb:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'wekandb', port: 27017 },
        address: 'wekandb:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 172948752,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo EAI_AGAIN wekandb
            at connectionFailureError (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:381:20)
            at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
            at Object.onceWrapper (events.js:520:26)
            at Socket.emit (events.js:400:28)
            at emitErrorNT (internal/streams/destroy.js:106:8)
            at emitErrorCloseNT (internal/streams/destroy.js:74:3)
            at processTicksAndRejections (internal/process/task_queues.js:82:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}
/build/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoServerSelectionError: getaddrinfo EAI_AGAIN wekandb
    at Timeout._onTimeout (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'wekandb:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'wekandb', port: 27017 },
        address: 'wekandb:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 172980768,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo EAI_AGAIN wekandb
            at connectionFailureError (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:381:20)
            at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
            at Object.onceWrapper (events.js:520:26)
            at Socket.emit (events.js:400:28)
            at emitErrorNT (internal/streams/destroy.js:106:8)
            at emitErrorCloseNT (internal/streams/destroy.js:74:3)
            at processTicksAndRejections (internal/process/task_queues.js:82:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}
/build/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoServerSelectionError: getaddrinfo EAI_AGAIN wekandb
    at Timeout._onTimeout (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'wekandb:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'wekandb', port: 27017 },
        address: 'wekandb:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 173012852,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo EAI_AGAIN wekandb
            at connectionFailureError (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:381:20)
            at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
            at Object.onceWrapper (events.js:520:26)
            at Socket.emit (events.js:400:28)
            at emitErrorNT (internal/streams/destroy.js:106:8)
            at emitErrorCloseNT (internal/streams/destroy.js:74:3)
            at processTicksAndRejections (internal/process/task_queues.js:82:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}
Can you help me?

**Comment by g-giordano** [comment]
I have find the problem:
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

TKS

**Comment by mfilser** [comment]
Maybe it's the same as #4321 ?

**Comment by g-giordano** [comment]
> Maybe it's the same as https://github.com/wekan/wekan/issues/4321 ? 
Yes sir.

**Comment by xet7** [comment]
Moved to #4321
