### ISSUE TITLE
[API] Edit card function does nothing

### ISSUE THREAD

**Issue by gu1ll0me** [wekan/wekan#4701]
I try to figure how to edit an existing card with the API using Docker image v6.49 and the Wekan API Python CLI (api.py) but the `editcard` command do nothing with the logs showing:

```
TypeError: req.body.hasOwnProperty is not a function
    at models/cards.js:3505:20
    at packages/simple_json-routes.js:100:9
```

However, the `addcard` command works great. The card is added correctly in the board.

Is there something more I can provide to help to solve this one ?

Thank you.

**Comment by HEMGDevelopment** [comment]
Hi, I am having the same problem.
@xet7 have you found a solution?
Thanks
Kind regard
Tomas

**Comment by xet7** [comment]
@HEMGDevelopment 

I looked at it and fixed it. Fix will be in upcoming WeKan v6.71.

Example how to use:

`api.py` at https://github.com/wekan/wekan
```
./api.py editcard BOARDID LISTID CARDID NEWCARDTITLE NEWCARDDESCRIPTION

./api.py editcard 4KE6ru4XfZTGyZovB nw5HigXFZHyavJQaH At6hq7HSe3bccGgo3 "Changed Card" "This card has been changed"
```
