### ISSUE TITLE
Bug: Export Board menu item - hardcoded host URL breaks with docker

### ISSUE THREAD

**Issue by srinathh** [wekan/wekan#472]
The `Export Board` menu item contains a hardcoded URL of the form `<root url>/api/boards/<board id>?authToken=<auth-token>` rather than using a relative URL.

This breaks when using Wekan on docker locally since the `<root url>` inside the docker container points to `http://127.0.0.1` whereas from outside the container, I need to access via something like `http://192.168.99.100:8081`.

If i copy the full URL and replace the `http://127.0.0.1` with `http://192.168.99.100:8081` it works as expected. I guess the simplest fix would be to use relative URLs

**Comment by mquandalle** [comment]
Did you set the `ROOT_URL` environment variable when launching the Wekan Docker container?

**Comment by srinathh** [comment]
Yup - it has been set to http://127.0.0.1

**Comment by mquandalle** [comment]
You need to set the `ROOT_URL` to the publicly accessible url, the one that you are going to type in your browser.

**Comment by mfaure** [comment]
On my instance I did configure it (`ROOT_URL=http://todo.m2t.ovh/`). But it does not work. It is visible when I get the link (URL) of a card: it is still http://127.0.0.1:8181/b/xyz

**Comment by mquandalle** [comment]
It’s weird, because at least on `devel` I’m able to customize this absolute card URL by using the `ROOT_URL` env variable.

**Comment by xavierpriour** [comment]
@mfaure it seems to me you're talking about a different thing - the URL you mention is not an export URL (export URL mention /api/boards/, yours is /b/). Do you confirm you have a problem when **exporting a board** or do you have a different issue?

**Comment by mfaure** [comment]
@mquandalle I'm still at v0.9 (upgrade is planned), I will check and tell you once the upgrade is done
@xavierpriour you're right ! I made a confusion between export URL and card URL (sorry)

**Comment by srinathh** [comment]
I made the change but since I made the change, Wekan's unable to connect to the MongoDB, even if i change the setting back to 127.0.0.1. MongoDB actually seems to be running properly in its container.
```
=> Starting meteor app on port:80
/built_app/programs/server/node_modules/fibers/future.js:278
throw(ex);
      ^
Error: failed to connect to [db:27017]
    at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at Package (packages/idmontie_migrations/migrations.js:23:1)
    at /built_app/programs/server/packages/idmontie_migrations.js:254:4
    at /built_app/programs/server/packages/idmontie_migrations.js:261:3
    at /built_app/programs/server/boot.js:242:10
    - - - - -
    at [object Object].<anonymous> (/built_app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/built_app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/built_app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)
```

**Comment by mquandalle** [comment]
The link to MongoDB is done using the `MONGO_URL` environment variable. Did you set it?

**Comment by srinathh** [comment]
Yup it is. I'll try resetting with a fresh docker image.

**Comment by vrms** [comment]
> This breaks when using Wekan on docker locally since the <root url> inside the docker container points to `http://127.0.0.1` whereas from outside the container, I need to access via something like `http://192.168.99.100:8081`

seems the same happens when running wekan from the new (I assume) snap package

**Comment by xet7** [comment]
@vrms 

You need to setup correct root url also in snap, and use your computer's IP address or URL, not localhost:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys
