### ISSUE TITLE
Bug: infrequent exception during invitation a new user to board via mail - TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by rgoltz** [wekan/wekan#473]
Hi,

I'm using wekan 0.10.1 (mongodb: v2.4.14 / node: v0.10.40). While I'm trying to add a new user -by typing a mail-address- to an existing board, I'm getting frequently:

```
Exception while invoking method 'inviteUserToBoard' TypeError: Cannot read property 'title' of undefined
    at Object.<anonymous> (models/activities.js:69:27)
    at packages/matb33_collection-hooks/insert.js:35:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at after (packages/matb33_collection-hooks/insert.js:34:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:101:1)
    at Object.Lists.after.update.Activities.insert.userId (models/lists.js:90:16)
    at packages/matb33_collection-hooks/insert.js:35:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at after (packages/matb33_collection-hooks/insert.js:34:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
```

On UI side I can see "500" within a yellow box.

From my testing I would say, it's a timing issue: If I'm entering the address and click on "Invite via Email" really fast, I can see the Exception. If I wait a small amount of time (e.g. 2 sec) and then clicking on "Invite via Email" the mail is sent successfully.

I'm using a gmail-account on this installation along following parameter: `MAIL_URL='smtp://address@gmail.com:pwd@smtp.gmail.com:465/'` (fyi)

Please advise, if you need more information from my side. It's my 1st post on github ;-)

Thanks a lot - It's a great project!
Robert

**Comment by mquandalle** [comment]
Thank you for the detailed bug report. We should be able to figure out with that.

**Comment by rgoltz** [comment]
Hi.

just for your information: I saw the same error/exception in the moment a user trying to create a new account: 

```
Exception while invoking method 'ATCreateUserServer' TypeError: Cannot read property 'title' of undefined
    at Object.<anonymous> (models/activities.js:69:27)
    at packages/matb33_collection-hooks/insert.js:35:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at after (packages/matb33_collection-hooks/insert.js:34:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:101:1)
    at Object.Lists.after.update.Activities.insert.userId (models/lists.js:90:16)
    at packages/matb33_collection-hooks/insert.js:35:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at after (packages/matb33_collection-hooks/insert.js:34:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
```

Best regards,
Robert

**Comment by Jonarod** [comment]
Hello.
Same problem here when creating new user.
I made a `meteor reset` in order to wipe the database first. Then, after restarting the project I tried to signup with a new user and got the same error message the console, and on the UI side I get a `internal server error` and the page just stays in /signup

It is important to mention that the user DO gets created anyways: I have verified it through minimongo, and I am able to connect with the user.
What is NOT happening is:
- redirection to / path
- email confirmation link
- cookie to keep user registered

Finally, I found that commenting this section in models/Activities.js line 69, bypasses the problem:

`    
if (activity.boardId) {
      board = activity.board();
      params.board = board.title;      
      title = 'act-withBoardTitle';
      params.url = board.absoluteUrl();
}
`
I understand that the variable board is defined by activity.board() which is undefined at users' creation but... why is that called at users' creation anyways ??? 
Is there a way we could redefine this function in the context of users' signup / invitation ??

**Comment by icharlie** [comment]
@Jonarod because user creation triggers welcome-board creation and welcome-board will create two lists 'Basics', 'Advanced'.

    // XXX i18n
    Users.after.insert((userId, doc) => {
      const ExampleBoard = {
        title: 'Welcome Board',
        userId: doc._id,
        permission: 'private',
      };

      // Insert the Welcome Board
      Boards.insert(ExampleBoard, (err, boardId) => {

        ['Basics', 'Advanced'].forEach((title) => {
          const list = {
            title,
            boardId,
            userId: ExampleBoard.userId,

            // XXX Not certain this is a bug, but we except these fields get
            // inserted by the Lists.before.insert collection-hook. Since this
            // hook is not called in this case, we have to dublicate the logic and
            // set them here.
            archived: false,
            createdAt: new Date(),
          };

          Lists.insert(list);
        });
      });
    });

Currently, welcome-board creation is failing because SimpleSchema validations run before the **Boards.before.insert** hook.

There are some related issues reported in meteor-collection-hooks and meteor-collection2.
https://github.com/aldeed/meteor-collection2/issues/226
https://github.com/matb33/meteor-collection-hooks/issues/167
https://github.com/matb33/meteor-collection-hooks/issues/153

I have tried matb33's suggestion in https://github.com/aldeed/meteor-collection2/issues/226 but it doesn't work on my machine.

**Comment by delapecci** [comment]
After some debugging, i found that the error comes from some mismatch of mongo collection schema:

1. Boards schema has some required properties
2. Boards.userId => Boards.members[{userId: xxx, isAdmin:true, isActive:true}]

**Comment by AlexanderS** [comment]
This should be fixed with #616.

**Comment by mquandalle** [comment]
This was indeed fixed by #616, thank you again @AlexanderS.

**Comment by rgoltz** [comment]
Hi @mquandalle @AlexanderS .
Just now, I installed the pre-release of wekan version: wekan-0.11.0-**rc1**. This wekan installation was started aganst a empty mongo-db. Below you can find the output of mongo-db and also the exception:

```

Thu Jul 21 00:41:21.640 [initandlisten] MongoDB starting : pid=11838 port=27017 dbpath=/data/db/ 32-bit host=goltz1
Thu Jul 21 00:41:21.640 [initandlisten] db version v2.4.14
Thu Jul 21 00:41:21.640 [initandlisten] git version: 05bebf9ab15511a71bfbded684bb226014c0a553
Thu Jul 21 00:41:21.640 [initandlisten] build info: Linux 2.6.21.7-2.fc8xen #1 SMP Fri Feb 15 12:39:36 EST 2008 i686 BOOST_LIB_VERSION=1_49
Thu Jul 21 00:41:21.640 [initandlisten] allocator: system
Thu Jul 21 00:41:21.640 [initandlisten] options: {}
Thu Jul 21 00:41:21.721 [initandlisten] waiting for connections on port 27017
Thu Jul 21 00:41:21.721 [websvr] admin web console waiting for connections on port 28017
Thu Jul 21 00:41:47.963 [initandlisten] connection accepted from 127.0.0.1:38770 #1 (1 connection now open)
Thu Jul 21 00:41:47.971 [conn1] end connection 127.0.0.1:38770 (0 connections now open)
Thu Jul 21 00:41:47.973 [initandlisten] connection accepted from 127.0.0.1:38771 #2 (1 connection now open)
Thu Jul 21 00:41:47.973 [initandlisten] connection accepted from 127.0.0.1:38772 #3 (2 connections now open)
Thu Jul 21 00:41:47.973 [initandlisten] connection accepted from 127.0.0.1:38773 #4 (3 connections now open)
Thu Jul 21 00:41:47.974 [initandlisten] connection accepted from 127.0.0.1:38774 #5 (4 connections now open)
Thu Jul 21 00:41:47.974 [initandlisten] connection accepted from 127.0.0.1:38775 #6 (5 connections now open)
Thu Jul 21 00:41:47.995 [conn6] allocating new ns file /data/db/wekan.ns, filling with zeroes...
Thu Jul 21 00:41:48.247 [FileAllocator] allocating new datafile /data/db/wekan.0, filling with zeroes...
Thu Jul 21 00:41:48.247 [FileAllocator] creating directory /data/db/_tmp
Thu Jul 21 00:41:48.247 [FileAllocator] done allocating datafile /data/db/wekan.0, size: 16MB,  took 0 secs
Thu Jul 21 00:41:48.247 [FileAllocator] allocating new datafile /data/db/wekan.1, filling with zeroes...
Thu Jul 21 00:41:48.247 [FileAllocator] done allocating datafile /data/db/wekan.1, size: 32MB,  took 0 secs
Thu Jul 21 00:41:48.248 [conn6] build index wekan.users { _id: 1 }
Thu Jul 21 00:41:48.248 [conn6] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.248 [conn6] info: creating collection wekan.users on add index
Thu Jul 21 00:41:48.248 [conn6] build index wekan.users { username: 1 }
Thu Jul 21 00:41:48.248 [conn6] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.248 [conn6] insert wekan.system.indexes ninserted:1 keyUpdates:0 locks(micros) w:253412 253ms
Thu Jul 21 00:41:48.250 [conn5] build index wekan.users { emails.address: 1 }
Thu Jul 21 00:41:48.250 [conn5] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.251 [conn4] build index wekan.users { services.resume.loginTokens.hashedToken: 1 }
Thu Jul 21 00:41:48.251 [conn4] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.252 [conn3] build index wekan.users { services.resume.loginTokens.token: 1 }
Thu Jul 21 00:41:48.253 [conn3] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.255 [conn2] build index wekan.users { services.resume.haveLoginTokensToDelete: 1 }
Thu Jul 21 00:41:48.255 [conn2] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.256 [conn6] build index wekan.users { services.resume.loginTokens.when: 1 }
Thu Jul 21 00:41:48.256 [conn6] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.571 [conn5] build index wekan.users { services.email.verificationTokens.token: 1 }
Thu Jul 21 00:41:48.571 [conn5] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.573 [conn4] build index wekan.users { services.password.reset.token: 1 }
Thu Jul 21 00:41:48.573 [conn4] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.577 [conn3] build index wekan.meteor_accounts_loginServiceConfiguration { _id: 1 }
Thu Jul 21 00:41:48.577 [conn3] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:48.577 [conn3] info: creating collection wekan.meteor_accounts_loginServiceConfiguration on add index
Thu Jul 21 00:41:48.577 [conn3] build index wekan.meteor_accounts_loginServiceConfiguration { service: 1 }
Thu Jul 21 00:41:48.577 [conn3] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.242 [initandlisten] connection accepted from 127.0.0.1:38778 #7 (6 connections now open)
Thu Jul 21 00:41:49.251 [conn7] end connection 127.0.0.1:38778 (5 connections now open)
Thu Jul 21 00:41:49.253 [initandlisten] connection accepted from 127.0.0.1:38779 #8 (6 connections now open)
Thu Jul 21 00:41:49.254 [initandlisten] connection accepted from 127.0.0.1:38780 #9 (7 connections now open)
Thu Jul 21 00:41:49.255 [initandlisten] connection accepted from 127.0.0.1:38781 #10 (8 connections now open)
Thu Jul 21 00:41:49.256 [initandlisten] connection accepted from 127.0.0.1:38782 #11 (9 connections now open)
Thu Jul 21 00:41:49.256 [initandlisten] connection accepted from 127.0.0.1:38783 #12 (10 connections now open)
Thu Jul 21 00:41:49.265 [initandlisten] connection accepted from 127.0.0.1:38784 #13 (11 connections now open)
Thu Jul 21 00:41:49.265 [conn13] end connection 127.0.0.1:38784 (10 connections now open)
Thu Jul 21 00:41:49.266 [initandlisten] connection accepted from 127.0.0.1:38785 #14 (11 connections now open)
Thu Jul 21 00:41:49.266 [initandlisten] connection accepted from 127.0.0.1:38786 #15 (12 connections now open)
Thu Jul 21 00:41:49.266 [initandlisten] connection accepted from 127.0.0.1:38787 #16 (13 connections now open)
Thu Jul 21 00:41:49.266 [initandlisten] connection accepted from 127.0.0.1:38788 #17 (14 connections now open)
Thu Jul 21 00:41:49.267 [initandlisten] connection accepted from 127.0.0.1:38789 #18 (15 connections now open)
> Starting board-background-color migration.
Thu Jul 21 00:41:49.307 [conn4] build index wekan.meteor-migrations { _id: 1 }
Thu Jul 21 00:41:49.307 [conn4] build index done.  scanned 0 total records. 0 secs
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
> Starting use-css-class-for-boards-colors migration.
> Finishing use-css-class-for-boards-colors migration.
> Starting denormalize-star-number-per-board migration.
> Finishing denormalize-star-number-per-board migration.
> Starting add-member-isactive-field migration.
> Finishing add-member-isactive-field migration.
Thu Jul 21 00:41:49.336 [conn4] build index wekan.activities { _id: 1 }
Thu Jul 21 00:41:49.336 [conn4] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.336 [conn4] info: creating collection wekan.activities on add index
Thu Jul 21 00:41:49.336 [conn4] build index wekan.activities { createdAt: -1 }
Thu Jul 21 00:41:49.336 [conn4] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.337 [conn3] build index wekan.activities { cardId: 1, createdAt: -1 }
Thu Jul 21 00:41:49.337 [conn3] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.338 [conn2] build index wekan.activities { boardId: 1, createdAt: -1 }
Thu Jul 21 00:41:49.338 [conn2] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.340 [conn6] build index wekan.boards { _id: 1 }
Thu Jul 21 00:41:49.340 [conn6] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.340 [conn6] info: creating collection wekan.boards on add index
Thu Jul 21 00:41:49.340 [conn6] build index wekan.boards { _id: 1, members.userId: 1 }
Thu Jul 21 00:41:49.340 [conn6] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.341 [conn5] build index wekan.cards { _id: 1 }
Thu Jul 21 00:41:49.342 [conn5] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.342 [conn5] info: creating collection wekan.cards on add index
Thu Jul 21 00:41:49.342 [conn5] build index wekan.cards { boardId: 1 }
Thu Jul 21 00:41:49.342 [conn5] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.344 [conn4] build index wekan.lists { _id: 1 }
Thu Jul 21 00:41:49.344 [conn4] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.344 [conn4] info: creating collection wekan.lists on add index
Thu Jul 21 00:41:49.344 [conn4] build index wekan.lists { boardId: 1 }
Thu Jul 21 00:41:49.345 [conn4] build index done.  scanned 0 total records. 0 secs
Thu Jul 21 00:41:49.825 [conn4] build index wekan.presences { _id: 1 }
Thu Jul 21 00:41:49.825 [conn4] build index done.  scanned 0 total records. 0 secs
Exception while invoking method 'ATCreateUserServer' TypeError: Cannot read property 'title' of undefined
    at Object.<anonymous> (models/activities.js:71:22)
    at packages/matb33_collection-hooks/insert.js:35:1
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at after (packages/matb33_collection-hooks/insert.js:34:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].insert (packages/mongo/collection.js:528:37)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
    at Object.<anonymous> (models/lists.js:99:16)
    at packages/matb33_collection-hooks/insert.js:35:1
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at after (packages/matb33_collection-hooks/insert.js:34:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].insert (packages/mongo/collection.js:528:37)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
```

This exception happens while I tried to create a new (here in this case the 1st) user. May you can take a look in order to check this within the process of rc-version before releasing v0.11 final.

Thanks a lot. In case I should so an addtional or adjusted test, please let me know!


Thanks + Cheers,
Robert

**Comment by rgoltz** [comment]
Yesterday, I installed and tested the wekan pre-release v0.11.0-rc2 - During this tests no exception was thrown and mails was sent successfully. Maybe my local git clone during rc1 was not fully updated before I build the application. I'll keep an eye on this during further rcX-testing over the next days.

**Comment by AlexanderS** [comment]
The error with 0.11-rc1 was maybe a consequence of #650.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
