### ISSUE TITLE
Building OpenAPI docs did break on Ubuntu 22.10

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4731]
@bentiss 

Do you have time to look at this?

I did:
```
cd wekan
./releases/rebuild-docs.sh 6.54
```
Has api2html disappeared somewhere? And also there is some other errors.
```
Traceback (most recent call last):
  File "/home/wekan/repos/wekan/./openapi/generate_openapi.py", line 4, in <module>
    import esprima
  File "/usr/local/lib/python3.10/dist-packages/esprima/__init__.py", line 29, in <module>
    from .esprima import *  # NOQA
  File "/usr/local/lib/python3.10/dist-packages/esprima/esprima.py", line 26, in <module>
    from .comment_handler import CommentHandler
  File "/usr/local/lib/python3.10/dist-packages/esprima/comment_handler.py", line 27, in <module>
    from .nodes import Node
  File "/usr/local/lib/python3.10/dist-packages/esprima/nodes.py", line 28, in <module>
    from .scanner import RegExp
  File "/usr/local/lib/python3.10/dist-packages/esprima/scanner.py", line 30, in <module>
    from .character import Character, HEX_CONV, OCTAL_CONV
ImportError: cannot import name 'HEX_CONV' from 'esprima.character' (/usr/local/lib/python3.10/dist-packages/esprima/character.py)
./releases/rebuild-docs.sh: rivi 46: api2html: command not found
```

**Comment by bentiss** [comment]
> Has api2html disappeared somewhere?

I just tested rebuilding the docs in a blank ubuntu 22.10 container, and everything worked. The issue might be that your local machine was updated and the script was not re-installing `api2html`

Removing `~/python/esprima-python` should force a re-install.

>  And also there is some other errors.

This esprima-python maintainer is really annoying. The tip of the master branch is broken and there is a pending pull request to fix it that is waiting for 10 months to be merged!

This should be fixed in #4732.
