### ISSUE TITLE
Fresh installation of wekan doesn't work; it crashes

### ISSUE THREAD

**Issue by ix3ayaic** [wekan/wekan#4735]
## Issue
I tried to install latest version of Wekan on lxc container using
procedure described in https://github.com/wekan/wekan/wiki/Raspberry-Pi.
My attempts were unsuccessful: wekan crashes immediately after starting.
The same problem arises when I try to install it on qemu virtual
machine.

I am using bundle method of installation (download
https://releases.wekan.team/wekan-latest-x64.zip, unzip it, run it).

I use
- Ubuntu 20.04.5 LTS
- nodejs 14.20.1
- mongodb 5.0.13
- meteor 2.7.3

Thanks in advance for any help.

## Logs

journalctl -u wekan output is following:

```
Oct 27 19:02:35 wekan systemd[1]: Started The Wekan Service.
Oct 27 19:02:37 wekan node[225]: /usr/local/wekan/bundle/programs/server/node_modules/fibers/future.js:280
Oct 27 19:02:37 wekan node[225]:                                                 throw(ex);
Oct 27 19:02:37 wekan node[225]:                                                 ^
Oct 27 19:02:37 wekan node[225]: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Oct 27 19:02:37 wekan node[225]:     at new NodeError (internal/errors.js:322:7)
Oct 27 19:02:37 wekan node[225]:     at validateString (internal/validators.js:124:11)
Oct 27 19:02:37 wekan node[225]:     at Object.join (path.js:1148:7)
Oct 27 19:02:37 wekan node[225]:     at module (models/attachments.js:40:22)
Oct 27 19:02:37 wekan node[225]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Oct 27 19:02:37 wekan node[225]:     at Module.require (packages/modules-runtime.js:238:14)
Oct 27 19:02:37 wekan node[225]:     at Module.moduleLink [as link] (/usr/local/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
Oct 27 19:02:37 wekan node[225]:     at module (server/publications/attachments.js:1:24)
Oct 27 19:02:37 wekan node[225]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Oct 27 19:02:37 wekan node[225]:     at Module.require (packages/modules-runtime.js:238:14)
Oct 27 19:02:37 wekan node[225]:     at require (packages/modules-runtime.js:258:21)
Oct 27 19:02:37 wekan node[225]:     at /usr/local/wekan/bundle/programs/server/app/app.js:168902:1
Oct 27 19:02:37 wekan node[225]:     at /usr/local/wekan/bundle/programs/server/boot.js:407:38
Oct 27 19:02:37 wekan node[225]:     at Array.forEach (<anonymous>)
Oct 27 19:02:37 wekan node[225]:     at /usr/local/wekan/bundle/programs/server/boot.js:232:21
Oct 27 19:02:37 wekan node[225]:     at /usr/local/wekan/bundle/programs/server/boot.js:470:7
Oct 27 19:02:37 wekan node[225]:     at Function.run (/usr/local/wekan/bundle/programs/server/profile.js:280:14)
Oct 27 19:02:37 wekan node[225]:     at /usr/local/wekan/bundle/programs/server/boot.js:469:13 {
Oct 27 19:02:37 wekan node[225]:   code: 'ERR_INVALID_ARG_TYPE'
Oct 27 19:02:37 wekan node[225]: }
Oct 27 19:02:37 wekan systemd[1]: wekan.service: Main process exited, code=exited, status=1/FAILURE
Oct 27 19:02:37 wekan systemd[1]: wekan.service: Failed with result 'exit-code'.
Oct 27 19:02:37 wekan systemd[1]: wekan.service: Consumed 2.873s CPU time.
```

## Environment file 
```
NODE_ENV=production
WITH_API=true
MONGO_URL=mongodb://127.0.0.1:27017/wekan
ROOT_URL=http://172.24.1.56
PORT=80
```

## Service file 
```
[Unit]
Description=The Wekan Service
After=syslog.target network.target

[Service]
EnvironmentFile=/etc/wekan.conf
User=wekan
Group=wekan
WorkingDirectory=/usr/local/wekan/bundle/
ExecStart=/usr/bin/node main.js
Restart=on-failure
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```

### Ubuntu

```
root@wekan:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
```

### Mongodb

```
root@wekan:~# dpkg -l mongodb-org
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++============-============-===================================================================
ii  mongodb-org    5.0.13       amd64        MongoDB open source document-oriented database system (metapackage)
```

### nodejs

```
root@wekan:~# node -v
v14.20.1
```

### meteor

```
root@wekan:~# npm list -g --depth=0
/usr/lib
├── corepack@0.10.0
├── meteor@2.7.3
└── npm@6.14.17
```

**Comment by xet7** [comment]
You don't have WRITABLE_PATH=.. as mentioned at start-wekan.sh at https://github.com/wekan/wekan

Also, user wekan needs permission to bind to port 80:

https://github.com/wekan/wekan/blob/master/releases/virtualbox/node-allow-port-80.sh

**Comment by ix3ayaic** [comment]
It works! Thank you!
