### ISSUE TITLE
Unable to run with node 5.3

### ISSUE THREAD

**Issue by tubia** [wekan/wekan#475]
Hi,
some info on the system:
node | 5.3
wekan | 0.10.1

At the beginning, I had some problem with `npm install` that returned errors with `fibers` package.  
I found that maybe the problem was related to conflict between fibers version and node 5. So I changed the dependency in `bundle/programs/server/package.json` and `bundle/programs/server/npm-shrinkwrap.json` with fibers 1.0.6.
After that the installation process with `npm install` gone through with few warnings.
The problem now is starting the application with `node main.js`.
I'll report below the error message:
```node
node main.js 
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
/var/wekan/bundle/programs/server/node_modules/fibers/future.js:267
                                                throw(ex);
                                                ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:423:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/var/wekan/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/var/wekan/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.Npm.require (/var/wekan/bundle/programs/server/boot.js:162:18)
    at packages/npm-bcrypt/packages/npm-bcrypt.js:9:1
```

**Comment by mquandalle** [comment]
Yes, you have to use node `v0.10.40`

**Comment by rgoltz** [comment]
Hi,
 
just to add an information and question:
Due reading throw this issue, I switched to node v0.10.41 here in my environment (https://nodejs.org/en/blog/release/v0.10.41/).
My wekan installation (0.10.1) is running fine so far. Any remarks, which should be taking in consideration while switching from v0.10.40 to v0.10.41, Maxime?

Just for my clarification and understanding: Wekan currently needs node v0.10.x - It's not running with node v0.12.x or v4.2.x or v5.1.x - That's right? (Just to be prepared, once my infrastructure- or security-guys going to ask me on this ;-)


Merci beaucoup!
Best regards,
Robert

**Comment by mquandalle** [comment]
To be clear, Wekan is a standard Meteor application, so the (sad) restriction of compatibility with the recent NodeJS is imputable to the platform. Currently Meteor support v0.10.40 and IIRC they plan to support v0.10.41 as it contains a security fix. As far as I know Wekan should run just fine on Node v0.10.41.

(By the way the support of the Node 4.x.y will probably come when Meteor won’t rely anymore on the native `fibers` module for running asynchronous code.)

**Comment by tubia** [comment]
Hi @mquandalle thank for the explanation.
So, It seems that we need to use `nvm` to switch to older 0.10.40 version of node.
Does the support for newer version of node come soon? It relies only on meteorjs update path?

**Comment by mquandalle** [comment]
Yes it’s only a Meteor limitation, I wasn’t able to find a clear ETA on Node update https://forums.meteor.com/t/nodejs-lts-support/14467

Meanwhile `nvm` works perfectly fine.

**Comment by HLFH** [comment]
Related to: https://github.com/meteor/meteor/pull/6923

**Comment by blue68** [comment]
@mquandalle,The following is my local environment configuration:

1.node v4.7.0; npm v2.15.11;  Meteor 1.3.5.1,  operating system : Linux x86_64-unknown-linux-gnu;
gcc  4.8.3, g++ 4.8.3

so
exec node main.js ,  There are the following exceptions

"Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/usr/local/wekan/code/wekan/.build/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/usr/local/wekan/code/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/wekan/code/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/usr/local/wekan/code/wekan/.build/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
"

2.According to your suggested version of the node will be downgraded to v0.10.40 meteor rely on the fiber package can not always be installed

**Comment by HLFH** [comment]
@blue68 So @mquandalle is no more. You can go here: https://github.com/wefork/wekan/issues/23
