### ISSUE TITLE
OIDC login loop for integer user ID

### ISSUE THREAD

**Issue by danielkaiser** [wekan/wekan#4795]
### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Ubuntu 22.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker

### Problem description
Since https://github.com/wekan/wekan/commit/d90e78e4179fbcb3d926eaf53d97af6cfe59fb43 login using OIDC results in an endless login loop for us. The issue seems to be that our Identity Provider uses numeric user ID which crashes in https://github.com/wekan/wekan/blob/a4f99a3a5539037e058ec7a1bad50b173e620806/packages/wekan-oidc/oidc_server.js#L286 and starts an infinite loop of reloading the login page.

#### Logs
```
XXX: getUserInfo response:  {
  avatar_url: null,
  email: 'mail@example.com',
  firstname: 'Test',
  id: 1000,
  is_admin: false,
  lastname: 'Account',
  name: 'Test Account',
  username: 'test',
  web_url: null
}
XXX: userinfo: {
  avatar_url: null,
  email: 'mail@example.com',
  firstname: 'Test',
  id: 1000,
  is_admin: false,
  lastname: 'Account',
  name: 'Test Account',
  username: 'test',
  web_url: null
}
XXX: serviceData: {
  id: 1000,
  username: 'test',
  fullname: 'Test Account',
  accessToken: '...',
  expiresAt: 1673597481145,
  email: 'mail@example.com',
  groups: undefined
}
XXX: profile: { name: 'Test Account', email: 'mail@example.com' }
{"line":"406","file":"oauth_server.js","message":"Error in OAuth Server: Match error: Expected string, got number","time":{"$date":1672733481204},"level":"warn"}
Exception while invoking method 'login' Error: Match error: Expected string, got number
    at check (packages/check/match.js:36:17)
    at MethodInvocation.groupRoutineOnLogin (packages/wekan-oidc/oidc_server.js:286:5)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at packages/ddp-server/livedata_server.js:1820:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at packages/ddp-server/livedata_server.js:1818:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1756:26)
    at Server.call (packages/ddp-server/livedata_server.js:1738:17)
    at Object.handleOauthRequest (packages/wekan-oidc/oidc_server.js:108:10)
    at packages/oauth2/oauth2_server.js:10:39
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

As a quick workaround I manually converted the user id argument of `groupRoutineOnLogin` to string which solves the issue for us:
```diff
diff --git a/packages/wekan-oidc/oidc_server.js b/packages/wekan-oidc/oidc_server.js
index 38a618061..d6b22f60d 100644
--- a/packages/wekan-oidc/oidc_server.js
+++ b/packages/wekan-oidc/oidc_server.js
@@ -105,7 +105,7 @@ OAuth.registerService('oidc', 2, null, function (query) {
     });
   }
 
-  Meteor.call('groupRoutineOnLogin',serviceData, serviceData.id);
+  Meteor.call('groupRoutineOnLogin', serviceData, ""+serviceData.id);
 
   return {
     serviceData: serviceData,
```

As I'm currently not quite sure if it's better to remove the string check for `userId` in `groupRoutineOnLogin` or to manually convert `serviceData.id` beforehand I opened this issue instead of a PR.

**Comment by xet7** [comment]
@Viehlieb

What is purpose of your code changes at https://github.com/wekan/wekan/commit/d90e78e4179fbcb3d926eaf53d97af6cfe59fb43 ? Does it fix or break something?

**Comment by xet7** [comment]
I think it would be more clear to add code like `userId.toString()`

**Comment by ogni90** [comment]
The provided fix seems not to work.

I run into the same issue as @danielkaiser, but I already run the fixed version 6.67. I also checked, that userId.toString() has been added to the code, which is the case.

`XXX: profile: { name: 'xxx', email: 'xxx@xxx.xxx' }
{"line":"406","file":"oauth_server.js","message":"Error in OAuth Server: Match error: Expected string, got number","time":{"$date":1673019099423},"level":"warn"}`

When applying the fix @danielkaiser proposed the issue is fixed for me.

**Comment by Viehlieb** [comment]
The fix i introduced was related to a different problem with the groupRoutineOnLogin not being called.

I did not check the numeric option. Sorry and many thanks to @danielkaiser .
