### ISSUE TITLE
Total sum of custom field doesn't show total sum

### ISSUE THREAD

**Issue by danger89** [wekan/wekan#4819]
## Issue

I don't see the total of the number or currency field at the top of the list. Despite checking "Show sum of fields at top of list" option, during creation of a custom field.

### Server Setup Information

Running Wekan version: 6.71.0

### Problem description

Despite checking "Show sum of fields at top of list" on the custom field, I don't see the total sum displayed at the top of the list.

![where_is_total](https://user-images.githubusercontent.com/628926/215871095-f4006622-32b2-4601-8dc9-db165c521a59.png)

(I definitely also not see a total sum of all cards of the board, which would be a bonus feature)

#### Reproduction Steps

1. Add board setting. And add a custom field. Select for example currency or number and check "Show sum of fields at top of list" option.
2. Now; add one or more cards and fill-in the custom field number/currency.
3. Look at the top of the list.. There is **no** total sum getting displayed. Ideally I would like to see the total sum of money getting displayed.

#### Expected Result

I would like to see the total sum of the numbers/money at the top of the list. As described in the checkbox option on the GUI.

**Bonus feature:** And even the total of _all_ the cards on _all_ the swim lanes and/or all the lists also at the top of the board!

#### Logs

I did also notice an error message on the client side (browser), when pressing the 'edit'-icon on the custom field..

```sh
Exception in template helper: t/i.parse@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:600899
i@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:599088
o@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:599194
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:598375
t/t/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:551878
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:551821
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:559338
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:557559
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:30:593895
__@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1029:324820
e/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1029:311349
e/a/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:32109
t/d._wrapCatchingExceptions/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:17552
e/o/</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:32743
e/c._withTemplateInstanceFunc@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:39040
e/o/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:32649
f.call@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:661:1909
f.mustacheImpl@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:661:1164
f.mustache@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:661:1223
e/Template.createCustomFieldPopup</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1027:755482
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:21464
t/d.View.prototype.autorun/n/</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:19399
e/c._withTemplateInstanceFunc@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:39040
t/d.View.prototype.autorun/n/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:19350
t/d._withCurrentView@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:23492
n@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:19298
n/_compute/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:2273
n/o.withComputation@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4227
_compute@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:2233
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:1402
n/o.autorun@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:3950
t/d.View.prototype.autorun@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:19481
t/d._materializeView/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:21400
n/o.withComputation@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4227
n/o.nonreactive@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4096
t/d._materializeView@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:21368
e@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:10398
r._materializeDOM@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:9633
r._materializeDOM@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:9675
t/d._materializeView/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:21827
n/o.withComputation@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4227
n/o.nonreactive@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4096
t/d._materializeView@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:21368
t/d.render@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:24623
t/d.renderWithData@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:24999
e/open/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1029:76559
s/t[e]/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:15743
q/</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:15311
t/d._withCurrentView@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:23492
q/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:15273
e/c._withTemplateInstanceFunc@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:39040
q@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:15248
s/t[e]@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:15718
t/d._addEventMap/i/</</</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:27623
t/d._withCurrentView@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:23492
t/d._addEventMap/i/</</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:27583
e/c/this.delegatedHandler<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:9501
dispatch@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:456:35731
t/</add/g.handle@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:456:33817
EventListener.handleEvent*add@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:456:34279
t/</dt/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:456:33498
each@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:445:3001
each@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:445:985
dt@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:456:33473
on@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:456:39362
delegateEvents@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:1284
e/c.prototype.bind@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:10084
e/i.listen@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:10652
t/d._addEventMap/i/</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:27467
t/d._addEventMap/i/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:27355
i@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:27301
e/n.prototype.attach@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:4769
r._DOMRange.prototype.attach@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:32238
e/n._insert@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:3333
e/n.prototype.attach@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:4457
r._DOMRange.prototype.attach@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:679:32311
e/n.prototype.setMembers@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:5142
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:21589
n/o.withComputation@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4227
n/o.nonreactive@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4096
t@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:21529
t/d.View.prototype.autorun/n/</<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:19399
e/c._withTemplateInstanceFunc@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:39040
t/d.View.prototype.autorun/n/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:19350
t/d._withCurrentView@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:23492
n@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:601:19298
n/_compute/<@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:2273
n/o.withComputation@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:4227
_compute@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:2233
_recompute@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:2426
n/o._runFlush@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:579:3437
a@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1:3319
EventListener.handleEvent*r@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1:3365
@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1:3630
@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1:3640
@https://todo.melroy.org/7e46e6f5e5e3ac3a619215a393d6ac362159a555.js?meteor_js_resource=true:1:9820
```

Logging at the Docker container could be UNrelated to the issue. but I will share it anyways:

```sh
Exception from sub board id JNBBihJ3xGNQQ39GR Error: Match error: Expected string, got null
    at check (packages/check/match.js:36:17)
    at CursorMethods.<anonymous> (server/publications/boards.js:162:3)
    at Subscription.<anonymous> (packages/cottz:publish-relations/lib/server/publish_relations.js:13:23)
    at packages/matb33:collection-hooks/server.js:33:71
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at packages/ddp-server/livedata_server.js:1124:9
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1123:60)
    at Session._startSubscription (packages/ddp-server/livedata_server.js:934:9)
    at Session.sub (packages/ddp-server/livedata_server.js:673:12)
    at packages/ddp-server/livedata_server.js:603:43
Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:692:17)
    at check (packages/check/match.js:36:17)
    at CursorMethods.<anonymous> (server/publications/boards.js:162:3)
    at Subscription.<anonymous> (packages/cottz:publish-relations/lib/server/publish_relations.js:13:23)
    at packages/matb33:collection-hooks/server.js:33:71
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at packages/ddp-server/livedata_server.js:1124:9
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1123:60)
    at Session._startSubscription (packages/ddp-server/livedata_server.js:934:9)
    at Session.sub (packages/ddp-server/livedata_server.js:673:12)
    at packages/ddp-server/livedata_server.js:603:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Match failed',
  details: undefined,
  errorType: 'Meteor.Error'
}
```

**Comment by xet7** [comment]
Moved to #3796 

Yes, it does not work yet.
