### ISSUE TITLE
Installation of V6.72 on Windows Server 2019 fails - Cannot find Fibers module

### ISSUE THREAD

**Issue by julred** [wekan/wekan#4832]
## Issue
I wanted to install latest Wekan program on a Windows Server 2019 using this [article](https://github.com/wekan/wekan/wiki/Offline).
I installed MongoDB successfully, I adjusted the `start-wekan.bat` towards the IP-Adress. I placed the latest 'node.exe file inside the bundle folder structure of Wekan and startet `start-wekan.bat` with normal and with admin privilegies.

In both ways I come to this error description:
```
D:\Transfer\Wekan\bundle>start-wekan.bat
D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers\bin\win32-x64-111\fibers.node is missing.

Try running this to fix the issue: D:\Transfer\Wekan\bundle\node.exe D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers/build
Error: Cannot find module D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers\bin\win32-x64-111\fibers'
Require stack:
- D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers\fibers.js
- D:\Transfer\Wekan\bundle\programs\server\boot.js
- D:\Transfer\Wekan\bundle\main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers\fibers.js:14:39)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Mp._compile (D:\Transfer\Wekan\bundle\programs\server\runtime.js:77:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Mp.load (D:\Transfer\Wekan\bundle\programs\server\runtime.js:37:33)
D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers\fibers.js:23
                throw new Error('Missing binary. See message above.');
                ^

Error: Missing binary. See message above.
    at Object.<anonymous> (D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers\fibers.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Mp._compile (D:\Transfer\Wekan\bundle\programs\server\runtime.js:77:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Mp.load (D:\Transfer\Wekan\bundle\programs\server\runtime.js:37:33)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (D:\Transfer\Wekan\bundle\programs\server\boot.js:2:15)

Node.js v19.6.0
```

I was wondering, that `D:\Transfer\Wekan\bundle\programs\server\node_modules\fibers\bin\win32-x64-111\fibers` come up, because in my downloaded bundle the folder `win32-x64-83` exists.

I kindly ask, which steps I might miss, or what I need to do to get Wekan running?

### Server Setup Information
* Did you test in newest Wekan?: yes, V6.72
* Operating System: Windows Server 2019
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Bundle - [this ](https://releases.wekan.team/windows/wekan-6.72-amd64-windows.zip)version
* Node.js Version: 19.6.0
* MongoDB Version: 6.0.4
* What webbrowser version are you using: Chrome V109

### Problem description
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/6383396/218084246-b9cc9240-9f55-42f2-916f-207f973706b3.png)

**Comment by xet7** [comment]
@julred 

WeKan v6.73 for Windows prebuilt .zip is at https://github.com/wekan/wekan/releases

WeKan is only compatible with Node.js 14.x https://nodejs.org/dist/latest-v14.x/ , it does not work with 19.x

Compatible versions are listed at Download section of https://wekan.github.io

**Comment by xet7** [comment]
WeKan is made with Meteor, so it depends on what versions Meteor is compatible with.
