### ISSUE TITLE
WeKan v6.75 build errors on Linux arm64 and s390x, and Windows amd64

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4842]
I try to figure it out.

## Linux arm64

```
Error: /home/wekan/bundle/programs/server/npm/node_modules/canvas/build/Release/canvas.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/home/wekan/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/wekan/bundle/programs/server/npm/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/home/wekan/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/home/wekan/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/wekan/bundle/programs/server/npm/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/home/wekan/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/home/wekan/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

## Linux s390x

```
/home/linux1/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /home/linux1/bundle/programs/server/npm/node_modules/canvas/build/Release/canvas.node: ELF file data encoding not big-endian
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/home/linux1/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/linux1/bundle/programs/server/npm/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/home/linux1/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/home/linux1/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/linux1/bundle/programs/server/npm/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/home/linux1/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/home/linux1/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```
## Windows amd64
```
C:\Users\lauri\Downloads\bundle\programs\server\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

Error: \\?\C:\Users\lauri\Downloads\bundle\programs\server\npm\node_modules\canvas\build\Release\canvas.node is not valid Win32-application.
\\?\C:\Users\lauri\Downloads\bundle\programs\server\npm\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (C:\Users\lauri\Downloads\bundle\programs\server\runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (C:\Users\lauri\Downloads\bundle\programs\server\npm\node_modules\canvas\lib\bindings.js:3:18)    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (C:\Users\lauri\Downloads\bundle\programs\server\runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (C:\Users\lauri\Downloads\bundle\programs\server\runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (C:\Users\lauri\Downloads\bundle\programs\server\npm\node_modules\canvas\lib\canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (C:\Users\lauri\Downloads\bundle\programs\server\runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (C:\Users\lauri\Downloads\bundle\programs\server\runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by BabyFnord** [comment]
Hi @xet7, may I add the following error message, which shows up after upgrading from 6.74 on a bundle install, running the startup-script:
`                                                ^
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/ion/wekan/wekan-6.75/bundle/programs/server/npm/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Module.Mp.load (/home/ion/wekan/wekan-6.75/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/ion/wekan/wekan-6.75/bundle/programs/server/npm/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.Mp._compile (/home/ion/wekan/wekan-6.75/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Module.Mp.load (/home/ion/wekan/wekan-6.75/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/ion/wekan/wekan-6.75/bundle/programs/server/npm/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.Mp._compile (/home/ion/wekan/wekan-6.75/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Module.Mp.load (/home/ion/wekan/wekan-6.75/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}`

**Comment by xet7** [comment]
Fixed.

**Comment by BabyFnord** [comment]
Thank you @xet7 !
