### ISSUE TITLE
wekan-6.80-amd64-windows.zip this version of windows package  throws some Exceptions in my project when runs

### ISSUE THREAD

**Issue by uservip** [wekan/wekan#4870]
### Discussed in https://github.com/wekan/wekan/discussions/4869

<div type='discussions-op-text'>

<sup>Originally posted by **uservip** March 26, 2023</sup>
Exception from sub notificationSwimlanes id PdK3Yjp9pSibkPNA9 TypeError: Cannot read property 'profile' of null
    at activities (server/publications/notifications.js:97:38)
    at Subscription.<anonymous> (server/publications/notifications.js:78:12)
    at packages/matb33:collection-hooks/server.js:33:71
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at packages/ddp-server/livedata_server.js:1124:9
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1123:60)
    at packages/ddp-server/livedata_server.js:894:16
    at Map.forEach (<anonymous>)
    at packages/ddp-server/livedata_server.js:889:20
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Session._setUserId (packages/ddp-server/livedata_server.js:883:34)
    at MethodInvocation.setUserId [as _setUserId] (packages/ddp-server/livedata_server.js:727:14)
    at MethodInvocation.setUserId (packages/ddp-common/method_invocation.js:92:10)
    at MethodInvocation.methods.logout (packages/accounts-base/accounts_server.js:663:12)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
Exception while invoking method 'ATCreateUserServer' Error: You have not provided a mail URL. You can provide it by using the environment variable MAIL_URL or your settings. You can read more about it here: https://docs.meteor.com/api/email.html.
    at packages/email/email.js:310:11
    at D:\wekan-6.80-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (D:\wekan-6.80-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:56:12)
    at Object.Email.send (packages/email/email.js:250:18)
    at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:734:9)
    at MethodInvocation.ATCreateUserServer (packages/useraccounts:core/lib/server_methods.js:119:16)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at packages/ddp-server/livedata_server.js:791:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
Exception from sub myCards id 4LsE5aLXZqBb8uTmh TypeError: Cannot read property 'username' of null
    at Subscription.<anonymous> (server/publications/cards.js:81:56)
    at packages/matb33:collection-hooks/server.js:33:71
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at packages/ddp-server/livedata_server.js:1124:9
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1123:60)
    at packages/ddp-server/livedata_server.js:894:16
    at Map.forEach (<anonymous>)
    at packages/ddp-server/livedata_server.js:889:20
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Session._setUserId (packages/ddp-server/livedata_server.js:883:34)
    at MethodInvocation.setUserId [as _setUserId] (packages/ddp-server/livedata_server.js:727:14)
    at MethodInvocation.setUserId (packages/ddp-common/method_invocation.js:92:10)
    at MethodInvocation.methods.logout (packages/accounts-base/accounts_server.js:663:12)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1329:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)</div>

**Comment by uservip** [comment]
steps:
   1. create a new account;
   2. get in system success;
   3. in admin account, granted team to new account;
   4. and granted a new board to new account;
   5. exit admin account, login new account;
   6. new account can not login;
   7. check logs, there throw up exceptions.

suggestions:
    if need debug, should better add something in boads card;

**Comment by uservip** [comment]
1. There also have a problem that avatar can not display.
Problem:
    a. Image can upload to Avatar file;
    b. but can not display on panel;
    c. And there has no Exception reported;

2. Id can not find is a normal problem in panel changed.
Exception in changedobserveChanges callback: Error: Could not find element with id hdAh9QmXbsdnzxQ3T to change
    at SessionCollectionView.changed (packages/ddp-server/livedata_server.js:219:13)
    at Session.changed (packages/ddp-server/livedata_server.js:444:12)
    at Subscription.changed (packages/ddp-server/livedata_server.js:1372:19)
    at changed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:44:13)
    at runWithEnvironment (packages\meteor.js:1417:24)
    at packages\meteor.js:1430:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages\underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages\meteor.js:994:16)
    at packages\meteor.js:971:12
