### ISSUE TITLE
Bug: File validation prevents some attachments migrations

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4891]
@NotTheEvilOne @mfilser

When migrating to newest WeKan, file validation prevents migrating some attachments from CollectionFS to ostrio-files/Meteor-Files. I tried to fix this at WeKan v6.77 https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v677-2023-02-27-wekan--release but those fixes did not work.

When I commented out file validation code, it looked like all attachments were migrated properly. But would be possible to fix validation code?

Also, I would think, that saving files temporarily to disk (that requires a lot of disk space) would not be required, and migraton would be faster, if migration of CollectionFS to ostrio-files would only change tables/collections text data like filename etc to be acceptable to ostrio-files/Meteor-files, and maybe rename collections that have file chunks, but not write all those chunks to disk and read back, because that is problematic when there are hundreds of GB of data and limited disk space.

Currently, when upgrading WeKan, migrations save each attachment temporarily to disk, and writes back to different data structure. Also with migrations, some file metadata is lost, like createdAt/modifiedAt/uploadedAt or similar.
https://github.com/wekan/wekan/blob/master/server/migrations.js#L1248-L1393

Successful migration and validation shows in serverside logs like this:
```
File Inserted:  FILE-ID-HERE
Validation of uploaded file successful: file .../attachments/something.jpg
Ended: .../attachments/something.jpg
```
Failed migration and validation looks like this:
```
> Starting add-cardcounterlist-allowed migration.
> Finishing add-cardcounterlist-allowed migration.
> Starting add-hide-card-counter-list migration.
> Finishing add-hide-card-counter-list migration.
> Starting add-hide-board-member-list migration.
> Finishing add-hide-board-member-list migration.
> Starting add-description-text-allowed-on-minicard migration.
> Finishing add-description-text-allowed-on-minicard migration.
> Starting add-hide-card-counter-list-by-default migration.
> Finishing add-hide-card-counter-list-by-default migration.
> Starting add-hide-board-member-list-by-default migration.
> Finishing add-hide-board-member-list-by-default migration.
> Starting add-card-details-show-lists migration.
> Finishing add-card-details-show-lists migration.
> Starting migrate-attachments-collectionFS-to-ostrioFiles migration.
Error:  /wekan-uploads/attachments/something.png Error [MongoError]: file with id FILE-ID-HERE not opened for writing
at Function.MongoError.create (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
at setCursorNotified (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
at queryCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
at processTicksAndRejections (internal/process/task_queues.js:77:11) {
driver: true
}

> Finishing migrate-attachments-collectionFS-to-ostrioFiles migration.
Error:  /wekan-uploads/attachments/something2.png Error [MongoError]: file with id FILE-ID-HERE not opened for writing
at Function.MongoError.create (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
at setCursorNotified (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
at queryCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
at processTicksAndRejections (internal/process/task_queues.js:77:11) {
driver: true
}

> Starting migrate-avatars-collectionFS-to-ostrioFiles migration.
> Finishing migrate-avatars-collectionFS-to-ostrioFiles migration.
> Starting migrate-attachment-drop-index-cardId migration.
> Finishing migrate-attachment-drop-index-cardId migration.
> Starting migrate-attachment-migration-fix-source-import migration.
> Finishing migrate-attachment-migration-fix-source-import migration.
Error:  /wekan-uploads/attachments/something3.png Error [MongoError]: file with id FILE-ID-HERE not opened for writing
at Function.MongoError.create (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
at handleCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
at setCursorNotified (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
at queryCallback (wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
at wekan/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
at processTicksAndRejections (internal/process/task_queues.js:77:11) {
driver: true
}
```

Related to missing attachments https://github.com/wekan/wekan/issues/4780#issuecomment-1498266055

What do you think?

I also try how to fix this.

**Comment by xet7** [comment]
File validation is at https://github.com/wekan/wekan/blob/master/models/fileValidation.js

**Comment by mfilser** [comment]
I dont know this file validation code.
If the migration fails because of the file validation, the attachments are invalid and would normally also dont upload.
