### ISSUE TITLE
Feature Request: Open card near where clicked open card. Not always at left.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4972]
From Brian King at Vanila Chat:

> The position of the card doesn't make it less editable.
> Its just user experience. When working on a card on the far right of the screen, I then have to mouse move to the far left of the screen to update the card. This involves a lot of left/right travel across the screen. I thought it felt 'nicer' when the card opened near where I had clicked to select the card.

![card-open-near](https://github.com/wekan/wekan/assets/15545/9669eff4-fd50-4200-a0dc-a4f4f9b4cf84)

**Comment by techworked** [comment]
Same issue here. Previously it is not.

**Comment by xet7** [comment]
That card is at left usually. It has maximize button to make card fullscreen.

Card is not currently freely moveable.

Previously there was bug, that when opening card, card opened off screen, it was not at visible area at all. It did take some fixes to have card always visible. That bug was in some cases, not always. So that bug was then fixed.

**Comment by mfilser** [comment]
I changed it to open in the middle of the screen. Needs some testing, if everything is fine, PR comes after v7.00

**Comment by chrisi51** [comment]
last working version was 6.81 what we are using right now ... im also checking this topic for a fix, which recovers the behavior for normal cases to show the opened card next to the minicard but also make maximized and scrolled view being displayed properly

**Comment by xet7** [comment]
@chrisi51 

Maybe some of these?

- https://github.com/wekan/wekan/issues/4572
- https://github.com/wekan/wekan/issues/4822
- https://github.com/wekan/wekan/issues/5052
- https://github.com/wekan/wekan/issues/5064

You could search open and closed issues:
https://github.com/wekan/wekan/issues?q=is%3Aissue+is%3Aopen+card+open

All help very welcome! There are many bugs in new browser versions.

**Comment by chrisi51** [comment]
> 

sorry @xet7 i tried for 2 hours to setup dev environment ... even put out my 2 year old from an snapshot ... i allways get dependency hell for some npm packets 
```
Please enter your choice: 1
Linux
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
wget is already the newest version (1.21.2-2ubuntu1).
curl is already the newest version (7.81.0-1ubuntu1.13).
git is already the newest version (1:2.34.1-1ubuntu1.9).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-agent-base but it is not going to be installed
       Depends: node-aproba but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-cacache but it is not going to be installed
       Depends: node-chalk but it is not going to be installed
       Depends: node-cli-table3
       Depends: node-colors but it is not going to be installed
       Depends: node-columnify but it is not going to be installed
       Depends: node-debug but it is not going to be installed
       Depends: node-emoji-regex
       Depends: node-got but it is not going to be installed
       Depends: node-graceful-fs but it is not going to be installed
       Depends: node-gyp but it is not going to be installed
       Depends: node-https-proxy-agent but it is not going to be installed
       Depends: node-mkdirp but it is not going to be installed
       Depends: node-ms but it is not going to be installed
       Depends: node-nopt but it is not going to be installed
       Depends: node-normalize-package-data but it is not going to be installed
       Depends: node-npm-package-arg but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-read-package-json but it is not going to be installed
       Depends: node-rimraf but it is not going to be installed
       Depends: node-semver but it is not going to be installed
       Depends: node-ssri but it is not going to be installed
       Depends: node-string-width but it is not going to be installed
       Depends: node-strip-ansi but it is not going to be installed
       Depends: node-tar but it is not going to be installed
       Depends: node-validate-npm-package-name but it is not going to be installed
       Depends: node-which but it is not going to be installed
       Depends: node-write-file-atomic but it is not going to be installed
       Depends: nodejs:any (>= 10)
       Recommends: node-tap but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
googled a lot and seem not to get it working ... even on brand new ubuntu 22 LTS =(

**Comment by xet7** [comment]
@chrisi51 

After you have made fork of https://github.com/wekan/wekan like at https://github.com/wekan/wekan/wiki/Emoji:

```
cd wekan

./rebuild-wekan.sh
```
And then first select 1. Then 2. Then 3.

Then at webbrowser http://localhost:4000

Works on any newest Debian or Ubuntu amd64 based distro.

**Comment by chrisi51** [comment]
i know ... i did it before but its not working anymore ... the output is from number 1 of rebuild script ... i cant even get all dependencies

**Comment by xet7** [comment]
> googled a lot and seem not to get it working ...

In other news, Google is wrong.

>  even on brand new ubuntu 22 LTS =(

That is not brand new. Ubuntu 23.04 is brand new.

**Comment by xet7** [comment]
@chrisi51 

> i know ... i did it before but its not working anymore ... the output is from number 1 of rebuild script ... i cant even get all dependencies

Hmm, I'll try. Very likely I messed it up again.

**Comment by xet7** [comment]
Currenly I'm running Debian 12 amd64.

**Comment by xet7** [comment]
Hmm, it works for me.

I presume you should:
1. Delete your fork from https://github.com/chrisi51/wekan
2. Make new fork of https://github.com/wekan/wekan to your account
3. `git clone git@github.com:chrisi51/wekan`
4. `cd wekan`
5. Then do that 1-2-3 stuff from https://github.com/wekan/wekan/issues/4972#issuecomment-1668467370

**Comment by chrisi51** [comment]
on debian 12 its meteor whos complaining ¯\_(ツ)_/¯ 

```
Please enter your choice: 2
Building Wekan.

> dtrace-provider@0.8.8 install /opt/wekan/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

Traceback (most recent call last):
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 6.1.0-10-amd64
gyp ERR! command "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/ch/.meteor/packages/meteor-tool/.2.13.0.ngfw5l.0fqom++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/wekan/node_modules/dtrace-provider
gyp ERR! node -v v14.21.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> fibers@5.0.3 install /opt/wekan/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-83-glibc` exists; testing
Binary is fine; exiting

> core-js@3.32.0 postinstall /opt/wekan/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://boosty.to/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md

added 507 packages from 451 contributors and audited 512 packages in 11.701s

92 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

./rebuild-wekan.sh: line 22: 20399 Killed                  meteor build .build --directory --platforms=web.browser
./rebuild-wekan.sh: line 103: cd: .build/bundle/programs/server: No such file or directory
./rebuild-wekan.sh: line 104: cd: .build/bundle/programs/server/node_modules/fibers: No such file or directory
./rebuild-wekan.sh: line 105: cd: .build/bundle/programs/server/npm/node_modules/meteor/accounts-password: No such file or directory
./rebuild-wekan.sh: line 107: cd: .build/bundle: No such file or directory
Done.
```

**Comment by xet7** [comment]
@chrisi51 

> `ValueError: invalid mode: 'rU' while trying to load binding.gyp`

That can be ignored.

> `/rebuild-wekan.sh: line 22: 20399 Killed           meteor build .build --directory --platforms=web.browser`

Huh? How much you have RAM?

```
free -h
```

**Comment by chrisi51** [comment]
2GB

**Comment by xet7** [comment]
@chrisi51 

Try to have more RAM, until your WeKan build is not killed, but continues normally.

**Comment by xet7** [comment]
@chrisi51 

For running only WeKan, without desktop, 4 GB RAM is usually minimum.

If running webbrowser and WeKan while developing, 16 GB is usable.

If there is 8 GB RAM, there is not enough RAM for both browser and WeKan, so browsers will crash.

If you only have 2 GB RAM, then send PRs to WeKan PHP prototype https://github.com/wekan/php , it works with limited amount of RAM.

**Comment by xet7** [comment]
@chrisi51 

With that 2 GB RAM, it is better to use Netsurf webbrowser, that works with limited amount of RAM.

Target of WeKan PHP prototype is to work on Netsurf, that has HTML4/CSS support, without Javascript and drag-drop browserside.

**Comment by xet7** [comment]
@chrisi51 

Or alternatively, send PRs to DOS and Bash prototypes https://github.com/wekan/wedos

**Comment by chrisi51** [comment]
debian 12 with 2GB + 2GB swap was enough to make it start ... dunno why it worked before on ubuntu with 2GB ram and now this dependency hell is forcing me to switch to debian ¯\_(ツ)_/¯ 

Maybe somebody can else can test the PR
