### ISSUE TITLE
Exception while invoking method 'login' ReferenceError: Utils is not defined

### ISSUE THREAD

**Issue by nebulade** [wekan/wekan#5018]
Just saw this while debugging the OpenID connect integration with Cloudron.
On first time login of a user, which presumably triggers the autoregistration of that user, the server side hit this exception, resulting in the browser side application to just stay in the login screen.

Second time login works as expected.

```
12:27:59 - Exception while invoking method 'login' ReferenceError: Utils is not defined
12:27:59 - at Object.<anonymous> (models/users.js:1959:33)
12:27:59 - at packages/matb33:collection-hooks/insert.js:50:18
12:27:59 - at Array.forEach (<anonymous>)
12:27:59 - at after (packages/matb33:collection-hooks/insert.js:49:21)
12:27:59 - at Object.<anonymous> (packages/matb33:collection-hooks/insert.js:64:12)
12:27:59 - at Object.collection.<computed> [as insert] (packages/matb33:collection-hooks/collection-hooks.js:106:21)
12:27:59 - at Collection.insert (packages/mongo/collection.js:640:39)
12:27:59 - at Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
12:27:59 - at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1197:27)
12:27:59 - at AccountsServer.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1362:22)
12:27:59 - at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:57:21)
12:27:59 - at MethodInvocation.<anonymous> (packages/meteor.js:365:18)
12:27:59 - at packages/accounts-base/accounts_server.js:589:31
12:27:59 - at /app/code/build/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

The culprit seems to be that `Utils` is only defined on the browser/client side of things, while 
https://github.com/wekan/wekan/blob/master/models/users.js#L1959C37-L1959C37 is run on the server.

I am no meteor expert to fully grasp this server/client code mix unfortunately, but seems to me this just misses some import/require?

**Comment by mfilser** [comment]
I will have a look at this

**Comment by mfilser** [comment]
PR comes soon

**Comment by nebulade** [comment]
Awesome, thanks for the fast fix! Much more comprehensive than I thought.
