### ISSUE TITLE
Errors when compiling from source v0.10.1

### ISSUE THREAD

**Issue by adityai** [wekan/wekan#506]
OS: Ubuntu 14.04
Meteor: 1.2.1
Instructions followed: https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source
Tar: https://github.com/wekan/wekan/archive/v0.10.1.tar.gz

WARNING: The output directory is under your source tree.
/home/nitrous/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: ENOSPC, write
    at Object.Future.wait (/home/nitrous/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as writeFile](/tools/fs/files.js:1334:20)
    at atomicallyRewriteFile (/tools/isobuild/builder.js:604:11)
    at Builder.write (/tools/isobuild/builder.js:240:9)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:353:10)
    at /tools/isobuild/bundler.js:1475:38
    at Array.forEach (native)
    at Function._.each._.forEach (/home/nitrous/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js
:79:11)
    at JsImage.write (/tools/isobuild/bundler.js:1449:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:1768:13)
    at /tools/isobuild/bundler.js:1847:30
    at Object.keys.forEach.subBuilder (/tools/isobuild/bundler.js:1971:9)
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:1963:26
    at /tools/isobuild/bundler.js:2010:7
    at /tools/isobuild/bundler.js:2287:22
    at /tools/utils/buildmessage.js:268:13
   at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2128:31)
    at buildCommand (/tools/cli/commands.js:916:30)
    at Command.main.registerCommand._.extend.name [as func](/tools/cli/commands.js:791:12)
    at /tools/cli/main.js:1378:23
    - - - - -

**Comment by xet7** [comment]
Today's tar.gz prebuilt release v0.19 has been built on Ubuntu 14.04 and shoud work ok after installing meteor.
