### ISSUE TITLE
MongoDB duplicate key at SyncendCron notification cleanup?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5110]
@mfilser 

I got this while developing. What do you think?

```
=> Client modified -- refreshing (x2)
I20230829-23:59:59.936(3) (percolate_synced-cron.js:87) SyncedCron: Starting "notification_cleanup".
I20230829-23:59:59.942(3) (percolate_synced-cron.js:87) SyncedCron: Finished "notification_cleanup".
I20230830-00:00:00.039(3)? Exception in setTimeout callback: MongoServerError: E11000 duplicate key error collection: meteor.cronHistory index: intendedAt_1_name_1 dup key: { intendedAt: new Date(1693342800000), name: "notification_cleanup" }
I20230830-00:00:00.039(3)?     at /Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/insert.js:53:33
I20230830-00:00:00.039(3)?     at /Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:333:25
I20230830-00:00:00.040(3)?     at /Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/sdam/server.js:210:17
I20230830-00:00:00.040(3)?     at handleOperationResult (/Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/sdam/server.js:326:20)
I20230830-00:00:00.040(3)?     at Connection.onMessage (/Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:243:9)
I20230830-00:00:00.040(3)?     at MessageStream.<anonymous> (/Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:61:60)
I20230830-00:00:00.040(3)?     at MessageStream.emit (events.js:400:28)
I20230830-00:00:00.040(3)?     at MessageStream.emit (domain.js:475:12)
I20230830-00:00:00.040(3)?     at processIncomingData (/Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
I20230830-00:00:00.040(3)?     at MessageStream._write (/Users/wekan/.meteor/packages/npm-mongo/.4.16.0.34ax73.49l9b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
I20230830-00:00:00.040(3)?     at writeOrBuffer (internal/streams/writable.js:358:12)
I20230830-00:00:00.041(3)?     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
I20230830-00:00:00.041(3)?     at Socket.ondata (internal/streams/readable.js:731:22)
I20230830-00:00:00.041(3)?     at Socket.emit (events.js:400:28)
I20230830-00:00:00.041(3)?     at Socket.emit (domain.js:475:12)
I20230830-00:00:00.041(3)?     at addChunk (internal/streams/readable.js:293:12)
I20230830-00:00:00.041(3)?     at readableAddChunk (internal/streams/readable.js:267:9)
I20230830-00:00:00.041(3)?     at Socket.Readable.push (internal/streams/readable.js:206:10)
I20230830-00:00:00.042(3)?     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
I20230830-00:00:00.042(3)?   index: 0,
I20230830-00:00:00.042(3)?   code: 11000,
I20230830-00:00:00.042(3)?   keyPattern: { intendedAt: 1, name: 1 },
I20230830-00:00:00.042(3)?   keyValue: {
I20230830-00:00:00.042(3)?     intendedAt: 2023-08-29T21:00:00.000Z,
I20230830-00:00:00.042(3)?     name: 'notification_cleanup'
I20230830-00:00:00.042(3)?   },
I20230830-00:00:00.042(3)?   [Symbol(errorLabels)]: Set(0) {}
I20230830-00:00:00.042(3)? }
```

**Comment by mfilser** [comment]
@xet7 
I think the error comes here:
https://github.com/percolatestudio/meteor-synced-cron/blob/822cc27712f299858a26dacf5812d870fadd7307/synced-cron-server.js#L211

It's probably an issue of that project which Wekan uses.

**Comment by xet7** [comment]
@mfilser 

It looks like that is not a bug, it is a feature. Job is run only once.

**Comment by xet7** [comment]
The percolate:synced-cron 'notification_cleanup' job that produced this MongoServerError E11000 duplicate key error on the meteor.cronHistory collection (index intendedAt_1_name_1) no longer exists. Notification cleanup was rewritten to run via Meteor.setInterval in server/models/users.js (runNotificationCleanup), entirely outside the cron-history mechanism, and the synced-cron package was replaced (server/cron/syncedCron.js now uses quave:synced-cron with collection 'cronJobs', not the old cronHistory index). The specific duplicate-key code path is gone. Please reopen if you can still reproduce a cronHistory dup-key error on the latest release.
