### ISSUE TITLE
Can't login via LDAP because of some node.js issues?

### ISSUE THREAD

**Issue by Danny-Graf** [wekan/wekan#5113]
Hello,

i can't login via ldap because of some node issues?

Exception while invoking method 'login' TypeError: Cannot read property 'replace' of undefined
    at escapedToHex (packages/wekan-ldap/server/ldap.js:8:14)
    at new LDAP (packages/wekan-ldap/server/ldap.js:44:44)
    at MethodInvocation.<anonymous> (packages/wekan-ldap/server/loginHandler.js:40:16)
    at MethodInvocation.<anonymous> (packages\meteor.js:365:18)
    at packages/accounts-base/accounts_server.js:589:31
    at E:\wekan-7.09-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (E:\wekan-7.09-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:56:12)
    at packages/accounts-base/accounts_server.js:1525:11
    at E:\wekan-7.09-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (E:\wekan-7.09-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:56:12)
    at packages/accounts-base/accounts_server.js:653:7
    at E:\wekan-7.09-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (E:\wekan-7.09-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:56:12)
    at packages\meteor.js:367:22
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1389:31)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
    at packages\meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1389:31)
    at packages/ddp-server/livedata_server.js:791:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43

**Comment by Danny-Graf** [comment]
@xet7 Could you give me a hint, for how to solve this problem?

Thank you and best regards

**Comment by xet7** [comment]
@Danny-Graf 

Are you using Node.js from here https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4 and MongoDB 6.x ?

**Comment by Danny-Graf** [comment]
@xet7 

I've downgraded to MongoDB 6.0.9 from 7.0.0 but the error still exists. I am using Node.Js from https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4 

Do you have any further hint to solve the problem?

Thank you and best regards

**Comment by xet7** [comment]
I think that before this line:

https://github.com/wekan/wekan/blob/master/packages/wekan-ldap/server/ldap.js#L7

Should be added:

```
if (str !== undefined) {
```
And block of code indented, and after that block add:
```
}
```
At your downloaded bundle, you could make those changes to file packages/wekan-ldap/server/ldap.js:8

**Comment by Danny-Graf** [comment]
@xet7 
 
With the added code it works, I am able to connect to the LDAP.

Thank you and best regards

**Comment by Danny-Graf** [comment]
After I added the given code I was able to connect to the LDAP
