### ISSUE TITLE
Bug : Importing from snap wekan to cloudron instance

### ISSUE THREAD

**Issue by lezioul** [wekan/wekan#5207]
Hi, i'm trying to import a small table from my actual wekan instance to a new one.
Actual wekan was installed using snap : 

```
Name   Version  Rev   Tracking       Publisher  Notes
wekan  6.09     1999  latest/stable  xet7       -
```

The new instance run into cloudron.
I've not created all the users as their username will be different in the new system, but it doesn't seems to be an issue since there is a message asking to map them, but when clicking the "done" button, i got an error 500 (see pictures below)

![image](https://github.com/wekan/wekan/assets/4048547/e6310fab-1cb4-427b-aefd-243160dd7f6b)

![image](https://github.com/wekan/wekan/assets/4048547/429da832-1bda-4437-8102-d87a32786c5f)

the logs show this error : 

```
Nov 16 10:15:59Exception while invoking method 'importBoard' TypeError: Cannot read property 'length' of undefined
Nov 16 10:15:59at CsvCreator.createCards (models/csvCreator.js:298:51)
Nov 16 10:15:59at CsvCreator.create (models/csvCreator.js:399:10)
Nov 16 10:15:59at MethodInvocation.importBoard (models/import.js:35:20)
Nov 16 10:15:59at packages/check/match.js:118:15
Nov 16 10:15:59at packages/meteor.js:365:18
Nov 16 10:15:59at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Nov 16 10:15:59at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
Nov 16 10:15:59at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
Nov 16 10:15:59at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
Nov 16 10:15:59at packages/meteor.js:365:18
Nov 16 10:15:59at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Nov 16 10:15:59at packages/ddp-server/livedata_server.js:827:46
Nov 16 10:15:59at new Promise (<anonymous>)
Nov 16 10:15:59at Session.method (packages/ddp-server/livedata_server.js:775:23)
Nov 16 10:15:59at packages/ddp-server/livedata_server.js:639:43
Nov 16 10:16:14Exception while invoking method 'importBoard' TypeError: Cannot read property 'length' of undefined
Nov 16 10:16:14at CsvCreator.createCards (models/csvCreator.js:298:51)
Nov 16 10:16:14at CsvCreator.create (models/csvCreator.js:399:10)
Nov 16 10:16:14at MethodInvocation.importBoard (models/import.js:35:20)
Nov 16 10:16:14at packages/check/match.js:118:15
Nov 16 10:16:14at packages/meteor.js:365:18
Nov 16 10:16:14at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Nov 16 10:16:14at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
Nov 16 10:16:14at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
Nov 16 10:16:14at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
Nov 16 10:16:14at packages/meteor.js:365:18
Nov 16 10:16:14at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Nov 16 10:16:14at packages/ddp-server/livedata_server.js:827:46
Nov 16 10:16:14at new Promise (<anonymous>)
Nov 16 10:16:14at Session.method (packages/ddp-server/livedata_server.js:775:23)
Nov 16 10:16:14at packages/ddp-server/livedata_server.js:639:43

```

**Comment by xet7** [comment]
Import/export tools will be added later

**Comment by lezioul** [comment]
What about the existing tool? where you can paste copyied data? it's not working at all or maybe it has a couple of limitations?

Is there any other way to export / import? Maybe by backup/restore MongoDB?

Best Regards :)

**Comment by xet7** [comment]
@lezioul 

Backup/Restore MongoDB maybe is not enough to keep attachments visible currently.

Existing tools will be fixed. Upload feature will be added, it is better than copy paste.

Export/Import JSON currently does not export attachments. Also exporting big boards may timeout.

It is possible to export from MongoDB to files and SQLite with https://github.com/wekan/minio-metadata . But that needs a way to import data back to WeKan.

When FerretDB gets some more features for database queries and OpLog, it will be possible to replace MongoDB with FerretDB proxy to SQLite or FerretDB proxy to PostgreSQL.

**Comment by C0rn3j** [comment]
```
Exception while invoking method 'importBoard' ReferenceError: Attachment is not defined
    at models/wekanCreator.js:476:13
    at Array.forEach (<anonymous>)
    at models/wekanCreator.js:451:21
    at Array.forEach (<anonymous>)
    at WekanCreator.createCards (models/wekanCreator.js:323:16)
    at WekanCreator.create (models/wekanCreator.js:919:10)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at packages/ddp-server/livedata_server.js:827:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:775:23)
    at packages/ddp-server/livedata_server.js:639:43
```

I get the same error importing snap to docker.

Is there any workaround even if I lose the attachments?

**Comment by xet7** [comment]
@C0rn3j

There will be ways to import export all data, including attachments, correctly in future versions of WeKan.

But there are no plans for workarounds, losing attachments, big warnings, and crashes. Sorry.

**Comment by C0rn3j** [comment]
No problem, did it myself.

```bash
docker exec -it wekan-app bash
sed -i -e 's|Attachment\.load|//|g' -e 's|Attachment\.write|//|g' /build/programs/server/app/app.js
exit
docker compose restart
```

Import then works, throwing away attachments.
