### ISSUE TITLE
OIDC with Zitadel not working

### ISSUE THREAD

**Issue by zmbcgn** [wekan/wekan#5250]
## Issue
Hi, i want to get Zitadel working as Identitfy provider for OpenID connect login. I set up the configuration of WeKan and Zitadel accordingly, and also create the "first user" of WeKan through the regular process. But still I cannot log in with a new user, and also registration through OIDC is not working. It gives me an "internal server error". I wonder if it is something Zitadel is not giving to WeKan, or if there is a mapping which I am missing. Please note: It is not possible to configure custom attributes or scopes in Zitadel (yet)

### Server Setup Information
```
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=<OMMITED>
      - OAUTH2_SERVER_URL=https://auth.nettailor.net
      - OAUTH2_AUTH_ENDPOINT=/oauth/v2/authorize
      - OAUTH2_USERINFO_ENDPOINT=/oidc/v1/userinfo
      - OAUTH2_TOKEN_ENDPOINT=/oauth/v2/token
      - OAUTH2_SECRET=<OMITTED>
      - OAUTH2_ID_MAP=preferred_username
      - OAUTH2_USERNAME=preferred_username
      - OAUTH2_FULLNAME_MAP=given_name
      - OAUTH2_EMAIL_MAP=email
      - OAUTH2_REQUEST_PERMISSIONS=openid profile email
```
#### Logs
```
XXX: getToken response:  {
  access_token: '<omitted>',
  token_type: 'Bearer',
  expires_in: 43199,
  id_token: '<ommited>',
  state: '<omitted>'
}
XXX: register token: {
  access_token: '<omitted>',
  token_type: 'Bearer',
  expires_in: 43199,
  id_token: '<ommited>',
  state: '<ommited>'
}
XXX: getUserInfo response:  {
  sub: '246198837243281411',
  name: 'Philipp Maihoefer',
  given_name: 'Philipp',
  family_name: 'Maihoefer',
  nickname: 'Philipp',
  locale: 'de',
  updated_at: 1703244850,
  preferred_username: 'pmaihoefer',
  email: 'philipp@maisec.de',
  email_verified: true
}
XXX: userinfo: {
  sub: '246198837243281411',
  name: 'Philipp Maihoefer',
  given_name: 'Philipp',
  family_name: 'Maihoefer',
  nickname: 'Philipp',
  locale: 'de',
  updated_at: 1703244850,
  preferred_username: 'pmaihoefer',
  email: 'philipp@maisec.de',
  email_verified: true
}

XXX: serviceData: {
  id: 'pmaihoefer',
  username: undefined,
  fullname: 'Philipp',
  accessToken: '<omitted>',
  expiresAt: 1703898104907,
  email: 'philipp@maisec.de',
  groups: undefined
}
XXX: profile: { name: 'Philipp', email: 'philipp@maisec.de' }
Exception while invoking method 'login' TypeError: Cannot read property 'includes' of undefined
    at AccountsServer.<anonymous> (models/users.js:1746:25)
    at AccountsServer._onCreateUserHook (packages/meteor.js:365:18)
    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1179:23)
    at AccountsServer.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1362:22)
    at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:57:21)
    at MethodInvocation.<anonymous> (packages/meteor.js:365:18)
    at packages/accounts-base/accounts_server.js:589:31
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/accounts-base/accounts_server.js:1533:11
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/accounts-base/accounts_server.js:653:7
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/meteor.js:367:22
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at packages/ddp-server/livedata_server.js:827:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:775:23)
    at packages/ddp-server/livedata_server.js:639:43
```

**Comment by xet7** [comment]
@zmbcgn 

>  - OAUTH2_LOGIN_STYLE=redirect

redirect does not currently work. Only popup works.

Probably you also need this:
```
- OAUTH2_ID_MAP=sub
```
Also, change this:
```
- OAUTH_USERNAME=preferred_username
```
To this:
```
- OAUTH_USERNAME_MAP=email
```

**Comment by zmbcgn** [comment]
cool. that fixed it. 

for the record, if somebody has this issue: it is OAUTH2_USERNAME_MAP.

may i ask what "sub" stands for? and why i cannot use preferred_username as username?

**Comment by xet7** [comment]
@zmbcgn 

Sub is per-user unique ID, used in login, like 1234abcd. preferred_username probably is not unique, there could be persons with same names.

https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes

https://stackoverflow.com/questions/52876679/the-sub-claim-value-is-different-between-access-and-id-tokens#52877830

https://github.com/wekan/wekan/wiki/Google-login

**Comment by xet7** [comment]
I added this Zitadel login to wiki: https://github.com/wekan/wekan/wiki/Zitadel

**Comment by zmbcgn** [comment]
please remove my domain from the wiki article. thx.

**Comment by xet7** [comment]
@zmbcgn 

I removed your domain. Thanks!
