### ISSUE TITLE
Error: Cannot find module '../' 9

### ISSUE THREAD

**Issue by farazkaleemmalik** [wekan/wekan#5261]
## Issue
Cannot build arm64 release on Raspberry Pi 4B due to issue with fibers.

### Server Setup Information
- Latest Wekan source from https://releases.wekan.team/raspi3/
- Latest npm from Ubuntu arm64 repo (v
- No node or mongod installed yet

#### Reproduction Steps
1. Download source from https://releases.wekan.team/raspi3/
2. ``` cd bundle/programs/server && npm install```

#### Logs
```
npm ERR! code 1
npm ERR! path /home/ubuntu/bundle/programs/server/npm/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! internal/modules/cjs/loader.js:818
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '../'
npm ERR! Require stack:
npm ERR! - /home/ubuntu/bundle/programs/server/node_modules/.bin/node-gyp
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/home/ubuntu/bundle/programs/server/node_modules/.bin/node-gyp:8:13)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [ '/home/ubuntu/bundle/programs/server/node_modules/.bin/node-gyp' ]
npm ERR! }
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! internal/modules/cjs/loader.js:818
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '../'
npm ERR! Require stack:
npm ERR! - /home/ubuntu/bundle/programs/server/node_modules/.bin/node-gyp
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/home/ubuntu/bundle/programs/server/node_modules/.bin/node-gyp:8:13)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [ '/home/ubuntu/bundle/programs/server/node_modules/.bin/node-gyp' ]
npm ERR! }
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
npm ERR! Alpine users please run: `sudo apk add python make g++`

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2024-01-08T11_12_23_833Z-debug-0.log
npm ERR! code 1
npm ERR! path /home/ubuntu/bundle/programs/server
npm ERR! command failed
npm ERR! command sh -c node npm-rebuild.js
```

**Comment by xet7** [comment]
There will not be fibers at all, when upgrading to newer Meteor 3.0 becomes possible sometime. Also, currently Node.js 14.21.4 crashes at arm64. Using arm64 will become possible later.

**Comment by larrasket** [comment]
So what is supposed to be done until Mentor upgrade is done? I'm having the same issue with latest version on amd64. @xet7

**Comment by xet7** [comment]
@larrasket 

Currently at amd64 works for example:
- Snap Candidate: `sudo snap install wekan --channel=latest/candidate`
- Docker: `docker-compose.yml` at https://github.com/wekan/wekan
