### ISSUE TITLE
Rule uncheck all Checklist does not work TypeError: Cannot read property 'uncheckAllItems' of undefined

### ISSUE THREAD

**Issue by Major2828** [wekan/wekan#5283]
### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Ubuntu Server
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): no 
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.13
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Latest Firefox

### Problem description
When the Uncheck All Items from a Checklist rule is triggered, a problem occurs and the checklist is deleted instead.
#### Logs
2024-02-05T16:37:03+01:00 wekan.wekan[38700]: Exception while invoking method 'copyCard' TypeError: Cannot read property 'uncheckAllItems' of undefined
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.performAction (server/rulesHelper.js:289:17)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.executeRules (server/rulesHelper.js:9:14)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.<anonymous> (models/activities.js:79:15)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at packages/matb33:collection-hooks/insert.js:50:18
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Array.forEach (<anonymous>)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at after (packages/matb33:collection-hooks/insert.js:49:21)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.<anonymous> (packages/matb33:collection-hooks/insert.js:64:12)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.collection.<computed> [as insert] (packages/matb33:collection-hooks/collection-hooks.js:116:21)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at ns.Collection.insert (packages/mongo/collection.js:628:39)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at cardCreation (models/cards.js:2908:14)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.<anonymous> (models/cards.js:3092:5)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at packages/matb33:collection-hooks/insert.js:50:18
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Array.forEach (<anonymous>)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at after (packages/matb33:collection-hooks/insert.js:49:21)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.<anonymous> (packages/matb33:collection-hooks/insert.js:64:12)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Object.collection.<computed> [as insert] (packages/matb33:collection-hooks/collection-hooks.js:116:21)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at ns.Collection.insert (packages/mongo/collection.js:628:39)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at Document.copy (models/cards.js:587:23)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at MethodInvocation.copyCard (models/cards.js:3068:24)
2024-02-05T16:37:03+01:00 wekan.wekan[38700]:     at packages/check/match.js:118:15

Unfortunately I do not have any experience with JS so I cannot go any deeper into this issue.

**Comment by xet7** [comment]
Fixed in the upcoming WeKan release. See CHANGELOG.md Upcoming section.
