### ISSUE TITLE
Error 500 when adding user to a board

### ISSUE THREAD

**Issue by xator91** [wekan/wekan#5302]
I have installed and compiled my Wekan version and get error 500 when I try to add user to a board, I also see my name duplicate 5-6 times? why? @xet7

**Comment by xator91** [comment]
Exception while invoking method 'inviteUserToBoard' TypeError: Cannot read property 'isActive' of undefined
    at MethodInvocation.inviteUserToBoard (models/users.js:1523:14)
    at packages/check/match.js:118:15
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at packages/ddp-server/livedata_server.js:827:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:775:23)
    at packages/ddp-server/livedata_server.js:639:43

**Comment by xator91** [comment]
Tried also to reinstall, empty MongoDB.

![Screenshot 2024-02-19 at 13-02-31 #1 -](https://github.com/wekan/wekan/assets/18429920/cbe53570-03a0-4ceb-b9ad-23ea164b0dec)

**Comment by xator91** [comment]
I think that the problem is the new meteor version

**Comment by mariogalan** [comment]
I can confirm the bug using Wekan version 7.31, Meteor 2.15, Node 14.21.4 and Mongo 5.0.24.

![image](https://github.com/wekan/wekan/assets/1736985/4cd4b510-9ee2-4be5-a62d-156a75b9bc1d)

Our instance is deployed using Docker.

**Comment by bbyszio** [comment]
I can confirm this for 2 snap instances.

**Comment by zeo101** [comment]
I have the same issue with Wekan 7.31, Meteor 2.15 MongoDB 6.0.13 using Docker

**Comment by xet7** [comment]
Hmm. I'll try does this work or not.

**Comment by laurentm255** [comment]
Same issue here :/

**Comment by bbyszio** [comment]
For snap a revert to 7.30 works for me.;)
