### ISSUE TITLE
Bug when archiving card

### ISSUE THREAD

**Issue by xator91** [wekan/wekan#5322]
Bug when archiving card, tried to archive single or multiple and get this error. Tried with Wekan 7.31 - 7.32 and newest 7.33 @xet7 

Exception in removedobserveChanges callback: Error: Removed nonexistent document a62e2L6kKoWEHD8so
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document a62e2L6kKoWEHD8so
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document 6LLGRGKCXHNPTi8ci
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document 6LLGRGKCXHNPTi8ci
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document rrdR7P4DzX7hvbCsX
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document rrdR7P4DzX7hvbCsX
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document KWxDKycZFLRvxyXLH
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document KWxDKycZFLRvxyXLH
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12

**Comment by xator91** [comment]
After this error when I delete a lot of card, the system become slow and I have to restart it.

**Comment by xator91** [comment]
@xet7 any idea?

**Comment by xator91** [comment]
Tried to fix, but come the error:

Exception in removedobserveChanges callback: Error: Removed nonexistent document addNXpeKsC2Qag6Cn
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document addNXpeKsC2Qag6Cn
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document addNXpeKsC2Qag6Cn
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document addNXpeKsC2Qag6Cn
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document addNXpeKsC2Qag6Cn
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document addNXpeKsC2Qag6Cn
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
Exception in removedobserveChanges callback: Error: Removed nonexistent document addNXpeKsC2Qag6Cn
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12

**Comment by xator91** [comment]
It slow down the instance and i have to reboot. @xet7

**Comment by xator91** [comment]
It happens when deleting checklist @xet7

**Comment by xator91** [comment]
Also checklist items

**Comment by xet7** [comment]
@xator91 

Ok, then look at checklists code:

https://github.com/wekan/wekan/blob/main/models/checklistItems.js

https://github.com/wekan/wekan/blob/main/models/checklistItems.js

https://github.com/wekan/wekan/blob/main/client/components/cards/checklists.js

https://github.com/wekan/wekan/blob/main/client/components/cards/checklists.jade

**Comment by xator91** [comment]
> @xator91
> 
> Ok, then look at checklists code:
> 
> https://github.com/wekan/wekan/blob/main/models/checklists.js
> 
> https://github.com/wekan/wekan/blob/main/models/checklistItems.js
> 
> https://github.com/wekan/wekan/blob/main/client/components/cards/checklists.js
> 
> https://github.com/wekan/wekan/blob/main/client/components/cards/checklists.jade

Ok i´ll try it. But tried to make a new card, just with title and archived and got error also.

**Comment by xator91** [comment]
If I go to "More - Delete Card" no error. Just "Archive Card" throw errors. How we can change rest-API to delete instead of archive?

**Comment by xator91** [comment]
When I try to delete a card with curl REST API instead of api.py:

TypeError: Cannot read property 'boardId' of undefined
    at Object.<anonymous> (models/checklistItems.js:239:26)
    at packages/matb33:collection-hooks/remove.js:28:30
    at Array.forEach (<anonymous>)
    at packages/matb33:collection-hooks/remove.js:27:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (packages/matb33:collection-hooks/remove.js:26:22)
    at Object.collection.<computed> [as remove] (packages/matb33:collection-hooks/collection-hooks.js:116:21)
    at ns.Collection.remove (packages/mongo/collection.js:744:31)
    at cardRemover (models/cards.js:2944:18)
    at models/cards.js:3952:7
    at packages/simple_json-routes.js:100:9

**Comment by xator91** [comment]
The problem happens when you try to delete or archive a card with a checklist inside.

**Comment by xator91** [comment]
@xet7 Maybe I found what´s the problem here.

Checklist created through rest-api on a card, throw the error, when you try to delete the checklist.

If you add checklist manually, then no error.

**Comment by xator91** [comment]
Maybe also card, not only checklist. 

If I try to add cards with rest-api and then I reboot the server and try to delete the card no error.

But If I try to delete before a reboot, then I got error.

**Comment by xator91** [comment]
Exception in removedobserveChanges callback: Error: Removed nonexistent document JA2ERsCwrnHKoutxY
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
    
    After adding card, tried to remove manually direct with MongoDB Compass a checklists and then I got error with checklistsID.

**Comment by xator91** [comment]
Also when adding card through rest-api I get error when I delete them.

**Comment by xator91** [comment]
If I add new card through MongoDB with a PHP script and then I try to delete them from MongoDB manually error come anyway. @xet7

**Comment by xator91** [comment]
Add cards and checklist through mongodb:

Delete checklisteitems no error.
Delete cards before deleting checklists error.
Delete checklists before deleting card error.

**Comment by xator91** [comment]
I want to try to fix the problem, but I don't know where I have to look. Do you have any idea about it? @xet7

**Comment by xet7** [comment]
@xator91 

Compare code that works, and does not work. Is there differences? If some code works, copy that kind of code where it does not work.

For example, adding and removing lists, cards, checklists, etc.

At serverside code:

https://github.com/wekan/wekan/tree/main/models

At Publish/Subscribe, database fields that are updated realtime when something changes, publishing them to serverside minimongo (you can see minimongo content browserside with browser extension Meteor DevTools Evolved, similar additional menu like right click / Inspect / Console, there is Inspect/ Meteor).

https://github.com/wekan/wekan/tree/main/server/publications

At clientside code:

https://github.com/wekan/wekan/tree/main/client/components

**Comment by xator91** [comment]
> @xator91
> 
> Compare code that works, and does not work. Is there differences? If some code works, copy that kind of code where it does not work.
> 
> For example, adding and removing lists, cards, checklists, etc.
> 
> At serverside code:
> 
> https://github.com/wekan/wekan/tree/main/models
> 
> At Publish/Subscribe, database fields that are updated realtime when something changes, publishing them to serverside minimongo (you can see minimongo content browserside with browser extension Meteor DevTools Evolved, similar additional menu like right click / Inspect / Console, there is Inspect/ Meteor).
> 
> https://github.com/wekan/wekan/tree/main/server/publications
> 
> At clientside code:
> 
> https://github.com/wekan/wekan/tree/main/client/components

As I said, the problem is maybe that card added through mongodb or rest-api will not be "find" from Wekan service while was not added through the client. If you do a restart, after adding from mongo-db or rest-api you will get no error.

**Comment by xator91** [comment]
https://github.com/meteor/meteor/issues/944 @xet7

**Comment by xator91** [comment]
@xet7 

_Test 1:_

Add card
add comment
Delete or archive card (from client or mongodb)
**Throw error: YES**

_Test2:_

Add Card
add checklists
delete card or archive card (from client or mongodb)
**Throw error: YES**

_Test3:_

Add Card
Add comment
Reboot wekan
Delete or archive card (from client or mongodb)
**Throw Error: NO**

_Test4:_

Add Card
add checklists
Reboot Wekan
delete card or archive card (from client or mongodb)
**Throw error: YES**

**Comment by xet7** [comment]
Update for the upcoming release.

**The crash in your stack trace is gone.** It originated in the `cottz:publish-relations` package (`.../publish-relations/lib/server/cursor/cursor.js:52` → "Removed nonexistent document"), which sent duplicate `removed` messages when a card left a relation cursor on archive. WeKan no longer uses that package — board data is published via `publishComposite` — so that specific server exception should no longer occur.

**The high CPU on bulk operations is partly addressed.** For **deletes**, `cardRemover` used to remove a card's checklist items / checklists / comments through the hooked `removeAsync`, firing each child's `before.remove` once per document — every one doing a `getCard` and inserting an activity — which then drove notification + publication observers (an activity-insert storm). It now removes those children with `.direct` and clears all of the card's activities in a single bulk op, which removes the storm (and also cleans up activities a delete previously left orphaned). Regression test added.

**Still open:** the **archive** path (a bulk *update* setting `archived: true`, not a delete) still recomputes publications per card and is a separate optimization. If you can still reproduce high CPU specifically on **archiving** many cards in the next release, please note the card count and whether it's archive vs. delete so we can target that path.

**Comment by xet7** [comment]
The DDP "Removed nonexistent document" double-remove is prevented by the publish-composite migration.

But if you still get some error, please reopen issue, or add comment to this issue.
