### ISSUE TITLE
Upgrade MongoDB from 5 to 6 in Docker setup

### ISSUE THREAD

**Issue by agru** [wekan/wekan#5362]
### Server Setup Information

* WeKan 7.41.0
* Meteor version 2.14
* Node version 14.21.4
* MongoDB version 5.0.13

### Problem description
When I change MongoDB version to 6 in docker-compose.yml and start WeKan, I get errors and WeKan is not working. What do I have to do to migrate do MongoDB 6?

#### Logs
```
Status: Downloaded newer image for mongo:6
Recreating wekan-db ... 

ERROR: for wekan-db  'ContainerConfig'

ERROR: for wekandb  'ContainerConfig'
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 648, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 634, in do
  File "compose/service.py", line 579, in execute_convergence_plan
  File "compose/service.py", line 501, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 494, in recreate
  File "compose/service.py", line 613, in recreate_container
  File "compose/service.py", line 332, in create_container
  File "compose/service.py", line 917, in _get_container_create_options
  File "compose/service.py", line 957, in _build_container_volume_options
  File "compose/service.py", line 1532, in merge_volume_bindings
  File "compose/service.py", line 1562, in get_container_data_volumes
KeyError: 'ContainerConfig'
[3634] Failed to execute script docker-compose
```

**Comment by C0rn3j** [comment]
`docker-compose` is dead, use `docker compose`

**Comment by xet7** [comment]
@agru 

You need to backup your old version MongoDB, and restore to new MongoDB, in Docker.

https://github.com/wekan/wekan/wiki/Backup

If you have some files at your Docker volumes, like files/attachments/avatars, also copy those files to new Docker volumes.
