### ISSUE TITLE
First user cannot be created `ATCreateUserServer` undefined

### ISSUE THREAD

**Issue by meteorplus** [wekan/wekan#537]
I installed wekan and tried to create the first user and got this issue:

```
[domain.tld] Exception while invoking method 'ATCreateUserServer' TypeError: Cannot read property 'title' of undefined
[domain.tld]     at Object.<anonymous> (models/activities.js:69:27)
[domain.tld]     at packages/matb33_collection-hooks/insert.js:35:1
[domain.tld]     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
[domain.tld]     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
[domain.tld]     at after (packages/matb33_collection-hooks/insert.js:34:1)
[domain.tld]     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
[domain.tld]     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
[domain.tld]     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
[domain.tld]     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:101:1)
[domain.tld]     at Object.Lists.after.update.Activities.insert.userId (models/lists.js:90:16)
[domain.tld]     at packages/matb33_collection-hooks/insert.js:35:1
[domain.tld]     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
[domain.tld]     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
[domain.tld]     at after (packages/matb33_collection-hooks/insert.js:34:1)
[domain.tld]     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
[domain.tld]     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
```

So the error is related to the title undefined `ATCreateUserServer' TypeError: Cannot read property 'title' of undefined`

``` javascript
    if (activity.boardId) {
      board = activity.board();
      params.board = board.title;//heeeere :D
      title = 'act-withBoardTitle';
      params.url = board.absoluteUrl();
    }
```

but the problem comes from the activity which didn't return the board()

`const activity = Activities._transform(doc);`

still confused from this but it seems something is wrong when this get transformed!

but it lets the user login because this is run after the user is added and then this hook is called...

Thanks

**Comment by striletskyy** [comment]
I have the same problem 
![934bd98ec85d63531af3cd161b1fb74f](https://cloud.githubusercontent.com/assets/5245787/13566726/9afe80f6-e45f-11e5-832d-62ec8f186d1d.png)

**Comment by rgoltz** [comment]
Hi Capensis-Team, Hi Mykola.

I recently created an issue #473, which seems to handle the same underlying issue. Jonarod mentioned an idea in this ticket, to workaround this.
Furthermore, I think your code-snippet and debugging is a useful input.

Cheers,
Robert

**Comment by xet7** [comment]
I think this is already fixed, also see:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
