### ISSUE TITLE
A user logged in with oauth2 cannot edit his profile

### ISSUE THREAD

**Issue by tholeb** [wekan/wekan#5375]
### Server Setup Information
* Did you test in newest Wekan?: yes (edit : no, 6.09)
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Ubuntu 22.04 LTS
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: managed by snap (v20.11.0 on host)
* MongoDB Version:  managed by snap (not installed on host)
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Version 123.0.6312.122 (Build officiel) (64 bits) google chrome

### Problem description

A user logged in with oauth2 (in my case, discord), cannot change his full name. In fact, the "edit profile" button is not available in the member settings, see below : 

My admin account : 
![image](https://github.com/wekan/wekan/assets/43311443/e3fbcb0a-2d92-45a0-82a4-59f8a79f2d2e)

My secondary account to test the discord connection : 
![image](https://github.com/wekan/wekan/assets/43311443/d80c84a2-cd2e-4953-a798-d73f29aec27c)

#### Reproduction Steps
1. Create (or log in) a user with oauth2
2. Try to edit the profile
3. Button is missing in the list

#### Logs
empty logs in browser console.

```
2024-04-13T14:13:19+02:00 wekan.wekan[430560]: XXX: serviceData: {
2024-04-13T14:13:19+02:00 wekan.wekan[430560]:   id: 'ID',
2024-04-13T14:13:19+02:00 wekan.wekan[430560]:   username: 'username',
2024-04-13T14:13:19+02:00 wekan.wekan[430560]:   fullname: 'username',
2024-04-13T14:13:19+02:00 wekan.wekan[430560]:   accessToken: 'token',
2024-04-13T14:13:19+02:00 wekan.wekan[430560]:   expiresAt: 1713615198979,
2024-04-13T14:13:19+02:00 wekan.wekan[430560]:   email: 'email',
2024-04-13T14:13:19+02:00 wekan.wekan[430560]:   refreshToken: 'anotherToken'
2024-04-13T14:13:19+02:00 wekan.wekan[430560]: }
2024-04-13T14:13:19+02:00 wekan.wekan[430560]: XXX: profile: { name: 'username', email: 'email' }
```

**Comment by xet7** [comment]
@tholeb 

Look at command:
```
sudo snap list
```
Are you running old Snap Stable WeKan 6.09
or newest Snap Candidate WeKan 7.x ?

Your OAuth2 settings should be:
- username: email
- email: email

And login with email address like user@example.com and password.

If you like to modify Full Name in WeKan, you should not add OAuth2 setting for Full Name at all. That way it is defined and saved at WeKan.

But if your OAuth2 server has some field that has Full Name, add that to OAuth2 settings.

WeKan can not save changes to OAuth2 values. Those are modified at OAuth2 server settings.

**Comment by tholeb** [comment]
> @tholeb
> 
> Look at command:
> 
> ```
> sudo snap list
> ```
> 
> Are you running old Snap Stable WeKan 6.09 or newest Snap Candidate WeKan 7.x ?
> 
> Your OAuth2 settings should be:
> 
> * username: email
> * email: email
> 
> And login with email address like [user@example.com](mailto:user@example.com) and password.
> 
> If you like to modify Full Name in WeKan, you should not add OAuth2 setting for Full Name at all. That way it is defined and saved at WeKan.
> 
> But if your OAuth2 server has some field that has Full Name, add that to OAuth2 settings.
> 
> WeKan can not save changes to OAuth2 values. Those are modified at OAuth2 server settings.

I am indeed running the 6.09 version (weird, I just installed the app). Here is my original oauth2 settings : 

```
sudo snap set wekan oauth2-enabled='true'
sudo snap set wekan oauth2-client-id='client id'
sudo snap set wekan oauth2-secret='secret'
sudo snap set wekan oauth2-server-url='https://discord.com/'
sudo snap set wekan oauth2-auth-endpoint='oauth2/authorize'
sudo snap set wekan oauth2-userinfo-endpoint='api/users/@me'
sudo snap set wekan oauth2-token-endpoint='api/oauth2/token'
sudo snap set wekan oauth2-id-map='id'
sudo snap set wekan oauth2-username-map='username'
sudo snap set wekan oauth2-fullname-map='username'
sudo snap set wekan oauth2-email-map='email'
sudo snap set wekan oauth2-request-permissions='identify email'
```

On another instance, I removed `sudo snap set wekan oauth2-username-map='username'` from the config, and I get "Internal Server Error". After a quick `snap log wekan` Here is the result : 
```
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at packages/ddp-server/livedata_server.js:719:19
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at packages/ddp-server/livedata_server.js:717:46
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at packages/ddp-server/livedata_server.js:715:46
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at new Promise (<anonymous>)
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2024-04-13T19:14:55+02:00 wekan.wekan[149829]:     at packages/ddp-server/livedata_server.js:559:43
```

I'll try to update to the newer version with snap and try again.

**Comment by tholeb** [comment]
I installed the snap on channel latest/candidate (7.42.0).

I can confirm that removing`sudo snap set wekan oauth2-username-map='username'` (or using an empty value) throws that error :
```
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at packages/meteor.js:365:18
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at packages/ddp-server/livedata_server.js:827:46
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at new Promise (<anonymous>)
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at Session.method (packages/ddp-server/livedata_server.js:775:23)
2024-04-13T19:33:25+02:00 wekan.wekan[251496]:     at packages/ddp-server/livedata_server.js:639:43
```

How can I use an oauth2 login without defining a fullname so the user can change his fullname in wekan ?

Thanks a lot for your help.

**Comment by xet7** [comment]
@tholeb 

You need to keep that username setting, so that it does not produce error.
```
sudo snap set wekan oauth2-username-map='username'
```
For fullname:
```
sudo snap unset wekan oauth2-fullname-map
```

**Comment by tholeb** [comment]
> @tholeb
> 
> You need to keep that username setting, so that it does not produce error.
> 
> ```
> sudo snap set wekan oauth2-username-map='username'
> ```
> 
> For fullname:
> 
> ```
> sudo snap unset wekan oauth2-fullname-map
> ```

I don't quite understand. If I set the value, I can't edit my profile, and if I unset it, I can't register a new user.

Is it possible to edit the profile (in my case, the fullname) of an oauth2 account ?

**Comment by xet7** [comment]
@tholeb 

Are you using Discord as OAuth2 identity provider?

If you don't use OAuth2, and use username/password login, you can edit profile.

**Comment by tholeb** [comment]
> @tholeb
> 
> Are you using Discord as OAuth2 identity provider?
> 
> If you don't use OAuth2, and use username/password login, you can edit profile.

Yes, I'm using discord as an oauth2 provider.

I'll stick with the username/password login. Thank you for your help.
