### ISSUE TITLE
[Docker-arm64] /data/attachments is not writable

### ISSUE THREAD

**Issue by eMUQI** [wekan/wekan#5414]
### Server Setup Information

* Did you test in newest Wekan?: YES, ghcr.io/wekan/wekan:v7.09-arm64
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? YES
* Operating System:  Debian GNU/Linux 12 (bookworm) aarch64 (Raspberry Pi 5)
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker-compose
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

### Problem description

The container cannot start, and Wekan cannot be used.

#### Reproduction Steps
```
wget https://raw.githubusercontent.com/wekan/wekan/main/docker-compose.yml-arm64
nano docker-compose.yml-arm64 #set root-url
docker-compose up -f docker-compose.yml-arm64
```

#### Logs

```
[+] Running 6/6
 ✔ Network wekan_wekan-tier      Created                                                                           0.1s
 ✔ Volume "wekan_wekan-files"    Created                                                                           0.0s
 ✔ Volume "wekan_wekan-db"       Created                                                                           0.0s
 ✔ Volume "wekan_wekan-db-dump"  Created                                                                           0.0s
 ✔ Container wekan-db            Created                                                                           0.4s
 ✔ Container wekan-app           Created                                                                           0.2s
Attaching to wekan-app, wekan-db
wekan-app  |
wekan-app  | /home/wekan/bundle/programs/server/node_modules/fibers/future.js:280
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^
wekan-app  | errorClass [Error]: [FilesCollection.attachments] Path "/data/attachments" is not writable! [401]
wekan-app  |     at new FilesCollection (packages/ostrio:files/server.js:356:15)
wekan-app  |     at module (models/attachments.js:49:15)
wekan-app  |     at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |     at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |     at Module.moduleLink [as link] (/home/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
wekan-app  |     at module (server/publications/attachments.js:1:24)
wekan-app  |     at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |     at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |     at require (packages/modules-runtime.js:258:21)
wekan-app  |     at /home/wekan/bundle/programs/server/app/app.js:184885:1
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:385:38
wekan-app  |     at Array.forEach (<anonymous>)
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:210:21
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:439:7
wekan-app  |     at Function.run (/home/wekan/bundle/programs/server/profile.js:256:14)
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:438:13 {
wekan-app  |   isClientSafe: true,
wekan-app  |   error: 401,
wekan-app  |   reason: '[FilesCollection.attachments] Path "/data/attachments" is not writable!',
wekan-app  |   details: Error: EACCES: permission denied, mkdir '/data/attachments'
wekan-app  |       at Object.mkdirSync (fs.js:1014:3)
wekan-app  |       at new FilesCollection (packages/ostrio:files/server.js:350:10)
wekan-app  |       at module (models/attachments.js:49:15)
wekan-app  |       at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |       at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |       at Module.moduleLink [as link] (/home/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
wekan-app  |       at module (server/publications/attachments.js:1:24)
wekan-app  |       at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |       at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |       at require (packages/modules-runtime.js:258:21)
wekan-app  |       at /home/wekan/bundle/programs/server/app/app.js:184885:1
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:385:38
wekan-app  |       at Array.forEach (<anonymous>)
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:210:21
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:439:7
wekan-app  |       at Function.run (/home/wekan/bundle/programs/server/profile.js:256:14)
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:438:13 {
wekan-app  |     errno: -13,
wekan-app  |     syscall: 'mkdir',
wekan-app  |     code: 'EACCES',
wekan-app  |     path: '/data/attachments'
wekan-app  |   },
wekan-app  |   errorType: 'Meteor.Error'
wekan-app  | }
wekan-app exited with code 0
wekan-app  |
wekan-app  | /home/wekan/bundle/programs/server/node_modules/fibers/future.js:280
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^
wekan-app  | errorClass [Error]: [FilesCollection.attachments] Path "/data/attachments" is not writable! [401]
wekan-app  |     at new FilesCollection (packages/ostrio:files/server.js:356:15)
wekan-app  |     at module (models/attachments.js:49:15)
wekan-app  |     at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |     at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |     at Module.moduleLink [as link] (/home/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
wekan-app  |     at module (server/publications/attachments.js:1:24)
wekan-app  |     at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |     at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |     at require (packages/modules-runtime.js:258:21)
wekan-app  |     at /home/wekan/bundle/programs/server/app/app.js:184885:1
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:385:38
wekan-app  |     at Array.forEach (<anonymous>)
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:210:21
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:439:7
wekan-app  |     at Function.run (/home/wekan/bundle/programs/server/profile.js:256:14)
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:438:13 {
wekan-app  |   isClientSafe: true,
wekan-app  |   error: 401,
wekan-app  |   reason: '[FilesCollection.attachments] Path "/data/attachments" is not writable!',
wekan-app  |   details: Error: EACCES: permission denied, mkdir '/data/attachments'
wekan-app  |       at Object.mkdirSync (fs.js:1014:3)
wekan-app  |       at new FilesCollection (packages/ostrio:files/server.js:350:10)
wekan-app  |       at module (models/attachments.js:49:15)
wekan-app  |       at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |       at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |       at Module.moduleLink [as link] (/home/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
wekan-app  |       at module (server/publications/attachments.js:1:24)
wekan-app  |       at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |       at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |       at require (packages/modules-runtime.js:258:21)
wekan-app  |       at /home/wekan/bundle/programs/server/app/app.js:184885:1
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:385:38
wekan-app  |       at Array.forEach (<anonymous>)
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:210:21
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:439:7
wekan-app  |       at Function.run (/home/wekan/bundle/programs/server/profile.js:256:14)
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:438:13 {
wekan-app  |     errno: -13,
wekan-app  |     syscall: 'mkdir',
wekan-app  |     code: 'EACCES',
wekan-app  |     path: '/data/attachments'
wekan-app  |   },
wekan-app  |   errorType: 'Meteor.Error'
wekan-app  | }
wekan-app exited with code 0
wekan-app  |
wekan-app  | /home/wekan/bundle/programs/server/node_modules/fibers/future.js:280
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^
wekan-app  | errorClass [Error]: [FilesCollection.attachments] Path "/data/attachments" is not writable! [401]
wekan-app  |     at new FilesCollection (packages/ostrio:files/server.js:356:15)
wekan-app  |     at module (models/attachments.js:49:15)
wekan-app  |     at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |     at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |     at Module.moduleLink [as link] (/home/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
wekan-app  |     at module (server/publications/attachments.js:1:24)
wekan-app  |     at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |     at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |     at require (packages/modules-runtime.js:258:21)
wekan-app  |     at /home/wekan/bundle/programs/server/app/app.js:184885:1
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:385:38
wekan-app  |     at Array.forEach (<anonymous>)
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:210:21
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:439:7
wekan-app  |     at Function.run (/home/wekan/bundle/programs/server/profile.js:256:14)
wekan-app  |     at /home/wekan/bundle/programs/server/boot.js:438:13 {
wekan-app  |   isClientSafe: true,
wekan-app  |   error: 401,
wekan-app  |   reason: '[FilesCollection.attachments] Path "/data/attachments" is not writable!',
wekan-app  |   details: Error: EACCES: permission denied, mkdir '/data/attachments'
wekan-app  |       at Object.mkdirSync (fs.js:1014:3)
wekan-app  |       at new FilesCollection (packages/ostrio:files/server.js:350:10)
wekan-app  |       at module (models/attachments.js:49:15)
wekan-app  |       at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |       at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |       at Module.moduleLink [as link] (/home/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
wekan-app  |       at module (server/publications/attachments.js:1:24)
wekan-app  |       at fileEvaluate (packages/modules-runtime.js:336:7)
wekan-app  |       at Module.require (packages/modules-runtime.js:238:14)
wekan-app  |       at require (packages/modules-runtime.js:258:21)
wekan-app  |       at /home/wekan/bundle/programs/server/app/app.js:184885:1
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:385:38
wekan-app  |       at Array.forEach (<anonymous>)
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:210:21
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:439:7
wekan-app  |       at Function.run (/home/wekan/bundle/programs/server/profile.js:256:14)
wekan-app  |       at /home/wekan/bundle/programs/server/boot.js:438:13 {
wekan-app  |     errno: -13,
wekan-app  |     syscall: 'mkdir',
wekan-app  |     code: 'EACCES',
wekan-app  |     path: '/data/attachments'
wekan-app  |   },
wekan-app  |   errorType: 'Meteor.Error'
wekan-app  | }
wekan-app exited with code 0
```

**Comment by nliakm** [comment]
This problem arises because the volume is defined through the "volumes" section and is created separately there. The user id of the volume will be that of the Docker user (usually root, i.e., 0). However, the Wekan container does not run as root but as the wekan user (user id 1000). Therefore it has no write permissions for that directory.

There are some ways to fix it, with the first one the simplest and the other need some more steps and may not be intended to do so:

1. Inside the wekan service section, use a non-existent path on the host machine and let the volume be created on the first container start:
```yaml
services:
  wekan:
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data:rw
```
2. Don't recommended! Run the wekan container as root user:
```yaml
services:
  wekan:
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw
    user: "0:0"
```
3. Extend the volume configuration to have the correct user permissions:
```yaml
volumes:
  wekan-files:
    driver: local
    driver_opts:
      type: "block"
      o: "uid=1000,gid=1000"
       # device depends on the underlying system. This example is for Mac, on Linux it can be for example /dev/sda1 
      device: "/dev/disk0"
```

**Comment by eMUQI** [comment]
Hello @makermelissa,

Today, I followed the installation tutorial again on a fresh Raspberry Pi setup, referring to the Automated Install section of [this guide](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi).

When I ran the following test code after completing the installation:

```python
import board
import digitalio
import busio

print("Hello, blinka!")

# Try to create a Digital input
pin = digitalio.DigitalInOut(board.D18)
print("Digital IO ok!")

# Try to create an I2C device
i2c = busio.I2C(board.SCL, board.SDA)
print("I2C ok!")

# Try to create an SPI device
spi = busio.SPI(board.SCLK, board.MOSI, board.MISO)
print("SPI ok!")

print("done!")
```

I encountered the `"RuntimeError: Cannot determine SOC peripheral base address"` error. Following the suggestion above, I installed `rpi-lgpio`, and everything returned to normal.

Perhaps it would be worth considering adding the installation of `rpi-lgpio` to the `raspi-blinka.py` script?
