### ISSUE TITLE
Export CSV/TSV from Board create unhandled Exception

### ISSUE THREAD

**Issue by Dexus** [wekan/wekan#5416]
### Server Setup Information

* Did you test in newest Wekan?: no - 7.38
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker (kubernetes/openshift)
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

### Problem description

Make the export working, how it can be that the https://github.com/wekan/wekan/blob/db73fb4e37d40c3ad1b8efe8a501a34145ffe687/models/exporter.js#L351C13-L353C20 `name` is not found?

#### Reproduction Steps
- user has an old board with many items, moved things etc. in the last year.
- click on export board as CSV or TSV crash with the same unhandledexception
- csv will start to export but then after 19 lines of data it will fail with error on download "network problem" but at the same the exception is thrown.

#### Logs

```
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
Exception in removedobserveChanges callback: Error: Removed nonexistent document rojp2CHuGEEaGx2ph
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:269:17)
    at Session.removed (packages/ddp-server/livedata_server.js:468:12)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1430:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
    at packages/meteor.js:1003:12
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at models/exporter.js:353:14
    at Array.forEach (<anonymous>)
    at models/exporter.js:342:25
    at Array.forEach (<anonymous>)
    at Exporter.buildCsv (models/exporter.js:272:18)
    at models/export.js:200:26
    at doCall (packages/communitypackages:picker/lib/implementation.js:118:14)
    at PickerImp._processRoute (packages/communitypackages:picker/lib/implementation.js:112:5)
    at packages/communitypackages:picker/lib/implementation.js:79:16
    at processNextMiddleware (packages/communitypackages:picker/lib/implementation.js:65:7)
    at processNextRoute (packages/communitypackages:picker/lib/implementation.js:75:9)
    at PickerImp._dispatch (packages/communitypackages:picker/lib/implementation.js:97:3)
    at packages/communitypackages:picker/lib/instance.js:6:10
    at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)
```

**Comment by Dexus** [comment]
Additional Information:

export the board, as JSON, shows that the `customFields` for one dropdown, does not create the `"value": null` if it is not set. 

example with two dropdowns - one is without value ?!?!?:
```
{ "_id": "rRb57kvf3vnED9RbL" },
{ "_id": "rvGjcf6rzngvu6Qgn", "value": null },
```
