### ISSUE TITLE
Adding attachments to cards semi-fails.

### ISSUE THREAD

**Issue by inDane** [wekan/wekan#5434]
### Server Setup Information

* Did you test in newest Wekan?:
** Newest release in sandstorm is: 6.15.0~2022-04-05, yes.
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
** They open correctly
* Operating System:
** ubuntu 24.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): 
** Sandstorm (v308)
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
** nginx
* Node.js Version: n/a
* MongoDB Version: n/a
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
** firefox 126.0.1

### Problem description
I've upgraded my WeKan Grain from 5.xx  to the latest 6.15.0. Unfortunately the attachments are not working anymore. It is generating a thumbnail and attaches this to the card, but the actual attachment is not available. I cannot open nor download it. If i delete it i get an error log (see below in Logs section).
`/opt/sandstorm/var/sandstorm/grains/McnQ4XKT6vZFsDBQsXctBE/sandbox/wekan-uploads/uploads/attachments`
is writable for sandstorm user.

![image](https://github.com/wekan/wekan/assets/5693407/9b3febf3-71a5-43bd-825d-54065c779c40)

Please let me know if I should provide more info.

#### Reproduction Steps
Create Wekan grain, add attachment.

#### Logs

When deleting "broken" attachment, I can see this in /opt/sandstorm/var/sandstorm/grains/McnQ4XKT6vZFsDBQsXctBE/log

```
Exception in callback of async function: TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (models/activities.js:251:38)
    at packages/matb33_collection-hooks.js:422:18
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:421:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:436:12)
    at Object.collection.<computed> [as insert] (packages/matb33_collection-hooks.js:150:21)
    at ns.Collection.insert (packages/mongo/collection.js:525:39)
    at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
    at insertActivity (models/attachments.js:16:14)
    at models/attachments.js:56:7
    at Array.forEach (<anonymous>)
    at FilesCollection.onAfterRemove (models/attachments.js:55:11)
    at packages/ostrio:files/server.js:1546:14
    at packages/mongo/collection.js:735:7
    at args.<computed> (packages/matb33_collection-hooks.js:623:23)
    at runWithEnvironment (packages/meteor.js:1286:24)
    at packages/meteor.js:1299:14
    at packages/mongo/mongo_driver.js:362:7
    at runWithEnvironment (packages/meteor.js:1286:24)
```

I did not find any log why it cannot write the attachment.

Best
inDane

**Comment by Firas-Git** [comment]
The error you're encountering suggests that the card or card.title is not defined when you are trying to assign it to the params.card in the code. This might be happening because activity.card() returns undefined or null in some cases.
I will try to fix it and make a pull request.

**Comment by xet7** [comment]
This is about old WeKan version at Sandstorm, that may not anymore use same file code. Only bugs of newest WeKan will be fixed. Newest WeKan will be released to Sandstorm later.
