### ISSUE TITLE
Can't add due date to API created cards

### ISSUE THREAD

**Issue by snarfsmojo** [wekan/wekan#5537]
### Server Setup Information

WeKan ® info 	7.60.0
Meteor_version 	2.14
Node_version 	14.21.4
MongoDB_version 	7.0.14

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: 6.1.79-Unraid
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 14.21.4
* MongoDB Version: 7.0.14
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox 130.0

### Problem description

Cards that are created via an API call don't appear to be able to be assigned due dates.  When I set a due date on a card that has been created via the API, the date I set flashes momentarily, and then goes back to whatever the value was before.

![Issue_adding_duedate_to_API_created_card](https://github.com/user-attachments/assets/1d949587-e2a7-4a6b-a943-1ede4ff4c8aa)

#### Reproduction Steps

Create a card via API
try to add a due date to it

#### Logs

Check Right Click / Inspect / Console in you browser - generally Chromium
based browsers show more detailed info than Firefox based browsers.

```
update failed 
Object { stack: "r@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:1:4708\n_livedata_result@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:582:19693\nonMessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:582:22004\nt/_launchConnection/this.socket.onmessage/<@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:2696\nforEachCallback@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:3767\nt/_launchConnection/this.socket.onmessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:2664\nt/</</<[5]</r.prototype.dispatchEvent@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:8506\nt/</</<[14]</</</x.prototype._transportMessage/<@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:18656\nt/</</<[14]</</</x.prototype._transportMessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:18621\nt/</</<[3]</o.prototype.emit@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:7389\nt/</</<[38]</u/this.ws.onmessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:43416\n", isClientSafe: true, error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error" }

details: undefined
 ​
error: 500
 ​
errorType: "Meteor.Error"
 ​
isClientSafe: true
 ​
message: "Internal server error [500]"
 ​
reason: "Internal server error"
 ​
stack: "r@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:1:4708\n_livedata_result@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:582:19693\nonMessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:582:22004\nt/_launchConnection/this.socket.onmessage/<@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:2696\nforEachCallback@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:3767\nt/_launchConnection/this.socket.onmessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:2664\nt/</</<[5]</r.prototype.dispatchEvent@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:8506\nt/</</<[14]</</</x.prototype._transportMessage/<@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:18656\nt/</</<[14]</</</x.prototype._transportMessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:18621\nt/</</<[3]</o.prototype.emit@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:7389\nt/</</<[38]</u/this.ws.onmessage@https://chores.redactedurl.com/ce14368ada83dce26abbad343b0dc78e381d1ad7.js?meteor_js_resource=true:580:43416\n"
 ​
<prototype>: Object { constructor: r(), clone: clone(), stack: "" }
ce14368ada83dce26abbad343b0dc78e381d1ad7.js:1:7223
```

Docker Logs -
```
Exception while invoking method '/cards/update' TypeError: Cannot read property 'title' of undefined
    at Object.<anonymous> (models/activities.js:197:34)
    at packages/matb33:collection-hooks/insert.js:50:18
    at Array.forEach (<anonymous>)
    at after (packages/matb33:collection-hooks/insert.js:49:21)
    at Object.<anonymous> (packages/matb33:collection-hooks/insert.js:64:12)
    at Object.collection.<computed> [as insert] (packages/matb33:collection-hooks/collection-hooks.js:116:21)
    at ns.Collection.insert (packages/mongo/collection.js:628:39)
    at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/aldeed_collection2-core.js:232:19)
    at Object.<anonymous> (models/cards.js:3171:18)
    at packages/matb33:collection-hooks/update.js:56:30
    at Array.forEach (<anonymous>)
    at packages/matb33:collection-hooks/update.js:55:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (packages/matb33:collection-hooks/update.js:54:22)
    at Object.collection.<computed> [as update] (packages/matb33:collection-hooks/collection-hooks.js:116:21)
    at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:362:34)
    at MethodInvocation.m.<computed> (packages/allow-deny/allow-deny.js:173:46)
    at packages/check/match.js:118:15
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
```

**Comment by xet7** [comment]
Fixed in commit 39e12035e ( https://github.com/wekan/wekan/commit/39e12035e ), in the upcoming WeKan release, as part of a REST card API fix batch: #5398 consolidated duplicated board-move variable names; #5399 API list-move now puts the card on top of the destination list like the Move Card dialog; #5537 due/received/start/end dates set via the API now persist; #5546 archived cards can be inspected via the single-card GET and de-archived without needing a list_id. Reopen if any still reproduce on the latest version.
