### ISSUE TITLE
Site not responding - AWS EC 2 Instance Free Tier

### ISSUE THREAD

**Issue by lanchingmaa** [wekan/wekan#5563]
I have been running a test for a few months on AWS using SNAP install of Wekan. Its been running well except the free tier causes issues and the server constantly needs to rebooted when more than 1 user happens or when someone imports from Trello. I think its time to move to a larger instance. I cannot access Wekan as of Friday. 

Steps taken:
1. The instance is reporting no errors. Rebooted EC2 instance. 
2. GET WEKAN shows its running in console.
3. Here are the logs:

2024-11-10T00:00:00Z wekan.wekan[2233]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Finished \"notification_cleanup\".","time":{"$date":1731196800015},"level":"info"}
2024-11-10T09:31:02Z wekan.wekan[2233]: Exception in callback of async function: URIError: URI malformed
2024-11-10T09:31:02Z wekan.wekan[2233]:     at decodeURI (<anonymous>)
2024-11-10T09:31:02Z wekan.wekan[2233]:     at Router.match (/snap/wekan/1999/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect-route/lib/connect-route.js:61:12)
2024-11-10T09:31:02Z wekan.wekan[2233]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect-route/lib/connect-route.js:102:24
2024-11-10T09:31:02Z wekan.wekan[2233]:     at runWithEnvironment (packages/meteor.js:1286:24)
2024-11-10T09:31:02Z wekan.wekan[2233]:     at packages/meteor.js:1299:14
2024-11-10T09:31:02Z wekan.wekan[2233]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2024-11-11T00:00:00Z wekan.wekan[2233]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Starting \"notification_cleanup\".","time":{"$date":1731283200011},"level":"info"}
2024-11-11T00:00:00Z wekan.wekan[2233]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Finished \"notification_cleanup\".","time":{"$date":1731283200015},"level":"info"}

What seems to be happening? The request for URL is unresponsive and times out.

**Comment by lanchingmaa** [comment]
Thank you! I’ll report back. I have been starting and stopping WeKan and it still times out. Will running a Cron job do the same?

**Comment by xet7** [comment]
@lanchingmaa 

Times out when?

**Comment by xet7** [comment]
@lanchingmaa 

If you mean Trello import, there will be later fixes to Trello import, WeKan export etc.

**Comment by xet7** [comment]
@lanchingmaa 

If you are trying to export from Trello, export Trello JSON to file, and use this to download attachments:

https://github.com/wekan/trello-attachments-downloader

There will be later better import to WeKan.

**Comment by lanchingmaa** [comment]
Sorry. The EC2 instance is operating properly. When I pull Get Wekan I see it’s also running but when I call for the url, it times out and never resolves the request. I e started the Wekan app and also stopped and started. Still not responding in the browser. My question was does this Cron job do the same? Meaning it’s starting and stopping which is what I’ve tried. If this is a memory leak issue, then I would assume my manual effort would be the same as this script?

**Comment by xet7** [comment]
@lanchingmaa 

How much total RAM your server has? You see it with:

```
free -h
```

**Comment by lanchingmaa** [comment]
total        used        free      shared  buff/cache   available
Mem:           957Mi       554Mi        70Mi       916Ki       486Mi       402Mi
Swap:             0B          0B          0B

**Comment by xet7** [comment]
@lanchingmaa 

Add swapfile. Then look, does it use much swap. If it uses much, then you have too little RAM. Without any swapfile, you just immediately get site not responding, when there is not any RAM at all available.

1 GB RAM total is too little for WeKan. When doing anything, you easily get site not responding.

If it is so important to be able to run WeKan at free hosting, I should just rewrite WeKan with PHP/MySQL.
