### ISSUE TITLE
No Linux arm64 bundle version currently available (was: releases wekan team cannot visit)

### ISSUE THREAD

**Issue by ncs19960831** [wekan/wekan#5617]
A pleasant day when I wanted to use Wekan, but suddenly he couldn't work. I have reviewed the error alert:

>/wekan/bundle/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/ubuntu/software/wekan/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Mp._compile (/home/ubuntu/software/wekan/bundle/programs/server/runtime.js:77:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Mp.load (/home/ubuntu/software/wekan/bundle/programs/server/runtime.js:37:33)
/home/ubuntu/software/wekan/bundle/programs/server/node_modules/fibers/fibers.js:23
                throw new Error('Missing binary. See message above.');
                ^

>Error: Missing binary. See message above.
    at Object.<anonymous> (/home/ubuntu/software/wekan/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Mp._compile (/home/ubuntu/software/wekan/bundle/programs/server/runtime.js:77:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Mp.load (/home/ubuntu/software/wekan/bundle/programs/server/runtime.js:37:33)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/ubuntu/software/wekan/bundle/programs/server/boot.js:2:15)

>Node.js v20.9.0
>ls /home/ubuntu/software/wekan/bundle/programs/server/node_modules/fibers/bin/linux-arm64-115-glibc/
>ls:  '/home/ubuntu/software/wekan/bundle/programs/server/node_modules/fibers/bin/linux-arm64-115-glibc/': no such file or directory

I think I seem to be lost something. But in fact, I haven't updated my WeKan Software for a long time (maybe one year ago), and I encountered a 503 error when trying to open the website https://releases.wekan.team according to the manual. I am unable to access the website URL even when using a domain name test. Has this website changed? Has there been any change in the arm64 install plan? How can I rebuild Wekan without losing my original data? I hope you can help me.
![image](https://github.com/user-attachments/assets/4d0a3568-df6a-4758-88c7-14819c4feb20)

**Comment by xet7** [comment]
Yes, URL has changed. Downloads are only at releases page https://github.com/wekan/wekan/releases

## Linux download script

download.sh:
```
wget https://github.com/wekan/wekan/releases/download/v$1/wekan-$1-amd64.zip
```
Example:
```
chmod +x download.sh

./download.sh 7.72
```

## Windows download script

download.bat
```
ECHO OFF

wget https://github.com/wekan/wekan/releases/download/v%1/wekan-%1-amd64.zip
```
Example with cmd.exe:
```
download.bat 7.72
```
Example with PowerShell:
```
.\download.bat 7.72
```
If wget is not installed to Windows, download without wget https://stackoverflow.com/questions/51225598/downloading-a-file-with-powershell

## Bundle .zip Platforms

Currently there is bundle .zip file only for Linux amd64 and Windows amd64.

More info:
- Linux amd64 https://github.com/wekan/wekan/wiki/Raspberry-Pi
- Windows amd64 https://github.com/wekan/wekan/wiki/Offline

**Comment by xet7** [comment]
Hmm, Linux arm64. That does not exist currently. I'll try later, is it possible to create it, using some version of Node.js. Currently used Node.js 14.21.4 segfaults (crashes) at arm64, s390x etc. Maybe older 14.21.3 would works. Or of I get WeKan ported from Meteor 2 to Meteor 3, then it would work with Node.js 22 and MongoDB 8.

**Comment by xet7** [comment]
Sure, there are tricks to run Linux amd64 WeKan at any CPU with qemu-user, but that would require some additional configuration.

https://www.youtube.com/watch?v=bnU9bUVeN04

https://github.com/xet7/simpletasks
