### ISSUE TITLE
Getting following error while installing using manual-installation-steps 

### ISSUE THREAD

**Issue by rnjailamba** [wekan/wekan#585]
https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps

[Error: dlopen(/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson/build/Release/bson.node, 1): no suitable image found.  Did find:
	/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson/build/Release/bson.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00]
js-bson: Failed to load c++ bson extension, using pure JS version

/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: dlopen(/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/boot.js:162:18)
    at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:9:1)
    at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:13:1)
    at /Users/rnjailamba/Desktop/NodeFolder/bundle/programs/server/packages/npm-bcrypt.js:33:4

**Comment by rnjailamba** [comment]
Build using source and the issue was resolved
