### ISSUE TITLE
Getting error while running meteor app, source code from github account.

### ISSUE THREAD

**Issue by priyanka-Sadh** [wekan/wekan#601]
i am using mac terminal and npm --version 1.4.28

/Users/mindcrewtechnologies/AfrivetOnline/build/bundle/programs/server/boot.js:283
}).run();
   ^
Error: dlopen(/Users/mindcrewtechnologies/AfrivetOnline/build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
    /Users/mindcrewtechnologies/AfrivetOnline/build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Users/mindcrewtechnologies/AfrivetOnline/build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/Users/mindcrewtechnologies/AfrivetOnline/build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

how can i run my application, as i am in trouble to run this meteor application, Please help me out, it will be greatfull to me.

**Comment by mquandalle** [comment]
This error message doesn’t seem related to Wekan code. If you are still interested in solving this issue you should tell me more about what commands you have executed.

**Comment by rsirres** [comment]
Seems to be a file permission problem or you forget to set the required environment variables. (See wiki)
