### ISSUE TITLE
Cannot start main.js : "Cannot find module '../build/Release/bson'"

### ISSUE THREAD

**Issue by sg6** [wekan/wekan#670]
When I try to install Wekan from sources, I get the following error:

```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/web/wekan/.build/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at Module.Mp.load (/web/wekan/.build/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

But the app does not quit, it continues running.

I re-installed meteor, node and npm. Ubuntu 14.04, Node = v6.4.0, NPM = 3.10.3

When opening http://IP:PORT I see the following errors in the console:

```
536ded9….js?meteor_js_resource=true:7 Uncaught Error: Cannot find module 'xss'
536ded9….js?meteor_js_resource=true:184 There is no route for the path: /
536ded9….js?meteor_js_resource=true:227 Uncaught TypeError: Cannot read property 'toLowerCase' of null
536ded9….js?meteor_js_resource=true:306 Uncaught ReferenceError: Boards is not definede
```

I also re-installed xss with `meteor npm install xss` but still does not work.

And when I do an nginx redirect from sub.domain.com to localhost:PORT it does not find the JS file and the CSS is empty. But I do not know if this is related to my issue.

Anyone experienced a similar issue?

Thanks!

**Comment by AlexanderS** [comment]
The current version is not compatible with node 6.x. See #634.

**Comment by sg6** [comment]
Ok. thanks. But node 0.10.40 does not work with node-fiber

```
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/root/.nvm/v0.10.40/bin/npm" "install" "node-fiber"
npm ERR! node v0.10.40
npm ERR! npm  v3.10.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/node-fiber
npm ERR! 404 
npm ERR! 404  'node-fiber' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

As #634 already mentioned. But is there any way to install Wekan? It uses an old version, which does not support a certain package. Any possibilites?

**Comment by AlexanderS** [comment]
The packages is called `fibers` but not `node-fiber`.

**Comment by sg6** [comment]
Oh dear, `fibers`. Thanks. Worked :)

**Comment by erperejildo** [comment]
What about if we have Meteor 1.5 and we need Node 6.x.x?
