### ISSUE TITLE
Error: Exception while invoking method 'quitBoard'

### ISSUE THREAD

**Issue by arturweb85** [wekan/wekan#688]
Getting this error when trying to leave a board:

Exception while invoking method 'quitBoard' Error: Match error: Expected string, got object
    at check (packages/check/match.js:33:1)
    at [object Object].Meteor.methods.quitBoard (models/boards.js:325:7)
    at packages/check/match.js:103:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:102:1)
    at maybeAuditArgumentChecks (livedata_server.js:1695:18)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/built_app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/built_app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
    at new Promise (/built_app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
    at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
    at livedata_server.js:548:43
Sanitized and reported to the client as: Match failed [400]

**Comment by xet7** [comment]
Probably related to pull request https://github.com/wekan/wekan/pull/719

**Comment by xet7** [comment]
Fixed at #719
