### ISSUE TITLE
Cannot Assign Member

### ISSUE THREAD

**Issue by ertanalytics** [wekan/wekan#730]
On sandstorm - latest stable Wekan version

Just started not allowing me to assign members to an existing board that I have been working in for some time.  I tried dragging the members, it briefly says '...added... to [card name]', but immediately fails to add them with the debug log below:

Exception while invoking method '/cards/update' Error: remote exception: readlinkat(identitiesDir, textId.cStr(), buf, sizeof(buf)): No such file or directory
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at packages/meteor/helpers.js:119:1
    at reportActivity (sandstorm.js:108:5)
    at sandstorm.js:198:11
    at Object.<anonymous> (sandstorm.js:147:26)
    at packages/matb33_collection-hooks/insert.js:35:1
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at after (packages/matb33_collection-hooks/insert.js:34:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:49:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].insert (packages/mongo/collection.js:528:37)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
    at Object.<anonymous> (models/cards.js:276:20)
    at packages/matb33_collection-hooks/update.js:43:1
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at packages/matb33_collection-hooks/update.js:42:1
    - - - - -

**Comment by dwrensha** [comment]
Thanks for the report. I am able to reproduce the problem and am currently working on diagnosis and a fix.

**Comment by ertanalytics** [comment]
No idea why, but it all the sudden started working.

**Comment by dwrensha** [comment]
I suspect that what happened is that the user you were assigning to actually visited the grain. The problem happens when you try to assign to someone who hasn't visited the grain since last week's update.

**Comment by dwrensha** [comment]
I've published an SPK that includes the fix for this issue. You can manually install it from the app market at https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h or you can wait for the auto-update to pick it up in the next 24 hours.

**Comment by ertanalytics** [comment]
Thanks!
