### ISSUE TITLE
Attachment Upload not working

### ISSUE THREAD

**Issue by port22** [wekan/wekan#773]
I run as simple as:

```
# docker run -d --name wekan-db -v $PWD/mongo:/data/db mongo
# docker run -d --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://wekan.server" -p 80:80 mquandalle/wekan
```

File Permissions are recursively 777. 

Everything's working except when I try to upload a file (regardless of filetype) to a card, it comes in yellow alert top line:

>  The application is currently offline, refreshing the page will cause data loss.

The Docker container now crashed and has been restarted due to restart-policy.
I refresh the page, the attachment is a grey box without the image. Clicking on Download has no effect. But I can delete.

As a note: Uploading an Attachment is awfully complicated. An "Attach a File..." - Link/Button between "Description" and "Activity" or right-floating besides Members and Labels would be great, maybe along with a small area to drag&drop files.

**Comment by port22** [comment]
`/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
SA GridFS - ERROR! { [MongoError: Can't get executor for query { files_id: ObjectId('5891b7df71a80707009cc449'), n: { $gte: 0 } }]
  name: 'MongoError',
  ok: 0,
  errmsg: 'Can\'t get executor for query { files_id: ObjectId(\'5891b7df71a80707009cc449\'), n: { $gte: 0 } }',
  code: 17241,
  codeName: 'Location17241' }
Error: Error storing uploaded file to TempStore: Can't get executor for query { files_id: ObjectId('5891b7df71a80707009cc449'), n: { $gte: 0 } }
    at EventEmitter.<anonymous> (packages/cfs_collection/packages/cfs_collection.js:161:1)
    at EventEmitter.emit (events.js:117:20)
    at Stream.<anonymous> (packages/cfs_tempstore/packages/cfs_tempstore.js:343:1)
    at Stream.emit (events.js:117:20)
    at Stream._error (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:128:28
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:524:58
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:474:20
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1194:16
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)`

**Comment by xet7** [comment]
@port22 

Backup your data:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

Then remove your docker containers and images, and install newest Wekan with MongoDB 3.2.11 like this, uploading images works now:

```
docker run -d --restart=always --name wekan-db mongo:3.2.11

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost:8080" -p 8080:80 mquandalle/wekan:latest
```

Then restore your data:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

For newest info about Docker, see README.md on root dir of repo.

Closing issue.

**Comment by onekiloparsec** [comment]
Well, this still doesn't work when installing latest version (0.18) from source.
