### ISSUE TITLE
When upload a image file , It go crash

### ISSUE THREAD

**Issue by airclear** [wekan/wekan#869]
OSX 10.11.5
install with docker 1.12.0

crashlog：
```
wekandb_1  | 2017-02-23T11:06:50.544+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:40316 #21 (17 connections now open)
wekandb_1  | 2017-02-23T11:06:50.544+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:40318 #22 (18 connections now open)
wekandb_1  | 2017-02-23T11:06:50.545+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:40320 #23 (19 connections now open)
wekandb_1  | 2017-02-23T11:06:50.546+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:40322 #24 (20 connections now open)
wekan_1    | SA GridFS - ERROR! { [MongoError: Can't get executor for query { files_id: ObjectId('58aec24a3b77c501009ba0f5'), n: { $gte: 0 } }]
wekan_1    |   name: 'MongoError',
wekan_1    |   ok: 0,
wekan_1    |   errmsg: 'Can\'t get executor for query { files_id: ObjectId(\'58aec24a3b77c501009ba0f5\'), n: { $gte: 0 } }',
wekan_1    |   code: 17241,
wekan_1    |   codeName: 'Location17241' }
wekan_1    | 
wekan_1    | /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:246
wekan_1    |         throw message;      
wekan_1    |               ^
wekan_1    | Error: Error storing uploaded file to TempStore: Can't get executor for query { files_id: ObjectId('58aec24a3b77c501009ba0f5'), n: { $gte: 0 } }
wekan_1    |     at EventEmitter.<anonymous> (packages/cfs_collection/packages/cfs_collection.js:161:1)
wekan_1    |     at EventEmitter.emit (events.js:117:20)
wekan_1    |     at Stream.<anonymous> (packages/cfs_tempstore/packages/cfs_tempstore.js:343:1)
wekan_1    |     at Stream.emit (events.js:117:20)
wekan_1    |     at Stream._error (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
wekan_1    |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:128:28
wekan_1    |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:524:58
wekan_1    |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:474:20
wekan_1    |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1194:16
wekan_1    |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1903:9
wekan_1    |     at Server.Base._callHandler (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
wekan_1    |     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
wekan_1    |     at [object Object].MongoReply.parseBody (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
wekan_1    |     at [object Object].<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
wekan_1    |     at [object Object].emit (events.js:95:17)
wekan_1    |     at [object Object].<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
wekandb_1  | 2017-02-23T11:06:50.658+0000 I -        [conn22] end connection 172.17.0.3:40318 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn15] end connection 172.17.0.3:40280 (19 connections now open)
wekandb_1  | 2017-02-23T11:06:50.658+0000 I -        [conn18] end connection 172.17.0.3:40286 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.660+0000 I -        [conn21] end connection 172.17.0.3:40316 (17 connections now open)
wekandb_1  | 2017-02-23T11:06:50.658+0000 I -        [conn17] end connection 172.17.0.3:40284 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn16] end connection 172.17.0.3:40282 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.661+0000 I -        [conn10] end connection 172.17.0.3:40270 (14 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn11] end connection 172.17.0.3:40272 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.661+0000 I -        [conn4] end connection 172.17.0.3:40258 (12 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn14] end connection 172.17.0.3:40278 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn12] end connection 172.17.0.3:40274 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.661+0000 I -        [conn3] end connection 172.17.0.3:40256 (14 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn6] end connection 172.17.0.3:40262 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.658+0000 I -        [conn23] end connection 172.17.0.3:40320 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn9] end connection 172.17.0.3:40268 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn8] end connection 172.17.0.3:40266 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn20] end connection 172.17.0.3:40314 (20 connections now open)
wekandb_1  | 2017-02-23T11:06:50.660+0000 I -        [conn24] end connection 172.17.0.3:40322 (17 connections now open)
wekandb_1  | 2017-02-23T11:06:50.661+0000 I -        [conn5] end connection 172.17.0.3:40260 (13 connections now open)
wekandb_1  | 2017-02-23T11:06:50.659+0000 I -        [conn2] end connection 172.17.0.3:40254 (20 connections now open)
docker_wekan_1 exited with code 8

```

**Comment by xet7** [comment]
@airclear 

What version of MongoDB you have? Wekan supports 3.2.x versions of MongoDB, newer versions crash with that error "Can't get executor for query".
