### ISSUE TITLE
download attachment doc/excel  error

### ISSUE THREAD

**Issue by mdhhdm** [wekan/wekan#902]
upload doc or excel files success,but when I download it ,error occurs,then wekan application stop.
the error is 
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
    at ServerResponse.res.setHeader (/build/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
    at packages/cfs_http-methods/http.methods.server.api.js:599:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at packages/cfs_http-methods/http.methods.server.api.js:595:1

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/784
