### ISSUE TITLE
Registration mail never sent using 0.16

### ISSUE THREAD

**Issue by anlx-sw** [wekan/wekan#951]
Hello,

I currently run into problems implementing wekan using wekan-snap:
https://github.com/kubiko/wekan-snap/
https://uappexplorer.com/app/wekan-ondra.ondra

I first thought it might be a snap issue  - so i did some troubleshooting and opened a ticket in the wekan-snap repo:
https://github.com/kubiko/wekan-snap/issues/3

please read through that issue as it contains problem details and troubleshooting steps so far.

the author advised me to seek help at the wekan developers as the problem seems to be in wekan itself and not the snap implementation.

to reproduce the problem:
run ubuntu 16.04 server
```
sudo apt-get install snapd
sudo snap install wekan-ondra
sudo snap set wekan-ondra mail-url='smtp://10.100.11.50:25/'
sudo snap set wekan-ondra mail-from='wekan@domain.local'
sudo snap set wekan-ondra port='3000'
sudo snap set wekan-ondra root-url='http://wekan.domain.local:3000'
```
then register the first user and you get the error mentioned

i also tried already changing the mail url to:
'smtp://wekan@10.100.11.50:25/'
'smtp://wekan:password@10.100.11.50:25/'

i get the following error:
```
Mar 29 15:40:21 myservername snap[21719]: Exception while invoking method 'ATCreateUserServer' Error: getaddrinfo ESRCH
Mar 29 15:40:21 myservername snap[21719]:     at Object.Future.wait (/snap/wekan-ondra/46/programs/server/node_modules/fibers/fu                                          ture.js:449:15)
Mar 29 15:40:21 myservername snap[21719]:     at smtpSend (packages/email/email.js:89:1)
Mar 29 15:40:21 myservername snap[21719]:     at Object.Email.send (packages/email/email.js:192:1)
Mar 29 15:40:21 myservername snap[21719]:     at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/passw                                          ord_server.js:797:9)
Mar 29 15:40:21 myservername snap[21719]:     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/l                                          ib/server_methods.js:119:1)
Mar 29 15:40:21 myservername snap[21719]:     at packages/check/match.js:107:1
Mar 29 15:40:21 myservername snap[21719]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 29 15:40:21 myservername snap[21719]:     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:                                          106:1)
Mar 29 15:40:21 myservername snap[21719]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
Mar 29 15:40:21 myservername snap[21719]:     at packages/ddp-server/livedata_server.js:711:19
Mar 29 15:40:21 myservername snap[21719]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 29 15:40:21 myservername snap[21719]:     at packages/ddp-server/livedata_server.js:709:40
Mar 29 15:40:21 myservername snap[21719]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 29 15:40:21 myservername snap[21719]:     at packages/ddp-server/livedata_server.js:707:46
Mar 29 15:40:21 myservername snap[21719]:     at tryCallTwo (/snap/wekan-ondra/46/programs/server/npm/node_modules/meteor/promis                                          e/node_modules/promise/lib/core.js:45:5)
Mar 29 15:40:21 myservername snap[21719]:     at doResolve (/snap/wekan-ondra/46/programs/server/npm/node_modules/meteor/promise                                          /node_modules/promise/lib/core.js:200:13)
Mar 29 15:40:21 myservername snap[21719]:     - - - - -
Mar 29 15:40:21 myservername snap[21719]:     at errnoException (dns.js:37:11)
Mar 29 15:40:21 myservername snap[21719]:     at Object.onanswer [as oncomplete] (dns.js:126:16)

```

**Comment by stephenmoloney** [comment]
How are these variables in ENV-- 

```
sudo snap set wekan-ondra mail-url='smtp://10.100.11.50:25/'
sudo snap set wekan-ondra mail-from='wekan@domain.local'
sudo snap set wekan-ondra port='3000'
sudo snap set wekan-ondra root-url='http://wekan.domain.local:3000'
```

Can you check what `MAIL_URL` AND `MAIL_FROM` are in the `env` of whereever it is running?

**Comment by anlx-sw** [comment]
i got the information from the snap developer concerning env:

> if you run $ wekan-ondra.help
there you can see all the supported variables.
If you want to see how those are mapped to final names, then run:
$ snap run --shell wekan-ondra.help
$ source ${SNAP}/bin/wekan-read-settings
this will print you and updates env variable in current shell

i get the following output:

```
root@srvkanban01:/home/ladmin# source ${SNAP}/bin/wekan-read-settings
using default value: MONGODB_PORT='27019'
using default value: MONGODB_BIND_IP='127.0.0.1'
MAIL_URL='smtp://wekan:password@10.100.11.50:25/'
MAIL_FROM='kanban@domain.local'
ROOT_URL='https://kanban.domain.local'
PORT='3000'
root@srvkanban01:/home/ladmin#
```


or with the env command using the snap commands:

```
root@srvkanban01:/home/ladmin# env
MAIL_URL=smtp://wekan:password@10.100.11.50:25/
MONGODB_BIND_IP=127.0.0.1
SNAP_USER_COMMON=/root/snap/wekan-ondra/common
SHELL=/bin/bash
TERM=xterm
MONGODB_PORT=27019
SNAP_REEXEC=
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SUDO_USER=ladmin
SUDO_UID=1000
SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/void
USERNAME=root
SNAP_COMMON=/var/snap/wekan-ondra/common
SNAP_DID_REEXEC=1
SNAP_USER_DATA=/root/snap/wekan-ondra/46
SNAP_DATA=/var/snap/wekan-ondra/46
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
MAIL=/var/mail/root
PWD=/home/ladmin
LANG=de_AT.UTF-8
MAIL_FROM=kanban@domain.local
ROOT_URL=https://kanban.domain.local
SNAP_REVISION=46
HOME=/root/snap/wekan-ondra/46
SHLVL=2
SUDO_COMMAND=/bin/su
SNAP_NAME=wekan-ondra
LANGUAGE=de_AT:de
LOGNAME=root
SNAP_ARCH=amd64
LESSOPEN=| /usr/bin/lesspipe %s
PORT=3000
SNAP_VERSION=0.16
SUDO_GID=1000
XDG_RUNTIME_DIR=/run/user/0/snap.wekan-ondra
SNAP=/snap/wekan-ondra/46
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
root@srvkanban01:/home/ladmin#

```

**Comment by stephenmoloney** [comment]
seems those variables are set correctly - it's not that then.

**Comment by anlx-sw** [comment]
i got mail running changing two things:
-use server dns name instead of ip
-use admin panel (enable admin role for user first via mongodb) to set all mailserver parameters

i didn't had time to test it finally but i think wekan  (or the components it uses) got a problem if the mailserver is used by ip instead of dns name.
