### ISSUE TITLE
[production] MongoError: driver is incompatible with this server version

### ISSUE THREAD

**Issue by tr37ion** [wekan/wekan#966]
Following the [Manual Installation](https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source) and starting Wekan manually works fine.

Then I  move on with [In Production](https://github.com/wekan/wekan/wiki/Install-and-Update#in-production) section and `./run-wekan.sh` leads to this error:

```
$ ./run-wekan.sh

/home/user/repos/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                      ^
MongoError: driver is incompatible with this server version
    at Object.Future.wait (/home/user/repos/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:10)
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:685:20)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1422:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:51:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /home/user/repos/wekan/.build/bundle/programs/server/packages/accounts-base.js:1829:15
    at /home/user/repos/wekan/.build/bundle/programs/server/packages/accounts-base.js:1840:3
    - - - - -
    at Object.toError (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at __executeInsertCommand (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1926:27)
    at Db._executeInsertCommand (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:2028:5)
    at /home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1348:12
    at /home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1442:20
    at /home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:16
    at /home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
```
I wonder why `meteor` works fine while production doesn't ... any idea how to fix this? 
(ArchLinux)

**Comment by xet7** [comment]
@tr37ion

Wekan is only compatible with MongoDB v3.2.x currently. Do you have MongoDB v3.4.x at server?

Ongoining Meteor 1.4 porting process can possibly bring MongoDB v3.4.x support, it's not known yet.

Currently file uploads crash Wekan with MongoDB v3.4.x

**Comment by xet7** [comment]
Also full build with compiling binary extensions including fibers etc is required for wekan to work correctly, or using precompiled .tar.gz version. Just running command meteor is not enough.

**Comment by tr37ion** [comment]
ArchLinux uses Mongo db version v3.4.1. on my system. Not sure what you mean with

>  Also full build with compiling binary extensions including fibers etc is required for wekan to work correctly, or using precompiled .tar.gz version.

I could build [production section](https://github.com/wekan/wekan/wiki/Install-and-Update#in-production) without any problems, I guess. My remark to `meteor` was to show that it works in [testing mode](https://github.com/wekan/wekan/wiki/Install-and-Update#for-development-and-testing).

Btw. ArchLinux is using Python 3.6.0 and I'm running Meteor 1.3.5, too.

For me is now the question, what I can do to run Wekan in the meantime. Can I use it in testing mode (no file upload needed) and later switch to production if Mongo 3.4.x is supported? Just for personal use, no other users need to connect to Wekan.

**Comment by xet7** [comment]
Can't you install MongoDB v3.2.x on your system? You can also import/export data between different versions of MongoDB:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

**Comment by Zokormazo** [comment]
tested with mongo 3.4.2 and it works
