### ISSUE TITLE
Bug : Node crash when download attachement with Polish caracters in the title.

### ISSUE THREAD

**Issue by vanisay** [wekan/wekan#984]
Hi all,

When  we want download a pdf file in attachement with Polish caracters in the title.,= the process node crash.
OS Version : Centos 7.1
Wekan Version : 0.18

Logs:
/root/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                      ^
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
    at ServerResponse.res.setHeader (/root/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
    at packages/cfs_http-methods/http.methods.server.api.js:599:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at packages/cfs_http-methods/http.methods.server.api.js:595:1

Thanks for your good work !

**Comment by xet7** [comment]
Moved to #784
