### ISSUE TITLE
Trello importer broken (Error: Is comment only is required)

### ISSUE THREAD

**Issue by Jean-Daniel** [wekan/wekan#996]
When trying to import Trello board, I have the following error:

```
Apr 11 16:43:31 wekan Wekan[23307]: Sanitized and reported to the client as: Is comment only is required [400]
Apr 11 16:43:31 wekan Wekan[23307]: Exception while invoking method 'importTrelloBoard' Error: Is comment only is required
Apr 11 16:43:31 wekan Wekan[23307]:     at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:437:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:420:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:173:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at packages/matb33_collection-hooks/collection-hooks.js:98:1
Apr 11 16:43:31 wekan Wekan[23307]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at Object.directOp (packages/matb33_collection-hooks/collection-hooks.js:18:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:97:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at TrelloCreator.createBoardAndLabels (models/import.js:189:35)
Apr 11 16:43:31 wekan Wekan[23307]:     at [object Object].importTrelloBoard (models/import.js:497:35)
Apr 11 16:43:31 wekan Wekan[23307]:     at packages/check/match.js:107:1
Apr 11 16:43:31 wekan Wekan[23307]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
Apr 11 16:43:31 wekan Wekan[23307]:     at packages/ddp-server/livedata_server.js:711:19
Apr 11 16:43:31 wekan Wekan[23307]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Apr 11 16:43:31 wekan Wekan[23307]:     at packages/ddp-server/livedata_server.js:709:40
Apr 11 16:43:31 wekan Wekan[23307]: Sanitized and reported to the client as: Is comment only is required [400]
```

This is probably due to a missing attribute when creating members in wekan/import.js:144

**Comment by neooleg** [comment]
@Jean-Daniel, pls look on https://github.com/wekan/wekan/issues/950. Here is discussion with @rhelsing -- author of related PR.

What I see you tackling the same issue.

**Comment by rhelsing** [comment]
@xet7 this should be closed! thx!
