### ISSUE TITLE
Attachment Picture Upload Fails

### ISSUE THREAD

**Issue by n00b42** [wekan/wekan#999]
When I try to attach an image it gets created (there is a placeholder for it) but remains empty.

The logs show the following error

```
 SA GridFS - ERROR! { MongoError: Can't get executor for query { files_id: ObjectId('58ee895efc089201002b101f'), n: { $gte: 0 } }
     at Object.toError (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/utils.js:114:11)
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1194:31
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1903:9
     at Server.Base._callHandler (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
     at MongoReply.parseBody (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
     at .<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
     at emitOne (events.js:96:13)
     at emit (events.js:188:7)
     at .<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
     at emitTwo (events.js:106:13)
     at emit (events.js:191:7)
     at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:176:18)
   name: 'MongoError',
   ok: 0,
   errmsg: 'Can\'t get executor for query { files_id: ObjectId(\'58ee895efc089201002b101f\'), n: { $gte: 0 } }',
   code: 17241,
   codeName: 'Location17241' }
 /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:246
         throw message;
         ^

 Error: Error storing uploaded file to TempStore: Can't get executor for query { files_id: ObjectId('58ee895efc089201002b101f'), n: { $gte: 0 } }
     at EventEmitter.<anonymous> (packages/cfs_collection.js:186:28)
     at emitTwo (events.js:111:20)
     at EventEmitter.emit (events.js:191:7)
     at Stream.<anonymous> (packages/cfs_tempstore.js:364:10)
     at emitOne (events.js:101:20)
     at Stream.emit (events.js:188:7)
     at Stream._error (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:128:28
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:524:58
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:474:20
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1194:16
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1903:9
     at Server.Base._callHandler (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
     at MongoReply.parseBody (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
     at .<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
 { Error: Cannot find module '../build/Release/bson'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/ext/index.js:15:10)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
 js-bson: Failed to load c++ bson extension, using pure JS version
 Note: you are using a pure-JavaScript implementation of bcrypt.
 While this implementation will work correctly, it is known to be
 approximately three times slower than the native implementation.
 In order to use the native implementation instead, run

   meteor npm install --save bcrypt

 in the root directory of your application.
```

**Comment by n00b42** [comment]
Screenshot of Attachment "placeholder":

![wekan](https://cloud.githubusercontent.com/assets/6792900/24977167/73cfe066-1fcc-11e7-95c4-8e555d4e6243.PNG)

**Comment by xet7** [comment]
@n00b42 

Hey thanks a lot! I did not know that newest Meteor 1.4 port still has this problem with MongoDB 3.4.x.

I will change dockerfiles to use MongoDB 3.2.12, there uploading attachments work, I tested it a moment ago.

**Comment by xet7** [comment]
Ok I have made changes to MongoDB 3.2.12.
